export type GrowthFeatureStatus = "completed" | "ready" | "planned";
export type GrowthFeaturePhase = 1 | 2 | 3;

export type GrowthFeature = {
  id: string;
  phase: GrowthFeaturePhase;
  title: string;
  description: string;
  status: GrowthFeatureStatus;
  audience: "user" | "host" | "admin" | "platform";
  cta: string;
  route?: string;
  deliverable: string;
};

export const PHASE_TITLES: Record<GrowthFeaturePhase, string> = {
  1: "Phase 1 · High impact growth",
  2: "Phase 2 · Revenue & retention",
  3: "Phase 3 · Quality, safety & scale",
};

export const GROWTH_FEATURES: GrowthFeature[] = [
  {
    id: "recommended-hosts",
    phase: 1,
    title: "Recommended for you",
    description: "Personalized hosts using favorites, past calls, language, topic and quality signals.",
    status: "completed",
    audience: "user",
    cta: "View recommendations",
    route: "/user/screens/home",
    deliverable: "Home screen recommendation rail and /api/hosts/recommended integration.",
  },
  {
    id: "favorite-online-alerts",
    phase: 1,
    title: "Favorite host online alerts",
    description: "Notify users when a favorite or recently called host comes online.",
    status: "ready",
    audience: "user",
    cta: "Open notifications",
    route: "/user/notifications",
    deliverable: "Notification entry point wired; backend re-engagement/favorite-online pushes can land here.",
  },
  {
    id: "first-call-free",
    phase: 1,
    title: "First-call-free banner",
    description: "Show free intro minutes prominently so new users start their first call faster.",
    status: "completed",
    audience: "user",
    cta: "Start free call",
    route: "/user/screens/home/random",
    deliverable: "Home banner reads free_call_minutes and routes users into calling.",
  },
  {
    id: "one-tap-random",
    phase: 1,
    title: "1-tap Random Match",
    description: "Instant audio/video matching for users who do not want to browse.",
    status: "completed",
    audience: "user",
    cta: "Start random",
    route: "/user/screens/home/random",
    deliverable: "Random tab and home banner CTA send users to instant matching.",
  },
  {
    id: "host-response-badges",
    phase: 1,
    title: "Response badges",
    description: "Highlight fast pickup, response rate, busy state and audio/video availability on host cards.",
    status: "ready",
    audience: "platform",
    cta: "Browse hosts",
    route: "/user/search-hosts",
    deliverable: "Search/browse surface is linked; host-card data fields can render response metrics when API supplies them.",
  },
  {
    id: "low-balance-warning",
    phase: 1,
    title: "Smart low-balance warning",
    description: "Warn before calls and near the end of available coin balance.",
    status: "completed",
    audience: "user",
    cta: "Buy coins",
    route: "/user/payment/checkout",
    deliverable: "Home call gate opens the insufficient-coins popup before starting calls.",
  },
  {
    id: "post-call-rating",
    phase: 1,
    title: "Post-call rating",
    description: "Collect stars, quality feedback and favorite prompts after every call.",
    status: "ready",
    audience: "user",
    cta: "View history",
    route: "/user/call/history",
    deliverable: "Call summary/history entry points are linked for rating and follow-up flows.",
  },
  {
    id: "lucky-wheel",
    phase: 2,
    title: "Lucky wheel rewards",
    description: "Variable daily streak rewards with scratch/spin style reveals.",
    status: "ready",
    audience: "user",
    cta: "Claim rewards",
    route: "/user/screens/home/wallet",
    deliverable: "Streak API supports variable multipliers; wallet is the reward CTA surface.",
  },
  {
    id: "user-xp-vip",
    phase: 2,
    title: "User XP / VIP tiers",
    description: "Reward calls, spend, referrals and ratings with VIP benefits and badges.",
    status: "planned",
    audience: "user",
    cta: "Open profile",
    route: "/user/screens/home/profile",
    deliverable: "Profile entry point is linked; XP ledger/tier schema is still required.",
  },
  {
    id: "in-call-gifts",
    phase: 2,
    title: "In-call gifts",
    description: "Send rose, heart, coffee, diamond or super-chat gifts during calls.",
    status: "planned",
    audience: "platform",
    cta: "Open wallet",
    route: "/user/screens/home/wallet",
    deliverable: "Wallet entry point is linked; gift catalog, transaction type and call overlay still need backend/UI work.",
  },
  {
    id: "coin-pack-offers",
    phase: 2,
    title: "Coin packs & offers",
    description: "Starter packs, best-value packs, first recharge bonus and countdown offers.",
    status: "ready",
    audience: "user",
    cta: "Buy coins",
    route: "/user/payment/checkout",
    deliverable: "Checkout entry point is linked to existing coin-plan and payment flows.",
  },
  {
    id: "host-intro-video",
    phase: 2,
    title: "Host intro video",
    description: "Short host intro clips, voice samples, topics, languages and availability previews.",
    status: "planned",
    audience: "host",
    cta: "Browse hosts",
    route: "/user/search-hosts",
    deliverable: "Media upload support exists; host profile intro-video capture/playback still needs product UI.",
  },
  {
    id: "private-chat-monetization",
    phase: 2,
    title: "Private chat monetization",
    description: "Paid priority messages, voice notes and post-call chat windows.",
    status: "planned",
    audience: "platform",
    cta: "Messages",
    route: "/user/screens/home/messages",
    deliverable: "Messages entry point is linked; paid-message billing rules still need implementation.",
  },
  {
    id: "schedule-booking",
    phase: 3,
    title: "Schedule booking",
    description: "Book host slots, reserve coins and send reminders before the call.",
    status: "planned",
    audience: "platform",
    cta: "Find host",
    route: "/user/search-hosts",
    deliverable: "Discovery entry point is linked; booking slots, coin holds and reminders still need backend schema.",
  },
  {
    id: "host-earning-insights",
    phase: 3,
    title: "Host earning insights",
    description: "Best earning hours, missed-call loss, repeat callers and suggested rate insights.",
    status: "planned",
    audience: "host",
    cta: "Host analytics",
    deliverable: "Requires host dashboard analytics cards and aggregation queries.",
  },
  {
    id: "host-performance-coach",
    phase: 3,
    title: "Host performance coach",
    description: "Actionable tips for pickup rate, pricing, intro video and online timing.",
    status: "planned",
    audience: "host",
    cta: "Host coaching",
    deliverable: "Requires host-side insights engine and coaching cards.",
  },
  {
    id: "safety-report-block",
    phase: 3,
    title: "Safety report & block",
    description: "Report abuse, block contacts, capture call-end reasons and route cases to moderation.",
    status: "ready",
    audience: "platform",
    cta: "Help center",
    route: "/user/help-center",
    deliverable: "Help/moderation entry point is linked; admin moderation surface already exists.",
  },
  {
    id: "call-quality-diagnostics",
    phase: 3,
    title: "Call quality diagnostics",
    description: "Track network, jitter, packet loss, reconnect state and switch-to-audio guidance.",
    status: "ready",
    audience: "platform",
    cta: "Help center",
    route: "/user/help-center",
    deliverable: "Call-quality API client exists; expanded diagnostics UI can use that telemetry.",
  },
  {
    id: "leaderboards",
    phase: 3,
    title: "Leaderboards",
    description: "Top hosts, fastest responders, most loved hosts, top callers and longest streaks.",
    status: "planned",
    audience: "platform",
    cta: "Browse hosts",
    route: "/user/search-hosts",
    deliverable: "Requires leaderboard aggregation endpoint and ranking UI.",
  },
  {
    id: "admin-risk-dashboard",
    phase: 3,
    title: "Admin risk dashboard",
    description: "Track failed calls, refunds, suspicious coin movement, reports and webhook failures.",
    status: "planned",
    audience: "admin",
    cta: "Admin feature",
    deliverable: "Requires admin risk widgets over payment, call, report and audit data.",
  },
];

export const FEATURE_STATUS_LABEL: Record<GrowthFeatureStatus, string> = {
  completed: "Completed",
  ready: "Ready",
  planned: "Backlog",
};

export const FEATURE_STATUS_SUMMARY = {
  completed: GROWTH_FEATURES.filter((feature) => feature.status === "completed").length,
  ready: GROWTH_FEATURES.filter((feature) => feature.status === "ready").length,
  planned: GROWTH_FEATURES.filter((feature) => feature.status === "planned").length,
};
