uploads = []
outputs = []

[[generated]]
id = "tqgGpq2MJHKXaJ1v_Gv-O"
uri = "file://artifacts/voxlink/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "--OEu1tPxisS_jGVHcHap"
uri = "file://artifacts/voxlink/assets/images/splash-icon.png"
type = "image"
title = "generated_image"
