// ============================================================================
// Expo config plugin — wires Codemagic CodePush into the native projects.
// ============================================================================
// These apps are Expo CNG (managed), so android/ & ios/ are generated by
// `expo prebuild`. Manual native edits would be wiped, so this plugin applies
// the CodePush native config on every prebuild:
//   • Android: strings.xml (server URL + deployment key), apply codepush.gradle,
//              MainApplication.getJSBundleFile -> CodePush
//   • iOS:     Info.plist (server URL + deployment key), AppDelegate bundleURL -> CodePush
//
// The deployment key is read from env so it is never hardcoded:
//   CODEPUSH_DEPLOYMENT_KEY_ANDROID / CODEPUSH_DEPLOYMENT_KEY_IOS
// Get keys via: code-push deployment list <app> -k
// ============================================================================

const {
  withStringsXml,
  withInfoPlist,
  withAppBuildGradle,
  withMainApplication,
  withAppDelegate,
  AndroidConfig,
} = require('@expo/config-plugins');

const SERVER_URL = 'https://codepush.pro/';
const CODEPUSH_GRADLE =
  'apply from: "../../node_modules/@code-push-next/react-native-code-push/android/codepush.gradle"';

// ── Android: strings.xml ─────────────────────────────────────────────────────
function withAndroidStrings(config) {
  return withStringsXml(config, (cfg) => {
    const key = process.env.CODEPUSH_DEPLOYMENT_KEY_ANDROID || '';
    cfg.modResults = AndroidConfig.Strings.setStringItem(
      [
        { $: { name: 'CodePushServerUrl', moduleConfig: 'true' }, _: SERVER_URL },
        { $: { name: 'CodePushDeploymentKey', moduleConfig: 'true' }, _: key },
      ],
      cfg.modResults,
    );
    return cfg;
  });
}

// ── Android: apply codepush.gradle ───────────────────────────────────────────
function withAndroidGradle(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (!cfg.modResults.contents.includes('codepush.gradle')) {
      cfg.modResults.contents = `${cfg.modResults.contents}\n${CODEPUSH_GRADLE}\n`;
    }
    return cfg;
  });
}

// ── Android: MainApplication.getJSBundleFile -> CodePush (RN 0.76+ pattern) ──
function withMainApplicationCodePush(config) {
  return withMainApplication(config, (cfg) => {
    let src = cfg.modResults.contents;
    if (!src.includes('com.microsoft.codepush.react.CodePush')) {
      src = src.replace(/^(package .+)$/m, `$1\n\nimport com.microsoft.codepush.react.CodePush`);
    }
    if (!src.includes('getJSBundleFile()') && src.includes('DefaultReactNativeHost(this)')) {
      src = src.replace(
        /(object\s*:\s*DefaultReactNativeHost\(this\)\s*\{)/,
        `$1\n          override fun getJSBundleFile(): String = CodePush.getJSBundleFile()\n`,
      );
    }
    cfg.modResults.contents = src;
    return cfg;
  });
}

// ── iOS: AppDelegate bundleURL -> CodePush (release only) ────────────────────
function withAppDelegateCodePush(config) {
  return withAppDelegate(config, (cfg) => {
    let src = cfg.modResults.contents;
    if (!src.includes('import CodePush')) {
      // Add the import after the first existing import line.
      src = src.replace(/^(import .+\n)/m, `$1import CodePush\n`);
    }
    // In release builds, load the JS bundle CodePush manages.
    src = src.replace(
      /Bundle\.main\.url\(forResource:\s*"main",\s*withExtension:\s*"jsbundle"\)/g,
      'CodePush.bundleURL()',
    );
    cfg.modResults.contents = src;
    return cfg;
  });
}

// ── iOS: Info.plist ──────────────────────────────────────────────────────────
function withInfoPlistCodePush(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.CodePushServerURL = SERVER_URL;
    cfg.modResults.CodePushDeploymentKey = process.env.CODEPUSH_DEPLOYMENT_KEY_IOS || '';
    return cfg;
  });
}

module.exports = function withCodePush(config) {
  config = withAndroidStrings(config);
  config = withAndroidGradle(config);
  config = withMainApplicationCodePush(config);
  config = withAppDelegateCodePush(config);
  config = withInfoPlistCodePush(config);
  return config;
};
