kind = "mobile"
previewPath = "/voxlink-host/"
title = "VoxLink Host App"
version = "1.0.0"
id = "artifacts/voxlink"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/voxlink-host/" ]
localPort = 8099

[services.development]
run = "pnpm --filter @workspace/voxlink-host run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/voxlink-host", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/voxlink-host", "run", "serve" ]

[services.env]
PORT = "8099"
BASE_PATH = "/voxlink-host/"
