// VoxLink — Arabic Strings

const ar = {
  common: {
    ok: "موافق",
    cancel: "إلغاء",
    confirm: "تأكيد",
    save: "حفظ",
    delete: "حذف",
    edit: "تعديل",
    done: "تم",
    back: "رجوع",
    close: "إغلاق",
    loading: "جاري التحميل...",
    error: "حدث خطأ",
    retry: "حاول مجددًا",
    submit: "إرسال",
    next: "التالي",
    skip: "تخطي",
    yes: "نعم",
    no: "لا",
    search: "بحث",
    filter: "تصفية",
    clear: "مسح",
    apply: "تطبيق",
    share: "مشاركة",
    copy: "نسخ",
    copied: "تم النسخ!",
    noResults: "لا توجد نتائج",
    optional: "اختياري",
    required: "مطلوب",
    all: "الكل",
    more: "المزيد",
    less: "أقل",
    seeAll: "عرض الكل",
    noData: "لا توجد بيانات",
    refresh: "تحديث",
  },
  auth: {
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    newPassword: "كلمة مرور جديدة",
    phone: "رقم الهاتف",
    otp: "رمز التحقق",
    sendOtp: "إرسال OTP",
    verifyOtp: "التحقق من OTP",
    resendOtp: "إعادة إرسال OTP",
    fullName: "الاسم الكامل",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    welcomeBack: "مرحبًا بعودتك!",
    loginToContinue: "سجّل الدخول للمتابعة",
    createYourAccount: "أنشئ حسابك",
    joinVoxLink: "انضم إلى VoxLink اليوم",
    enterOtp: "أدخل رمز OTP المُرسَل إلى",
    passwordResetSent: "تم إرسال بريد إعادة تعيين كلمة المرور",
    checkEmail: "تحقق من بريدك الإلكتروني للتعليمات",
    passwordChanged: "تم تغيير كلمة المرور بنجاح",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    accountDeleted: "تم حذف الحساب بنجاح",
    deleteAccountConfirm: "هل أنت متأكد من أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.",
    tagline: "تواصل. تحدّث. انمُ.",
    welcomeToVoxLink: "مرحبًا بك في VoxLink",
    autoCreateAccount: "مستخدم جديد؟ سننشئ حسابك تلقائيًا عند أول تسجيل دخول",
    continueWithGoogle: "المتابعة عبر Google",
    signingIn: "جارٍ تسجيل الدخول...",
    or: "أو",
    quickLogin: "تسجيل دخول سريع",
    pleaseWait: "يرجى الانتظار...",
    quickLoginNote: "يحفظ تسجيل الدخول السريع حسابك على هذا الجهاز — أعد التثبيت وسيظل ملكك",
    welcomeName: "مرحبًا، {name}!",
    welcomeBackToast: "مرحبًا بعودتك!",
    quickLoginTitle: "تسجيل دخول سريع",
    accountCreated: "تم إنشاء الحساب! مرحبًا بك في VoxLink.",
    welcomeTitle: "مرحبًا",
    connectionError: "لا يوجد اتصال بالإنترنت. يرجى التحقق من شبكتك.",
    connectionErrorTitle: "خطأ في الاتصال",
    quickLoginFailed: "فشل تسجيل الدخول السريع. يرجى المحاولة مجددًا.",
  },
  nav: {
    home: "الرئيسية",
    search: "بحث",
    messages: "الرسائل",
    wallet: "المحفظة",
    profile: "الملف الشخصي",
    notifications: "الإشعارات",
  },
  home: {
    greeting: "مرحبًا",
    findHosts: "ابحث عن مضيف",
    topListeners: "أبرز المستمعين",
    trending: "الأكثر رواجًا",
    newHosts: "مضيفون جدد",
    onlineNow: "متصل الآن",
    featuredHosts: "مضيفون مميزون",
    seeAll: "عرض الكل",
    searchPlaceholder: "ابحث عن مضيفين ومواضيع...",
    findMore: "اكتشف المزيد",
    findMoreSub: "تواصل مع مستمع عشوائي الآن",
    startRandomCall: "ابدأ مكالمة عشوائية",
    welcome: "مرحبًا",
    freeMinutesTitle: "{count} دقائق مكالمة مجانية متاحة!",
    freeMinutesSub: "أول {count} دقائق لك على حسابنا — ابدأ مكالمة مع أي مضيف.",
    lowOnCoins: "رصيد العملات منخفض (متبقٍ {count})",
    lowOnCoinsSub: "أعد الشحن الآن حتى لا تنقطع مكالمتك في منتصفها.",
    topUp: "إعادة شحن",
    yourFavorites: "مفضلاتك",
    viewAll: "عرض الكل",
    recommendedForYou: "موصى به لك",
    browseByTopic: "تصفّح حسب الموضوع",
    availableNow: "متاح الآن",
    online: "متصل",
    noListenersAvailable: "لا يوجد مستمعون متاحون الآن",
    offlineListeners: "مستمعون غير متصلين",
  },

  // Random Match
  random: {
    title: "مطابقة عشوائية",
    randomMatch: "🎲 مطابقة عشوائية",
    cancel: "إلغاء",
    voiceCall: "مكالمة صوتية",
    videoCall: "مكالمة فيديو",
    findingMatch: "نبحث عن تطابق…",
    listenersOnline: "{count} مستمع متصل",
    listenerOnline: "{count} مستمع متصل",
    chooseCallType: "اختر نوع المكالمة",
    matchFound: "تم التطابق! 🎉",
    accept: "قبول",
    decline: "رفض",
    skipNext: "تخطٍ / التالي",
    checking: "جارٍ التحقق…",
    filters: "عوامل التصفية",
    matchFilters: "عوامل تصفية المطابقة",
    gender: "الجنس",
    genderAny: "الكل",
    genderMale: "ذكر",
    genderFemale: "أنثى",
    minimumRating: "الحد الأدنى للتقييم",
    ratingAny: "أي تقييم",
    rating3: "3★ +",
    rating4: "4★ +",
    rating4_5: "4.5★ +",
    reset: "إعادة تعيين",
    done: "تم",
    myBalance: "رصيدي",
    needCoins: "تحتاج إلى {count} عملة على الأقل لبدء هذه المكالمة.",
    statusInsufficientCoins: "العملات غير كافية لبدء مكالمة عشوائية.",
    statusNotEnoughCoinsTitle: "عملات غير كافية",
    statusRateLimited: "تمهّل قليلاً، ثم حاول مجددًا…",
    statusDailyLimit: "بلغت الحد اليومي للمطابقات.",
    statusDeclineCooldown: "عدد كبير من الرفض — خذ استراحة قصيرة.",
    statusNoMatchFilters: "لا يوجد مضيف يطابق فلاترك — جرّب تخفيفها.",
    statusSearching: "نبحث بين المستمعين المتصلين…",
    statusNoneOnline: "لا يوجد مستمعون متصلون الآن — لا نزال نبحث…",
    statusGiveUp: "لم نعثر على مضيف الآن. حاول لاحقًا.",
    statusNetworkError: "خطأ شبكة، إعادة المحاولة…",
    statusServerUnreachable: "تعذّر الوصول إلى الخادم. يُرجى المحاولة مجددًا.",
    hostBusy: "المضيف مشغول الآن — نبحث عن غيره.",
    hostOffline: "خرج المضيف عن الاتصال — نبحث عن غيره.",
    hostUnavailable: "المضيف غير متاح — نبحث عن غيره.",
    failedLoadHosts: "تعذّر تحميل المضيفين المتاحين.",
  },
  hosts: {
    host: "مضيف",
    listener: "مستمع",
    online: "متصل",
    offline: "غير متصل",
    busy: "مشغول",
    rating: "التقييم",
    reviews: "التقييمات",
    review: "تقييم",
    coinsPerMinute: "عملة/دقيقة",
    totalMinutes: "إجمالي الدقائق",
    specialties: "التخصصات",
    languages: "اللغات",
    about: "عن",
    callNow: "اتصل الآن",
    audioCall: "مكالمة صوتية",
    videoCall: "مكالمة مرئية",
    sendMessage: "إرسال رسالة",
    talkNow: "تحدث الآن",
    noHostsFound: "لم يتم العثور على مضيفين",
    adjustFilters: "حاول تعديل الفلاتر",
    topRated: "الأعلى تقييمًا",
    viewProfile: "عرض الملف",
    startCall: "بدء المكالمة",
  },
  calls: {
    incoming: "مكالمة واردة",
    outgoing: "جاري الاتصال...",
    ongoing: "في مكالمة",
    ended: "انتهت المكالمة",
    audio: "مكالمة صوتية",
    video: "مكالمة مرئية",
    accept: "قبول",
    decline: "رفض",
    endCall: "إنهاء المكالمة",
    mute: "كتم الصوت",
    unmute: "إلغاء الكتم",
    speaker: "مكبر الصوت",
    flipCamera: "قلب الكاميرا",
    callDuration: "مدة المكالمة",
    callWith: "مكالمة مع",
    rateCall: "قيّم هذه المكالمة",
    callHistory: "سجل المكالمات",
    noCallHistory: "لا يوجد سجل مكالمات",
    callCost: "تكلفة المكالمة",
    perMinute: "في الدقيقة",
    lowBalance: "رصيد العملات منخفض",
    lowBalanceMsg: "رصيدك من العملات منخفض. أعد الشحن للمتابعة.",
    callEnded: "انتهت المكالمة",
    callEndedMsg: "انتهت مكالمتك",
    missed: "فائتة",
    answered: "مُجاب",
    rejected: "مرفوضة",
    callingHistory: "سجل المكالمات",
    audioShort: "صوت",
    videoShort: "فيديو",
    incomingVideo: "مكالمة فيديو واردة",
    incomingAudio: "مكالمة صوتية واردة",
    unknown: "غير معروف",
    voxlinkHost: "مضيف VoxLink",
    voxlinkUser: "مستخدم VoxLink",
    voiceCall: "مكالمة صوتية",
    callDeclined: "تم رفض المكالمة",
    noAnswer: "لا يوجد رد",
    ringing: "يرن",
    connecting: "جارٍ الاتصال",
    coinsPerMin: "عملة / دقيقة",
    oneMinMinimum: "الحد الأدنى دقيقة واحدة",
    callAutoEnded: "انتهت المكالمة تلقائيًا",
    autoDisconnected: "نفدت عملاتك — تم قطع المكالمة تلقائيًا",
    with: "مع",
    minBilling: "تم تطبيق فوترة دقيقة واحدة كحد أدنى",
    duration: "المدة",
    coinsSpent: "العملات المنفقة",
    rateName: "قيّم {name}",
    feedbackHelps: "ملاحظاتك تساعد المضيف على التحسن",
    ratingPoor: "ضعيف",
    ratingFair: "مقبول",
    ratingGood: "جيد",
    ratingGreat: "رائع",
    ratingExcellent: "ممتاز!",
    submitRating: "إرسال التقييم",
    thankYou: "شكرًا! 🙏",
    ratingSubmitted: "تم إرسال تقييمك",
    rechargeCoins: "إعادة شحن العملات",
    backHome: "العودة إلى الرئيسية",
    rateFailed: "فشل إرسال التقييم، يرجى المحاولة مجددًا.",
    errorTitle: "خطأ",
    completed: "مكتملة",
    cancelled: "ملغاة",
    noCallHistoryFound: "لم يتم العثور على سجل مكالمات",
    failedLoadHistory: "فشل تحميل سجل المكالمات.",
    micAccessNeeded: "مطلوب الوصول إلى الميكروفون — اضغط للإصلاح",
    coinsRunningLow: "العملات على وشك النفاد",
    secondsRemaining: "{count}ث متبقية",
    minLeft: "{count} دقيقة متبقية",
    ringingDots: "يرن...",
    connectingDots: "جارٍ الاتصال...",
    connected: "متصل",
    networkDrop: "انقطاع الشبكة — جارٍ إعادة الاتصال...",
    connectionFailed: "فشل الاتصال — جارٍ إعادة المحاولة...",
    callEndedShort: "انتهت المكالمة",
    mutedHint: "🔇 صامت",
    speakerOn: "مكبر الصوت مفعّل",
    runningOutCoins: "عملاتك على وشك النفاد!",
    autoDisconnectIn: "سيتم قطع المكالمة خلال {time}",
    second: "ثانية",
    seconds: "ثوانٍ",
    fewSeconds: "بضع ثوانٍ",
    rechargeNow: "أعد الشحن الآن",
    continueCall: "متابعة المكالمة",
    cameraOff: "الكاميرا مغلقة",
    cameraUnavailable: "الكاميرا غير متاحة",
    startingCamera: "جارٍ تشغيل الكاميرا…",
    noPermission: "لا يوجد إذن",
    cameraOffShort: "الكاميرا مغلقة",
    you: "أنت",
    mutedLabel: "صامت",
    noMic: "لا ميكروفون",
    lowCoins: "عملات قليلة",
    secondsLeft: "{count}ث متبقية",
    connectionIssue: "مشكلة في الاتصال",
    live: "مباشر",
    waitingResponse: "في انتظار الرد...",
    camera: "الكاميرا",
    camOff: "إيقاف الكاميرا",
    end: "إنهاء",
    flip: "تبديل",
    earpiece: "سماعة الأذن",
  },
  chat: {
    messages: "الرسائل",
    newMessage: "رسالة جديدة",
    typeMessage: "اكتب رسالة...",
    send: "إرسال",
    noMessages: "لا توجد رسائل بعد",
    startConversation: "ابدأ محادثة",
    online: "متصل",
    offline: "غير متصل",
    typing: "يكتب...",
    delivered: "تم التسليم",
    read: "مقروء",
    deleteChat: "حذف المحادثة",
    deleteChatConfirm: "هل أنت متأكد من حذف هذه المحادثة؟",
    chats: "المحادثات",
    searchConversations: "ابحث في المحادثات...",
    noConversationsFound: "لم يتم العثور على محادثات",
    noConversationsYet: "لا توجد محادثات بعد",
    tryDifferentName: "جرّب اسمًا آخر",
    startChattingAfterCall: "ابدأ الدردشة بعد مكالمة مع مضيف",
  },
  wallet: {
    wallet: "المحفظة",
    coinBalance: "رصيد العملات",
    coins: "عملات",
    coin: "عملة",
    buyCoins: "شراء عملات",
    coinHistory: "سجل العملات",
    transactions: "المعاملات",
    noTransactions: "لا توجد معاملات بعد",
    purchased: "مشتراة",
    spent: "مُنفَق",
    bonus: "مكافأة",
    refunded: "مسترد",
    withdrawal: "سحب",
    totalSpent: "إجمالي الإنفاق",
    totalPurchased: "إجمالي الشراء",
    popular: "الأكثر شعبية",
    bestValue: "أفضل قيمة",
    bonus_label: "مكافأة",
    recharge: "إعادة شحن",
    choosePackage: "اختر الباقة",
    instantDelivery: "تسليم فوري",
    securePayment: "دفع آمن",
    guaranteed: "ضمان الرضا",
  },
  profile: {
    profile: "الملف الشخصي",
    editProfile: "تعديل الملف",
    myProfile: "ملفي الشخصي",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    other: "آخر",
    country: "البلد",
    bio: "النبذة",
    language: "اللغة",
    settings: "الإعدادات",
    helpCenter: "مركز المساعدة",
    privacy: "سياسة الخصوصية",
    about: "عن VoxLink",
    shareApp: "مشاركة VoxLink",
    rateApp: "قيّم التطبيق",
    logout: "تسجيل الخروج",
    deleteAccount: "حذف الحساب",
    callHistory: "سجل المكالمات",
    joinedOn: "انضم في",
    totalCalls: "إجمالي المكالمات",
    hoursSpent: "الساعات المُقضاة",
  },
  settings: {
    settings: "الإعدادات",
    notifications: "الإشعارات",
    callNotifications: "إشعارات المكالمات",
    messageNotifications: "إشعارات الرسائل",
    promoNotifications: "الإشعارات الترويجية",
    language: "اللغة",
    theme: "المظهر",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    systemDefault: "افتراضي النظام",
    privacy: "الخصوصية",
    security: "الأمان",
    changePassword: "تغيير كلمة المرور",
    twoFactor: "التحقق بخطوتين",
    account: "الحساب",
    support: "الدعم",
  },
  payment: {
    checkout: "إتمام الشراء",
    selectPackage: "اختر الباقة",
    paymentMethod: "طريقة الدفع",
    creditCard: "بطاقة ائتمان/خصم",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "جاري معالجة الدفع...",
    paymentSuccess: "تمت عملية الدفع بنجاح!",
    paymentFailed: "فشلت عملية الدفع",
    orderSummary: "ملخص الطلب",
    total: "الإجمالي",
    coins: "عملات",
    bonusCoins: "عملات مكافأة",
    tryAgain: "حاول مجددًا",
    secureNote: "جميع المدفوعات مؤمّنة ومشفّرة",
  },
  host: {
    dashboard: "لوحة التحكم",
    totalEarnings: "إجمالي الأرباح",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    totalCalls: "إجمالي المكالمات",
    avgRating: "متوسط التقييم",
    onlineStatus: "حالة الاتصال",
    goOnline: "تسجيل الدخول",
    goOffline: "تسجيل الخروج",
    setBusy: "تعيين كمشغول",
    earnings: "الأرباح",
    withdraw: "سحب",
    withdrawal: "سحب الأرباح",
    minimumWithdraw: "الحد الأدنى 100 عملة",
    enterAmount: "أدخل المبلغ",
    withdrawMethod: "طريقة السحب",
    bankTransfer: "تحويل بنكي",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "تفاصيل الحساب",
    withdrawSuccess: "تم تقديم طلب السحب",
    withdrawPending: "طلبك قيد المعالجة",
    hostSettings: "إعدادات المضيف",
    availability: "التوفر",
    payoutSettings: "إعدادات الدفع",
    becomeHost: "كن مضيفًا",
    apply: "تقدّم الآن",
    applicationSent: "تم إرسال الطلب!",
    applicationDesc: "سنراجع طلبك ونتواصل معك خلال 2-3 أيام عمل.",
  },
  errors: {
    network: "خطأ في الشبكة. يرجى التحقق من اتصالك.",
    server: "خطأ في الخادم. يرجى المحاولة لاحقًا.",
    unauthorized: "انتهت الجلسة. يرجى تسجيل الدخول مجددًا.",
    notFound: "المورد المطلوب غير موجود.",
    insufficientCoins: "عملات غير كافية. يرجى إعادة الشحن.",
    callFailed: "لا يمكن الاتصال. يرجى المحاولة مجددًا.",
    permissionDenied: "تم رفض الإذن.",
    generic: "حدث خطأ ما. يرجى المحاولة مجددًا.",
  },

  tabs: {
    home: "الرئيسية",
    listener: "مستمع",
    random: "عشوائي",
    chat: "محادثة",
    calling: "مكالمات",
  },

  listener: {
    allListeners: "جميع المستمعين",
    language: "اللغة",
    talkAbout: "تحدث عن",
    selectLanguage: "اختر اللغة",
    noListenersFound: "لم يتم العثور على مستمعين",
    failedLoad: "فشل تحميل المستمعين.",
    available: "متاح",
    offline: "غير متصل",
    audio: "صوت",
    video: "فيديو",
    perMin: "/دقيقة",
    hrs: "ساعة",
  },

  onboarding: {
    find: "اكتشف",
    findDesc: "يمكنك التواصل مع أشخاص حول\nالعالم للدردشة والرسائل\nوبناء علاقات معهم.",
    chat: "دردشة",
    chatDesc: "دردش مع الغرباء لتتعرفوا على\nبعضكم بشكل أفضل وتحظوا\nبتوافق جيد.",
    videoCall: "مكالمة فيديو",
    videoCallDesc: "يمكنك مشاركة مقاطع الفيديو والصور\nمع أصدقائك ومعارفك.",
  },

  hostsScreen: {
    allHosts: "كل المضيفين",
    failedLoad: "تعذّر تحميل المضيفين. اسحب للتحديث.",
  },

  reviews: {
    failedLoad: "تعذّر تحميل المراجعات.",
    reviewsCount: "{count} مراجعات",
    noReviews: "لا توجد مراجعات بعد",
    beFirst: "كن أول من يترك مراجعة",
    user: "مستخدم",
    today: "اليوم",
    yesterday: "أمس",
    daysAgo: "قبل {count} أيام",
    weekAgo: "قبل {count} أسبوع",
    weeksAgo: "قبل {count} أسابيع",
    monthAgo: "قبل {count} شهر",
    monthsAgo: "قبل {count} أشهر",
  },
};

export default ar;
