// VoxLink — Arabic Strings

const ar = {
  common: {
    minute: "دقيقة",
    minutes: "دقائق",
    vip: "VIP",
    ok: "موافق",
    cancel: "إلغاء",
    confirm: "تأكيد",
    save: "حفظ",
    delete: "حذف",
    edit: "تعديل",
    done: "تم",
    back: "رجوع",
    close: "إغلاق",
    loading: "جاري التحميل...",
    error: "حدث خطأ",
    retry: "حاول مجددًا",
    submit: "إرسال",
    next: "التالي",
    skip: "تخطي",
    yes: "نعم",
    no: "لا",
    search: "بحث",
    filter: "تصفية",
    clear: "مسح",
    apply: "تطبيق",
    share: "مشاركة",
    copy: "نسخ",
    copied: "تم النسخ!",
    noResults: "لا توجد نتائج",
    optional: "اختياري",
    required: "مطلوب",
    all: "الكل",
    more: "المزيد",
    less: "أقل",
    seeAll: "عرض الكل",
    noData: "لا توجد بيانات",
    refresh: "تحديث",
  },
  auth: {
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    newPassword: "كلمة مرور جديدة",
    phone: "رقم الهاتف",
    otp: "رمز التحقق",
    sendOtp: "إرسال OTP",
    verifyOtp: "التحقق من OTP",
    resendOtp: "إعادة إرسال OTP",
    fullName: "الاسم الكامل",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    welcomeBack: "مرحبًا بعودتك!",
    loginToContinue: "سجّل الدخول للمتابعة",
    createYourAccount: "أنشئ حسابك",
    joinVoxLink: "انضم إلى VoxLink اليوم",
    enterOtp: "أدخل رمز OTP المُرسَل إلى",
    passwordResetSent: "تم إرسال بريد إعادة تعيين كلمة المرور",
    checkEmail: "تحقق من بريدك الإلكتروني للتعليمات",
    passwordChanged: "تم تغيير كلمة المرور بنجاح",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    accountDeleted: "تم حذف الحساب بنجاح",
    deleteAccountConfirm: "هل أنت متأكد من أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.",
    tagline: "تواصل. تحدّث. انمُ.",
    welcomeToVoxLink: "مرحبًا بك في VoxLink",
    autoCreateAccount: "مستخدم جديد؟ سننشئ حسابك تلقائيًا عند أول تسجيل دخول",
    continueWithGoogle: "المتابعة عبر Google",
    signingIn: "جارٍ تسجيل الدخول...",
    or: "أو",
    quickLogin: "تسجيل دخول سريع",
    pleaseWait: "يرجى الانتظار...",
    quickLoginNote: "يحفظ تسجيل الدخول السريع حسابك على هذا الجهاز — أعد التثبيت وسيظل ملكك",
    welcomeName: "مرحبًا، {name}!",
    welcomeBackToast: "مرحبًا بعودتك!",
    quickLoginTitle: "تسجيل دخول سريع",
    accountCreated: "تم إنشاء الحساب! مرحبًا بك في VoxLink.",
    welcomeTitle: "مرحبًا",
    connectionError: "لا يوجد اتصال بالإنترنت. يرجى التحقق من شبكتك.",
    connectionErrorTitle: "خطأ في الاتصال",
    quickLoginFailed: "فشل تسجيل الدخول السريع. يرجى المحاولة مجددًا.",
  },
  nav: {
    home: "الرئيسية",
    search: "بحث",
    messages: "الرسائل",
    wallet: "المحفظة",
    profile: "الملف الشخصي",
    notifications: "الإشعارات",
  },
  home: {
    dailyFreeTitle: "{count} دقيقة مكالمة مجانية اليوم!",
    dailyFreeSub: "احصل على دقائقك المجانية اليومية واتصل بأي مضيف مجاناً.",
    dailyFreeA11y: "احصل على {count} دقيقة مكالمة مجانية",
    claim: "احصل عليها",
    dailyFreeClaimedTitle: "تم الحصول على الدقائق المجانية",
    dailyFreeClaimedBody: "🎁 تمت إضافة {count} {unit} مجانية! اختر مضيفاً واتصل مجاناً.",
    freeMinutesA11y: "{count} دقيقة مكالمة مجانية متاحة. اضغط لاختيار مضيف وبدء مكالمة.",
    greeting: "مرحبًا",
    findHosts: "ابحث عن مضيف",
    topListeners: "أبرز المستمعين",
    trending: "الأكثر رواجًا",
    newHosts: "مضيفون جدد",
    onlineNow: "متصل الآن",
    featuredHosts: "مضيفون مميزون",
    seeAll: "عرض الكل",
    searchPlaceholder: "ابحث عن مضيفين ومواضيع...",
    findMore: "اكتشف المزيد",
    findMoreSub: "تواصل مع مستمع عشوائي الآن",
    startRandomCall: "ابدأ مكالمة عشوائية",
    welcome: "مرحبًا",
    freeMinutesTitle: "{count} دقائق مكالمة مجانية متاحة!",
    freeMinutesSub: "أول {count} دقائق لك على حسابنا — ابدأ مكالمة مع أي مضيف.",
    lowOnCoins: "رصيد العملات منخفض (متبقٍ {count})",
    lowOnCoinsSub: "أعد الشحن الآن حتى لا تنقطع مكالمتك في منتصفها.",
    topUp: "إعادة شحن",
    yourFavorites: "مفضلاتك",
    viewAll: "عرض الكل",
    recommendedForYou: "موصى به لك",
    browseByTopic: "تصفّح حسب الموضوع",
    availableNow: "متاح الآن",
    online: "متصل",
    noListenersAvailable: "لا يوجد مستمعون متاحون الآن",
    offlineListeners: "مستمعون غير متصلين",
  },

  // Random Match
  random: {
    title: "مطابقة عشوائية",
    randomMatch: "🎲 مطابقة عشوائية",
    cancel: "إلغاء",
    voiceCall: "مكالمة صوتية",
    videoCall: "مكالمة فيديو",
    findingMatch: "نبحث عن تطابق…",
    listenersOnline: "{count} مستمع متصل",
    listenerOnline: "{count} مستمع متصل",
    chooseCallType: "اختر نوع المكالمة",
    matchFound: "تم التطابق! 🎉",
    accept: "قبول",
    decline: "رفض",
    skipNext: "تخطٍ / التالي",
    checking: "جارٍ التحقق…",
    filters: "عوامل التصفية",
    matchFilters: "عوامل تصفية المطابقة",
    gender: "الجنس",
    genderAny: "الكل",
    genderMale: "ذكر",
    genderFemale: "أنثى",
    minimumRating: "الحد الأدنى للتقييم",
    ratingAny: "أي تقييم",
    rating3: "3★ +",
    rating4: "4★ +",
    rating4_5: "4.5★ +",
    reset: "إعادة تعيين",
    done: "تم",
    myBalance: "رصيدي",
    needCoins: "تحتاج إلى {count} عملة على الأقل لبدء هذه المكالمة.",
    statusInsufficientCoins: "العملات غير كافية لبدء مكالمة عشوائية.",
    statusNotEnoughCoinsTitle: "عملات غير كافية",
    statusRateLimited: "تمهّل قليلاً، ثم حاول مجددًا…",
    statusDailyLimit: "بلغت الحد اليومي للمطابقات.",
    statusDeclineCooldown: "عدد كبير من الرفض — خذ استراحة قصيرة.",
    statusNoMatchFilters: "لا يوجد مضيف يطابق فلاترك — جرّب تخفيفها.",
    statusSearching: "نبحث بين المستمعين المتصلين…",
    statusNoneOnline: "لا يوجد مستمعون متصلون الآن — لا نزال نبحث…",
    statusGiveUp: "لم نعثر على مضيف الآن. حاول لاحقًا.",
    statusNetworkError: "خطأ شبكة، إعادة المحاولة…",
    statusServerUnreachable: "تعذّر الوصول إلى الخادم. يُرجى المحاولة مجددًا.",
    retryIn: "أعد المحاولة خلال {time}",
    dailyLimitReset: "تتم إعادة التعيين غدًا",
    hostBusy: "المضيف مشغول الآن — نبحث عن غيره.",
    hostOffline: "خرج المضيف عن الاتصال — نبحث عن غيره.",
    hostUnavailable: "المضيف غير متاح — نبحث عن غيره.",
    failedLoadHosts: "تعذّر تحميل المضيفين المتاحين.",
  },
  hosts: {
    host: "مضيف",
    listener: "مستمع",
    online: "متصل",
    offline: "غير متصل",
    busy: "مشغول",
    rating: "التقييم",
    reviews: "التقييمات",
    review: "تقييم",
    coinsPerMinute: "عملة/دقيقة",
    totalMinutes: "إجمالي الدقائق",
    specialties: "التخصصات",
    languages: "اللغات",
    about: "عن",
    callNow: "اتصل الآن",
    audioCall: "مكالمة صوتية",
    videoCall: "مكالمة مرئية",
    sendMessage: "إرسال رسالة",
    talkNow: "تحدث الآن",
    noHostsFound: "لم يتم العثور على مضيفين",
    adjustFilters: "حاول تعديل الفلاتر",
    topRated: "الأعلى تقييمًا",
    viewProfile: "عرض الملف",
    startCall: "بدء المكالمة",
  },
  calls: {
    freeMinLeft: "{count} دقيقة مجانية متبقية",
    freeMin: "{count} دقيقة مجانية",
    incoming: "مكالمة واردة",
    outgoing: "جاري الاتصال...",
    ongoing: "في مكالمة",
    ended: "انتهت المكالمة",
    audio: "مكالمة صوتية",
    video: "مكالمة مرئية",
    accept: "قبول",
    decline: "رفض",
    endCall: "إنهاء المكالمة",
    mute: "كتم الصوت",
    unmute: "إلغاء الكتم",
    speaker: "مكبر الصوت",
    flipCamera: "قلب الكاميرا",
    callDuration: "مدة المكالمة",
    callWith: "مكالمة مع",
    rateCall: "قيّم هذه المكالمة",
    callHistory: "سجل المكالمات",
    noCallHistory: "لا يوجد سجل مكالمات",
    callCost: "تكلفة المكالمة",
    perMinute: "في الدقيقة",
    lowBalance: "رصيد العملات منخفض",
    lowBalanceMsg: "رصيدك من العملات منخفض. أعد الشحن للمتابعة.",
    callEnded: "انتهت المكالمة",
    callEndedMsg: "انتهت مكالمتك",
    missed: "فائتة",
    answered: "مُجاب",
    rejected: "مرفوضة",
    callingHistory: "سجل المكالمات",
    audioShort: "صوت",
    videoShort: "فيديو",
    incomingVideo: "مكالمة فيديو واردة",
    incomingAudio: "مكالمة صوتية واردة",
    unknown: "غير معروف",
    voxlinkHost: "مضيف VoxLink",
    voxlinkUser: "مستخدم VoxLink",
    voiceCall: "مكالمة صوتية",
    callDeclined: "تم رفض المكالمة",
    noAnswer: "لا يوجد رد",
    ringing: "يرن",
    connecting: "جارٍ الاتصال",
    coinsPerMin: "عملة / دقيقة",
    oneMinMinimum: "الحد الأدنى دقيقة واحدة",
    callAutoEnded: "انتهت المكالمة تلقائيًا",
    autoDisconnected: "نفدت عملاتك — تم قطع المكالمة تلقائيًا",
    connectionLost: "انقطعت المكالمة — فقد الاتصال. يرجى التحقق من شبكتك.",
    with: "مع",
    minBilling: "تم تطبيق فوترة دقيقة واحدة كحد أدنى",
    duration: "المدة",
    coinsSpent: "العملات المنفقة",
    rateName: "قيّم {name}",
    feedbackHelps: "ملاحظاتك تساعد المضيف على التحسن",
    ratingPoor: "ضعيف",
    ratingFair: "مقبول",
    ratingGood: "جيد",
    ratingGreat: "رائع",
    ratingExcellent: "ممتاز!",
    submitRating: "إرسال التقييم",
    thankYou: "شكرًا! 🙏",
    ratingSubmitted: "تم إرسال تقييمك",
    rechargeCoins: "إعادة شحن العملات",
    backHome: "العودة إلى الرئيسية",
    rateFailed: "فشل إرسال التقييم، يرجى المحاولة مجددًا.",
    errorTitle: "خطأ",
    completed: "مكتملة",
    cancelled: "ملغاة",
    noCallHistoryFound: "لم يتم العثور على سجل مكالمات",
    failedLoadHistory: "فشل تحميل سجل المكالمات.",
    micAccessNeeded: "مطلوب الوصول إلى الميكروفون — اضغط للإصلاح",
    coinsRunningLow: "العملات على وشك النفاد",
    secondsRemaining: "{count}ث متبقية",
    minLeft: "{count} دقيقة متبقية",
    ringingDots: "يرن...",
    connectingDots: "جارٍ الاتصال...",
    connected: "متصل",
    networkDrop: "انقطاع الشبكة — جارٍ إعادة الاتصال...",
    connectionFailed: "فشل الاتصال — جارٍ إعادة المحاولة...",
    callEndedShort: "انتهت المكالمة",
    mutedHint: "🔇 صامت",
    speakerOn: "مكبر الصوت مفعّل",
    runningOutCoins: "عملاتك على وشك النفاد!",
    autoDisconnectIn: "سيتم قطع المكالمة خلال {time}",
    second: "ثانية",
    seconds: "ثوانٍ",
    fewSeconds: "بضع ثوانٍ",
    rechargeNow: "أعد الشحن الآن",
    continueCall: "متابعة المكالمة",
    cameraOff: "الكاميرا مغلقة",
    cameraUnavailable: "الكاميرا غير متاحة",
    startingCamera: "جارٍ تشغيل الكاميرا…",
    noPermission: "لا يوجد إذن",
    cameraOffShort: "الكاميرا مغلقة",
    you: "أنت",
    mutedLabel: "صامت",
    noMic: "لا ميكروفون",
    lowCoins: "عملات قليلة",
    secondsLeft: "{count}ث متبقية",
    connectionIssue: "مشكلة في الاتصال",
    live: "مباشر",
    waitingResponse: "في انتظار الرد...",
    camera: "الكاميرا",
    camOff: "إيقاف الكاميرا",
    end: "إنهاء",
    flip: "تبديل",
    earpiece: "سماعة الأذن",
  },
  chat: {
    messages: "الرسائل",
    newMessage: "رسالة جديدة",
    typeMessage: "اكتب رسالة...",
    send: "إرسال",
    noMessages: "لا توجد رسائل بعد",
    startConversation: "ابدأ محادثة",
    online: "متصل",
    offline: "غير متصل",
    typing: "يكتب...",
    delivered: "تم التسليم",
    read: "مقروء",
    deleteChat: "حذف المحادثة",
    deleteChatConfirm: "هل أنت متأكد من حذف هذه المحادثة؟",
    chats: "المحادثات",
    searchConversations: "ابحث في المحادثات...",
    noConversationsFound: "لم يتم العثور على محادثات",
    noConversationsYet: "لا توجد محادثات بعد",
    tryDifferentName: "جرّب اسمًا آخر",
    startChattingAfterCall: "ابدأ الدردشة بعد مكالمة مع مضيف",
  },
  wallet: {
    wallet: "المحفظة",
    coinBalance: "رصيد العملات",
    coins: "عملات",
    coin: "عملة",
    buyCoins: "شراء عملات",
    coinHistory: "سجل العملات",
    transactions: "المعاملات",
    noTransactions: "لا توجد معاملات بعد",
    purchased: "مشتراة",
    spent: "مُنفَق",
    bonus: "مكافأة",
    refunded: "مسترد",
    withdrawal: "سحب",
    totalSpent: "إجمالي الإنفاق",
    totalPurchased: "إجمالي الشراء",
    popular: "الأكثر شعبية",
    bestValue: "أفضل قيمة",
    bonus_label: "مكافأة",
    recharge: "إعادة شحن",
    choosePackage: "اختر الباقة",
    instantDelivery: "تسليم فوري",
    securePayment: "دفع آمن",
    guaranteed: "ضمان الرضا",
  },
  profile: {
    profile: "الملف الشخصي",
    editProfile: "تعديل الملف",
    myProfile: "ملفي الشخصي",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    other: "آخر",
    country: "البلد",
    bio: "النبذة",
    language: "اللغة",
    settings: "الإعدادات",
    helpCenter: "مركز المساعدة",
    privacy: "سياسة الخصوصية",
    about: "عن VoxLink",
    shareApp: "مشاركة VoxLink",
    rateApp: "قيّم التطبيق",
    logout: "تسجيل الخروج",
    deleteAccount: "حذف الحساب",
    callHistory: "سجل المكالمات",
    joinedOn: "انضم في",
    totalCalls: "إجمالي المكالمات",
    hoursSpent: "الساعات المُقضاة",
  },
  settings: {
    settings: "الإعدادات",
    notifications: "الإشعارات",
    callNotifications: "إشعارات المكالمات",
    messageNotifications: "إشعارات الرسائل",
    promoNotifications: "الإشعارات الترويجية",
    language: "اللغة",
    theme: "المظهر",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    systemDefault: "افتراضي النظام",
    privacy: "الخصوصية",
    security: "الأمان",
    changePassword: "تغيير كلمة المرور",
    twoFactor: "التحقق بخطوتين",
    account: "الحساب",
    support: "الدعم",
  },
  payment: {
    checkout: "إتمام الشراء",
    selectPackage: "اختر الباقة",
    paymentMethod: "طريقة الدفع",
    creditCard: "بطاقة ائتمان/خصم",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "جاري معالجة الدفع...",
    paymentSuccess: "تمت عملية الدفع بنجاح!",
    paymentFailed: "فشلت عملية الدفع",
    orderSummary: "ملخص الطلب",
    total: "الإجمالي",
    coins: "عملات",
    bonusCoins: "عملات مكافأة",
    tryAgain: "حاول مجددًا",
    secureNote: "جميع المدفوعات مؤمّنة ومشفّرة",
  },
  host: {
    dashboard: "لوحة التحكم",
    totalEarnings: "إجمالي الأرباح",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    totalCalls: "إجمالي المكالمات",
    avgRating: "متوسط التقييم",
    onlineStatus: "حالة الاتصال",
    goOnline: "تسجيل الدخول",
    goOffline: "تسجيل الخروج",
    setBusy: "تعيين كمشغول",
    earnings: "الأرباح",
    withdraw: "سحب",
    withdrawal: "سحب الأرباح",
    minimumWithdraw: "الحد الأدنى 100 عملة",
    enterAmount: "أدخل المبلغ",
    withdrawMethod: "طريقة السحب",
    bankTransfer: "تحويل بنكي",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "تفاصيل الحساب",
    withdrawSuccess: "تم تقديم طلب السحب",
    withdrawPending: "طلبك قيد المعالجة",
    hostSettings: "إعدادات المضيف",
    availability: "التوفر",
    payoutSettings: "إعدادات الدفع",
    becomeHost: "كن مضيفًا",
    apply: "تقدّم الآن",
    applicationSent: "تم إرسال الطلب!",
    applicationDesc: "سنراجع طلبك ونتواصل معك خلال 2-3 أيام عمل.",
  },
  errors: {
    network: "خطأ في الشبكة. يرجى التحقق من اتصالك.",
    server: "خطأ في الخادم. يرجى المحاولة لاحقًا.",
    unauthorized: "انتهت الجلسة. يرجى تسجيل الدخول مجددًا.",
    notFound: "المورد المطلوب غير موجود.",
    insufficientCoins: "عملات غير كافية. يرجى إعادة الشحن.",
    callFailed: "لا يمكن الاتصال. يرجى المحاولة مجددًا.",
    permissionDenied: "تم رفض الإذن.",
    generic: "حدث خطأ ما. يرجى المحاولة مجددًا.",
  },

  tabs: {
    home: "الرئيسية",
    listener: "مستمع",
    random: "عشوائي",
    chat: "محادثة",
    calling: "مكالمات",
  },

  listener: {
    allListeners: "جميع المستمعين",
    language: "اللغة",
    talkAbout: "تحدث عن",
    selectLanguage: "اختر اللغة",
    noListenersFound: "لم يتم العثور على مستمعين",
    failedLoad: "فشل تحميل المستمعين.",
    available: "متاح",
    offline: "غير متصل",
    audio: "صوت",
    video: "فيديو",
    perMin: "/دقيقة",
    hrs: "ساعة",
  },

  onboarding: {
    find: "اكتشف",
    findDesc: "يمكنك التواصل مع أشخاص حول\nالعالم للدردشة والرسائل\nوبناء علاقات معهم.",
    chat: "دردشة",
    chatDesc: "دردش مع الغرباء لتتعرفوا على\nبعضكم بشكل أفضل وتحظوا\nبتوافق جيد.",
    videoCall: "مكالمة فيديو",
    videoCallDesc: "يمكنك مشاركة مقاطع الفيديو والصور\nمع أصدقائك ومعارفك.",
  },

  hostsScreen: {
    allHosts: "كل المضيفين",
    failedLoad: "تعذّر تحميل المضيفين. اسحب للتحديث.",
  },

  reviews: {
    failedLoad: "تعذّر تحميل المراجعات.",
    reviewsCount: "{count} مراجعات",
    noReviews: "لا توجد مراجعات بعد",
    beFirst: "كن أول من يترك مراجعة",
    user: "مستخدم",
    today: "اليوم",
    yesterday: "أمس",
    daysAgo: "قبل {count} أيام",
    weekAgo: "قبل {count} أسبوع",
    weeksAgo: "قبل {count} أسابيع",
    monthAgo: "قبل {count} شهر",
    monthsAgo: "قبل {count} أشهر",
  },

  notFound: {
    title: "عذرًا!",
    message: "هذه الشاشة غير موجودة.",
    goHome: "اذهب إلى الشاشة الرئيسية!",
  },

  aboutScreen: {
    title: "عن VoxLink",
    appTagline: "اتصال صوتي ومرئي",
    version: "الإصدار {version}",
    statActiveUsers: "المستخدمون النشطون",
    statHosts: "المضيفون",
    statCallsMade: "المكالمات التي أُجريت",
    statAppRating: "تقييم التطبيق",
    whatIsTitle: "ما هو VoxLink؟",
    whatIsBody1: "VoxLink هي منصة اجتماعية للمكالمات الصوتية والمرئية تربط الناس بمضيفين موثوقين لإجراء محادثات هادفة. سواء كنت بحاجة إلى نصائح حياتية أو ممارسة لغة أو دعم عاطفي أو مجرد شخص للحديث معه — مضيفونا هنا من أجلك.",
    whatIsBody2: "المضيفون أشخاص حقيقيون مدربون تم التحقق منهم بواسطة فريقنا. كل مكالمة آمنة وخاصة ومدعومة بنظام الدفع القائم على العملات — لذا تدفع فقط مقابل الوقت الذي تستخدمه.",
    keyFeatures: "الميزات الرئيسية",
    feature1: "مكالمات صوتية ومرئية عالية الدقة",
    feature2: "تشفير من طرف إلى طرف",
    feature3: "أكثر من 1,200 مضيف موثوق",
    feature4: "تسعير عادل قائم على العملات",
    feature5: "محادثة داخل التطبيق",
    feature6: "نظام مراجعات مُقيّم",
    connectWithUs: "تواصل معنا",
    linkWebsite: "الموقع الإلكتروني",
    linkTwitter: "Twitter / X",
    linkInstagram: "Instagram",
    linkContact: "اتصل بنا",
    helpCenter: "مركز المساعدة",
    copyright: "© 2026 VoxLink Inc. جميع الحقوق محفوظة.",
  },

  privacyScreen: {
    bannerTitle: "خصوصيتك تهمنا",
    bannerSub: "توضح هذه السياسة كيف يجمع VoxLink بياناتك ويستخدمها ويحميها.",
    lastUpdated: "آخر تحديث: 1 مارس 2026",
    contactTitle: "أسئلة حول الخصوصية؟",
    s1Title: "1. المعلومات التي نجمعها",
    s1Body: "نجمع المعلومات التي تقدمها لنا مباشرةً، مثل عند إنشاء حساب أو تحديث ملفك الشخصي أو إجراء عمليات شراء أو الاتصال بنا للدعم. ويشمل ذلك اسمك وعنوان بريدك الإلكتروني واسم المستخدم وصورة الملف الشخصي ومعلومات الدفع.\n\nنجمع أيضًا معلومات تلقائيًا عند استخدامك VoxLink، بما في ذلك بيانات السجل ومعلومات الجهاز ومعلومات الموقع (إن سُمح بها) وبيانات الاستخدام مثل الميزات التي تستخدمها والوقت الذي تقضيه في المكالمات.",
    s2Title: "2. كيف نستخدم معلوماتك",
    s2Body: "نستخدم المعلومات التي نجمعها لتقديم خدماتنا وصيانتها وتحسينها، ومعالجة المعاملات وإرسال المعلومات ذات الصلة، وإرسال الإشعارات والإشعارات الفنية والتحديثات ورسائل الدعم.\n\nنستخدم بياناتك أيضًا للرد على تعليقاتك وأسئلتك وطلباتك، ومراقبة الاتجاهات والاستخدام وتحليلها، واكتشاف المعاملات الاحتيالية والأنشطة غير القانونية الأخرى والتحقيق فيها ومنعها.",
    s3Title: "3. مشاركة المعلومات",
    s3Body: "لا نشارك معلوماتك الشخصية مع أطراف ثالثة إلا كما هو موضح في هذه السياسة. قد نشارك المعلومات مع البائعين والاستشاريين ومزودي الخدمات الآخرين الذين يحتاجون إلى الوصول إلى هذه المعلومات لتنفيذ العمل نيابةً عنا.\n\nقد نكشف معلوماتك إذا اعتقدنا أن الكشف يتوافق مع أي قانون أو إجراء قانوني معمول به أو مطلوب بموجبه، بما في ذلك الطلبات القانونية من السلطات العامة لتلبية متطلبات الأمن القومي أو إنفاذ القانون.",
    s4Title: "4. بيانات المكالمات والصوت",
    s4Body: "يتم نقل محتوى المكالمات الصوتية والمرئية عبر قنوات مشفرة. لا نسجل أو نخزن محتوى مكالماتك ما لم تُفعّل صراحةً ميزة التسجيل (إن كانت متاحة). يتم تخزين بيانات تعريف المكالمة (المدة والمشاركون والطوابع الزمنية) لتوفير ميزات الفوترة والسجل.",
    s5Title: "5. العملات والمدفوعات",
    s5Body: "تتم معالجة معلومات الدفع عبر معالجات دفع آمنة من جهات خارجية. لا نخزن تفاصيل بطاقة الدفع الكاملة على خوادمنا. يتم تسجيل معاملات العملات لأغراض المحاسبة وحل النزاعات.",
    s6Title: "6. أمن البيانات",
    s6Body: "نتخذ تدابير معقولة للمساعدة في حماية المعلومات المتعلقة بك من الفقدان والسرقة وسوء الاستخدام والوصول غير المصرح به والكشف والتغيير والتدمير. يتم تشفير جميع البيانات أثناء النقل باستخدام TLS وفي حالة السكون باستخدام تشفير AES-256.",
    s7Title: "7. الاحتفاظ بالبيانات",
    s7Body: "نحتفظ بالمعلومات الشخصية طالما كان ذلك ضروريًا لتقديم خدماتنا وتحقيق الأغراض المبينة في سياسة الخصوصية هذه، ما لم تكن هناك فترة احتفاظ أطول مطلوبة أو مسموح بها بموجب القانون. يمكنك طلب حذف حسابك والبيانات المرتبطة به في أي وقت من خلال شاشة الإعدادات.",
    s8Title: "8. خصوصية الأطفال",
    s8Body: "VoxLink غير مخصص للأطفال دون سن 18 عامًا. لا نجمع عن قصد معلومات شخصية من الأطفال دون سن 18. إذا علمنا أننا جمعنا معلومات شخصية من طفل دون سن 18، فسنحذف تلك المعلومات.",
    s9Title: "9. حقوقك",
    s9Body: "لديك الحق في الوصول إلى معلوماتك الشخصية أو تحديثها أو حذفها في أي وقت. يمكنك أيضًا الاعتراض على المعالجة أو طلب قابلية نقل البيانات أو سحب الموافقة عندما تستند المعالجة إلى الموافقة. لممارسة هذه الحقوق، اتصل بنا عبر مركز المساعدة.",
    s10Title: "10. التغييرات على هذه السياسة",
    s10Body: "قد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر. سنخطرك بأي تغييرات عن طريق نشر السياسة الجديدة على هذه الصفحة وتحديث تاريخ 'آخر تحديث'. استمرارك في استخدام VoxLink بعد أي تغيير يشكل قبولك لسياسة الخصوصية الجديدة.",
  },

  helpScreen: {
    submitRequest: "إرسال طلب",
    title: "مركز المساعدة",
    bannerTitle: "تحتاج مساعدة أو أسئلة شائعة؟",
    bannerSub: "اعثر على إجابات للأسئلة الشائعة",
    contactTitle: "هل لديك مشكلة؟",
    faqTitle: "الأسئلة الشائعة",
    q1: "ما هو VoxLink؟",
    a1: "VoxLink هي منصة اجتماعية يمكنك من خلالها التواصل مع مستمعين ومضيفين محترفين عبر المكالمات الصوتية أو المرئية. احصل على دعم مخصص حول مواضيع مثل العلاقات والمهنة والإرشاد الحياتي والمزيد.",
    q2: "من هم المضيفون/المستمعون؟",
    a2: "المضيفون محترفون موثوقون أو أفراد ذوو خبرة يقدمون الدعم والمحادثة. يتخصصون في مواضيع متنوعة ومتاحون للمكالمات الصوتية والمرئية.",
    q3: "كيف أجري مكالمة؟",
    a3: "تصفح المضيفين المتاحين على الشاشة الرئيسية، اضغط على بطاقة مضيف لعرض ملفه الشخصي، ثم اضغط على 'تحدث الآن' لبدء مكالمة صوتية أو مرئية. تُحتسب المكالمات بالعملات لكل دقيقة.",
    q4: "ما هي العملات؟",
    a4: "العملات هي العملة داخل تطبيق VoxLink. تشتري باقات العملات من قسم المحفظة وتنفقها أثناء المكالمات مع المضيفين وفق سعرهم المعلن لكل دقيقة.",
    q5: "هل محادثتي خاصة؟",
    a5: "نعم، جميع المحادثات خاصة وسرية. نتبع سياسات صارمة لحماية البيانات ولا نشارك تفاصيل المحادثات الشخصية مع أطراف ثالثة.",
    q6: "كيف أصبح مضيفًا؟",
    a6: "تتم الاستضافة عبر تطبيقنا المنفصل VoxLink Host. نزّل تطبيق Host للتقديم والتحقق من هويتك والبدء في تلقي المكالمات والكسب.",
    q7: "ماذا لو نفدت عملاتي؟",
    a7: "إذا نفدت عملاتك أثناء مكالمة، فستنتهي المكالمة تلقائيًا. يمكنك شراء المزيد من العملات في أي وقت من قسم المحفظة.",
  },

  coinHistory: {
    title: "سجل العملات",
    currentBalance: "الرصيد الحالي",
    earned: "المكتسبة",
    spent: "المنفقة",
    tabAll: "الكل",
    tabPurchase: "شراء",
    tabSpent: "منفق",
    tabBonus: "مكافأة",
    today: "اليوم",
    yesterday: "أمس",
    ref: "مرجع:",
    noTransactions: "لم يتم العثور على معاملات",
    failedLoad: "فشل تحميل سجل العملات.",
  },

  notificationsScreen: {
    markAllRead: "تحديد الكل كمقروء",
    empty: "لا توجد إشعارات بعد",
    goBack: "رجوع",
    markAllReadLabel: "تحديد جميع الإشعارات كمقروءة",
    failedLoad: "فشل تحميل الإشعارات.",
    failedMarkAll: "فشل تحديد الإشعارات كمقروءة.",
    failedUpdate: "فشل تحديث الإشعار.",
  },

  searchHosts: {
    searchPlaceholder: "ابحث عن المضيفين بالاسم...",
    topic: "الموضوع",
    status: "الحالة",
    language: "اللغة",
    hostsFound: "تم العثور على {count} مضيف",
    noResults: "لم يتم العثور على مضيفين يطابقون بحثك",
    talk: "تحدث",
    failedLoad: "فشل تحميل المضيفين.",
  },

  chatScreen: {
    defaultName: "محادثة",
    emptyHint: "أرسل رسالة لبدء المحادثة",
    sending: "جارٍ الإرسال…",
    tapToRetry: "اضغط لإعادة المحاولة",
    a11yBack: "رجوع",
    a11yPhotoMessage: "رسالة صورة",
    a11yRetry: "إعادة إرسال الرسالة",
    a11yAttach: "إرفاق صورة",
    a11ySend: "إرسال رسالة",
    permissionTitle: "الإذن مطلوب",
    permissionPhoto: "يرجى السماح بالوصول إلى مكتبة الصور لإرسال صورة.",
    failedLoadMessages: "فشل تحميل الرسائل.",
    uploadFailed: "فشل الرفع. يرجى المحاولة مجددًا.",
    photoSendFailed: "تعذّر إرسال الصورة. يرجى المحاولة مجددًا.",
  },

  hostDetail: {
    freeFirstMinutes: "🎁 أول {count} {unit} مجانية لك",
    notFound: "لم يتم العثور على المضيف",
    selectCallType: "اختر نوع المكالمة",
    highlights: "أبرز اللحظات",
    introVideo: "فيديو تعريفي",
    coinPerMin: "{count} عملة/دقيقة",
    coin: "{count} عملة",
    levelShort: "مستوى",
    languageColon: "اللغة : ",
    idLabel: "المعرّف:",
    totalCall: "إجمالي المكالمات",
    experience: "الخبرة",
    recent: "حديثًا",
    chatNow: "تحدث الآن",
    chatLocked: "🔒 محادثة",
    chatLockedTitle: "🔒 المحادثة مقفلة",
    chatLockedMsg: "للدردشة مع {name}، عليك الاتصال به أولاً. تُفتح المحادثة تلقائيًا بعد المكالمة!",
    chatLockedMsg2: "أجرِ مكالمة أولاً، ثم ستُفتح المحادثة تلقائيًا!",
    offlineMsg: "{name} غير متصل حاليًا.",
    idCopied: "تم نسخ معرّف المضيف إلى الحافظة.",
    reportThanks: "شكرًا على بلاغك. سيراجعه فريقنا قريبًا.",
    reportSubmitted: "تم إرسال البلاغ",
    reportFailMsg: "تعذّر إرسال البلاغ. يرجى المحاولة مجددًا.",
    reportFailed: "فشل البلاغ",
    failedLoad: "فشل تحميل تفاصيل المضيف.",
    reportTitle: "الإبلاغ عن {name}",
    reportSubtitle: "لماذا تبلّغ عن هذا المضيف؟",
    reportInappropriate: "محتوى غير لائق",
    reportHarassment: "تحرش",
    reportFakeProfile: "ملف شخصي مزيف",
    reportScam: "احتيال / نصب",
    reportSpam: "بريد عشوائي",
  },

  checkout: {
    currentBalance: "الرصيد الحالي",
    popular: "شائع",
    online: "متصل",
    autoGateway: "بوابة تلقائية",
    manualUpi: "UPI يدوي",
    qrUpiId: "QR / معرّف UPI",
    manualApprovalNote: "⏱ يتطلب الدفع اليدوي موافقة المشرف (بضع ساعات). ستُضاف العملات بعد التحقق.",
    promoCode: "رمز ترويجي",
    promoPlaceholder: "أدخل الرمز الترويجي",
    remove: "إزالة",
    invalidPromo: "رمز ترويجي غير صالح",
    percentOff: "🎉 خصم {pct}% — وفّر {amount}",
    bonusCoinsAdded: "🎁 تمت إضافة +{count} عملة مكافأة!",
    promoBonus: "مكافأة ترويجية",
    youGet: "تحصل على",
    promoDiscount: "خصم ترويجي",
    securePayments: "المدفوعات مؤمّنة ومشفّرة بنسبة 100%",
    selectPackageBtn: "اختر باقة",
    payViaUpi: "ادفع عبر UPI — {price} مقابل {coins} عملة",
    continuePay: "متابعة — {price} مقابل {coins} عملة",
    redirecting: "جارٍ التحويل إلى الدفع...",
    submittedForReview: "تم إرسال الدفع للمراجعة!",
    submitted: "تم الإرسال",
    coinsAddedToast: "تمت إضافة {count} عملة!",
    purchaseSuccessful: "تم الشراء بنجاح",
    paymentFailed: "فشل الدفع. يرجى المحاولة مجددًا.",
    paymentFailedTitle: "فشل الدفع",
    manualUpiTitle: "دفع UPI يدوي",
    autoApproved: "⚡ تمت الموافقة تلقائيًا!",
    coinsAdded: "تمت إضافة العملات!",
    paymentSubmitted: "تم إرسال الدفع!",
    autoApprovedSub: "تمت إضافة {count} عملة فورًا إلى حسابك!",
    underReviewSub: "دفعتك قيد المراجعة. ستُضاف العملات بمجرد موافقة المشرف (عادةً خلال بضع ساعات).",
    package: "الباقة",
    utrRef: "UTR / مرجع",
    loadingPayment: "جارٍ تحميل تفاصيل الدفع...",
    unavailable: "غير متاح",
    unavailableSub: "الدفع اليدوي غير متاح الآن. يرجى تجربة طريقة دفع أخرى.",
    scanQrStep: "امسح رمز QR أو ادفع إلى معرّف UPI",
    payToUpi: "ادفع إلى معرّف UPI",
    account: "الحساب:",
    autoRotating: "🔄 تدوير تلقائي",
    enterUtrStep: "أدخل UTR / معرّف المعاملة",
    utrHint: "بعد الدفع، ابحث عن UTR المكوّن من 12 رقمًا أو مرجع المعاملة في تطبيق UPI الخاص بك.",
    utrPlaceholder: "أدخل UTR / رقم المرجع",
    adminApprovalTitle: "⏱ مطلوب موافقة المشرف",
    adminApprovalNote: "يتم التحقق من المدفوعات اليدوية بواسطة فريقنا. ستُضاف العملات خلال بضع ساعات من الموافقة. تأكد من دفع المبلغ المحدد بدقة.",
    submitProof: "إرسال إثبات الدفع",
    utrRequiredMsg: "يرجى إدخال رقم UTR / مرجع المعاملة.",
    submissionFailed: "فشل الإرسال",
    submissionFailedMsg: "تعذّر إرسال الدفع. يرجى المحاولة مجددًا.",
    coinPack: "باقة عملات",
    upiQrPayment: "دفع UPI / QR",
    notAvailable: "غير متاح",
    manualUnavailable: "دفع UPI اليدوي غير متاح حاليًا. يرجى تجربة طريقة دفع أخرى.",
    retry: "إعادة المحاولة",
    instantApproval: "موافقة فورية",
    coinsAddedWallet: "تمت إضافة {count} عملة إلى محفظتك!",
    beingReviewed: "تتم مراجعة دفعتك. ستُضاف العملات خلال بضع ساعات.",
    amount: "المبلغ",
    status: "الحالة",
    approved: "موافق عليه",
    pendingReview: "بانتظار المراجعة",
    scanQrPay: "امسح رمز QR وادفع",
    qrNotAvailable: "رمز QR غير متاح",
    upiId: "معرّف UPI",
    copy: "نسخ",
    payExactly: "ادفع {amount} بالضبط إلى معرّف UPI هذا",
    utrHintHistory: "بعد الدفع، ابحث عن UTR المكوّن من 12 رقمًا أو مرجع المعاملة في سجل المدفوعات بتطبيق UPI الخاص بك.",
    utrExample: "مثال 412345678901",
    whereUtr: "أين أجد UTR؟",
    whereUtrText: "افتح تطبيق UPI (PhonePe / GPay / Paytm) ← سجل المعاملات ← اضغط على الدفع ← انسخ \"UTR\" أو \"معرّف المرجع\"",
    verifyNote: "ستُضاف العملات بعد تحقق المشرف (عادةً خلال بضع ساعات). تأكد من دفع المبلغ المحدد بدقة.",
    submitPayment: "إرسال الدفع",
    enterUtrContinue: "أدخل UTR للمتابعة",
    utrRequiredMsg2: "يرجى إدخال رقم UTR / مرجع المعاملة",
    utrTooShort: "يجب ألا يقل UTR عن 6 أحرف",
    invalidUtr: "UTR غير صالح",
    planMissing: "معلومات الباقة مفقودة. يرجى العودة والمحاولة مجددًا.",
    submissionFailedShort: "فشل الإرسال. يرجى المحاولة مجددًا.",
  },

  successScreen: {
    title: "تم الدفع بنجاح!",
    subtitle: "تمت إضافة العملات إلى محفظتك",
    note: "يمكنك الآن استخدام عملاتك لإجراء مكالمات مع المضيفين",
    findHost: "ابحث عن مضيف للتحدث معه",
    viewWallet: "عرض المحفظة",
  },

  editProfile: {
    updated: "تم تحديث ملفك الشخصي.",
    savedTitle: "تم حفظ الملف الشخصي",
    saveFailedMsg: "تعذّر حفظ ملفك الشخصي. يرجى المحاولة مجددًا.",
    saveFailed: "فشل الحفظ",
    permissionTitle: "الإذن مطلوب",
    permissionMsg: "يرجى السماح بالوصول إلى مكتبة الصور لتغيير صورتك الرمزية.",
    uploadFailed: "فشل الرفع",
    uploadFailedMsg: "تعذّر رفع الصورة الرمزية. يرجى المحاولة مجددًا.",
    displayName: "الاسم المعروض",
    namePlaceholder: "اسمك",
    bioPlaceholder: "أخبر الآخرين عن نفسك...",
    saveChanges: "حفظ التغييرات",
  },

  referralScreen: {
    title: "أحِل واربح",
    heroTitle: "ادعُ أصدقاءك واربح عملات!",
    heroSub: "مقابل كل صديق ينضم إلى VoxLink باستخدام رمزك، يحصل صديقك على {newUser} عملة مكافأة وتربح أنت {referrer} عملة!",
    yourCode: "رمز الإحالة الخاص بك",
    shareWithFriends: "المشاركة مع الأصدقاء",
    yourStats: "إحصائيات الإحالة الخاصة بك",
    friendsInvited: "الأصدقاء المدعوون",
    coinsEarned: "العملات المكتسبة",
    howItWorks: "كيف يعمل",
    step1: "شارك رمز الإحالة الفريد الخاص بك مع الأصدقاء",
    step2: "يسجّل صديقك باستخدام رمزك ويحصل على {count} عملة",
    step3Instant: "تربح {reward} عملة فورًا!",
    step3OneCall: "عندما يُكملون مكالمة واحدة، تربح {reward} عملة!",
    step3Calls: "عندما يُكملون {count} مكالمات، تربح {reward} عملة!",
    failedLoad: "فشل تحميل معلومات الإحالة.",
    codeCopied: "تم نسخ رمز الإحالة!",
    copyFailed: "تعذّر نسخ الرمز. يرجى المحاولة مجددًا.",
    shareTitle: "انضم إلى VoxLink",
    shareMessage: "انضم إلى VoxLink وتواصل مع مضيفين رائعين للمكالمات الصوتية والمرئية!\n\nاستخدم رمز الإحالة الخاص بي: {code} للحصول على عملات مكافأة عند التسجيل!\n\nحمّله الآن: https://voxlink.app",
  },

  splash: {
    tagline: "تواصل وأنشئ علاقات هادفة",
  },

  dailyReward: {
    title: "المكافأة اليومية",
    titleClaimed: "تم استلام المكافأة!",
    dayOfStreak: "اليوم {day} من سلسلتك",
    streakUnlocked: "تم فتح سلسلة اليوم {day}",
    claimHint: "استلم اليوم للحفاظ على سلسلتك.",
    dayBonus: "مكافأة اليوم {day}: +{count} عملة إضافية!",
    claim: "استلم {count} عملة",
    claiming: "جارٍ الاستلام…",
    later: "لاحقاً",
    awesome: "رائع!",
    addedToWallet: "أُضيفت إلى محفظتك",
    baseMilestone: "{base} أساسية + {bonus} مكافأة إنجاز",
    newBalance: "الرصيد الجديد",
    coins: "عملات",
    freeMinutes: "+{count} دقيقة مكالمة مجانية!",
    monthlyChest: "صندوق شهري: +{count} عملة!",
    comebackBonus: "مكافأة العودة: +{count} عملة",
    spinning: "يدور…",
    luckyWheel: "عجلة الحظ",
    lucky: "محظوظ!",
    scheduleLabel: "جدول السلسلة",
    nextMilestone: "{count} يوم حتى مكافأة اليوم {day}",
    nextMilestonePlural: "{count} أيام حتى مكافأة اليوم {day}",
    missedDay: "لقد فوّت يوماً!",
    restoreWithSaver: "استعد سلسلتك المكوّنة من {streak} أيام بحافظ سلسلة مجاني (متبقٍ {count}).",
    restoreWithCoins: "استعد سلسلتك المكوّنة من {streak} أيام مقابل {count} عملة.",
    restoring: "جارٍ الاستعادة…",
    useStreakSaver: "استخدم حافظ السلسلة",
    restoreForCoins: "استعد مقابل {count} عملة",
    atRiskCountdown: "استلم قريباً — ستُعاد سلسلتك خلال {time}!",
    atRisk: "استلم قريباً — ستُعاد سلسلتك عند منتصف الليل!",
  },

  // VIP membership
  vip: {
    title: "عضوية VIP",
    active: "نشط",
    fallbackName: "VIP",
    daysLeftRenews: "بقي {count} {unit} · يتجدد في {date}",
    day: "يوم",
    days: "أيام",
    claimDaily: "احصل على {reward} اليومية",
    dailyClaimed: "تم الحصول على المكافأة اليومية",
    becomeVip: "كن عضو VIP",
    becomeVipSub: "مكالمات أرخص، عملات مجانية يومية، محادثة مع أي شخص وشارة حصرية.",
    choosePlan: "اختر باقتك",
    noPlans: "لا توجد باقات متاحة حالياً.",
    planDays: "{count} يوم",
    current: "الحالية",
    renew: "تجديد",
    subscribe: "اشتراك",
    footNote: "يُدفع VIP بالعملات وينتهي تلقائياً في نهاية المدة. تُطبَّق المزايا أثناء التفعيل.",
    rewardCoins: "{count} عملة",
    rewardMinutes: "{count} دقيقة",
    rewardFallback: "مكافأة",
    subscribedTitle: "مرحباً بك في VIP 🎉",
    subscribedMsg: "{plan} نشط — استمتع بمزاياك!",
    subscribeFailTitle: "فشل الاشتراك",
    subscribeFailMsg: "تعذّر إتمام شراء VIP.",
    renewConfirmTitle: "تجديد {plan}؟",
    subscribeConfirmTitle: "الاشتراك في {plan}؟",
    confirmMsg: "سيستخدم هذا {coins} عملة مقابل {days} يوماً من VIP.",
    dailyClaimedTitle: "تم الحصول على المكافأة اليومية 🎁",
    dailyRewardAdded: "تمت إضافة {parts}.",
    dailyRewardAddedGeneric: "تمت إضافة المكافأة إلى حسابك.",
    claimGrantedCoins: "+{count} عملة",
    claimGrantedMinutes: "+{count} دقيقة مجانية",
    alreadyClaimed: "لقد حصلت عليها اليوم بالفعل. عد غداً.",
    claimFail: "تعذّر الحصول على مكافأتك.",
  },
};

export default ar;
