// VoxLink — English Strings

const en = {
  // Common
  common: {
    ok: "OK",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    done: "Done",
    back: "Back",
    close: "Close",
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Try Again",
    submit: "Submit",
    next: "Next",
    skip: "Skip",
    yes: "Yes",
    no: "No",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    share: "Share",
    copy: "Copy",
    copied: "Copied!",
    noResults: "No results found",
    optional: "Optional",
    required: "Required",
    all: "All",
    more: "More",
    less: "Less",
    seeAll: "See All",
    noData: "No data available",
    refresh: "Refresh",
  },

  // Auth
  auth: {
    login: "Log In",
    register: "Sign Up",
    logout: "Log Out",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password?",
    newPassword: "New Password",
    phone: "Phone Number",
    otp: "Verification Code",
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    resendOtp: "Resend OTP",
    fullName: "Full Name",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    welcomeBack: "Welcome Back!",
    loginToContinue: "Log in to continue",
    createYourAccount: "Create Your Account",
    joinVoxLink: "Join VoxLink today",
    enterOtp: "Enter the OTP sent to",
    passwordResetSent: "Password reset email sent",
    checkEmail: "Check your email for instructions",
    passwordChanged: "Password changed successfully",
    invalidCredentials: "Invalid email or password",
    accountDeleted: "Account deleted successfully",
    deleteAccountConfirm: "Are you sure you want to delete your account? This action cannot be undone.",
    tagline: "Connect. Talk. Grow.",
    welcomeToVoxLink: "Welcome to VoxLink",
    autoCreateAccount: "New user? We'll create your account automatically on first login",
    continueWithGoogle: "Continue with Google",
    signingIn: "Signing in...",
    or: "or",
    quickLogin: "Quick Login",
    pleaseWait: "Please wait...",
    quickLoginNote: "Quick Login saves your account to this device — reinstall and it's still yours",
    welcomeName: "Welcome, {name}!",
    welcomeBackToast: "Welcome back!",
    quickLoginTitle: "Quick Login",
    accountCreated: "Account created! Welcome to VoxLink.",
    welcomeTitle: "Welcome",
    connectionError: "No internet connection. Please check your network.",
    connectionErrorTitle: "Connection Error",
    quickLoginFailed: "Quick Login failed. Please try again.",
  },

  // Navigation
  nav: {
    home: "Home",
    search: "Search",
    messages: "Messages",
    wallet: "Wallet",
    profile: "Profile",
    notifications: "Notifications",
  },

  // Home
  home: {
    greeting: "Hi",
    findHosts: "Find a Host",
    topListeners: "Top Listeners",
    trending: "Trending Now",
    newHosts: "New Hosts",
    onlineNow: "Online Now",
    featuredHosts: "Featured Hosts",
    seeAll: "See All",
    searchPlaceholder: "Search hosts, topics...",
    findMore: "Find More",
    findMoreSub: "Connect with a random listener now",
    startRandomCall: "Start Random Call",
    welcome: "Welcome",
    freeMinutesTitle: "{count} free call minutes available!",
    freeMinutesSub: "Your first {count} minutes are on us — start a call with any host.",
    lowOnCoins: "Low on coins ({count} left)",
    lowOnCoinsSub: "Top up now so you don't get cut off mid-call.",
    topUp: "Top up",
    yourFavorites: "Your favorites",
    viewAll: "View All",
    recommendedForYou: "Recommended for you",
    browseByTopic: "Browse by Topic",
    availableNow: "Available Now",
    online: "online",
    noListenersAvailable: "No listeners available right now",
    offlineListeners: "Offline Listeners",
  },

  // Random Match
  random: {
    title: "Random Match",
    randomMatch: "🎲 Random Match",
    cancel: "Cancel",
    voiceCall: "Voice Call",
    videoCall: "Video Call",
    findingMatch: "Finding your match…",
    listenersOnline: "{count} listeners online",
    listenerOnline: "{count} listener online",
    chooseCallType: "Choose Call Type",
    matchFound: "It's a Match! 🎉",
    accept: "Accept",
    decline: "Decline",
    skipNext: "Skip / Next",
    checking: "Checking…",
    filters: "Filters",
    matchFilters: "Match Filters",
    gender: "Gender",
    genderAny: "Any",
    genderMale: "Male",
    genderFemale: "Female",
    minimumRating: "Minimum rating",
    ratingAny: "Any rating",
    rating3: "3★ +",
    rating4: "4★ +",
    rating4_5: "4.5★ +",
    reset: "Reset",
    done: "Done",
    myBalance: "My Balance",
    needCoins: "You need at least {count} coins to start this call.",
    // Status messages keyed by server `code`
    statusInsufficientCoins: "Not enough coins to start a random call.",
    statusNotEnoughCoinsTitle: "Not enough coins",
    statusRateLimited: "Slow down a moment, then try again…",
    statusDailyLimit: "You've reached today's random-match limit.",
    statusDeclineCooldown: "Too many declines — please take a short break.",
    statusNoMatchFilters: "No host matches your filters — relaxing them may help.",
    statusSearching: "Searching among online listeners…",
    statusNoneOnline: "No listeners online right now — still searching…",
    statusGiveUp: "No host found right now. Try again in a bit.",
    statusNetworkError: "Network error, retrying…",
    statusServerUnreachable: "Couldn't reach the server. Please try again.",
    retryIn: "Try again in {time}",
    hostBusy: "Host just got busy — finding another match.",
    hostOffline: "Host went offline — finding another match.",
    hostUnavailable: "Host unavailable — finding another match.",
    failedLoadHosts: "Failed to load available hosts.",
  },

  // Hosts
  hosts: {
    host: "Host",
    listener: "Listener",
    online: "Online",
    offline: "Offline",
    busy: "Busy",
    rating: "Rating",
    reviews: "Reviews",
    review: "Review",
    coinsPerMinute: "coins/min",
    totalMinutes: "min total",
    specialties: "Specialties",
    languages: "Languages",
    about: "About",
    callNow: "Call Now",
    audioCall: "Audio Call",
    videoCall: "Video Call",
    sendMessage: "Send Message",
    talkNow: "Talk Now",
    noHostsFound: "No hosts found",
    adjustFilters: "Try adjusting your filters",
    topRated: "Top Rated",
    viewProfile: "View Profile",
    startCall: "Start Call",
  },

  // Calls
  calls: {
    incoming: "Incoming Call",
    outgoing: "Connecting...",
    ongoing: "On Call",
    ended: "Call Ended",
    audio: "Audio Call",
    video: "Video Call",
    accept: "Accept",
    decline: "Decline",
    endCall: "End Call",
    mute: "Mute",
    unmute: "Unmute",
    speaker: "Speaker",
    flipCamera: "Flip Camera",
    callDuration: "Call Duration",
    callWith: "Call with",
    rateCall: "Rate this call",
    callHistory: "Call History",
    noCallHistory: "No call history yet",
    callCost: "Call Cost",
    perMinute: "per minute",
    lowBalance: "Low Coin Balance",
    lowBalanceMsg: "You're running low on coins. Recharge to continue.",
    callEnded: "Call Ended",
    callEndedMsg: "Your call has ended",
    missed: "Missed",
    answered: "Answered",
    rejected: "Rejected",
    callingHistory: "Calling History",
    audioShort: "Audio",
    videoShort: "Video",
    incomingVideo: "Incoming Video Call",
    incomingAudio: "Incoming Audio Call",
    unknown: "Unknown",
    voxlinkHost: "VoxLink Host",
    voxlinkUser: "VoxLink User",
    voiceCall: "Voice Call",
    callDeclined: "Call Declined",
    noAnswer: "No Answer",
    ringing: "Ringing",
    connecting: "Connecting",
    coinsPerMin: "coins / min",
    oneMinMinimum: "1 min minimum",
    callAutoEnded: "Call Auto-Ended",
    autoDisconnected: "You ran out of coins — call was auto-disconnected",
    with: "with",
    minBilling: "Min. 1 min billing applied",
    duration: "Duration",
    coinsSpent: "Coins Spent",
    rateName: "Rate {name}",
    feedbackHelps: "Your feedback helps the host improve",
    ratingPoor: "Poor",
    ratingFair: "Fair",
    ratingGood: "Good",
    ratingGreat: "Great",
    ratingExcellent: "Excellent!",
    submitRating: "Submit Rating",
    thankYou: "Thank you! 🙏",
    ratingSubmitted: "Your rating has been submitted",
    rechargeCoins: "Recharge Coins",
    backHome: "Back to Home",
    rateFailed: "Failed to submit rating, please try again.",
    errorTitle: "Error",
    completed: "Completed",
    cancelled: "Cancelled",
    noCallHistoryFound: "No call history found",
    failedLoadHistory: "Failed to load call history.",
    micAccessNeeded: "Microphone access needed — Tap to fix",
    coinsRunningLow: "Coins running low",
    secondsRemaining: "{count}s remaining",
    minLeft: "{count} min left",
    ringingDots: "Ringing...",
    connectingDots: "Connecting...",
    connected: "Connected",
    networkDrop: "Network drop — reconnecting...",
    connectionFailed: "Connection failed — retrying...",
    callEndedShort: "Call ended",
    mutedHint: "🔇 Muted",
    speakerOn: "Speaker On",
    runningOutCoins: "Running Out of Coins!",
    autoDisconnectIn: "Call will auto-disconnect in {time}",
    second: "second",
    seconds: "seconds",
    fewSeconds: "a few seconds",
    rechargeNow: "Recharge Now",
    continueCall: "Continue Call",
    cameraOff: "Camera off",
    cameraUnavailable: "Camera unavailable",
    startingCamera: "Starting camera…",
    noPermission: "No Permission",
    cameraOffShort: "Camera Off",
    you: "You",
    mutedLabel: "Muted",
    noMic: "No mic",
    lowCoins: "Low coins",
    secondsLeft: "{count}s left",
    connectionIssue: "Connection issue",
    live: "LIVE",
    waitingResponse: "Waiting for response...",
    camera: "Camera",
    camOff: "Cam Off",
    end: "End",
    flip: "Flip",
    earpiece: "Earpiece",
  },

  // Chat
  chat: {
    messages: "Messages",
    newMessage: "New Message",
    typeMessage: "Type a message...",
    send: "Send",
    noMessages: "No messages yet",
    startConversation: "Start a conversation",
    online: "Online",
    offline: "Offline",
    typing: "typing...",
    delivered: "Delivered",
    read: "Read",
    deleteChat: "Delete Chat",
    deleteChatConfirm: "Are you sure you want to delete this conversation?",
    chats: "Chats",
    searchConversations: "Search conversations...",
    noConversationsFound: "No conversations found",
    noConversationsYet: "No conversations yet",
    tryDifferentName: "Try a different name",
    startChattingAfterCall: "Start chatting after a call with a host",
  },

  // Wallet
  wallet: {
    wallet: "Wallet",
    coinBalance: "Coin Balance",
    coins: "Coins",
    coin: "Coin",
    buyCoins: "Buy Coins",
    coinHistory: "Coin History",
    transactions: "Transactions",
    noTransactions: "No transactions yet",
    purchased: "Purchased",
    spent: "Spent",
    bonus: "Bonus",
    refunded: "Refunded",
    withdrawal: "Withdrawal",
    totalSpent: "Total Spent",
    totalPurchased: "Total Purchased",
    popular: "Most Popular",
    bestValue: "Best Value",
    bonus_label: "BONUS",
    recharge: "Recharge",
    choosePackage: "Choose a Package",
    instantDelivery: "Instant Delivery",
    securePayment: "Secure Payment",
    guaranteed: "Satisfaction Guaranteed",
  },

  // Profile
  profile: {
    profile: "Profile",
    editProfile: "Edit Profile",
    myProfile: "My Profile",
    name: "Name",
    email: "Email",
    phone: "Phone",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    country: "Country",
    bio: "Bio",
    language: "Language",
    settings: "Settings",
    helpCenter: "Help & FAQ",
    privacy: "Privacy Policy",
    about: "About VoxLink",
    shareApp: "Share VoxLink",
    rateApp: "Rate the App",
    logout: "Log Out",
    deleteAccount: "Delete Account",
    callHistory: "Call History",
    joinedOn: "Joined",
    totalCalls: "Total Calls",
    hoursSpent: "Hours Spent",
  },

  // Settings
  settings: {
    settings: "Settings",
    notifications: "Notifications",
    callNotifications: "Call Notifications",
    messageNotifications: "Message Notifications",
    promoNotifications: "Promotional Notifications",
    language: "Language",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemDefault: "System Default",
    privacy: "Privacy",
    security: "Security",
    changePassword: "Change Password",
    twoFactor: "Two-Factor Authentication",
    account: "Account",
    support: "Support",
  },

  // Payments
  payment: {
    checkout: "Checkout",
    selectPackage: "Select Package",
    paymentMethod: "Payment Method",
    creditCard: "Credit / Debit Card",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "Processing Payment...",
    paymentSuccess: "Payment Successful!",
    paymentFailed: "Payment Failed",
    orderSummary: "Order Summary",
    total: "Total",
    coins: "Coins",
    bonusCoins: "Bonus Coins",
    tryAgain: "Try Again",
    secureNote: "All payments are secured and encrypted",
  },

  // Host Mode
  host: {
    dashboard: "Dashboard",
    totalEarnings: "Total Earnings",
    thisWeek: "This Week",
    thisMonth: "This Month",
    totalCalls: "Total Calls",
    avgRating: "Avg. Rating",
    onlineStatus: "Online Status",
    goOnline: "Go Online",
    goOffline: "Go Offline",
    setBusy: "Set Busy",
    earnings: "Earnings",
    withdraw: "Withdraw",
    withdrawal: "Withdrawal",
    minimumWithdraw: "Minimum 100 coins",
    enterAmount: "Enter Amount",
    withdrawMethod: "Withdrawal Method",
    bankTransfer: "Bank Transfer",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "Account Details",
    withdrawSuccess: "Withdrawal request submitted",
    withdrawPending: "Your request is being processed",
    hostSettings: "Host Settings",
    availability: "Availability",
    payoutSettings: "Payout Settings",
    becomeHost: "Become a Host",
    apply: "Apply Now",
    applicationSent: "Application Sent!",
    applicationDesc: "We'll review your application and get back to you within 2-3 business days.",
  },

  // Errors
  errors: {
    network: "Network error. Please check your connection.",
    server: "Server error. Please try again later.",
    unauthorized: "Session expired. Please log in again.",
    notFound: "The requested resource was not found.",
    insufficientCoins: "Insufficient coins. Please recharge.",
    callFailed: "Call could not be connected. Please try again.",
    permissionDenied: "Permission denied.",
    generic: "Something went wrong. Please try again.",
  },

  // Bottom tab labels
  tabs: {
    home: "Home",
    listener: "Listener",
    random: "Random",
    chat: "Chat",
    calling: "Calling",
  },

  // Listener list screen
  listener: {
    allListeners: "All Listeners",
    language: "Language",
    talkAbout: "Talk About",
    selectLanguage: "Select Language",
    noListenersFound: "No listeners found",
    failedLoad: "Failed to load listeners.",
    available: "Available",
    offline: "Offline",
    audio: "Audio",
    video: "Video",
    perMin: "/min",
    hrs: "hrs",
  },

  // Onboarding
  onboarding: {
    find: "FIND",
    findDesc: "You can connect with the people around\nthe world for doing chat, messages and\nmake connections with them.",
    chat: "CHAT",
    chatDesc: "Chat with the strangers to know each\nother better and have a nice\ncompatibility.",
    videoCall: "VIDEO CALL",
    videoCallDesc: "You can share your videos and photos\nwith your friend and connections.",
  },

  hostsScreen: {
    allHosts: "All Hosts",
    failedLoad: "Couldn't load hosts. Pull to refresh.",
  },

  reviews: {
    failedLoad: "Couldn't load reviews.",
    reviewsCount: "{count} reviews",
    noReviews: "No reviews yet",
    beFirst: "Be the first to leave a review",
    user: "User",
    today: "Today",
    yesterday: "Yesterday",
    daysAgo: "{count} days ago",
    weekAgo: "{count} week ago",
    weeksAgo: "{count} weeks ago",
    monthAgo: "{count} month ago",
    monthsAgo: "{count} months ago",
  },

  notFound: {
    title: "Oops!",
    message: "This screen doesn't exist.",
    goHome: "Go to home screen!",
  },

  aboutScreen: {
    title: "About VoxLink",
    appTagline: "Voice & Video Connection",
    version: "Version {version}",
    statActiveUsers: "Active Users",
    statHosts: "Hosts",
    statCallsMade: "Calls Made",
    statAppRating: "App Rating",
    whatIsTitle: "What is VoxLink?",
    whatIsBody1: "VoxLink is a social audio and video calling platform that connects people with verified hosts for meaningful conversations. Whether you need life advice, language practice, emotional support, or just someone to talk to — our hosts are here for you.",
    whatIsBody2: "Hosts are real, trained individuals vetted by our team. Every call is secure, private, and backed by our coin-based payment system — so you only pay for the time you use.",
    keyFeatures: "Key Features",
    feature1: "HD Audio & Video Calls",
    feature2: "End-to-End Encrypted",
    feature3: "1,200+ Verified Hosts",
    feature4: "Coin-Based Fair Pricing",
    feature5: "In-App Chat",
    feature6: "Rated Reviews System",
    connectWithUs: "Connect With Us",
    linkWebsite: "Website",
    linkTwitter: "Twitter / X",
    linkInstagram: "Instagram",
    linkContact: "Contact Us",
    helpCenter: "Help Center",
    copyright: "© 2026 VoxLink Inc. All rights reserved.",
  },

  privacyScreen: {
    bannerTitle: "Your Privacy Matters",
    bannerSub: "This policy explains how VoxLink collects, uses, and protects your data.",
    lastUpdated: "Last Updated: March 1, 2026",
    contactTitle: "Questions about Privacy?",
    s1Title: "1. Information We Collect",
    s1Body: "We collect information you provide directly to us, such as when you create an account, update your profile, make purchases, or contact us for support. This includes your name, email address, username, profile picture, and payment information.\n\nWe also collect information automatically when you use VoxLink, including log data, device information, location information (if permitted), and usage data such as the features you use and the time spent on calls.",
    s2Title: "2. How We Use Your Information",
    s2Body: "We use the information we collect to provide, maintain, and improve our services, process transactions and send related information, send notifications, technical notices, updates, and support messages.\n\nWe also use your data to respond to your comments, questions, and requests, monitor and analyze trends and usage, detect, investigate and prevent fraudulent transactions and other illegal activities.",
    s3Title: "3. Sharing of Information",
    s3Body: "We do not share your personal information with third parties except as described in this policy. We may share information with vendors, consultants, and other service providers who need access to such information to carry out work on our behalf.\n\nWe may disclose your information if we believe disclosure is in accordance with, or required by, any applicable law or legal process, including lawful requests by public authorities to meet national security or law enforcement requirements.",
    s4Title: "4. Call Data & Audio",
    s4Body: "Audio and video call content is transmitted through encrypted channels. We do not record or store the content of your calls unless you explicitly enable a recording feature (if available). Call metadata (duration, participants, timestamps) is stored to provide billing and history features.",
    s5Title: "5. Coins & Payments",
    s5Body: "Payment information is processed through secure third-party payment processors. We do not store full payment card details on our servers. Coin transactions are logged for accounting and dispute resolution purposes.",
    s6Title: "6. Data Security",
    s6Body: "We take reasonable measures to help protect information about you from loss, theft, misuse and unauthorized access, disclosure, alteration, and destruction. All data is encrypted in transit using TLS and at rest using AES-256 encryption.",
    s7Title: "7. Data Retention",
    s7Body: "We retain personal information for as long as necessary to provide our services and fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law. You may request deletion of your account and associated data at any time through the Settings screen.",
    s8Title: "8. Children's Privacy",
    s8Body: "VoxLink is not intended for children under the age of 18. We do not knowingly collect personal information from children under 18. If we learn we have collected personal information from a child under 18, we will delete that information.",
    s9Title: "9. Your Rights",
    s9Body: "You have the right to access, update, or delete your personal information at any time. You may also object to processing, request data portability, or withdraw consent where processing is based on consent. To exercise these rights, contact us through the Help Center.",
    s10Title: "10. Changes to This Policy",
    s10Body: "We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the 'Last Updated' date. Your continued use of VoxLink after any change constitutes your acceptance of the new Privacy Policy.",
  },

  helpScreen: {
    title: "Help Center",
    bannerTitle: "Need Help or FAQ?",
    bannerSub: "Find answers to common questions",
    contactTitle: "Have an Issue?",
    faqTitle: "Frequently Asked Questions",
    q1: "What is VoxLink?",
    a1: "VoxLink is a social platform where you can connect with professional listeners and hosts via audio or video calls. Get personalized support on topics like relationships, career, life coaching, and more.",
    q2: "Who are Hosts/Listeners?",
    a2: "Hosts are verified professionals or experienced individuals who provide support and conversation. They specialize in various topics and are available for audio and video calls.",
    q3: "How can I make a call?",
    a3: "Browse available hosts on the home screen, tap a host card to view their profile, then tap 'Talk Now' to start an audio or video call. Calls are charged in coins per minute.",
    q4: "What are Coins?",
    a4: "Coins are VoxLink's in-app currency. You purchase coin packages from the Wallet section and spend them during calls with hosts at their listed rate per minute.",
    q5: "Is my conversation private?",
    a5: "Yes, all conversations are private and confidential. We follow strict data protection policies and do not share personal conversation details with third parties.",
    q6: "How do I become a Host?",
    a6: "Hosting is done through our separate VoxLink Host app. Download the Host app to apply, verify your identity, and start taking calls and earning.",
    q7: "What if I run out of coins?",
    a7: "If you run out of coins during a call, the call will end automatically. You can purchase more coins anytime from the Wallet section.",
  },

  coinHistory: {
    title: "Coin History",
    currentBalance: "Current Balance",
    earned: "Earned",
    spent: "Spent",
    tabAll: "All",
    tabPurchase: "Purchase",
    tabSpent: "Spent",
    tabBonus: "Bonus",
    today: "Today",
    yesterday: "Yesterday",
    ref: "Ref:",
    noTransactions: "No transactions found",
    failedLoad: "Failed to load coin history.",
  },

  notificationsScreen: {
    markAllRead: "Mark all read",
    empty: "No notifications yet",
    goBack: "Go back",
    markAllReadLabel: "Mark all notifications as read",
    failedLoad: "Failed to load notifications.",
    failedMarkAll: "Failed to mark notifications as read.",
    failedUpdate: "Failed to update notification.",
  },

  searchHosts: {
    searchPlaceholder: "Search hosts by name...",
    topic: "Topic",
    status: "Status",
    language: "Language",
    hostsFound: "{count} hosts found",
    noResults: "No hosts found matching your search",
    talk: "Talk",
    failedLoad: "Failed to load hosts.",
  },

  chatScreen: {
    defaultName: "Chat",
    emptyHint: "Send a message to start the conversation",
    sending: "Sending…",
    tapToRetry: "Tap to retry",
    a11yBack: "Go back",
    a11yPhotoMessage: "Photo message",
    a11yRetry: "Retry sending message",
    a11yAttach: "Attach photo",
    a11ySend: "Send message",
    permissionTitle: "Permission Required",
    permissionPhoto: "Please allow photo library access to send a photo.",
    failedLoadMessages: "Failed to load messages.",
    uploadFailed: "Upload failed. Please try again.",
    photoSendFailed: "Couldn't send photo. Please try again.",
  },

  hostDetail: {
    notFound: "Host not found",
    selectCallType: "Select Call Type",
    coinPerMin: "{count} Coin/min",
    coin: "{count} Coin",
    levelShort: "Lv.",
    languageColon: "Language : ",
    idLabel: "ID:",
    totalCall: "Total Call",
    experience: "Experience",
    recent: "Recent",
    chatNow: "Chat Now",
    chatLocked: "🔒 Chat",
    chatLockedTitle: "🔒 Chat Locked",
    chatLockedMsg: "To chat with {name}, you need to call them first. Chat unlocks automatically after a call!",
    chatLockedMsg2: "Make a call first, then chat will unlock automatically!",
    offlineMsg: "{name} is currently offline.",
    idCopied: "Host ID copied to clipboard.",
    reportThanks: "Thank you for your report. Our team will review it shortly.",
    reportSubmitted: "Report Submitted",
    reportFailMsg: "Could not submit report. Please try again.",
    reportFailed: "Report Failed",
    failedLoad: "Failed to load host details.",
    reportTitle: "Report {name}",
    reportSubtitle: "Why are you reporting this host?",
    reportInappropriate: "Inappropriate Content",
    reportHarassment: "Harassment",
    reportFakeProfile: "Fake Profile",
    reportScam: "Scam / Fraud",
    reportSpam: "Spam",
  },

  checkout: {
    currentBalance: "Current Balance",
    popular: "Popular",
    online: "Online",
    autoGateway: "Auto gateway",
    manualUpi: "Manual UPI",
    qrUpiId: "QR / UPI ID",
    manualApprovalNote: "⏱ Manual payment requires admin approval (a few hours). Coins will be added after verification.",
    promoCode: "Promo Code",
    promoPlaceholder: "Enter promo code",
    remove: "Remove",
    invalidPromo: "Invalid promo code",
    percentOff: "🎉 {pct}% off — Save {amount}",
    bonusCoinsAdded: "🎁 +{count} Bonus Coins added!",
    promoBonus: "Promo Bonus",
    youGet: "You Get",
    promoDiscount: "Promo Discount",
    securePayments: "Payments are 100% secured & encrypted",
    selectPackageBtn: "Select a Package",
    payViaUpi: "Pay via UPI — {price} for {coins} Coins",
    continuePay: "Continue — {price} for {coins} Coins",
    redirecting: "Redirecting to payment...",
    submittedForReview: "Payment submitted for review!",
    submitted: "Submitted",
    coinsAddedToast: "{count} coins added!",
    purchaseSuccessful: "Purchase Successful",
    paymentFailed: "Payment failed. Please try again.",
    paymentFailedTitle: "Payment Failed",
    manualUpiTitle: "Manual UPI Payment",
    autoApproved: "⚡ Auto-Approved!",
    coinsAdded: "Coins Added!",
    paymentSubmitted: "Payment Submitted!",
    autoApprovedSub: "{count} coins have been instantly added to your account!",
    underReviewSub: "Your payment is under review. Coins will be added once the admin approves it (usually within a few hours).",
    package: "Package",
    utrRef: "UTR / Ref",
    loadingPayment: "Loading payment details...",
    unavailable: "Unavailable",
    unavailableSub: "Manual payment is not available right now. Please try another payment method.",
    scanQrStep: "Scan QR or pay to UPI ID",
    payToUpi: "Pay to UPI ID",
    account: "Account:",
    autoRotating: "🔄 Auto-rotating",
    enterUtrStep: "Enter UTR / Transaction ID",
    utrHint: "After payment, find the 12-digit UTR or transaction reference in your UPI app.",
    utrPlaceholder: "Enter UTR / Reference No.",
    adminApprovalTitle: "⏱ Admin Approval Required",
    adminApprovalNote: "Manual payments are verified by our team. Coins will be credited within a few hours of approval. Ensure the exact amount is paid.",
    submitProof: "Submit Payment Proof",
    utrRequiredMsg: "Please enter the UTR / transaction reference number.",
    submissionFailed: "Submission Failed",
    submissionFailedMsg: "Could not submit payment. Please try again.",
    coinPack: "Coin Pack",
    upiQrPayment: "UPI / QR Payment",
    notAvailable: "Not Available",
    manualUnavailable: "Manual UPI payment is currently unavailable. Please try another payment method.",
    retry: "Retry",
    instantApproval: "Instant Approval",
    coinsAddedWallet: "{count} coins have been added to your wallet!",
    beingReviewed: "Your payment is being reviewed. Coins will be credited within a few hours.",
    amount: "Amount",
    status: "Status",
    approved: "Approved",
    pendingReview: "Pending Review",
    scanQrPay: "Scan QR Code & Pay",
    qrNotAvailable: "QR not available",
    upiId: "UPI ID",
    copy: "Copy",
    payExactly: "Pay exactly {amount} to this UPI ID",
    utrHintHistory: "After payment, find the 12-digit UTR or transaction reference in your UPI app's payment history.",
    utrExample: "e.g. 412345678901",
    whereUtr: "Where to find UTR?",
    whereUtrText: "Open your UPI app (PhonePe / GPay / Paytm) → Transaction History → Tap on the payment → Copy the \"UTR\" or \"Reference ID\"",
    verifyNote: "Coins will be added after admin verification (usually within a few hours). Make sure to pay the exact amount.",
    submitPayment: "Submit Payment",
    enterUtrContinue: "Enter UTR to continue",
    utrRequiredMsg2: "Please enter UTR / Transaction Reference number",
    utrTooShort: "UTR should be at least 6 characters",
    invalidUtr: "Invalid UTR",
    planMissing: "Plan information missing. Please go back and try again.",
    submissionFailedShort: "Submission failed. Please try again.",
  },

  successScreen: {
    title: "Payment Successful!",
    subtitle: "Coins have been added to your wallet",
    note: "You can now use your coins to make calls with hosts",
    findHost: "Find a Host to Talk With",
    viewWallet: "View Wallet",
  },

  editProfile: {
    updated: "Your profile has been updated.",
    savedTitle: "Profile Saved",
    saveFailedMsg: "Could not save your profile. Please try again.",
    saveFailed: "Save Failed",
    permissionTitle: "Permission Required",
    permissionMsg: "Please allow access to your photo library to change your avatar.",
    uploadFailed: "Upload Failed",
    uploadFailedMsg: "Could not upload avatar. Please try again.",
    displayName: "Display Name",
    namePlaceholder: "Your name",
    bioPlaceholder: "Tell others about yourself...",
    saveChanges: "Save Changes",
  },

  referralScreen: {
    title: "Refer & Earn",
    heroTitle: "Invite Friends, Earn Coins!",
    heroSub: "For every friend who joins VoxLink with your code, your friend gets {newUser} bonus coins and you earn {referrer} coins!",
    yourCode: "Your Referral Code",
    shareWithFriends: "Share with Friends",
    yourStats: "Your Referral Stats",
    friendsInvited: "Friends Invited",
    coinsEarned: "Coins Earned",
    howItWorks: "How it Works",
    step1: "Share your unique referral code with friends",
    step2: "Friend signs up using your code & gets {count} coins",
    step3Instant: "You instantly earn {reward} coins!",
    step3OneCall: "After they complete 1 call, you earn {reward} coins!",
    step3Calls: "After they complete {count} calls, you earn {reward} coins!",
    failedLoad: "Failed to load referral info.",
    codeCopied: "Referral code copied!",
    copyFailed: "Couldn't copy the code. Please try again.",
    shareTitle: "Join VoxLink",
    shareMessage: "Join VoxLink and connect with amazing hosts for audio & video calls!\n\nUse my referral code: {code} to get bonus coins on signup!\n\nDownload now: https://voxlink.app",
  },

  splash: {
    tagline: "Connect & establish meaningful connections",
  },

  dailyReward: {
    title: "Daily Reward",
    titleClaimed: "Reward Claimed!",
    dayOfStreak: "Day {day} of your streak",
    streakUnlocked: "Day {day} streak unlocked",
    claimHint: "Claim today to keep your streak going.",
    dayBonus: "Day {day} bonus: +{count} extra coins!",
    claim: "Claim {count} coins",
    claiming: "Claiming…",
    later: "Later",
    awesome: "Awesome!",
    addedToWallet: "added to your wallet",
    baseMilestone: "{base} base + {bonus} milestone bonus",
    newBalance: "New balance",
    coins: "coins",
    freeMinutes: "+{count} free call minutes!",
    monthlyChest: "Monthly chest: +{count} coins!",
    comebackBonus: "Welcome back bonus: +{count} coins",
    spinning: "Spinning…",
    luckyWheel: "Lucky wheel",
    lucky: "LUCKY!",
    scheduleLabel: "Streak schedule",
    nextMilestone: "{count} day to your Day {day} bonus",
    nextMilestonePlural: "{count} days to your Day {day} bonus",
    missedDay: "You missed a day!",
    restoreWithSaver: "Restore your {streak}-day streak with a free streak saver ({count} left).",
    restoreWithCoins: "Restore your {streak}-day streak for {count} coins.",
    restoring: "Restoring…",
    useStreakSaver: "Use Streak Saver",
    restoreForCoins: "Restore for {count} coins",
    atRiskCountdown: "Claim soon — your streak resets in {time}!",
    atRisk: "Claim soon — your streak resets at midnight!",
  },
};

export type Translations = typeof en;
export default en;
