// VoxLink — English Strings

const en = {
  // Common
  common: {
    ok: "OK",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    done: "Done",
    back: "Back",
    close: "Close",
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Try Again",
    submit: "Submit",
    next: "Next",
    skip: "Skip",
    yes: "Yes",
    no: "No",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    share: "Share",
    copy: "Copy",
    copied: "Copied!",
    noResults: "No results found",
    optional: "Optional",
    required: "Required",
    all: "All",
    more: "More",
    less: "Less",
    seeAll: "See All",
    noData: "No data available",
    refresh: "Refresh",
  },

  // Auth
  auth: {
    login: "Log In",
    register: "Sign Up",
    logout: "Log Out",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password?",
    newPassword: "New Password",
    phone: "Phone Number",
    otp: "Verification Code",
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    resendOtp: "Resend OTP",
    fullName: "Full Name",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    welcomeBack: "Welcome Back!",
    loginToContinue: "Log in to continue",
    createYourAccount: "Create Your Account",
    joinVoxLink: "Join VoxLink today",
    enterOtp: "Enter the OTP sent to",
    passwordResetSent: "Password reset email sent",
    checkEmail: "Check your email for instructions",
    passwordChanged: "Password changed successfully",
    invalidCredentials: "Invalid email or password",
    accountDeleted: "Account deleted successfully",
    deleteAccountConfirm: "Are you sure you want to delete your account? This action cannot be undone.",
    tagline: "Connect. Talk. Grow.",
    welcomeToVoxLink: "Welcome to VoxLink",
    autoCreateAccount: "New user? We'll create your account automatically on first login",
    continueWithGoogle: "Continue with Google",
    signingIn: "Signing in...",
    or: "or",
    quickLogin: "Quick Login",
    pleaseWait: "Please wait...",
    quickLoginNote: "Quick Login saves your account to this device — reinstall and it's still yours",
    welcomeName: "Welcome, {name}!",
    welcomeBackToast: "Welcome back!",
    quickLoginTitle: "Quick Login",
    accountCreated: "Account created! Welcome to VoxLink.",
    welcomeTitle: "Welcome",
    connectionError: "No internet connection. Please check your network.",
    connectionErrorTitle: "Connection Error",
    quickLoginFailed: "Quick Login failed. Please try again.",
  },

  // Navigation
  nav: {
    home: "Home",
    search: "Search",
    messages: "Messages",
    wallet: "Wallet",
    profile: "Profile",
    notifications: "Notifications",
  },

  // Home
  home: {
    greeting: "Hi",
    findHosts: "Find a Host",
    topListeners: "Top Listeners",
    trending: "Trending Now",
    newHosts: "New Hosts",
    onlineNow: "Online Now",
    featuredHosts: "Featured Hosts",
    seeAll: "See All",
    searchPlaceholder: "Search hosts, topics...",
    findMore: "Find More",
    findMoreSub: "Connect with a random listener now",
    startRandomCall: "Start Random Call",
    welcome: "Welcome",
    freeMinutesTitle: "{count} free call minutes available!",
    freeMinutesSub: "Your first {count} minutes are on us — start a call with any host.",
    lowOnCoins: "Low on coins ({count} left)",
    lowOnCoinsSub: "Top up now so you don't get cut off mid-call.",
    topUp: "Top up",
    yourFavorites: "Your favorites",
    viewAll: "View All",
    recommendedForYou: "Recommended for you",
    browseByTopic: "Browse by Topic",
    availableNow: "Available Now",
    online: "online",
    noListenersAvailable: "No listeners available right now",
    offlineListeners: "Offline Listeners",
  },

  // Random Match
  random: {
    title: "Random Match",
    randomMatch: "🎲 Random Match",
    cancel: "Cancel",
    voiceCall: "Voice Call",
    videoCall: "Video Call",
    findingMatch: "Finding your match…",
    listenersOnline: "{count} listeners online",
    listenerOnline: "{count} listener online",
    chooseCallType: "Choose Call Type",
    matchFound: "It's a Match! 🎉",
    accept: "Accept",
    decline: "Decline",
    skipNext: "Skip / Next",
    checking: "Checking…",
    filters: "Filters",
    matchFilters: "Match Filters",
    gender: "Gender",
    genderAny: "Any",
    genderMale: "Male",
    genderFemale: "Female",
    minimumRating: "Minimum rating",
    ratingAny: "Any rating",
    rating3: "3★ +",
    rating4: "4★ +",
    rating4_5: "4.5★ +",
    reset: "Reset",
    done: "Done",
    myBalance: "My Balance",
    needCoins: "You need at least {count} coins to start this call.",
    // Status messages keyed by server `code`
    statusInsufficientCoins: "Not enough coins to start a random call.",
    statusNotEnoughCoinsTitle: "Not enough coins",
    statusRateLimited: "Slow down a moment, then try again…",
    statusDailyLimit: "You've reached today's random-match limit.",
    statusDeclineCooldown: "Too many declines — please take a short break.",
    statusNoMatchFilters: "No host matches your filters — relaxing them may help.",
    statusSearching: "Searching among online listeners…",
    statusNoneOnline: "No listeners online right now — still searching…",
    statusGiveUp: "No host found right now. Try again in a bit.",
    statusNetworkError: "Network error, retrying…",
    statusServerUnreachable: "Couldn't reach the server. Please try again.",
    hostBusy: "Host just got busy — finding another match.",
    hostOffline: "Host went offline — finding another match.",
    hostUnavailable: "Host unavailable — finding another match.",
    failedLoadHosts: "Failed to load available hosts.",
  },

  // Hosts
  hosts: {
    host: "Host",
    listener: "Listener",
    online: "Online",
    offline: "Offline",
    busy: "Busy",
    rating: "Rating",
    reviews: "Reviews",
    review: "Review",
    coinsPerMinute: "coins/min",
    totalMinutes: "min total",
    specialties: "Specialties",
    languages: "Languages",
    about: "About",
    callNow: "Call Now",
    audioCall: "Audio Call",
    videoCall: "Video Call",
    sendMessage: "Send Message",
    talkNow: "Talk Now",
    noHostsFound: "No hosts found",
    adjustFilters: "Try adjusting your filters",
    topRated: "Top Rated",
    viewProfile: "View Profile",
    startCall: "Start Call",
  },

  // Calls
  calls: {
    incoming: "Incoming Call",
    outgoing: "Connecting...",
    ongoing: "On Call",
    ended: "Call Ended",
    audio: "Audio Call",
    video: "Video Call",
    accept: "Accept",
    decline: "Decline",
    endCall: "End Call",
    mute: "Mute",
    unmute: "Unmute",
    speaker: "Speaker",
    flipCamera: "Flip Camera",
    callDuration: "Call Duration",
    callWith: "Call with",
    rateCall: "Rate this call",
    callHistory: "Call History",
    noCallHistory: "No call history yet",
    callCost: "Call Cost",
    perMinute: "per minute",
    lowBalance: "Low Coin Balance",
    lowBalanceMsg: "You're running low on coins. Recharge to continue.",
    callEnded: "Call Ended",
    callEndedMsg: "Your call has ended",
    missed: "Missed",
    answered: "Answered",
    rejected: "Rejected",
    callingHistory: "Calling History",
    audioShort: "Audio",
    videoShort: "Video",
    incomingVideo: "Incoming Video Call",
    incomingAudio: "Incoming Audio Call",
    unknown: "Unknown",
    voxlinkHost: "VoxLink Host",
    voxlinkUser: "VoxLink User",
    voiceCall: "Voice Call",
    callDeclined: "Call Declined",
    noAnswer: "No Answer",
    ringing: "Ringing",
    connecting: "Connecting",
    coinsPerMin: "coins / min",
    oneMinMinimum: "1 min minimum",
    callAutoEnded: "Call Auto-Ended",
    autoDisconnected: "You ran out of coins — call was auto-disconnected",
    with: "with",
    minBilling: "Min. 1 min billing applied",
    duration: "Duration",
    coinsSpent: "Coins Spent",
    rateName: "Rate {name}",
    feedbackHelps: "Your feedback helps the host improve",
    ratingPoor: "Poor",
    ratingFair: "Fair",
    ratingGood: "Good",
    ratingGreat: "Great",
    ratingExcellent: "Excellent!",
    submitRating: "Submit Rating",
    thankYou: "Thank you! 🙏",
    ratingSubmitted: "Your rating has been submitted",
    rechargeCoins: "Recharge Coins",
    backHome: "Back to Home",
    rateFailed: "Failed to submit rating, please try again.",
    errorTitle: "Error",
    completed: "Completed",
    cancelled: "Cancelled",
    noCallHistoryFound: "No call history found",
    failedLoadHistory: "Failed to load call history.",
    micAccessNeeded: "Microphone access needed — Tap to fix",
    coinsRunningLow: "Coins running low",
    secondsRemaining: "{count}s remaining",
    minLeft: "{count} min left",
    ringingDots: "Ringing...",
    connectingDots: "Connecting...",
    connected: "Connected",
    networkDrop: "Network drop — reconnecting...",
    connectionFailed: "Connection failed — retrying...",
    callEndedShort: "Call ended",
    mutedHint: "🔇 Muted",
    speakerOn: "Speaker On",
    runningOutCoins: "Running Out of Coins!",
    autoDisconnectIn: "Call will auto-disconnect in {time}",
    second: "second",
    seconds: "seconds",
    fewSeconds: "a few seconds",
    rechargeNow: "Recharge Now",
    continueCall: "Continue Call",
    cameraOff: "Camera off",
    cameraUnavailable: "Camera unavailable",
    startingCamera: "Starting camera…",
    noPermission: "No Permission",
    cameraOffShort: "Camera Off",
    you: "You",
    mutedLabel: "Muted",
    noMic: "No mic",
    lowCoins: "Low coins",
    secondsLeft: "{count}s left",
    connectionIssue: "Connection issue",
    live: "LIVE",
    waitingResponse: "Waiting for response...",
    camera: "Camera",
    camOff: "Cam Off",
    end: "End",
    flip: "Flip",
    earpiece: "Earpiece",
  },

  // Chat
  chat: {
    messages: "Messages",
    newMessage: "New Message",
    typeMessage: "Type a message...",
    send: "Send",
    noMessages: "No messages yet",
    startConversation: "Start a conversation",
    online: "Online",
    offline: "Offline",
    typing: "typing...",
    delivered: "Delivered",
    read: "Read",
    deleteChat: "Delete Chat",
    deleteChatConfirm: "Are you sure you want to delete this conversation?",
    chats: "Chats",
    searchConversations: "Search conversations...",
    noConversationsFound: "No conversations found",
    noConversationsYet: "No conversations yet",
    tryDifferentName: "Try a different name",
    startChattingAfterCall: "Start chatting after a call with a host",
  },

  // Wallet
  wallet: {
    wallet: "Wallet",
    coinBalance: "Coin Balance",
    coins: "Coins",
    coin: "Coin",
    buyCoins: "Buy Coins",
    coinHistory: "Coin History",
    transactions: "Transactions",
    noTransactions: "No transactions yet",
    purchased: "Purchased",
    spent: "Spent",
    bonus: "Bonus",
    refunded: "Refunded",
    withdrawal: "Withdrawal",
    totalSpent: "Total Spent",
    totalPurchased: "Total Purchased",
    popular: "Most Popular",
    bestValue: "Best Value",
    bonus_label: "BONUS",
    recharge: "Recharge",
    choosePackage: "Choose a Package",
    instantDelivery: "Instant Delivery",
    securePayment: "Secure Payment",
    guaranteed: "Satisfaction Guaranteed",
  },

  // Profile
  profile: {
    profile: "Profile",
    editProfile: "Edit Profile",
    myProfile: "My Profile",
    name: "Name",
    email: "Email",
    phone: "Phone",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    country: "Country",
    bio: "Bio",
    language: "Language",
    settings: "Settings",
    helpCenter: "Help & FAQ",
    privacy: "Privacy Policy",
    about: "About VoxLink",
    shareApp: "Share VoxLink",
    rateApp: "Rate the App",
    logout: "Log Out",
    deleteAccount: "Delete Account",
    callHistory: "Call History",
    joinedOn: "Joined",
    totalCalls: "Total Calls",
    hoursSpent: "Hours Spent",
  },

  // Settings
  settings: {
    settings: "Settings",
    notifications: "Notifications",
    callNotifications: "Call Notifications",
    messageNotifications: "Message Notifications",
    promoNotifications: "Promotional Notifications",
    language: "Language",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemDefault: "System Default",
    privacy: "Privacy",
    security: "Security",
    changePassword: "Change Password",
    twoFactor: "Two-Factor Authentication",
    account: "Account",
    support: "Support",
  },

  // Payments
  payment: {
    checkout: "Checkout",
    selectPackage: "Select Package",
    paymentMethod: "Payment Method",
    creditCard: "Credit / Debit Card",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "Processing Payment...",
    paymentSuccess: "Payment Successful!",
    paymentFailed: "Payment Failed",
    orderSummary: "Order Summary",
    total: "Total",
    coins: "Coins",
    bonusCoins: "Bonus Coins",
    tryAgain: "Try Again",
    secureNote: "All payments are secured and encrypted",
  },

  // Host Mode
  host: {
    dashboard: "Dashboard",
    totalEarnings: "Total Earnings",
    thisWeek: "This Week",
    thisMonth: "This Month",
    totalCalls: "Total Calls",
    avgRating: "Avg. Rating",
    onlineStatus: "Online Status",
    goOnline: "Go Online",
    goOffline: "Go Offline",
    setBusy: "Set Busy",
    earnings: "Earnings",
    withdraw: "Withdraw",
    withdrawal: "Withdrawal",
    minimumWithdraw: "Minimum 100 coins",
    enterAmount: "Enter Amount",
    withdrawMethod: "Withdrawal Method",
    bankTransfer: "Bank Transfer",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "Account Details",
    withdrawSuccess: "Withdrawal request submitted",
    withdrawPending: "Your request is being processed",
    hostSettings: "Host Settings",
    availability: "Availability",
    payoutSettings: "Payout Settings",
    becomeHost: "Become a Host",
    apply: "Apply Now",
    applicationSent: "Application Sent!",
    applicationDesc: "We'll review your application and get back to you within 2-3 business days.",
  },

  // Errors
  errors: {
    network: "Network error. Please check your connection.",
    server: "Server error. Please try again later.",
    unauthorized: "Session expired. Please log in again.",
    notFound: "The requested resource was not found.",
    insufficientCoins: "Insufficient coins. Please recharge.",
    callFailed: "Call could not be connected. Please try again.",
    permissionDenied: "Permission denied.",
    generic: "Something went wrong. Please try again.",
  },

  // Bottom tab labels
  tabs: {
    home: "Home",
    listener: "Listener",
    random: "Random",
    chat: "Chat",
    calling: "Calling",
  },

  // Listener list screen
  listener: {
    allListeners: "All Listeners",
    language: "Language",
    talkAbout: "Talk About",
    selectLanguage: "Select Language",
    noListenersFound: "No listeners found",
    failedLoad: "Failed to load listeners.",
    available: "Available",
    offline: "Offline",
    audio: "Audio",
    video: "Video",
    perMin: "/min",
    hrs: "hrs",
  },

  // Onboarding
  onboarding: {
    find: "FIND",
    findDesc: "You can connect with the people around\nthe world for doing chat, messages and\nmake connections with them.",
    chat: "CHAT",
    chatDesc: "Chat with the strangers to know each\nother better and have a nice\ncompatibility.",
    videoCall: "VIDEO CALL",
    videoCallDesc: "You can share your videos and photos\nwith your friend and connections.",
  },

  hostsScreen: {
    allHosts: "All Hosts",
    failedLoad: "Couldn't load hosts. Pull to refresh.",
  },

  reviews: {
    failedLoad: "Couldn't load reviews.",
    reviewsCount: "{count} reviews",
    noReviews: "No reviews yet",
    beFirst: "Be the first to leave a review",
    user: "User",
    today: "Today",
    yesterday: "Yesterday",
    daysAgo: "{count} days ago",
    weekAgo: "{count} week ago",
    weeksAgo: "{count} weeks ago",
    monthAgo: "{count} month ago",
    monthsAgo: "{count} months ago",
  },
};

export type Translations = typeof en;
export default en;
