// VoxLink — Spanish Strings

const es = {
  common: {
    ok: "Aceptar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Guardar",
    delete: "Eliminar",
    edit: "Editar",
    done: "Listo",
    back: "Atrás",
    close: "Cerrar",
    loading: "Cargando...",
    error: "Algo salió mal",
    retry: "Reintentar",
    submit: "Enviar",
    next: "Siguiente",
    skip: "Omitir",
    yes: "Sí",
    no: "No",
    search: "Buscar",
    filter: "Filtrar",
    clear: "Limpiar",
    apply: "Aplicar",
    share: "Compartir",
    copy: "Copiar",
    copied: "Copiado!",
    noResults: "Sin resultados",
    optional: "Opcional",
    required: "Requerido",
    all: "Todos",
    more: "Más",
    less: "Menos",
    seeAll: "Ver todo",
    noData: "Sin datos disponibles",
    refresh: "Actualizar",
  },
  auth: {
    login: "Iniciar sesión",
    register: "Registrarse",
    logout: "Cerrar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    newPassword: "Nueva contraseña",
    phone: "Número de teléfono",
    otp: "Código de verificación",
    sendOtp: "Enviar OTP",
    verifyOtp: "Verificar OTP",
    resendOtp: "Reenviar OTP",
    fullName: "Nombre completo",
    createAccount: "Crear cuenta",
    alreadyHaveAccount: "¿Ya tienes cuenta?",
    dontHaveAccount: "¿No tienes cuenta?",
    welcomeBack: "¡Bienvenido de nuevo!",
    loginToContinue: "Inicia sesión para continuar",
    createYourAccount: "Crea tu cuenta",
    joinVoxLink: "Únete a VoxLink hoy",
    enterOtp: "Introduce el OTP enviado a",
    passwordResetSent: "Correo de restablecimiento enviado",
    checkEmail: "Revisa tu correo para las instrucciones",
    passwordChanged: "Contraseña cambiada exitosamente",
    invalidCredentials: "Correo o contraseña inválidos",
    accountDeleted: "Cuenta eliminada exitosamente",
    deleteAccountConfirm: "¿Seguro que quieres eliminar tu cuenta? Esta acción es irreversible.",
    tagline: "Conecta. Habla. Crece.",
    welcomeToVoxLink: "Bienvenido a VoxLink",
    autoCreateAccount: "¿Usuario nuevo? Crearemos tu cuenta automáticamente en el primer inicio de sesión",
    continueWithGoogle: "Continuar con Google",
    signingIn: "Iniciando sesión...",
    or: "o",
    quickLogin: "Inicio rápido",
    pleaseWait: "Por favor espera...",
    quickLoginNote: "El inicio rápido guarda tu cuenta en este dispositivo — reinstala y seguirá siendo tuya",
    welcomeName: "¡Bienvenido, {name}!",
    welcomeBackToast: "¡Bienvenido de nuevo!",
    quickLoginTitle: "Inicio rápido",
    accountCreated: "¡Cuenta creada! Bienvenido a VoxLink.",
    welcomeTitle: "Bienvenido",
    connectionError: "Sin conexión a internet. Por favor verifica tu red.",
    connectionErrorTitle: "Error de conexión",
    quickLoginFailed: "Falló el inicio rápido. Inténtalo de nuevo.",
  },
  nav: {
    home: "Inicio",
    search: "Buscar",
    messages: "Mensajes",
    wallet: "Billetera",
    profile: "Perfil",
    notifications: "Notificaciones",
  },
  home: {
    greeting: "Hola",
    findHosts: "Buscar anfitrión",
    topListeners: "Mejores oyentes",
    trending: "En tendencia",
    newHosts: "Nuevos anfitriones",
    onlineNow: "En línea ahora",
    featuredHosts: "Anfitriones destacados",
    seeAll: "Ver todo",
    searchPlaceholder: "Buscar anfitriones, temas...",
    findMore: "Buscar más",
    findMoreSub: "Conéctate con un oyente aleatorio ahora",
    startRandomCall: "Iniciar llamada aleatoria",
    welcome: "Bienvenido",
    freeMinutesTitle: "¡{count} minutos de llamada gratis disponibles!",
    freeMinutesSub: "Tus primeros {count} minutos corren por nuestra cuenta — inicia una llamada con cualquier anfitrión.",
    lowOnCoins: "Pocas monedas ({count} restantes)",
    lowOnCoinsSub: "Recarga ahora para que no te corten a mitad de la llamada.",
    topUp: "Recargar",
    yourFavorites: "Tus favoritos",
    viewAll: "Ver todo",
    recommendedForYou: "Recomendado para ti",
    browseByTopic: "Explorar por tema",
    availableNow: "Disponible ahora",
    online: "en línea",
    noListenersAvailable: "No hay oyentes disponibles en este momento",
    offlineListeners: "Oyentes desconectados",
  },

  // Random Match
  random: {
    title: "Coincidencia Aleatoria",
    randomMatch: "🎲 Coincidencia Aleatoria",
    cancel: "Cancelar",
    voiceCall: "Llamada de Voz",
    videoCall: "Videollamada",
    findingMatch: "Buscando tu coincidencia…",
    listenersOnline: "{count} oyentes en línea",
    listenerOnline: "{count} oyente en línea",
    chooseCallType: "Elegir Tipo de Llamada",
    matchFound: "¡Es una coincidencia! 🎉",
    accept: "Aceptar",
    decline: "Rechazar",
    skipNext: "Saltar / Siguiente",
    checking: "Comprobando…",
    filters: "Filtros",
    matchFilters: "Filtros de coincidencia",
    gender: "Género",
    genderAny: "Cualquiera",
    genderMale: "Masculino",
    genderFemale: "Femenino",
    minimumRating: "Calificación mínima",
    ratingAny: "Cualquiera",
    rating3: "3★ +",
    rating4: "4★ +",
    rating4_5: "4.5★ +",
    reset: "Restablecer",
    done: "Listo",
    myBalance: "Mi saldo",
    needCoins: "Necesitas al menos {count} monedas para iniciar esta llamada.",
    statusInsufficientCoins: "Monedas insuficientes para iniciar una llamada aleatoria.",
    statusNotEnoughCoinsTitle: "Monedas insuficientes",
    statusRateLimited: "Más despacio, vuelve a intentarlo…",
    statusDailyLimit: "Has alcanzado el límite diario de coincidencias.",
    statusDeclineCooldown: "Demasiados rechazos — toma un breve descanso.",
    statusNoMatchFilters: "Ningún anfitrión coincide con tus filtros — relájalos.",
    statusSearching: "Buscando entre los oyentes en línea…",
    statusNoneOnline: "No hay oyentes en línea ahora — aún buscando…",
    statusGiveUp: "No se encontró anfitrión. Inténtalo más tarde.",
    statusNetworkError: "Error de red, reintentando…",
    statusServerUnreachable: "No se pudo contactar el servidor. Inténtalo de nuevo.",
    hostBusy: "El anfitrión está ocupado — buscando otro.",
    hostOffline: "El anfitrión se desconectó — buscando otro.",
    hostUnavailable: "Anfitrión no disponible — buscando otro.",
    failedLoadHosts: "No se pudieron cargar los anfitriones disponibles.",
  },
  hosts: {
    host: "Anfitrión",
    listener: "Oyente",
    online: "En línea",
    offline: "Fuera de línea",
    busy: "Ocupado",
    rating: "Calificación",
    reviews: "Reseñas",
    review: "Reseña",
    coinsPerMinute: "monedas/min",
    totalMinutes: "min totales",
    specialties: "Especialidades",
    languages: "Idiomas",
    about: "Acerca de",
    callNow: "Llamar ahora",
    audioCall: "Llamada de audio",
    videoCall: "Videollamada",
    sendMessage: "Enviar mensaje",
    talkNow: "Hablar ahora",
    noHostsFound: "No se encontraron anfitriones",
    adjustFilters: "Intenta ajustar los filtros",
    topRated: "Mejor calificado",
    viewProfile: "Ver perfil",
    startCall: "Iniciar llamada",
  },
  calls: {
    incoming: "Llamada entrante",
    outgoing: "Conectando...",
    ongoing: "En llamada",
    ended: "Llamada terminada",
    audio: "Llamada de audio",
    video: "Videollamada",
    accept: "Aceptar",
    decline: "Rechazar",
    endCall: "Terminar llamada",
    mute: "Silenciar",
    unmute: "Activar micrófono",
    speaker: "Altavoz",
    flipCamera: "Voltear cámara",
    callDuration: "Duración de la llamada",
    callWith: "Llamada con",
    rateCall: "Calificar esta llamada",
    callHistory: "Historial de llamadas",
    noCallHistory: "Sin historial de llamadas",
    callCost: "Costo de la llamada",
    perMinute: "por minuto",
    lowBalance: "Saldo bajo de monedas",
    lowBalanceMsg: "Pocas monedas. Recarga para continuar.",
    callEnded: "Llamada terminada",
    callEndedMsg: "Tu llamada ha terminado",
    missed: "Perdida",
    answered: "Contestada",
    rejected: "Rechazada",
    callingHistory: "Historial de llamadas",
    audioShort: "Audio",
    videoShort: "Video",
    incomingVideo: "Videollamada entrante",
    incomingAudio: "Llamada de voz entrante",
    unknown: "Desconocido",
    voxlinkHost: "Anfitrión de VoxLink",
    voxlinkUser: "Usuario de VoxLink",
    voiceCall: "Llamada de voz",
    callDeclined: "Llamada rechazada",
    noAnswer: "Sin respuesta",
    ringing: "Llamando",
    connecting: "Conectando",
    coinsPerMin: "monedas / min",
    oneMinMinimum: "1 min mínimo",
    callAutoEnded: "Llamada finalizada automáticamente",
    autoDisconnected: "Te quedaste sin monedas — la llamada se desconectó automáticamente",
    with: "con",
    minBilling: "Cobro mínimo de 1 min aplicado",
    duration: "Duración",
    coinsSpent: "Monedas gastadas",
    rateName: "Califica a {name}",
    feedbackHelps: "Tus comentarios ayudan al anfitrión a mejorar",
    ratingPoor: "Mala",
    ratingFair: "Regular",
    ratingGood: "Buena",
    ratingGreat: "Muy buena",
    ratingExcellent: "¡Excelente!",
    submitRating: "Enviar calificación",
    thankYou: "¡Gracias! 🙏",
    ratingSubmitted: "Tu calificación ha sido enviada",
    rechargeCoins: "Recargar monedas",
    backHome: "Volver al inicio",
    rateFailed: "No se pudo enviar la calificación, inténtalo de nuevo.",
    errorTitle: "Error",
    completed: "Completada",
    cancelled: "Cancelada",
    noCallHistoryFound: "No se encontró historial de llamadas",
    failedLoadHistory: "No se pudo cargar el historial de llamadas.",
    micAccessNeeded: "Se necesita acceso al micrófono — Toca para solucionar",
    coinsRunningLow: "Quedan pocas monedas",
    secondsRemaining: "{count}s restantes",
    minLeft: "{count} min restantes",
    ringingDots: "Llamando...",
    connectingDots: "Conectando...",
    connected: "Conectado",
    networkDrop: "Caída de red — reconectando...",
    connectionFailed: "Conexión fallida — reintentando...",
    callEndedShort: "Llamada finalizada",
    mutedHint: "🔇 Silenciado",
    speakerOn: "Altavoz activado",
    runningOutCoins: "¡Te estás quedando sin monedas!",
    autoDisconnectIn: "La llamada se desconectará en {time}",
    second: "segundo",
    seconds: "segundos",
    fewSeconds: "unos segundos",
    rechargeNow: "Recargar ahora",
    continueCall: "Continuar llamada",
    cameraOff: "Cámara apagada",
    cameraUnavailable: "Cámara no disponible",
    startingCamera: "Iniciando cámara…",
    noPermission: "Sin permiso",
    cameraOffShort: "Cámara apagada",
    you: "Tú",
    mutedLabel: "Silenciado",
    noMic: "Sin micrófono",
    lowCoins: "Pocas monedas",
    secondsLeft: "{count}s restantes",
    connectionIssue: "Problema de conexión",
    live: "EN VIVO",
    waitingResponse: "Esperando respuesta...",
    camera: "Cámara",
    camOff: "Cám. apagada",
    end: "Colgar",
    flip: "Girar",
    earpiece: "Auricular",
  },
  chat: {
    messages: "Mensajes",
    newMessage: "Nuevo mensaje",
    typeMessage: "Escribe un mensaje...",
    send: "Enviar",
    noMessages: "Sin mensajes aún",
    startConversation: "Iniciar conversación",
    online: "En línea",
    offline: "Fuera de línea",
    typing: "escribiendo...",
    delivered: "Entregado",
    read: "Leído",
    deleteChat: "Eliminar chat",
    deleteChatConfirm: "¿Seguro que quieres eliminar esta conversación?",
    chats: "Chats",
    searchConversations: "Buscar conversaciones...",
    noConversationsFound: "No se encontraron conversaciones",
    noConversationsYet: "Aún no hay conversaciones",
    tryDifferentName: "Prueba con otro nombre",
    startChattingAfterCall: "Empieza a chatear después de una llamada con un anfitrión",
  },
  wallet: {
    wallet: "Billetera",
    coinBalance: "Saldo de monedas",
    coins: "Monedas",
    coin: "Moneda",
    buyCoins: "Comprar monedas",
    coinHistory: "Historial de monedas",
    transactions: "Transacciones",
    noTransactions: "Sin transacciones aún",
    purchased: "Comprado",
    spent: "Gastado",
    bonus: "Bono",
    refunded: "Reembolsado",
    withdrawal: "Retiro",
    totalSpent: "Total gastado",
    totalPurchased: "Total comprado",
    popular: "Más popular",
    bestValue: "Mejor valor",
    bonus_label: "BONO",
    recharge: "Recargar",
    choosePackage: "Elegir paquete",
    instantDelivery: "Entrega instantánea",
    securePayment: "Pago seguro",
    guaranteed: "Satisfacción garantizada",
  },
  profile: {
    profile: "Perfil",
    editProfile: "Editar perfil",
    myProfile: "Mi perfil",
    name: "Nombre",
    email: "Correo electrónico",
    phone: "Teléfono",
    gender: "Género",
    male: "Masculino",
    female: "Femenino",
    other: "Otro",
    country: "País",
    bio: "Biografía",
    language: "Idioma",
    settings: "Configuración",
    helpCenter: "Centro de ayuda",
    privacy: "Política de privacidad",
    about: "Acerca de VoxLink",
    shareApp: "Compartir VoxLink",
    rateApp: "Calificar la app",
    logout: "Cerrar sesión",
    deleteAccount: "Eliminar cuenta",
    callHistory: "Historial de llamadas",
    joinedOn: "Miembro desde",
    totalCalls: "Total de llamadas",
    hoursSpent: "Horas dedicadas",
  },
  settings: {
    settings: "Configuración",
    notifications: "Notificaciones",
    callNotifications: "Notificaciones de llamadas",
    messageNotifications: "Notificaciones de mensajes",
    promoNotifications: "Notificaciones promocionales",
    language: "Idioma",
    theme: "Tema",
    lightMode: "Modo claro",
    darkMode: "Modo oscuro",
    systemDefault: "Predeterminado del sistema",
    privacy: "Privacidad",
    security: "Seguridad",
    changePassword: "Cambiar contraseña",
    twoFactor: "Autenticación de dos factores",
    account: "Cuenta",
    support: "Soporte",
  },
  payment: {
    checkout: "Pagar",
    selectPackage: "Seleccionar paquete",
    paymentMethod: "Método de pago",
    creditCard: "Tarjeta de crédito/débito",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "Procesando pago...",
    paymentSuccess: "Pago exitoso!",
    paymentFailed: "Pago fallido",
    orderSummary: "Resumen del pedido",
    total: "Total",
    coins: "Monedas",
    bonusCoins: "Monedas de bono",
    tryAgain: "Intentar de nuevo",
    secureNote: "Todos los pagos están protegidos y encriptados",
  },
  host: {
    dashboard: "Panel",
    totalEarnings: "Ganancias totales",
    thisWeek: "Esta semana",
    thisMonth: "Este mes",
    totalCalls: "Total llamadas",
    avgRating: "Calificación promedio",
    onlineStatus: "Estado en línea",
    goOnline: "Conectarse",
    goOffline: "Desconectarse",
    setBusy: "Marcar como ocupado",
    earnings: "Ganancias",
    withdraw: "Retirar",
    withdrawal: "Retiro",
    minimumWithdraw: "Mínimo 100 monedas",
    enterAmount: "Ingresar monto",
    withdrawMethod: "Método de retiro",
    bankTransfer: "Transferencia bancaria",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "Detalles de cuenta",
    withdrawSuccess: "Solicitud de retiro enviada",
    withdrawPending: "Tu solicitud está siendo procesada",
    hostSettings: "Configuración del anfitrión",
    availability: "Disponibilidad",
    payoutSettings: "Configuración de pago",
    becomeHost: "Ser anfitrión",
    apply: "Aplicar ahora",
    applicationSent: "¡Solicitud enviada!",
    applicationDesc: "Revisaremos tu solicitud y te contactaremos en 2-3 días hábiles.",
  },
  errors: {
    network: "Error de red. Por favor verifica tu conexión.",
    server: "Error del servidor. Intenta más tarde.",
    unauthorized: "Sesión expirada. Por favor inicia sesión de nuevo.",
    notFound: "El recurso solicitado no fue encontrado.",
    insufficientCoins: "Monedas insuficientes. Por favor recarga.",
    callFailed: "La llamada no pudo conectarse. Intenta de nuevo.",
    permissionDenied: "Permiso denegado.",
    generic: "Algo salió mal. Por favor intenta de nuevo.",
  },

  tabs: {
    home: "Inicio",
    listener: "Oyente",
    random: "Aleatorio",
    chat: "Chat",
    calling: "Llamadas",
  },

  listener: {
    allListeners: "Todos los oyentes",
    language: "Idioma",
    talkAbout: "Hablar sobre",
    selectLanguage: "Seleccionar idioma",
    noListenersFound: "No se encontraron oyentes",
    failedLoad: "No se pudieron cargar los oyentes.",
    available: "Disponible",
    offline: "Desconectado",
    audio: "Audio",
    video: "Video",
    perMin: "/min",
    hrs: "h",
  },

  onboarding: {
    find: "DESCUBRE",
    findDesc: "Puedes conectarte con personas de todo\nel mundo para chatear, enviar mensajes y\ncrear conexiones con ellas.",
    chat: "CHATEA",
    chatDesc: "Chatea con desconocidos para conoceros\nmejor y tener una buena\ncompatibilidad.",
    videoCall: "VIDEOLLAMADA",
    videoCallDesc: "Puedes compartir tus videos y fotos\ncon tus amigos y conexiones.",
  },

  hostsScreen: {
    allHosts: "Todos los hosts",
    failedLoad: "No se pudieron cargar los hosts. Desliza para actualizar.",
  },

  reviews: {
    failedLoad: "No se pudieron cargar las reseñas.",
    reviewsCount: "{count} reseñas",
    noReviews: "Aún no hay reseñas",
    beFirst: "Sé el primero en dejar una reseña",
    user: "Usuario",
    today: "Hoy",
    yesterday: "Ayer",
    daysAgo: "hace {count} días",
    weekAgo: "hace {count} semana",
    weeksAgo: "hace {count} semanas",
    monthAgo: "hace {count} mes",
    monthsAgo: "hace {count} meses",
  },
};

export default es;
