// VoxLink — Spanish Strings

const es = {
  common: {
    ok: "Aceptar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Guardar",
    delete: "Eliminar",
    edit: "Editar",
    done: "Listo",
    back: "Atrás",
    close: "Cerrar",
    loading: "Cargando...",
    error: "Algo salió mal",
    retry: "Reintentar",
    submit: "Enviar",
    next: "Siguiente",
    skip: "Omitir",
    yes: "Sí",
    no: "No",
    search: "Buscar",
    filter: "Filtrar",
    clear: "Limpiar",
    apply: "Aplicar",
    share: "Compartir",
    copy: "Copiar",
    copied: "Copiado!",
    noResults: "Sin resultados",
    optional: "Opcional",
    required: "Requerido",
    all: "Todos",
    more: "Más",
    less: "Menos",
    seeAll: "Ver todo",
    noData: "Sin datos disponibles",
    refresh: "Actualizar",
  },
  auth: {
    login: "Iniciar sesión",
    register: "Registrarse",
    logout: "Cerrar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    newPassword: "Nueva contraseña",
    phone: "Número de teléfono",
    otp: "Código de verificación",
    sendOtp: "Enviar OTP",
    verifyOtp: "Verificar OTP",
    resendOtp: "Reenviar OTP",
    fullName: "Nombre completo",
    createAccount: "Crear cuenta",
    alreadyHaveAccount: "¿Ya tienes cuenta?",
    dontHaveAccount: "¿No tienes cuenta?",
    welcomeBack: "¡Bienvenido de nuevo!",
    loginToContinue: "Inicia sesión para continuar",
    createYourAccount: "Crea tu cuenta",
    joinVoxLink: "Únete a VoxLink hoy",
    enterOtp: "Introduce el OTP enviado a",
    passwordResetSent: "Correo de restablecimiento enviado",
    checkEmail: "Revisa tu correo para las instrucciones",
    passwordChanged: "Contraseña cambiada exitosamente",
    invalidCredentials: "Correo o contraseña inválidos",
    accountDeleted: "Cuenta eliminada exitosamente",
    deleteAccountConfirm: "¿Seguro que quieres eliminar tu cuenta? Esta acción es irreversible.",
    tagline: "Conecta. Habla. Crece.",
    welcomeToVoxLink: "Bienvenido a VoxLink",
    autoCreateAccount: "¿Usuario nuevo? Crearemos tu cuenta automáticamente en el primer inicio de sesión",
    continueWithGoogle: "Continuar con Google",
    signingIn: "Iniciando sesión...",
    or: "o",
    quickLogin: "Inicio rápido",
    pleaseWait: "Por favor espera...",
    quickLoginNote: "El inicio rápido guarda tu cuenta en este dispositivo — reinstala y seguirá siendo tuya",
    welcomeName: "¡Bienvenido, {name}!",
    welcomeBackToast: "¡Bienvenido de nuevo!",
    quickLoginTitle: "Inicio rápido",
    accountCreated: "¡Cuenta creada! Bienvenido a VoxLink.",
    welcomeTitle: "Bienvenido",
    connectionError: "Sin conexión a internet. Por favor verifica tu red.",
    connectionErrorTitle: "Error de conexión",
    quickLoginFailed: "Falló el inicio rápido. Inténtalo de nuevo.",
  },
  nav: {
    home: "Inicio",
    search: "Buscar",
    messages: "Mensajes",
    wallet: "Billetera",
    profile: "Perfil",
    notifications: "Notificaciones",
  },
  home: {
    greeting: "Hola",
    findHosts: "Buscar anfitrión",
    topListeners: "Mejores oyentes",
    trending: "En tendencia",
    newHosts: "Nuevos anfitriones",
    onlineNow: "En línea ahora",
    featuredHosts: "Anfitriones destacados",
    seeAll: "Ver todo",
    searchPlaceholder: "Buscar anfitriones, temas...",
    findMore: "Buscar más",
    findMoreSub: "Conéctate con un oyente aleatorio ahora",
    startRandomCall: "Iniciar llamada aleatoria",
    welcome: "Bienvenido",
    freeMinutesTitle: "¡{count} minutos de llamada gratis disponibles!",
    freeMinutesSub: "Tus primeros {count} minutos corren por nuestra cuenta — inicia una llamada con cualquier anfitrión.",
    lowOnCoins: "Pocas monedas ({count} restantes)",
    lowOnCoinsSub: "Recarga ahora para que no te corten a mitad de la llamada.",
    topUp: "Recargar",
    yourFavorites: "Tus favoritos",
    viewAll: "Ver todo",
    recommendedForYou: "Recomendado para ti",
    browseByTopic: "Explorar por tema",
    availableNow: "Disponible ahora",
    online: "en línea",
    noListenersAvailable: "No hay oyentes disponibles en este momento",
    offlineListeners: "Oyentes desconectados",
  },

  // Random Match
  random: {
    title: "Coincidencia Aleatoria",
    randomMatch: "🎲 Coincidencia Aleatoria",
    cancel: "Cancelar",
    voiceCall: "Llamada de Voz",
    videoCall: "Videollamada",
    findingMatch: "Buscando tu coincidencia…",
    listenersOnline: "{count} oyentes en línea",
    listenerOnline: "{count} oyente en línea",
    chooseCallType: "Elegir Tipo de Llamada",
    matchFound: "¡Es una coincidencia! 🎉",
    accept: "Aceptar",
    decline: "Rechazar",
    skipNext: "Saltar / Siguiente",
    checking: "Comprobando…",
    filters: "Filtros",
    matchFilters: "Filtros de coincidencia",
    gender: "Género",
    genderAny: "Cualquiera",
    genderMale: "Masculino",
    genderFemale: "Femenino",
    minimumRating: "Calificación mínima",
    ratingAny: "Cualquiera",
    rating3: "3★ +",
    rating4: "4★ +",
    rating4_5: "4.5★ +",
    reset: "Restablecer",
    done: "Listo",
    myBalance: "Mi saldo",
    needCoins: "Necesitas al menos {count} monedas para iniciar esta llamada.",
    statusInsufficientCoins: "Monedas insuficientes para iniciar una llamada aleatoria.",
    statusNotEnoughCoinsTitle: "Monedas insuficientes",
    statusRateLimited: "Más despacio, vuelve a intentarlo…",
    statusDailyLimit: "Has alcanzado el límite diario de coincidencias.",
    statusDeclineCooldown: "Demasiados rechazos — toma un breve descanso.",
    statusNoMatchFilters: "Ningún anfitrión coincide con tus filtros — relájalos.",
    statusSearching: "Buscando entre los oyentes en línea…",
    statusNoneOnline: "No hay oyentes en línea ahora — aún buscando…",
    statusGiveUp: "No se encontró anfitrión. Inténtalo más tarde.",
    statusNetworkError: "Error de red, reintentando…",
    statusServerUnreachable: "No se pudo contactar el servidor. Inténtalo de nuevo.",
    hostBusy: "El anfitrión está ocupado — buscando otro.",
    hostOffline: "El anfitrión se desconectó — buscando otro.",
    hostUnavailable: "Anfitrión no disponible — buscando otro.",
    failedLoadHosts: "No se pudieron cargar los anfitriones disponibles.",
  },
  hosts: {
    host: "Anfitrión",
    listener: "Oyente",
    online: "En línea",
    offline: "Fuera de línea",
    busy: "Ocupado",
    rating: "Calificación",
    reviews: "Reseñas",
    review: "Reseña",
    coinsPerMinute: "monedas/min",
    totalMinutes: "min totales",
    specialties: "Especialidades",
    languages: "Idiomas",
    about: "Acerca de",
    callNow: "Llamar ahora",
    audioCall: "Llamada de audio",
    videoCall: "Videollamada",
    sendMessage: "Enviar mensaje",
    talkNow: "Hablar ahora",
    noHostsFound: "No se encontraron anfitriones",
    adjustFilters: "Intenta ajustar los filtros",
    topRated: "Mejor calificado",
    viewProfile: "Ver perfil",
    startCall: "Iniciar llamada",
  },
  calls: {
    incoming: "Llamada entrante",
    outgoing: "Conectando...",
    ongoing: "En llamada",
    ended: "Llamada terminada",
    audio: "Llamada de audio",
    video: "Videollamada",
    accept: "Aceptar",
    decline: "Rechazar",
    endCall: "Terminar llamada",
    mute: "Silenciar",
    unmute: "Activar micrófono",
    speaker: "Altavoz",
    flipCamera: "Voltear cámara",
    callDuration: "Duración de la llamada",
    callWith: "Llamada con",
    rateCall: "Calificar esta llamada",
    callHistory: "Historial de llamadas",
    noCallHistory: "Sin historial de llamadas",
    callCost: "Costo de la llamada",
    perMinute: "por minuto",
    lowBalance: "Saldo bajo de monedas",
    lowBalanceMsg: "Pocas monedas. Recarga para continuar.",
    callEnded: "Llamada terminada",
    callEndedMsg: "Tu llamada ha terminado",
    missed: "Perdida",
    answered: "Contestada",
    rejected: "Rechazada",
    callingHistory: "Historial de llamadas",
    audioShort: "Audio",
    videoShort: "Video",
    incomingVideo: "Videollamada entrante",
    incomingAudio: "Llamada de voz entrante",
    unknown: "Desconocido",
    voxlinkHost: "Anfitrión de VoxLink",
    voxlinkUser: "Usuario de VoxLink",
    voiceCall: "Llamada de voz",
    callDeclined: "Llamada rechazada",
    noAnswer: "Sin respuesta",
    ringing: "Llamando",
    connecting: "Conectando",
    coinsPerMin: "monedas / min",
    oneMinMinimum: "1 min mínimo",
    callAutoEnded: "Llamada finalizada automáticamente",
    autoDisconnected: "Te quedaste sin monedas — la llamada se desconectó automáticamente",
    with: "con",
    minBilling: "Cobro mínimo de 1 min aplicado",
    duration: "Duración",
    coinsSpent: "Monedas gastadas",
    rateName: "Califica a {name}",
    feedbackHelps: "Tus comentarios ayudan al anfitrión a mejorar",
    ratingPoor: "Mala",
    ratingFair: "Regular",
    ratingGood: "Buena",
    ratingGreat: "Muy buena",
    ratingExcellent: "¡Excelente!",
    submitRating: "Enviar calificación",
    thankYou: "¡Gracias! 🙏",
    ratingSubmitted: "Tu calificación ha sido enviada",
    rechargeCoins: "Recargar monedas",
    backHome: "Volver al inicio",
    rateFailed: "No se pudo enviar la calificación, inténtalo de nuevo.",
    errorTitle: "Error",
    completed: "Completada",
    cancelled: "Cancelada",
    noCallHistoryFound: "No se encontró historial de llamadas",
    failedLoadHistory: "No se pudo cargar el historial de llamadas.",
    micAccessNeeded: "Se necesita acceso al micrófono — Toca para solucionar",
    coinsRunningLow: "Quedan pocas monedas",
    secondsRemaining: "{count}s restantes",
    minLeft: "{count} min restantes",
    ringingDots: "Llamando...",
    connectingDots: "Conectando...",
    connected: "Conectado",
    networkDrop: "Caída de red — reconectando...",
    connectionFailed: "Conexión fallida — reintentando...",
    callEndedShort: "Llamada finalizada",
    mutedHint: "🔇 Silenciado",
    speakerOn: "Altavoz activado",
    runningOutCoins: "¡Te estás quedando sin monedas!",
    autoDisconnectIn: "La llamada se desconectará en {time}",
    second: "segundo",
    seconds: "segundos",
    fewSeconds: "unos segundos",
    rechargeNow: "Recargar ahora",
    continueCall: "Continuar llamada",
    cameraOff: "Cámara apagada",
    cameraUnavailable: "Cámara no disponible",
    startingCamera: "Iniciando cámara…",
    noPermission: "Sin permiso",
    cameraOffShort: "Cámara apagada",
    you: "Tú",
    mutedLabel: "Silenciado",
    noMic: "Sin micrófono",
    lowCoins: "Pocas monedas",
    secondsLeft: "{count}s restantes",
    connectionIssue: "Problema de conexión",
    live: "EN VIVO",
    waitingResponse: "Esperando respuesta...",
    camera: "Cámara",
    camOff: "Cám. apagada",
    end: "Colgar",
    flip: "Girar",
    earpiece: "Auricular",
  },
  chat: {
    messages: "Mensajes",
    newMessage: "Nuevo mensaje",
    typeMessage: "Escribe un mensaje...",
    send: "Enviar",
    noMessages: "Sin mensajes aún",
    startConversation: "Iniciar conversación",
    online: "En línea",
    offline: "Fuera de línea",
    typing: "escribiendo...",
    delivered: "Entregado",
    read: "Leído",
    deleteChat: "Eliminar chat",
    deleteChatConfirm: "¿Seguro que quieres eliminar esta conversación?",
    chats: "Chats",
    searchConversations: "Buscar conversaciones...",
    noConversationsFound: "No se encontraron conversaciones",
    noConversationsYet: "Aún no hay conversaciones",
    tryDifferentName: "Prueba con otro nombre",
    startChattingAfterCall: "Empieza a chatear después de una llamada con un anfitrión",
  },
  wallet: {
    wallet: "Billetera",
    coinBalance: "Saldo de monedas",
    coins: "Monedas",
    coin: "Moneda",
    buyCoins: "Comprar monedas",
    coinHistory: "Historial de monedas",
    transactions: "Transacciones",
    noTransactions: "Sin transacciones aún",
    purchased: "Comprado",
    spent: "Gastado",
    bonus: "Bono",
    refunded: "Reembolsado",
    withdrawal: "Retiro",
    totalSpent: "Total gastado",
    totalPurchased: "Total comprado",
    popular: "Más popular",
    bestValue: "Mejor valor",
    bonus_label: "BONO",
    recharge: "Recargar",
    choosePackage: "Elegir paquete",
    instantDelivery: "Entrega instantánea",
    securePayment: "Pago seguro",
    guaranteed: "Satisfacción garantizada",
  },
  profile: {
    profile: "Perfil",
    editProfile: "Editar perfil",
    myProfile: "Mi perfil",
    name: "Nombre",
    email: "Correo electrónico",
    phone: "Teléfono",
    gender: "Género",
    male: "Masculino",
    female: "Femenino",
    other: "Otro",
    country: "País",
    bio: "Biografía",
    language: "Idioma",
    settings: "Configuración",
    helpCenter: "Centro de ayuda",
    privacy: "Política de privacidad",
    about: "Acerca de VoxLink",
    shareApp: "Compartir VoxLink",
    rateApp: "Calificar la app",
    logout: "Cerrar sesión",
    deleteAccount: "Eliminar cuenta",
    callHistory: "Historial de llamadas",
    joinedOn: "Miembro desde",
    totalCalls: "Total de llamadas",
    hoursSpent: "Horas dedicadas",
  },
  settings: {
    settings: "Configuración",
    notifications: "Notificaciones",
    callNotifications: "Notificaciones de llamadas",
    messageNotifications: "Notificaciones de mensajes",
    promoNotifications: "Notificaciones promocionales",
    language: "Idioma",
    theme: "Tema",
    lightMode: "Modo claro",
    darkMode: "Modo oscuro",
    systemDefault: "Predeterminado del sistema",
    privacy: "Privacidad",
    security: "Seguridad",
    changePassword: "Cambiar contraseña",
    twoFactor: "Autenticación de dos factores",
    account: "Cuenta",
    support: "Soporte",
  },
  payment: {
    checkout: "Pagar",
    selectPackage: "Seleccionar paquete",
    paymentMethod: "Método de pago",
    creditCard: "Tarjeta de crédito/débito",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "Procesando pago...",
    paymentSuccess: "Pago exitoso!",
    paymentFailed: "Pago fallido",
    orderSummary: "Resumen del pedido",
    total: "Total",
    coins: "Monedas",
    bonusCoins: "Monedas de bono",
    tryAgain: "Intentar de nuevo",
    secureNote: "Todos los pagos están protegidos y encriptados",
  },
  host: {
    dashboard: "Panel",
    totalEarnings: "Ganancias totales",
    thisWeek: "Esta semana",
    thisMonth: "Este mes",
    totalCalls: "Total llamadas",
    avgRating: "Calificación promedio",
    onlineStatus: "Estado en línea",
    goOnline: "Conectarse",
    goOffline: "Desconectarse",
    setBusy: "Marcar como ocupado",
    earnings: "Ganancias",
    withdraw: "Retirar",
    withdrawal: "Retiro",
    minimumWithdraw: "Mínimo 100 monedas",
    enterAmount: "Ingresar monto",
    withdrawMethod: "Método de retiro",
    bankTransfer: "Transferencia bancaria",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "Detalles de cuenta",
    withdrawSuccess: "Solicitud de retiro enviada",
    withdrawPending: "Tu solicitud está siendo procesada",
    hostSettings: "Configuración del anfitrión",
    availability: "Disponibilidad",
    payoutSettings: "Configuración de pago",
    becomeHost: "Ser anfitrión",
    apply: "Aplicar ahora",
    applicationSent: "¡Solicitud enviada!",
    applicationDesc: "Revisaremos tu solicitud y te contactaremos en 2-3 días hábiles.",
  },
  errors: {
    network: "Error de red. Por favor verifica tu conexión.",
    server: "Error del servidor. Intenta más tarde.",
    unauthorized: "Sesión expirada. Por favor inicia sesión de nuevo.",
    notFound: "El recurso solicitado no fue encontrado.",
    insufficientCoins: "Monedas insuficientes. Por favor recarga.",
    callFailed: "La llamada no pudo conectarse. Intenta de nuevo.",
    permissionDenied: "Permiso denegado.",
    generic: "Algo salió mal. Por favor intenta de nuevo.",
  },

  tabs: {
    home: "Inicio",
    listener: "Oyente",
    random: "Aleatorio",
    chat: "Chat",
    calling: "Llamadas",
  },

  listener: {
    allListeners: "Todos los oyentes",
    language: "Idioma",
    talkAbout: "Hablar sobre",
    selectLanguage: "Seleccionar idioma",
    noListenersFound: "No se encontraron oyentes",
    failedLoad: "No se pudieron cargar los oyentes.",
    available: "Disponible",
    offline: "Desconectado",
    audio: "Audio",
    video: "Video",
    perMin: "/min",
    hrs: "h",
  },

  onboarding: {
    find: "DESCUBRE",
    findDesc: "Puedes conectarte con personas de todo\nel mundo para chatear, enviar mensajes y\ncrear conexiones con ellas.",
    chat: "CHATEA",
    chatDesc: "Chatea con desconocidos para conoceros\nmejor y tener una buena\ncompatibilidad.",
    videoCall: "VIDEOLLAMADA",
    videoCallDesc: "Puedes compartir tus videos y fotos\ncon tus amigos y conexiones.",
  },

  hostsScreen: {
    allHosts: "Todos los hosts",
    failedLoad: "No se pudieron cargar los hosts. Desliza para actualizar.",
  },

  reviews: {
    failedLoad: "No se pudieron cargar las reseñas.",
    reviewsCount: "{count} reseñas",
    noReviews: "Aún no hay reseñas",
    beFirst: "Sé el primero en dejar una reseña",
    user: "Usuario",
    today: "Hoy",
    yesterday: "Ayer",
    daysAgo: "hace {count} días",
    weekAgo: "hace {count} semana",
    weeksAgo: "hace {count} semanas",
    monthAgo: "hace {count} mes",
    monthsAgo: "hace {count} meses",
  },

  notFound: {
    title: "¡Ups!",
    message: "Esta pantalla no existe.",
    goHome: "¡Ir a la pantalla de inicio!",
  },

  aboutScreen: {
    title: "Acerca de VoxLink",
    appTagline: "Conexión de voz y video",
    version: "Versión {version}",
    statActiveUsers: "Usuarios activos",
    statHosts: "Anfitriones",
    statCallsMade: "Llamadas hechas",
    statAppRating: "Valoración de la app",
    whatIsTitle: "¿Qué es VoxLink?",
    whatIsBody1: "VoxLink es una plataforma social de llamadas de audio y video que conecta a las personas con anfitriones verificados para conversaciones significativas. Ya sea que necesites consejos de vida, práctica de idiomas, apoyo emocional o solo alguien con quien hablar — nuestros anfitriones están aquí para ti.",
    whatIsBody2: "Los anfitriones son personas reales y capacitadas, verificadas por nuestro equipo. Cada llamada es segura, privada y respaldada por nuestro sistema de pago basado en monedas — así solo pagas por el tiempo que usas.",
    keyFeatures: "Funciones clave",
    feature1: "Llamadas de audio y video HD",
    feature2: "Cifrado de extremo a extremo",
    feature3: "Más de 1,200 anfitriones verificados",
    feature4: "Precios justos basados en monedas",
    feature5: "Chat en la app",
    feature6: "Sistema de reseñas calificadas",
    connectWithUs: "Conéctate con nosotros",
    linkWebsite: "Sitio web",
    linkTwitter: "Twitter / X",
    linkInstagram: "Instagram",
    linkContact: "Contáctanos",
    helpCenter: "Centro de ayuda",
    copyright: "© 2026 VoxLink Inc. Todos los derechos reservados.",
  },

  privacyScreen: {
    bannerTitle: "Tu privacidad importa",
    bannerSub: "Esta política explica cómo VoxLink recopila, usa y protege tus datos.",
    lastUpdated: "Última actualización: 1 de marzo de 2026",
    contactTitle: "¿Preguntas sobre privacidad?",
    s1Title: "1. Información que recopilamos",
    s1Body: "Recopilamos la información que nos proporcionas directamente, como cuando creas una cuenta, actualizas tu perfil, realizas compras o nos contactas para soporte. Esto incluye tu nombre, dirección de correo electrónico, nombre de usuario, foto de perfil e información de pago.\n\nTambién recopilamos información automáticamente cuando usas VoxLink, incluyendo datos de registro, información del dispositivo, información de ubicación (si se permite) y datos de uso como las funciones que utilizas y el tiempo dedicado a las llamadas.",
    s2Title: "2. Cómo usamos tu información",
    s2Body: "Usamos la información que recopilamos para proporcionar, mantener y mejorar nuestros servicios, procesar transacciones y enviar información relacionada, enviar notificaciones, avisos técnicos, actualizaciones y mensajes de soporte.\n\nTambién usamos tus datos para responder a tus comentarios, preguntas y solicitudes, monitorear y analizar tendencias y uso, detectar, investigar y prevenir transacciones fraudulentas y otras actividades ilegales.",
    s3Title: "3. Compartir información",
    s3Body: "No compartimos tu información personal con terceros, excepto como se describe en esta política. Podemos compartir información con proveedores, consultores y otros prestadores de servicios que necesiten acceso a dicha información para realizar trabajos en nuestro nombre.\n\nPodemos divulgar tu información si creemos que la divulgación es conforme a, o requerida por, cualquier ley o proceso legal aplicable, incluidas las solicitudes legales de autoridades públicas para cumplir con requisitos de seguridad nacional o de las fuerzas del orden.",
    s4Title: "4. Datos de llamadas y audio",
    s4Body: "El contenido de las llamadas de audio y video se transmite a través de canales cifrados. No grabamos ni almacenamos el contenido de tus llamadas a menos que habilites explícitamente una función de grabación (si está disponible). Los metadatos de la llamada (duración, participantes, marcas de tiempo) se almacenan para proporcionar funciones de facturación e historial.",
    s5Title: "5. Monedas y pagos",
    s5Body: "La información de pago se procesa a través de procesadores de pago de terceros seguros. No almacenamos los detalles completos de la tarjeta de pago en nuestros servidores. Las transacciones de monedas se registran con fines de contabilidad y resolución de disputas.",
    s6Title: "6. Seguridad de los datos",
    s6Body: "Tomamos medidas razonables para ayudar a proteger la información sobre ti de pérdida, robo, mal uso y acceso, divulgación, alteración y destrucción no autorizados. Todos los datos se cifran en tránsito mediante TLS y en reposo mediante cifrado AES-256.",
    s7Title: "7. Retención de datos",
    s7Body: "Conservamos la información personal durante el tiempo necesario para prestar nuestros servicios y cumplir los fines descritos en esta Política de privacidad, a menos que la ley exija o permita un período de retención más largo. Puedes solicitar la eliminación de tu cuenta y los datos asociados en cualquier momento a través de la pantalla de Configuración.",
    s8Title: "8. Privacidad de los menores",
    s8Body: "VoxLink no está destinado a menores de 18 años. No recopilamos a sabiendas información personal de menores de 18 años. Si descubrimos que hemos recopilado información personal de un menor de 18 años, eliminaremos esa información.",
    s9Title: "9. Tus derechos",
    s9Body: "Tienes derecho a acceder, actualizar o eliminar tu información personal en cualquier momento. También puedes oponerte al procesamiento, solicitar la portabilidad de los datos o retirar el consentimiento cuando el procesamiento se base en el consentimiento. Para ejercer estos derechos, contáctanos a través del Centro de ayuda.",
    s10Title: "10. Cambios en esta política",
    s10Body: "Podemos actualizar esta Política de privacidad de vez en cuando. Te notificaremos cualquier cambio publicando la nueva política en esta página y actualizando la fecha de 'Última actualización'. Tu uso continuado de VoxLink después de cualquier cambio constituye tu aceptación de la nueva Política de privacidad.",
  },

  helpScreen: {
    title: "Centro de ayuda",
    bannerTitle: "¿Necesitas ayuda o FAQ?",
    bannerSub: "Encuentra respuestas a preguntas comunes",
    contactTitle: "¿Tienes un problema?",
    faqTitle: "Preguntas frecuentes",
    q1: "¿Qué es VoxLink?",
    a1: "VoxLink es una plataforma social donde puedes conectarte con oyentes y anfitriones profesionales mediante llamadas de audio o video. Obtén apoyo personalizado sobre temas como relaciones, carrera, coaching de vida y más.",
    q2: "¿Quiénes son los anfitriones/oyentes?",
    a2: "Los anfitriones son profesionales verificados o personas con experiencia que brindan apoyo y conversación. Se especializan en diversos temas y están disponibles para llamadas de audio y video.",
    q3: "¿Cómo hago una llamada?",
    a3: "Explora los anfitriones disponibles en la pantalla de inicio, toca la tarjeta de un anfitrión para ver su perfil y luego toca 'Hablar ahora' para iniciar una llamada de audio o video. Las llamadas se cobran en monedas por minuto.",
    q4: "¿Qué son las monedas?",
    a4: "Las monedas son la moneda dentro de la app de VoxLink. Compras paquetes de monedas en la sección Billetera y las gastas durante las llamadas con anfitriones según su tarifa por minuto.",
    q5: "¿Mi conversación es privada?",
    a5: "Sí, todas las conversaciones son privadas y confidenciales. Seguimos políticas estrictas de protección de datos y no compartimos detalles de conversaciones personales con terceros.",
    q6: "¿Cómo me convierto en anfitrión?",
    a6: "El hospedaje se realiza a través de nuestra app independiente VoxLink Host. Descarga la app Host para postularte, verificar tu identidad y comenzar a recibir llamadas y ganar.",
    q7: "¿Qué pasa si me quedo sin monedas?",
    a7: "Si te quedas sin monedas durante una llamada, la llamada finalizará automáticamente. Puedes comprar más monedas en cualquier momento desde la sección Billetera.",
  },

  coinHistory: {
    title: "Historial de monedas",
    currentBalance: "Saldo actual",
    earned: "Ganado",
    spent: "Gastado",
    tabAll: "Todos",
    tabPurchase: "Compra",
    tabSpent: "Gastado",
    tabBonus: "Bono",
    today: "Hoy",
    yesterday: "Ayer",
    ref: "Ref:",
    noTransactions: "No se encontraron transacciones",
    failedLoad: "No se pudo cargar el historial de monedas.",
  },

  notificationsScreen: {
    markAllRead: "Marcar todo como leído",
    empty: "Aún no hay notificaciones",
    goBack: "Volver",
    markAllReadLabel: "Marcar todas las notificaciones como leídas",
    failedLoad: "No se pudieron cargar las notificaciones.",
    failedMarkAll: "No se pudieron marcar las notificaciones como leídas.",
    failedUpdate: "No se pudo actualizar la notificación.",
  },

  searchHosts: {
    searchPlaceholder: "Buscar anfitriones por nombre...",
    topic: "Tema",
    status: "Estado",
    language: "Idioma",
    hostsFound: "{count} anfitriones encontrados",
    noResults: "No se encontraron anfitriones que coincidan con tu búsqueda",
    talk: "Hablar",
    failedLoad: "No se pudieron cargar los anfitriones.",
  },

  chatScreen: {
    defaultName: "Chat",
    emptyHint: "Envía un mensaje para iniciar la conversación",
    sending: "Enviando…",
    tapToRetry: "Toca para reintentar",
    a11yBack: "Volver",
    a11yPhotoMessage: "Mensaje de foto",
    a11yRetry: "Reintentar enviar mensaje",
    a11yAttach: "Adjuntar foto",
    a11ySend: "Enviar mensaje",
    permissionTitle: "Permiso requerido",
    permissionPhoto: "Permite el acceso a la fototeca para enviar una foto.",
    failedLoadMessages: "No se pudieron cargar los mensajes.",
    uploadFailed: "Error al subir. Inténtalo de nuevo.",
    photoSendFailed: "No se pudo enviar la foto. Inténtalo de nuevo.",
  },

  hostDetail: {
    notFound: "Anfitrión no encontrado",
    selectCallType: "Seleccionar tipo de llamada",
    coinPerMin: "{count} monedas/min",
    coin: "{count} monedas",
    levelShort: "Nv.",
    languageColon: "Idioma : ",
    idLabel: "ID:",
    totalCall: "Llamadas totales",
    experience: "Experiencia",
    recent: "Reciente",
    chatNow: "Chatear ahora",
    chatLocked: "🔒 Chat",
    chatLockedTitle: "🔒 Chat bloqueado",
    chatLockedMsg: "Para chatear con {name}, primero debes llamarle. ¡El chat se desbloquea automáticamente después de una llamada!",
    chatLockedMsg2: "¡Haz una llamada primero y el chat se desbloqueará automáticamente!",
    offlineMsg: "{name} está desconectado en este momento.",
    idCopied: "ID del anfitrión copiado al portapapeles.",
    reportThanks: "Gracias por tu reporte. Nuestro equipo lo revisará pronto.",
    reportSubmitted: "Reporte enviado",
    reportFailMsg: "No se pudo enviar el reporte. Inténtalo de nuevo.",
    reportFailed: "Reporte fallido",
    failedLoad: "No se pudieron cargar los detalles del anfitrión.",
    reportTitle: "Reportar a {name}",
    reportSubtitle: "¿Por qué reportas a este anfitrión?",
    reportInappropriate: "Contenido inapropiado",
    reportHarassment: "Acoso",
    reportFakeProfile: "Perfil falso",
    reportScam: "Estafa / Fraude",
    reportSpam: "Spam",
  },

  checkout: {
    currentBalance: "Saldo actual",
    popular: "Popular",
    online: "En línea",
    autoGateway: "Pasarela automática",
    manualUpi: "UPI manual",
    qrUpiId: "QR / ID UPI",
    manualApprovalNote: "⏱ El pago manual requiere aprobación del administrador (unas horas). Las monedas se añadirán tras la verificación.",
    promoCode: "Código promocional",
    promoPlaceholder: "Ingresa el código promocional",
    remove: "Quitar",
    invalidPromo: "Código promocional inválido",
    percentOff: "🎉 {pct}% de descuento — Ahorras {amount}",
    bonusCoinsAdded: "🎁 ¡+{count} monedas de bono añadidas!",
    promoBonus: "Bono promocional",
    youGet: "Recibes",
    promoDiscount: "Descuento promocional",
    securePayments: "Los pagos están 100% protegidos y cifrados",
    selectPackageBtn: "Selecciona un paquete",
    payViaUpi: "Pagar por UPI — {price} por {coins} monedas",
    continuePay: "Continuar — {price} por {coins} monedas",
    redirecting: "Redirigiendo al pago...",
    submittedForReview: "¡Pago enviado para revisión!",
    submitted: "Enviado",
    coinsAddedToast: "¡{count} monedas añadidas!",
    purchaseSuccessful: "Compra exitosa",
    paymentFailed: "Pago fallido. Inténtalo de nuevo.",
    paymentFailedTitle: "Pago fallido",
    manualUpiTitle: "Pago manual por UPI",
    autoApproved: "⚡ ¡Aprobado automáticamente!",
    coinsAdded: "¡Monedas añadidas!",
    paymentSubmitted: "¡Pago enviado!",
    autoApprovedSub: "¡{count} monedas se han añadido instantáneamente a tu cuenta!",
    underReviewSub: "Tu pago está en revisión. Las monedas se añadirán una vez que el administrador lo apruebe (generalmente en unas horas).",
    package: "Paquete",
    utrRef: "UTR / Ref",
    loadingPayment: "Cargando detalles del pago...",
    unavailable: "No disponible",
    unavailableSub: "El pago manual no está disponible en este momento. Prueba otro método de pago.",
    scanQrStep: "Escanea el QR o paga al ID UPI",
    payToUpi: "Pagar al ID UPI",
    account: "Cuenta:",
    autoRotating: "🔄 Rotación automática",
    enterUtrStep: "Ingresa el UTR / ID de transacción",
    utrHint: "Después del pago, busca el UTR de 12 dígitos o la referencia de transacción en tu app UPI.",
    utrPlaceholder: "Ingresa el UTR / Núm. de referencia",
    adminApprovalTitle: "⏱ Se requiere aprobación del administrador",
    adminApprovalNote: "Los pagos manuales son verificados por nuestro equipo. Las monedas se acreditarán dentro de unas horas tras la aprobación. Asegúrate de pagar el monto exacto.",
    submitProof: "Enviar comprobante de pago",
    utrRequiredMsg: "Ingresa el número de UTR / referencia de transacción.",
    submissionFailed: "Envío fallido",
    submissionFailedMsg: "No se pudo enviar el pago. Inténtalo de nuevo.",
    coinPack: "Paquete de monedas",
    upiQrPayment: "Pago UPI / QR",
    notAvailable: "No disponible",
    manualUnavailable: "El pago manual por UPI no está disponible actualmente. Prueba otro método de pago.",
    retry: "Reintentar",
    instantApproval: "Aprobación instantánea",
    coinsAddedWallet: "¡{count} monedas se han añadido a tu billetera!",
    beingReviewed: "Tu pago está siendo revisado. Las monedas se acreditarán dentro de unas horas.",
    amount: "Monto",
    status: "Estado",
    approved: "Aprobado",
    pendingReview: "Revisión pendiente",
    scanQrPay: "Escanea el código QR y paga",
    qrNotAvailable: "QR no disponible",
    upiId: "ID UPI",
    copy: "Copiar",
    payExactly: "Paga exactamente {amount} a este ID UPI",
    utrHintHistory: "Después del pago, busca el UTR de 12 dígitos o la referencia de transacción en el historial de pagos de tu app UPI.",
    utrExample: "p. ej. 412345678901",
    whereUtr: "¿Dónde encontrar el UTR?",
    whereUtrText: "Abre tu app UPI (PhonePe / GPay / Paytm) → Historial de transacciones → Toca el pago → Copia el \"UTR\" o \"ID de referencia\"",
    verifyNote: "Las monedas se añadirán tras la verificación del administrador (generalmente en unas horas). Asegúrate de pagar el monto exacto.",
    submitPayment: "Enviar pago",
    enterUtrContinue: "Ingresa el UTR para continuar",
    utrRequiredMsg2: "Ingresa el número de UTR / referencia de transacción",
    utrTooShort: "El UTR debe tener al menos 6 caracteres",
    invalidUtr: "UTR inválido",
    planMissing: "Falta la información del plan. Vuelve atrás e inténtalo de nuevo.",
    submissionFailedShort: "Envío fallido. Inténtalo de nuevo.",
  },

  successScreen: {
    title: "¡Pago exitoso!",
    subtitle: "Las monedas se han añadido a tu billetera",
    note: "Ahora puedes usar tus monedas para hacer llamadas con anfitriones",
    findHost: "Encuentra un anfitrión para hablar",
    viewWallet: "Ver billetera",
  },

  editProfile: {
    updated: "Tu perfil se ha actualizado.",
    savedTitle: "Perfil guardado",
    saveFailedMsg: "No se pudo guardar tu perfil. Inténtalo de nuevo.",
    saveFailed: "Error al guardar",
    permissionTitle: "Permiso requerido",
    permissionMsg: "Permite el acceso a tu fototeca para cambiar tu avatar.",
    uploadFailed: "Error al subir",
    uploadFailedMsg: "No se pudo subir el avatar. Inténtalo de nuevo.",
    displayName: "Nombre visible",
    namePlaceholder: "Tu nombre",
    bioPlaceholder: "Cuéntales a los demás sobre ti...",
    saveChanges: "Guardar cambios",
  },

  referralScreen: {
    title: "Recomienda y gana",
    heroTitle: "¡Invita amigos, gana monedas!",
    heroSub: "Por cada amigo que se una a VoxLink con tu código, tu amigo recibe {newUser} monedas de bono y tú ganas {referrer} monedas.",
    yourCode: "Tu código de referido",
    shareWithFriends: "Compartir con amigos",
    yourStats: "Tus estadísticas de referidos",
    friendsInvited: "Amigos invitados",
    coinsEarned: "Monedas ganadas",
    howItWorks: "Cómo funciona",
    step1: "Comparte tu código de referido único con amigos",
    step2: "Tu amigo se registra con tu código y recibe {count} monedas",
    step3Instant: "¡Ganas {reward} monedas al instante!",
    step3OneCall: "Cuando completen 1 llamada, ganas {reward} monedas.",
    step3Calls: "Cuando completen {count} llamadas, ganas {reward} monedas.",
    failedLoad: "No se pudo cargar la información de referidos.",
    codeCopied: "¡Código de referido copiado!",
    copyFailed: "No se pudo copiar el código. Inténtalo de nuevo.",
    shareTitle: "Únete a VoxLink",
    shareMessage: "¡Únete a VoxLink y conéctate con anfitriones increíbles para llamadas de audio y video!\n\nUsa mi código de referido: {code} para obtener monedas de bono al registrarte.\n\nDescárgala ahora: https://voxlink.app",
  },

  splash: {
    tagline: "Conecta y crea relaciones significativas",
  },

  dailyReward: {
    title: "Recompensa diaria",
    titleClaimed: "¡Recompensa reclamada!",
    dayOfStreak: "Día {day} de tu racha",
    streakUnlocked: "Día {day} de racha desbloqueado",
    claimHint: "Reclama hoy para mantener tu racha.",
    dayBonus: "Bono del día {day}: ¡+{count} monedas extra!",
    claim: "Reclamar {count} monedas",
    claiming: "Reclamando…",
    later: "Más tarde",
    awesome: "¡Genial!",
    addedToWallet: "añadidas a tu cartera",
    baseMilestone: "{base} base + {bonus} bono por hito",
    newBalance: "Nuevo saldo",
    coins: "monedas",
    freeMinutes: "¡+{count} minutos de llamada gratis!",
    monthlyChest: "Cofre mensual: ¡+{count} monedas!",
    comebackBonus: "Bono de regreso: +{count} monedas",
    spinning: "Girando…",
    luckyWheel: "Ruleta de la suerte",
    lucky: "¡SUERTE!",
    scheduleLabel: "Calendario de racha",
    nextMilestone: "{count} día para tu bono del día {day}",
    nextMilestonePlural: "{count} días para tu bono del día {day}",
    missedDay: "¡Te perdiste un día!",
    restoreWithSaver: "Restaura tu racha de {streak} días con un salvavidas gratis ({count} restantes).",
    restoreWithCoins: "Restaura tu racha de {streak} días por {count} monedas.",
    restoring: "Restaurando…",
    useStreakSaver: "Usar salvavidas de racha",
    restoreForCoins: "Restaurar por {count} monedas",
    atRiskCountdown: "Reclama pronto — ¡tu racha se reinicia en {time}!",
    atRisk: "Reclama pronto — ¡tu racha se reinicia a medianoche!",
  },
};

export default es;
