// VoxLink — Hindi Strings

const hi = {
  common: {
    ok: "ठीक है",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    save: "सहेजें",
    delete: "हटाएं",
    edit: "संपादित करें",
    done: "हो गया",
    back: "वापस",
    close: "बंद करें",
    loading: "लोड हो रहा है...",
    error: "कुछ गलत हो गया",
    retry: "फिर कोशिश करें",
    submit: "जमा करें",
    next: "अगला",
    skip: "छोड़ें",
    yes: "हाँ",
    no: "नहीं",
    search: "खोजें",
    filter: "फ़िल्टर",
    clear: "साफ़ करें",
    apply: "लागू करें",
    share: "साझा करें",
    copy: "कॉपी करें",
    copied: "कॉपी हो गया!",
    noResults: "कोई परिणाम नहीं मिला",
    optional: "वैकल्पिक",
    required: "ज़रूरी",
    all: "सभी",
    more: "अधिक",
    less: "कम",
    seeAll: "सब देखें",
    noData: "कोई डेटा उपलब्ध नहीं",
    refresh: "रीफ्रेश",
  },

  auth: {
    login: "लॉग इन",
    register: "साइन अप",
    logout: "लॉग आउट",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    forgotPassword: "पासवर्ड भूल गए?",
    newPassword: "नया पासवर्ड",
    phone: "फ़ोन नंबर",
    otp: "सत्यापन कोड",
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP सत्यापित करें",
    resendOtp: "OTP फिर भेजें",
    fullName: "पूरा नाम",
    createAccount: "खाता बनाएं",
    alreadyHaveAccount: "पहले से खाता है?",
    dontHaveAccount: "खाता नहीं है?",
    welcomeBack: "वापस स्वागत है!",
    loginToContinue: "जारी रखने के लिए लॉग इन करें",
    createYourAccount: "अपना खाता बनाएं",
    joinVoxLink: "आज VoxLink से जुड़ें",
    enterOtp: "इस नंबर पर भेजा OTP दर्ज करें",
    passwordResetSent: "पासवर्ड रीसेट ईमेल भेजा गया",
    checkEmail: "निर्देशों के लिए ईमेल जांचें",
    passwordChanged: "पासवर्ड सफलतापूर्वक बदला गया",
    invalidCredentials: "अमान्य ईमेल या पासवर्ड",
    accountDeleted: "खाता सफलतापूर्वक हटाया गया",
    deleteAccountConfirm: "क्या आप वाकई अपना खाता हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।",
    tagline: "जुड़ें. बात करें. आगे बढ़ें.",
    welcomeToVoxLink: "VoxLink में आपका स्वागत है",
    autoCreateAccount: "नए उपयोगकर्ता? पहली बार लॉगिन पर हम आपका खाता स्वतः बना देंगे",
    continueWithGoogle: "Google से जारी रखें",
    signingIn: "साइन इन हो रहा है...",
    or: "या",
    quickLogin: "क्विक लॉगिन",
    pleaseWait: "कृपया प्रतीक्षा करें...",
    quickLoginNote: "क्विक लॉगिन आपके खाते को इस डिवाइस पर सहेजता है — पुनः इंस्टॉल करें और यह फिर भी आपका रहेगा",
    welcomeName: "स्वागत है, {name}!",
    welcomeBackToast: "वापसी पर स्वागत है!",
    quickLoginTitle: "क्विक लॉगिन",
    accountCreated: "खाता बन गया! VoxLink में आपका स्वागत है।",
    welcomeTitle: "स्वागत है",
    connectionError: "कोई इंटरनेट कनेक्शन नहीं। कृपया अपना नेटवर्क जांचें।",
    connectionErrorTitle: "कनेक्शन त्रुटि",
    quickLoginFailed: "क्विक लॉगिन विफल। कृपया पुनः प्रयास करें।",
  },

  nav: {
    home: "होम",
    search: "खोजें",
    messages: "संदेश",
    wallet: "वॉलेट",
    profile: "प्रोफ़ाइल",
    notifications: "सूचनाएं",
  },

  home: {
    greeting: "नमस्ते",
    findHosts: "होस्ट खोजें",
    topListeners: "शीर्ष श्रोता",
    trending: "अभी ट्रेंडिंग",
    newHosts: "नए होस्ट",
    onlineNow: "अभी ऑनलाइन",
    featuredHosts: "विशेष होस्ट",
    seeAll: "सब देखें",
    searchPlaceholder: "होस्ट, विषय खोजें...",
    findMore: "और खोजें",
    findMoreSub: "अभी किसी रैंडम लिसनर से जुड़ें",
    startRandomCall: "रैंडम कॉल शुरू करें",
    welcome: "स्वागत है",
    freeMinutesTitle: "{count} मुफ़्त कॉल मिनट उपलब्ध!",
    freeMinutesSub: "आपके पहले {count} मिनट हमारी ओर से — किसी भी होस्ट के साथ कॉल शुरू करें।",
    lowOnCoins: "कॉइन कम हैं ({count} बचे)",
    lowOnCoinsSub: "अभी रीचार्ज करें ताकि कॉल बीच में न कटे।",
    topUp: "रीचार्ज करें",
    yourFavorites: "आपके पसंदीदा",
    viewAll: "सभी देखें",
    recommendedForYou: "आपके लिए अनुशंसित",
    browseByTopic: "विषय के अनुसार ब्राउज़ करें",
    availableNow: "अभी उपलब्ध",
    online: "ऑनलाइन",
    noListenersAvailable: "अभी कोई लिसनर उपलब्ध नहीं है",
    offlineListeners: "ऑफ़लाइन लिसनर",
  },

  // Random Match
  random: {
    title: "रैंडम मैच",
    randomMatch: "🎲 रैंडम मैच",
    cancel: "रद्द करें",
    voiceCall: "वॉइस कॉल",
    videoCall: "वीडियो कॉल",
    findingMatch: "आपका मैच ढूंढ़ रहे हैं…",
    listenersOnline: "{count} लिसनर ऑनलाइन",
    listenerOnline: "{count} लिसनर ऑनलाइन",
    chooseCallType: "कॉल का प्रकार चुनें",
    matchFound: "मैच मिल गया! 🎉",
    accept: "स्वीकार करें",
    decline: "अस्वीकार",
    skipNext: "स्किप / अगला",
    checking: "जाँच हो रही…",
    filters: "फ़िल्टर",
    matchFilters: "मैच फ़िल्टर",
    gender: "लिंग",
    genderAny: "कोई भी",
    genderMale: "पुरुष",
    genderFemale: "महिला",
    minimumRating: "न्यूनतम रेटिंग",
    ratingAny: "कोई भी रेटिंग",
    rating3: "3★ +",
    rating4: "4★ +",
    rating4_5: "4.5★ +",
    reset: "रीसेट",
    done: "हो गया",
    myBalance: "मेरा बैलेंस",
    needCoins: "इस कॉल को शुरू करने के लिए आपको कम से कम {count} कॉइन चाहिए।",
    statusInsufficientCoins: "रैंडम कॉल शुरू करने के लिए पर्याप्त कॉइन नहीं हैं।",
    statusNotEnoughCoinsTitle: "कॉइन कम हैं",
    statusRateLimited: "थोड़ा रुकिए, फिर कोशिश करें…",
    statusDailyLimit: "आज की रैंडम मैच सीमा पूरी हो गई।",
    statusDeclineCooldown: "बहुत बार अस्वीकार किया — कुछ देर रुकें।",
    statusNoMatchFilters: "इन फ़िल्टर से कोई होस्ट नहीं मिला — फ़िल्टर ढीले करें।",
    statusSearching: "ऑनलाइन लिसनर्स में खोज रहे हैं…",
    statusNoneOnline: "अभी कोई लिसनर ऑनलाइन नहीं है — फिर भी खोज रहे हैं…",
    statusGiveUp: "अभी कोई होस्ट नहीं मिला। थोड़ी देर बाद पुनः प्रयास करें।",
    statusNetworkError: "नेटवर्क त्रुटि, फिर से कोशिश हो रही…",
    statusServerUnreachable: "सर्वर तक नहीं पहुँच सके। कृपया फिर से प्रयास करें।",
    retryIn: "{time} में फिर से प्रयास करें",
    dailyLimitReset: "कल रीसेट होगा",
    hostBusy: "होस्ट अभी व्यस्त हो गया — दूसरा मैच खोज रहे हैं।",
    hostOffline: "होस्ट ऑफ़लाइन हो गया — दूसरा मैच खोज रहे हैं।",
    hostUnavailable: "होस्ट उपलब्ध नहीं — दूसरा मैच खोज रहे हैं।",
    failedLoadHosts: "उपलब्ध होस्ट लोड नहीं हो सके।",
  },

  hosts: {
    host: "होस्ट",
    listener: "श्रोता",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    busy: "व्यस्त",
    rating: "रेटिंग",
    reviews: "समीक्षाएं",
    review: "समीक्षा",
    coinsPerMinute: "कॉइन/मिनट",
    totalMinutes: "कुल मिनट",
    specialties: "विशेषताएं",
    languages: "भाषाएं",
    about: "के बारे में",
    callNow: "अभी कॉल करें",
    audioCall: "ऑडियो कॉल",
    videoCall: "वीडियो कॉल",
    sendMessage: "संदेश भेजें",
    talkNow: "अभी बात करें",
    noHostsFound: "कोई होस्ट नहीं मिला",
    adjustFilters: "अपने फ़िल्टर समायोजित करें",
    topRated: "शीर्ष रेटेड",
    viewProfile: "प्रोफ़ाइल देखें",
    startCall: "कॉल शुरू करें",
  },

  calls: {
    incoming: "आने वाली कॉल",
    outgoing: "कनेक्ट हो रहा है...",
    ongoing: "कॉल पर",
    ended: "कॉल समाप्त",
    audio: "ऑडियो कॉल",
    video: "वीडियो कॉल",
    accept: "स्वीकार करें",
    decline: "अस्वीकार करें",
    endCall: "कॉल समाप्त करें",
    mute: "म्यूट",
    unmute: "अनम्यूट",
    speaker: "स्पीकर",
    flipCamera: "कैमरा बदलें",
    callDuration: "कॉल अवधि",
    callWith: "के साथ कॉल",
    rateCall: "इस कॉल को रेट करें",
    callHistory: "कॉल इतिहास",
    noCallHistory: "अभी तक कोई कॉल इतिहास नहीं",
    callCost: "कॉल लागत",
    perMinute: "प्रति मिनट",
    lowBalance: "कम कॉइन बैलेंस",
    lowBalanceMsg: "आपके कॉइन कम हैं। जारी रखने के लिए रीचार्ज करें।",
    callEnded: "कॉल समाप्त",
    callEndedMsg: "आपकी कॉल समाप्त हो गई है",
    missed: "मिस्ड",
    answered: "उत्तर दिया",
    rejected: "अस्वीकृत",
    callingHistory: "कॉलिंग इतिहास",
    audioShort: "ऑडियो",
    videoShort: "वीडियो",
    incomingVideo: "इनकमिंग वीडियो कॉल",
    incomingAudio: "इनकमिंग ऑडियो कॉल",
    unknown: "अज्ञात",
    voxlinkHost: "VoxLink होस्ट",
    voxlinkUser: "VoxLink उपयोगकर्ता",
    voiceCall: "वॉइस कॉल",
    callDeclined: "कॉल अस्वीकृत",
    noAnswer: "कोई उत्तर नहीं",
    ringing: "रिंग हो रही है",
    connecting: "कनेक्ट हो रहा है",
    coinsPerMin: "कॉइन / मिनट",
    oneMinMinimum: "न्यूनतम 1 मिनट",
    callAutoEnded: "कॉल स्वतः समाप्त",
    autoDisconnected: "आपके कॉइन समाप्त हो गए — कॉल स्वतः कट गई",
    connectionLost: "कॉल कट गई — कनेक्शन टूट गया। कृपया अपना नेटवर्क जांचें।",
    with: "के साथ",
    minBilling: "न्यूनतम 1 मिनट की बिलिंग लागू",
    duration: "अवधि",
    coinsSpent: "खर्च किए कॉइन",
    rateName: "{name} को रेट करें",
    feedbackHelps: "आपकी प्रतिक्रिया होस्ट को बेहतर बनने में मदद करती है",
    ratingPoor: "खराब",
    ratingFair: "ठीक-ठाक",
    ratingGood: "अच्छा",
    ratingGreat: "बहुत अच्छा",
    ratingExcellent: "उत्कृष्ट!",
    submitRating: "रेटिंग सबमिट करें",
    thankYou: "धन्यवाद! 🙏",
    ratingSubmitted: "आपकी रेटिंग सबमिट हो गई",
    rechargeCoins: "कॉइन रीचार्ज करें",
    backHome: "होम पर वापस जाएं",
    rateFailed: "रेटिंग सबमिट करने में विफल, कृपया पुनः प्रयास करें।",
    errorTitle: "त्रुटि",
    completed: "पूर्ण",
    cancelled: "रद्द",
    noCallHistoryFound: "कोई कॉल इतिहास नहीं मिला",
    failedLoadHistory: "कॉल इतिहास लोड करने में विफल।",
    micAccessNeeded: "माइक्रोफ़ोन एक्सेस आवश्यक — ठीक करने के लिए टैप करें",
    coinsRunningLow: "कॉइन कम हो रहे हैं",
    secondsRemaining: "{count}s शेष",
    minLeft: "{count} मिनट शेष",
    ringingDots: "रिंग हो रही है...",
    connectingDots: "कनेक्ट हो रहा है...",
    connected: "कनेक्टेड",
    networkDrop: "नेटवर्क टूट गया — पुनः कनेक्ट हो रहा है...",
    connectionFailed: "कनेक्शन विफल — पुनः प्रयास हो रहा है...",
    callEndedShort: "कॉल समाप्त",
    mutedHint: "🔇 म्यूट",
    speakerOn: "स्पीकर चालू",
    runningOutCoins: "कॉइन खत्म हो रहे हैं!",
    autoDisconnectIn: "कॉल {time} में स्वतः कट जाएगी",
    second: "सेकंड",
    seconds: "सेकंड",
    fewSeconds: "कुछ सेकंड",
    rechargeNow: "अभी रीचार्ज करें",
    continueCall: "कॉल जारी रखें",
    cameraOff: "कैमरा बंद",
    cameraUnavailable: "कैमरा अनुपलब्ध",
    startingCamera: "कैमरा शुरू हो रहा है…",
    noPermission: "अनुमति नहीं",
    cameraOffShort: "कैमरा बंद",
    you: "आप",
    mutedLabel: "म्यूट",
    noMic: "माइक नहीं",
    lowCoins: "कॉइन कम",
    secondsLeft: "{count}s शेष",
    connectionIssue: "कनेक्शन समस्या",
    live: "लाइव",
    waitingResponse: "प्रतिक्रिया की प्रतीक्षा...",
    camera: "कैमरा",
    camOff: "कैमरा बंद",
    end: "समाप्त",
    flip: "फ्लिप",
    earpiece: "इयरपीस",
  },

  chat: {
    messages: "संदेश",
    newMessage: "नया संदेश",
    typeMessage: "संदेश लिखें...",
    send: "भेजें",
    noMessages: "अभी तक कोई संदेश नहीं",
    startConversation: "बातचीत शुरू करें",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    typing: "लिख रहा है...",
    delivered: "डिलीवर",
    read: "पढ़ा",
    deleteChat: "चैट हटाएं",
    deleteChatConfirm: "क्या आप इस बातचीत को हटाना चाहते हैं?",
    chats: "चैट",
    searchConversations: "बातचीत खोजें...",
    noConversationsFound: "कोई बातचीत नहीं मिली",
    noConversationsYet: "अभी कोई बातचीत नहीं",
    tryDifferentName: "कोई और नाम आज़माएं",
    startChattingAfterCall: "किसी होस्ट के साथ कॉल के बाद चैट शुरू करें",
  },

  wallet: {
    wallet: "वॉलेट",
    coinBalance: "कॉइन बैलेंस",
    coins: "कॉइन",
    coin: "कॉइन",
    buyCoins: "कॉइन खरीदें",
    coinHistory: "कॉइन इतिहास",
    transactions: "लेन-देन",
    noTransactions: "अभी तक कोई लेन-देन नहीं",
    purchased: "खरीदा",
    spent: "खर्च किया",
    bonus: "बोनस",
    refunded: "वापस किया",
    withdrawal: "निकासी",
    totalSpent: "कुल खर्च",
    totalPurchased: "कुल खरीद",
    popular: "सबसे लोकप्रिय",
    bestValue: "सर्वोत्तम मूल्य",
    bonus_label: "बोनस",
    recharge: "रीचार्ज",
    choosePackage: "पैकेज चुनें",
    instantDelivery: "तत्काल डिलीवरी",
    securePayment: "सुरक्षित भुगतान",
    guaranteed: "संतुष्टि की गारंटी",
  },

  profile: {
    profile: "प्रोफ़ाइल",
    editProfile: "प्रोफ़ाइल संपादित करें",
    myProfile: "मेरी प्रोफ़ाइल",
    name: "नाम",
    email: "ईमेल",
    phone: "फ़ोन",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    country: "देश",
    bio: "बायो",
    language: "भाषा",
    settings: "सेटिंग्स",
    helpCenter: "सहायता और FAQ",
    privacy: "गोपनीयता नीति",
    about: "VoxLink के बारे में",
    shareApp: "VoxLink शेयर करें",
    rateApp: "ऐप को रेट करें",
    logout: "लॉग आउट",
    deleteAccount: "खाता हटाएं",
    callHistory: "कॉल इतिहास",
    joinedOn: "शामिल हुए",
    totalCalls: "कुल कॉल",
    hoursSpent: "बिताए घंटे",
  },

  settings: {
    settings: "सेटिंग्स",
    notifications: "सूचनाएं",
    callNotifications: "कॉल सूचनाएं",
    messageNotifications: "संदेश सूचनाएं",
    promoNotifications: "प्रचार सूचनाएं",
    language: "भाषा",
    theme: "थीम",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    systemDefault: "सिस्टम डिफ़ॉल्ट",
    privacy: "गोपनीयता",
    security: "सुरक्षा",
    changePassword: "पासवर्ड बदलें",
    twoFactor: "दो-कारक प्रमाणीकरण",
    account: "खाता",
    support: "सहायता",
  },

  payment: {
    checkout: "चेकआउट",
    selectPackage: "पैकेज चुनें",
    paymentMethod: "भुगतान विधि",
    creditCard: "क्रेडिट / डेबिट कार्ड",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "भुगतान प्रक्रिया में...",
    paymentSuccess: "भुगतान सफल!",
    paymentFailed: "भुगतान विफल",
    orderSummary: "ऑर्डर सारांश",
    total: "कुल",
    coins: "कॉइन",
    bonusCoins: "बोनस कॉइन",
    tryAgain: "फिर कोशिश करें",
    secureNote: "सभी भुगतान सुरक्षित और एन्क्रिप्टेड हैं",
  },

  host: {
    dashboard: "डैशबोर्ड",
    totalEarnings: "कुल कमाई",
    thisWeek: "इस सप्ताह",
    thisMonth: "इस महीने",
    totalCalls: "कुल कॉल",
    avgRating: "औसत रेटिंग",
    onlineStatus: "ऑनलाइन स्थिति",
    goOnline: "ऑनलाइन जाएं",
    goOffline: "ऑफलाइन जाएं",
    setBusy: "व्यस्त सेट करें",
    earnings: "कमाई",
    withdraw: "निकालें",
    withdrawal: "निकासी",
    minimumWithdraw: "न्यूनतम 100 कॉइन",
    enterAmount: "राशि दर्ज करें",
    withdrawMethod: "निकासी विधि",
    bankTransfer: "बैंक ट्रांसफर",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "खाता विवरण",
    withdrawSuccess: "निकासी अनुरोध सबमिट किया गया",
    withdrawPending: "आपका अनुरोध संसाधित किया जा रहा है",
    hostSettings: "होस्ट सेटिंग्स",
    availability: "उपलब्धता",
    payoutSettings: "पेआउट सेटिंग्स",
    becomeHost: "होस्ट बनें",
    apply: "अभी आवेदन करें",
    applicationSent: "आवेदन भेजा गया!",
    applicationDesc: "हम आपके आवेदन की समीक्षा करेंगे और 2-3 कार्य दिवसों के भीतर वापस आएंगे।",
  },

  errors: {
    network: "नेटवर्क त्रुटि। कृपया अपना कनेक्शन जांचें।",
    server: "सर्वर त्रुटि। कृपया बाद में पुनः प्रयास करें।",
    unauthorized: "सत्र समाप्त। कृपया फिर से लॉग इन करें।",
    notFound: "अनुरोधित संसाधन नहीं मिला।",
    insufficientCoins: "अपर्याप्त कॉइन। कृपया रीचार्ज करें।",
    callFailed: "कॉल कनेक्ट नहीं हो सका। कृपया पुनः प्रयास करें।",
    permissionDenied: "अनुमति अस्वीकृत।",
    generic: "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
  },

  tabs: {
    home: "होम",
    listener: "लिसनर",
    random: "रैंडम",
    chat: "चैट",
    calling: "कॉलिंग",
  },

  listener: {
    allListeners: "सभी लिसनर",
    language: "भाषा",
    talkAbout: "किस बारे में बात करें",
    selectLanguage: "भाषा चुनें",
    noListenersFound: "कोई लिसनर नहीं मिला",
    failedLoad: "लिसनर लोड करने में विफल।",
    available: "उपलब्ध",
    offline: "ऑफ़लाइन",
    audio: "ऑडियो",
    video: "वीडियो",
    perMin: "/मिनट",
    hrs: "घंटे",
  },

  onboarding: {
    find: "खोजें",
    findDesc: "आप दुनिया भर के लोगों से जुड़ सकते हैं\nचैट और संदेश के लिए और\nउनके साथ संबंध बना सकते हैं।",
    chat: "चैट",
    chatDesc: "एक-दूसरे को बेहतर जानने के लिए\nअजनबियों से चैट करें और\nअच्छी अनुकूलता पाएं।",
    videoCall: "वीडियो कॉल",
    videoCallDesc: "आप अपने दोस्तों और कनेक्शनों के साथ\nअपने वीडियो और फ़ोटो साझा कर सकते हैं।",
  },

  hostsScreen: {
    allHosts: "सभी होस्ट",
    failedLoad: "होस्ट लोड नहीं हो सके। रिफ्रेश करने के लिए खींचें।",
  },

  reviews: {
    failedLoad: "समीक्षाएं लोड नहीं हो सकीं।",
    reviewsCount: "{count} समीक्षाएं",
    noReviews: "अभी तक कोई समीक्षा नहीं",
    beFirst: "समीक्षा छोड़ने वाले पहले व्यक्ति बनें",
    user: "उपयोगकर्ता",
    today: "आज",
    yesterday: "कल",
    daysAgo: "{count} दिन पहले",
    weekAgo: "{count} सप्ताह पहले",
    weeksAgo: "{count} सप्ताह पहले",
    monthAgo: "{count} माह पहले",
    monthsAgo: "{count} माह पहले",
  },

  notFound: {
    title: "अरे!",
    message: "यह स्क्रीन मौजूद नहीं है।",
    goHome: "होम स्क्रीन पर जाएं!",
  },

  aboutScreen: {
    title: "VoxLink के बारे में",
    appTagline: "वॉइस और वीडियो कनेक्शन",
    version: "संस्करण {version}",
    statActiveUsers: "सक्रिय उपयोगकर्ता",
    statHosts: "होस्ट",
    statCallsMade: "की गई कॉल",
    statAppRating: "ऐप रेटिंग",
    whatIsTitle: "VoxLink क्या है?",
    whatIsBody1: "VoxLink एक सोशल ऑडियो और वीडियो कॉलिंग प्लेटफ़ॉर्म है जो लोगों को सार्थक बातचीत के लिए सत्यापित होस्ट से जोड़ता है। चाहे आपको जीवन सलाह, भाषा अभ्यास, भावनात्मक समर्थन या केवल बात करने के लिए किसी की ज़रूरत हो — हमारे होस्ट आपके लिए यहाँ हैं।",
    whatIsBody2: "होस्ट असली, प्रशिक्षित व्यक्ति हैं जिन्हें हमारी टीम द्वारा जांचा जाता है। हर कॉल सुरक्षित, निजी और हमारी कॉइन-आधारित भुगतान प्रणाली द्वारा समर्थित है — इसलिए आप केवल उपयोग किए गए समय का भुगतान करते हैं।",
    keyFeatures: "मुख्य विशेषताएं",
    feature1: "HD ऑडियो और वीडियो कॉल",
    feature2: "एंड-टू-एंड एन्क्रिप्टेड",
    feature3: "1,200+ सत्यापित होस्ट",
    feature4: "कॉइन-आधारित उचित मूल्य",
    feature5: "इन-ऐप चैट",
    feature6: "रेटेड समीक्षा प्रणाली",
    connectWithUs: "हमसे जुड़ें",
    linkWebsite: "वेबसाइट",
    linkTwitter: "Twitter / X",
    linkInstagram: "Instagram",
    linkContact: "संपर्क करें",
    helpCenter: "सहायता केंद्र",
    copyright: "© 2026 VoxLink Inc. सर्वाधिकार सुरक्षित।",
  },

  privacyScreen: {
    bannerTitle: "आपकी गोपनीयता मायने रखती है",
    bannerSub: "यह नीति बताती है कि VoxLink आपके डेटा को कैसे एकत्र, उपयोग और सुरक्षित करता है।",
    lastUpdated: "अंतिम अपडेट: 1 मार्च 2026",
    contactTitle: "गोपनीयता के बारे में प्रश्न?",
    s1Title: "1. हम कौन सी जानकारी एकत्र करते हैं",
    s1Body: "हम वह जानकारी एकत्र करते हैं जो आप सीधे हमें प्रदान करते हैं, जैसे कि जब आप खाता बनाते हैं, अपनी प्रोफ़ाइल अपडेट करते हैं, खरीदारी करते हैं या समर्थन के लिए हमसे संपर्क करते हैं। इसमें आपका नाम, ईमेल पता, उपयोगकर्ता नाम, प्रोफ़ाइल चित्र और भुगतान जानकारी शामिल है।\n\nजब आप VoxLink का उपयोग करते हैं तो हम स्वचालित रूप से भी जानकारी एकत्र करते हैं, जिसमें लॉग डेटा, डिवाइस जानकारी, स्थान जानकारी (यदि अनुमति दी गई हो) और उपयोग डेटा जैसे आपके द्वारा उपयोग की जाने वाली सुविधाएं और कॉल पर बिताया गया समय शामिल है।",
    s2Title: "2. हम आपकी जानकारी का उपयोग कैसे करते हैं",
    s2Body: "हम एकत्र की गई जानकारी का उपयोग अपनी सेवाओं को प्रदान करने, बनाए रखने और बेहतर बनाने, लेन-देन संसाधित करने और संबंधित जानकारी भेजने, सूचनाएं, तकनीकी नोटिस, अपडेट और समर्थन संदेश भेजने के लिए करते हैं।\n\nहम आपके डेटा का उपयोग आपकी टिप्पणियों, प्रश्नों और अनुरोधों का जवाब देने, रुझानों और उपयोग की निगरानी और विश्लेषण करने, धोखाधड़ी वाले लेन-देन और अन्य अवैध गतिविधियों का पता लगाने, जांच करने और रोकने के लिए भी करते हैं।",
    s3Title: "3. जानकारी साझा करना",
    s3Body: "हम इस नीति में वर्णित के अलावा आपकी व्यक्तिगत जानकारी तीसरे पक्षों के साथ साझा नहीं करते हैं। हम विक्रेताओं, सलाहकारों और अन्य सेवा प्रदाताओं के साथ जानकारी साझा कर सकते हैं जिन्हें हमारी ओर से कार्य करने के लिए ऐसी जानकारी तक पहुँच की आवश्यकता होती है।\n\nयदि हमें लगता है कि प्रकटीकरण किसी लागू कानून या कानूनी प्रक्रिया के अनुसार है या आवश्यक है, तो हम आपकी जानकारी का खुलासा कर सकते हैं, जिसमें राष्ट्रीय सुरक्षा या कानून प्रवर्तन आवश्यकताओं को पूरा करने के लिए सार्वजनिक अधिकारियों के वैध अनुरोध शामिल हैं।",
    s4Title: "4. कॉल डेटा और ऑडियो",
    s4Body: "ऑडियो और वीडियो कॉल सामग्री एन्क्रिप्टेड चैनलों के माध्यम से प्रसारित की जाती है। हम आपकी कॉल की सामग्री को रिकॉर्ड या संग्रहीत नहीं करते जब तक कि आप स्पष्ट रूप से रिकॉर्डिंग सुविधा (यदि उपलब्ध हो) सक्षम न करें। बिलिंग और इतिहास सुविधाएं प्रदान करने के लिए कॉल मेटाडेटा (अवधि, प्रतिभागी, टाइमस्टैम्प) संग्रहीत किया जाता है।",
    s5Title: "5. कॉइन और भुगतान",
    s5Body: "भुगतान जानकारी सुरक्षित तृतीय-पक्ष भुगतान प्रोसेसर के माध्यम से संसाधित की जाती है। हम अपने सर्वर पर पूर्ण भुगतान कार्ड विवरण संग्रहीत नहीं करते। लेखांकन और विवाद समाधान उद्देश्यों के लिए कॉइन लेन-देन लॉग किए जाते हैं।",
    s6Title: "6. डेटा सुरक्षा",
    s6Body: "हम आपके बारे में जानकारी को हानि, चोरी, दुरुपयोग और अनधिकृत पहुँच, प्रकटीकरण, परिवर्तन और विनाश से बचाने के लिए उचित उपाय करते हैं। सभी डेटा TLS का उपयोग करके पारगमन में और AES-256 एन्क्रिप्शन का उपयोग करके आराम में एन्क्रिप्ट किया जाता है।",
    s7Title: "7. डेटा प्रतिधारण",
    s7Body: "हम व्यक्तिगत जानकारी को तब तक बनाए रखते हैं जब तक हमारी सेवाएं प्रदान करने और इस गोपनीयता नीति में उल्लिखित उद्देश्यों को पूरा करने के लिए आवश्यक हो, जब तक कि कानून द्वारा लंबी प्रतिधारण अवधि की आवश्यकता या अनुमति न हो। आप किसी भी समय सेटिंग्स स्क्रीन के माध्यम से अपने खाते और संबंधित डेटा को हटाने का अनुरोध कर सकते हैं।",
    s8Title: "8. बच्चों की गोपनीयता",
    s8Body: "VoxLink 18 वर्ष से कम उम्र के बच्चों के लिए नहीं है। हम जानबूझकर 18 वर्ष से कम उम्र के बच्चों से व्यक्तिगत जानकारी एकत्र नहीं करते। यदि हमें पता चलता है कि हमने 18 वर्ष से कम उम्र के बच्चे से व्यक्तिगत जानकारी एकत्र की है, तो हम उस जानकारी को हटा देंगे।",
    s9Title: "9. आपके अधिकार",
    s9Body: "आपको किसी भी समय अपनी व्यक्तिगत जानकारी तक पहुँचने, अपडेट करने या हटाने का अधिकार है। आप प्रसंस्करण पर आपत्ति कर सकते हैं, डेटा पोर्टेबिलिटी का अनुरोध कर सकते हैं या जहां प्रसंस्करण सहमति पर आधारित है वहां सहमति वापस ले सकते हैं। इन अधिकारों का प्रयोग करने के लिए, सहायता केंद्र के माध्यम से हमसे संपर्क करें।",
    s10Title: "10. इस नीति में परिवर्तन",
    s10Body: "हम समय-समय पर इस गोपनीयता नीति को अपडेट कर सकते हैं। हम इस पृष्ठ पर नई नीति पोस्ट करके और 'अंतिम अपडेट' तिथि अपडेट करके आपको किसी भी परिवर्तन की सूचना देंगे। किसी भी परिवर्तन के बाद VoxLink का आपका निरंतर उपयोग नई गोपनीयता नीति की आपकी स्वीकृति का गठन करता है।",
  },

  helpScreen: {
    title: "सहायता केंद्र",
    bannerTitle: "मदद या FAQ चाहिए?",
    bannerSub: "सामान्य प्रश्नों के उत्तर खोजें",
    contactTitle: "कोई समस्या है?",
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    q1: "VoxLink क्या है?",
    a1: "VoxLink एक सोशल प्लेटफ़ॉर्म है जहां आप ऑडियो या वीडियो कॉल के माध्यम से पेशेवर श्रोताओं और होस्ट से जुड़ सकते हैं। रिश्तों, करियर, जीवन कोचिंग और अधिक जैसे विषयों पर व्यक्तिगत समर्थन प्राप्त करें।",
    q2: "होस्ट/श्रोता कौन हैं?",
    a2: "होस्ट सत्यापित पेशेवर या अनुभवी व्यक्ति हैं जो समर्थन और बातचीत प्रदान करते हैं। वे विभिन्न विषयों में विशेषज्ञ होते हैं और ऑडियो तथा वीडियो कॉल के लिए उपलब्ध रहते हैं।",
    q3: "मैं कॉल कैसे करूं?",
    a3: "होम स्क्रीन पर उपलब्ध होस्ट ब्राउज़ करें, प्रोफ़ाइल देखने के लिए किसी होस्ट कार्ड पर टैप करें, फिर ऑडियो या वीडियो कॉल शुरू करने के लिए 'अभी बात करें' पर टैप करें। कॉल प्रति मिनट कॉइन में शुल्क लिए जाते हैं।",
    q4: "कॉइन क्या हैं?",
    a4: "कॉइन VoxLink की इन-ऐप मुद्रा है। आप वॉलेट अनुभाग से कॉइन पैकेज खरीदते हैं और होस्ट के साथ कॉल के दौरान उनकी सूचीबद्ध प्रति मिनट दर पर खर्च करते हैं।",
    q5: "क्या मेरी बातचीत निजी है?",
    a5: "हाँ, सभी बातचीत निजी और गोपनीय हैं। हम सख्त डेटा सुरक्षा नीतियों का पालन करते हैं और व्यक्तिगत बातचीत के विवरण तीसरे पक्ष के साथ साझा नहीं करते।",
    q6: "मैं होस्ट कैसे बनूं?",
    a6: "होस्टिंग हमारे अलग VoxLink Host ऐप के माध्यम से की जाती है। आवेदन करने, अपनी पहचान सत्यापित करने और कॉल लेना तथा कमाई शुरू करने के लिए Host ऐप डाउनलोड करें।",
    q7: "अगर मेरे कॉइन खत्म हो जाएं तो क्या होगा?",
    a7: "यदि कॉल के दौरान आपके कॉइन खत्म हो जाते हैं, तो कॉल स्वतः समाप्त हो जाएगी। आप वॉलेट अनुभाग से कभी भी अधिक कॉइन खरीद सकते हैं।",
  },

  coinHistory: {
    title: "कॉइन इतिहास",
    currentBalance: "वर्तमान बैलेंस",
    earned: "अर्जित",
    spent: "खर्च किया",
    tabAll: "सभी",
    tabPurchase: "खरीद",
    tabSpent: "खर्च",
    tabBonus: "बोनस",
    today: "आज",
    yesterday: "कल",
    ref: "संदर्भ:",
    noTransactions: "कोई लेन-देन नहीं मिला",
    failedLoad: "कॉइन इतिहास लोड करने में विफल।",
  },

  notificationsScreen: {
    markAllRead: "सभी पढ़ा हुआ चिह्नित करें",
    empty: "अभी कोई सूचना नहीं",
    goBack: "वापस जाएं",
    markAllReadLabel: "सभी सूचनाओं को पढ़ा हुआ चिह्नित करें",
    failedLoad: "सूचनाएं लोड करने में विफल।",
    failedMarkAll: "सूचनाओं को पढ़ा हुआ चिह्नित करने में विफल।",
    failedUpdate: "सूचना अपडेट करने में विफल।",
  },

  searchHosts: {
    searchPlaceholder: "नाम से होस्ट खोजें...",
    topic: "विषय",
    status: "स्थिति",
    language: "भाषा",
    hostsFound: "{count} होस्ट मिले",
    noResults: "आपकी खोज से मेल खाने वाला कोई होस्ट नहीं मिला",
    talk: "बात करें",
    failedLoad: "होस्ट लोड करने में विफल।",
  },

  chatScreen: {
    defaultName: "चैट",
    emptyHint: "बातचीत शुरू करने के लिए एक संदेश भेजें",
    sending: "भेजा जा रहा है…",
    tapToRetry: "पुनः प्रयास के लिए टैप करें",
    a11yBack: "वापस जाएं",
    a11yPhotoMessage: "फ़ोटो संदेश",
    a11yRetry: "संदेश पुनः भेजें",
    a11yAttach: "फ़ोटो संलग्न करें",
    a11ySend: "संदेश भेजें",
    permissionTitle: "अनुमति आवश्यक",
    permissionPhoto: "फ़ोटो भेजने के लिए कृपया फ़ोटो लाइब्रेरी एक्सेस की अनुमति दें।",
    failedLoadMessages: "संदेश लोड करने में विफल।",
    uploadFailed: "अपलोड विफल। कृपया पुनः प्रयास करें।",
    photoSendFailed: "फ़ोटो नहीं भेज सके। कृपया पुनः प्रयास करें।",
  },

  hostDetail: {
    notFound: "होस्ट नहीं मिला",
    selectCallType: "कॉल प्रकार चुनें",
    highlights: "झलकियाँ",
    introVideo: "परिचय वीडियो",
    coinPerMin: "{count} कॉइन/मिनट",
    coin: "{count} कॉइन",
    levelShort: "लेव.",
    languageColon: "भाषा : ",
    idLabel: "आईडी:",
    totalCall: "कुल कॉल",
    experience: "अनुभव",
    recent: "हाल ही में",
    chatNow: "अभी चैट करें",
    chatLocked: "🔒 चैट",
    chatLockedTitle: "🔒 चैट लॉक है",
    chatLockedMsg: "{name} के साथ चैट करने के लिए, आपको पहले उन्हें कॉल करना होगा। कॉल के बाद चैट स्वतः अनलॉक हो जाती है!",
    chatLockedMsg2: "पहले कॉल करें, फिर चैट स्वतः अनलॉक हो जाएगी!",
    offlineMsg: "{name} इस समय ऑफ़लाइन हैं।",
    idCopied: "होस्ट आईडी क्लिपबोर्ड पर कॉपी हो गई।",
    reportThanks: "आपकी रिपोर्ट के लिए धन्यवाद। हमारी टीम जल्द ही इसकी समीक्षा करेगी।",
    reportSubmitted: "रिपोर्ट सबमिट हुई",
    reportFailMsg: "रिपोर्ट सबमिट नहीं हो सकी। कृपया पुनः प्रयास करें।",
    reportFailed: "रिपोर्ट विफल",
    failedLoad: "होस्ट विवरण लोड करने में विफल।",
    reportTitle: "{name} की रिपोर्ट करें",
    reportSubtitle: "आप इस होस्ट की रिपोर्ट क्यों कर रहे हैं?",
    reportInappropriate: "अनुचित सामग्री",
    reportHarassment: "उत्पीड़न",
    reportFakeProfile: "नकली प्रोफ़ाइल",
    reportScam: "घोटाला / धोखाधड़ी",
    reportSpam: "स्पैम",
  },

  checkout: {
    currentBalance: "वर्तमान बैलेंस",
    popular: "लोकप्रिय",
    online: "ऑनलाइन",
    autoGateway: "ऑटो गेटवे",
    manualUpi: "मैनुअल UPI",
    qrUpiId: "QR / UPI आईडी",
    manualApprovalNote: "⏱ मैनुअल भुगतान के लिए एडमिन अनुमोदन (कुछ घंटे) आवश्यक है। सत्यापन के बाद कॉइन जोड़े जाएंगे।",
    promoCode: "प्रोमो कोड",
    promoPlaceholder: "प्रोमो कोड दर्ज करें",
    remove: "हटाएं",
    invalidPromo: "अमान्य प्रोमो कोड",
    percentOff: "🎉 {pct}% छूट — {amount} बचाएं",
    bonusCoinsAdded: "🎁 +{count} बोनस कॉइन जोड़े गए!",
    promoBonus: "प्रोमो बोनस",
    youGet: "आपको मिलेंगे",
    promoDiscount: "प्रोमो छूट",
    securePayments: "भुगतान 100% सुरक्षित और एन्क्रिप्टेड हैं",
    selectPackageBtn: "एक पैकेज चुनें",
    payViaUpi: "UPI से भुगतान करें — {coins} कॉइन के लिए {price}",
    continuePay: "जारी रखें — {coins} कॉइन के लिए {price}",
    redirecting: "भुगतान पर रीडायरेक्ट हो रहा है...",
    submittedForReview: "भुगतान समीक्षा के लिए सबमिट किया गया!",
    submitted: "सबमिट हुआ",
    coinsAddedToast: "{count} कॉइन जोड़े गए!",
    purchaseSuccessful: "खरीद सफल",
    paymentFailed: "भुगतान विफल। कृपया पुनः प्रयास करें।",
    paymentFailedTitle: "भुगतान विफल",
    manualUpiTitle: "मैनुअल UPI भुगतान",
    autoApproved: "⚡ ऑटो-स्वीकृत!",
    coinsAdded: "कॉइन जोड़े गए!",
    paymentSubmitted: "भुगतान सबमिट हुआ!",
    autoApprovedSub: "{count} कॉइन तुरंत आपके खाते में जोड़ दिए गए हैं!",
    underReviewSub: "आपका भुगतान समीक्षाधीन है। एडमिन के अनुमोदन के बाद कॉइन जोड़े जाएंगे (आमतौर पर कुछ घंटों में)।",
    package: "पैकेज",
    utrRef: "UTR / संदर्भ",
    loadingPayment: "भुगतान विवरण लोड हो रहा है...",
    unavailable: "अनुपलब्ध",
    unavailableSub: "मैनुअल भुगतान इस समय उपलब्ध नहीं है। कृपया कोई अन्य भुगतान विधि आज़माएं।",
    scanQrStep: "QR स्कैन करें या UPI आईडी पर भुगतान करें",
    payToUpi: "UPI आईडी पर भुगतान करें",
    account: "खाता:",
    autoRotating: "🔄 स्वतः-घूर्णन",
    enterUtrStep: "UTR / लेन-देन आईडी दर्ज करें",
    utrHint: "भुगतान के बाद, अपने UPI ऐप में 12-अंकीय UTR या लेन-देन संदर्भ खोजें।",
    utrPlaceholder: "UTR / संदर्भ संख्या दर्ज करें",
    adminApprovalTitle: "⏱ एडमिन अनुमोदन आवश्यक",
    adminApprovalNote: "मैनुअल भुगतान हमारी टीम द्वारा सत्यापित किए जाते हैं। अनुमोदन के कुछ घंटों के भीतर कॉइन जमा कर दिए जाएंगे। सुनिश्चित करें कि सटीक राशि का भुगतान किया गया है।",
    submitProof: "भुगतान प्रमाण सबमिट करें",
    utrRequiredMsg: "कृपया UTR / लेन-देन संदर्भ संख्या दर्ज करें।",
    submissionFailed: "सबमिशन विफल",
    submissionFailedMsg: "भुगतान सबमिट नहीं हो सका। कृपया पुनः प्रयास करें।",
    coinPack: "कॉइन पैक",
    upiQrPayment: "UPI / QR भुगतान",
    notAvailable: "उपलब्ध नहीं",
    manualUnavailable: "मैनुअल UPI भुगतान इस समय उपलब्ध नहीं है। कृपया कोई अन्य भुगतान विधि आज़माएं।",
    retry: "पुनः प्रयास करें",
    instantApproval: "तत्काल अनुमोदन",
    coinsAddedWallet: "{count} कॉइन आपके वॉलेट में जोड़ दिए गए हैं!",
    beingReviewed: "आपके भुगतान की समीक्षा की जा रही है। कुछ घंटों के भीतर कॉइन जमा कर दिए जाएंगे।",
    amount: "राशि",
    status: "स्थिति",
    approved: "स्वीकृत",
    pendingReview: "समीक्षा लंबित",
    scanQrPay: "QR कोड स्कैन करें और भुगतान करें",
    qrNotAvailable: "QR उपलब्ध नहीं",
    upiId: "UPI आईडी",
    copy: "कॉपी",
    payExactly: "इस UPI आईडी पर ठीक {amount} का भुगतान करें",
    utrHintHistory: "भुगतान के बाद, अपने UPI ऐप के भुगतान इतिहास में 12-अंकीय UTR या लेन-देन संदर्भ खोजें।",
    utrExample: "उदा. 412345678901",
    whereUtr: "UTR कहां मिलेगा?",
    whereUtrText: "अपना UPI ऐप खोलें (PhonePe / GPay / Paytm) → लेन-देन इतिहास → भुगतान पर टैप करें → \"UTR\" या \"संदर्भ आईडी\" कॉपी करें",
    verifyNote: "एडमिन सत्यापन के बाद कॉइन जोड़े जाएंगे (आमतौर पर कुछ घंटों में)। सुनिश्चित करें कि सटीक राशि का भुगतान करें।",
    submitPayment: "भुगतान सबमिट करें",
    enterUtrContinue: "जारी रखने के लिए UTR दर्ज करें",
    utrRequiredMsg2: "कृपया UTR / लेन-देन संदर्भ संख्या दर्ज करें",
    utrTooShort: "UTR कम से कम 6 अक्षरों का होना चाहिए",
    invalidUtr: "अमान्य UTR",
    planMissing: "प्लान जानकारी अनुपलब्ध। कृपया वापस जाकर पुनः प्रयास करें।",
    submissionFailedShort: "सबमिशन विफल। कृपया पुनः प्रयास करें।",
  },

  successScreen: {
    title: "भुगतान सफल!",
    subtitle: "कॉइन आपके वॉलेट में जोड़ दिए गए हैं",
    note: "अब आप होस्ट के साथ कॉल करने के लिए अपने कॉइन का उपयोग कर सकते हैं",
    findHost: "बात करने के लिए होस्ट खोजें",
    viewWallet: "वॉलेट देखें",
  },

  editProfile: {
    updated: "आपकी प्रोफ़ाइल अपडेट हो गई है।",
    savedTitle: "प्रोफ़ाइल सहेजी गई",
    saveFailedMsg: "आपकी प्रोफ़ाइल सहेजी नहीं जा सकी। कृपया पुनः प्रयास करें।",
    saveFailed: "सहेजना विफल",
    permissionTitle: "अनुमति आवश्यक",
    permissionMsg: "अपना अवतार बदलने के लिए कृपया अपनी फ़ोटो लाइब्रेरी तक पहुँच की अनुमति दें।",
    uploadFailed: "अपलोड विफल",
    uploadFailedMsg: "अवतार अपलोड नहीं हो सका। कृपया पुनः प्रयास करें।",
    displayName: "प्रदर्शित नाम",
    namePlaceholder: "आपका नाम",
    bioPlaceholder: "दूसरों को अपने बारे में बताएं...",
    saveChanges: "परिवर्तन सहेजें",
  },

  referralScreen: {
    title: "रेफ़र करें और कमाएं",
    heroTitle: "दोस्तों को आमंत्रित करें, कॉइन कमाएं!",
    heroSub: "हर उस दोस्त के लिए जो आपके कोड से VoxLink से जुड़ता है, आपके दोस्त को {newUser} बोनस कॉइन मिलते हैं और आप {referrer} कॉइन कमाते हैं!",
    yourCode: "आपका रेफ़रल कोड",
    shareWithFriends: "दोस्तों के साथ साझा करें",
    yourStats: "आपके रेफ़रल आँकड़े",
    friendsInvited: "आमंत्रित दोस्त",
    coinsEarned: "कमाए गए कॉइन",
    howItWorks: "यह कैसे काम करता है",
    step1: "अपना अनूठा रेफ़रल कोड दोस्तों के साथ साझा करें",
    step2: "दोस्त आपके कोड से साइन अप करता है और {count} कॉइन पाता है",
    step3Instant: "आप तुरंत {reward} कॉइन कमाते हैं!",
    step3OneCall: "जब वे 1 कॉल पूरी करते हैं, तो आप {reward} कॉइन कमाते हैं!",
    step3Calls: "जब वे {count} कॉल पूरी करते हैं, तो आप {reward} कॉइन कमाते हैं!",
    failedLoad: "रेफ़रल जानकारी लोड करने में विफल।",
    codeCopied: "रेफ़रल कोड कॉपी हो गया!",
    copyFailed: "कोड कॉपी नहीं हो सका। कृपया पुनः प्रयास करें।",
    shareTitle: "VoxLink से जुड़ें",
    shareMessage: "VoxLink से जुड़ें और शानदार होस्ट के साथ ऑडियो और वीडियो कॉल पर जुड़ें!\n\nसाइनअप पर बोनस कॉइन पाने के लिए मेरा रेफ़रल कोड उपयोग करें: {code}!\n\nअभी डाउनलोड करें: https://voxlink.app",
  },

  splash: {
    tagline: "जुड़ें और सार्थक रिश्ते बनाएं",
  },

  dailyReward: {
    title: "दैनिक इनाम",
    titleClaimed: "इनाम मिल गया!",
    dayOfStreak: "आपकी स्ट्रीक का दिन {day}",
    streakUnlocked: "दिन {day} स्ट्रीक अनलॉक हुई",
    claimHint: "अपनी स्ट्रीक जारी रखने के लिए आज क्लेम करें।",
    dayBonus: "दिन {day} बोनस: +{count} अतिरिक्त कॉइन!",
    claim: "{count} कॉइन क्लेम करें",
    claiming: "क्लेम हो रहा है…",
    later: "बाद में",
    awesome: "बढ़िया!",
    addedToWallet: "आपके वॉलेट में जोड़ दिए गए",
    baseMilestone: "{base} बेस + {bonus} माइलस्टोन बोनस",
    newBalance: "नया शेष",
    coins: "कॉइन",
    freeMinutes: "+{count} मुफ़्त कॉल मिनट!",
    monthlyChest: "मासिक चेस्ट: +{count} कॉइन!",
    comebackBonus: "वापसी बोनस: +{count} कॉइन",
    spinning: "घूम रहा है…",
    luckyWheel: "लकी व्हील",
    lucky: "लकी!",
    scheduleLabel: "स्ट्रीक शेड्यूल",
    nextMilestone: "आपके दिन {day} बोनस तक {count} दिन",
    nextMilestonePlural: "आपके दिन {day} बोनस तक {count} दिन",
    missedDay: "आपने एक दिन छोड़ दिया!",
    restoreWithSaver: "अपनी {streak}-दिन की स्ट्रीक एक मुफ़्त स्ट्रीक सेवर से बहाल करें ({count} बचे)।",
    restoreWithCoins: "अपनी {streak}-दिन की स्ट्रीक {count} कॉइन में बहाल करें।",
    restoring: "बहाल हो रहा है…",
    useStreakSaver: "स्ट्रीक सेवर उपयोग करें",
    restoreForCoins: "{count} कॉइन में बहाल करें",
    atRiskCountdown: "जल्दी क्लेम करें — आपकी स्ट्रीक {time} में रीसेट होगी!",
    atRisk: "जल्दी क्लेम करें — आपकी स्ट्रीक आधी रात को रीसेट होगी!",
  },
};

export default hi;
