// VoxLink — Hindi Strings

const hi = {
  common: {
    ok: "ठीक है",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    save: "सहेजें",
    delete: "हटाएं",
    edit: "संपादित करें",
    done: "हो गया",
    back: "वापस",
    close: "बंद करें",
    loading: "लोड हो रहा है...",
    error: "कुछ गलत हो गया",
    retry: "फिर कोशिश करें",
    submit: "जमा करें",
    next: "अगला",
    skip: "छोड़ें",
    yes: "हाँ",
    no: "नहीं",
    search: "खोजें",
    filter: "फ़िल्टर",
    clear: "साफ़ करें",
    apply: "लागू करें",
    share: "साझा करें",
    copy: "कॉपी करें",
    copied: "कॉपी हो गया!",
    noResults: "कोई परिणाम नहीं मिला",
    optional: "वैकल्पिक",
    required: "ज़रूरी",
    all: "सभी",
    more: "अधिक",
    less: "कम",
    seeAll: "सब देखें",
    noData: "कोई डेटा उपलब्ध नहीं",
    refresh: "रीफ्रेश",
  },

  auth: {
    login: "लॉग इन",
    register: "साइन अप",
    logout: "लॉग आउट",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    forgotPassword: "पासवर्ड भूल गए?",
    newPassword: "नया पासवर्ड",
    phone: "फ़ोन नंबर",
    otp: "सत्यापन कोड",
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP सत्यापित करें",
    resendOtp: "OTP फिर भेजें",
    fullName: "पूरा नाम",
    createAccount: "खाता बनाएं",
    alreadyHaveAccount: "पहले से खाता है?",
    dontHaveAccount: "खाता नहीं है?",
    welcomeBack: "वापस स्वागत है!",
    loginToContinue: "जारी रखने के लिए लॉग इन करें",
    createYourAccount: "अपना खाता बनाएं",
    joinVoxLink: "आज VoxLink से जुड़ें",
    enterOtp: "इस नंबर पर भेजा OTP दर्ज करें",
    passwordResetSent: "पासवर्ड रीसेट ईमेल भेजा गया",
    checkEmail: "निर्देशों के लिए ईमेल जांचें",
    passwordChanged: "पासवर्ड सफलतापूर्वक बदला गया",
    invalidCredentials: "अमान्य ईमेल या पासवर्ड",
    accountDeleted: "खाता सफलतापूर्वक हटाया गया",
    deleteAccountConfirm: "क्या आप वाकई अपना खाता हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।",
    tagline: "जुड़ें. बात करें. आगे बढ़ें.",
    welcomeToVoxLink: "VoxLink में आपका स्वागत है",
    autoCreateAccount: "नए उपयोगकर्ता? पहली बार लॉगिन पर हम आपका खाता स्वतः बना देंगे",
    continueWithGoogle: "Google से जारी रखें",
    signingIn: "साइन इन हो रहा है...",
    or: "या",
    quickLogin: "क्विक लॉगिन",
    pleaseWait: "कृपया प्रतीक्षा करें...",
    quickLoginNote: "क्विक लॉगिन आपके खाते को इस डिवाइस पर सहेजता है — पुनः इंस्टॉल करें और यह फिर भी आपका रहेगा",
    welcomeName: "स्वागत है, {name}!",
    welcomeBackToast: "वापसी पर स्वागत है!",
    quickLoginTitle: "क्विक लॉगिन",
    accountCreated: "खाता बन गया! VoxLink में आपका स्वागत है।",
    welcomeTitle: "स्वागत है",
    connectionError: "कोई इंटरनेट कनेक्शन नहीं। कृपया अपना नेटवर्क जांचें।",
    connectionErrorTitle: "कनेक्शन त्रुटि",
    quickLoginFailed: "क्विक लॉगिन विफल। कृपया पुनः प्रयास करें।",
  },

  nav: {
    home: "होम",
    search: "खोजें",
    messages: "संदेश",
    wallet: "वॉलेट",
    profile: "प्रोफ़ाइल",
    notifications: "सूचनाएं",
  },

  home: {
    greeting: "नमस्ते",
    findHosts: "होस्ट खोजें",
    topListeners: "शीर्ष श्रोता",
    trending: "अभी ट्रेंडिंग",
    newHosts: "नए होस्ट",
    onlineNow: "अभी ऑनलाइन",
    featuredHosts: "विशेष होस्ट",
    seeAll: "सब देखें",
    searchPlaceholder: "होस्ट, विषय खोजें...",
    findMore: "और खोजें",
    findMoreSub: "अभी किसी रैंडम लिसनर से जुड़ें",
    startRandomCall: "रैंडम कॉल शुरू करें",
    welcome: "स्वागत है",
    freeMinutesTitle: "{count} मुफ़्त कॉल मिनट उपलब्ध!",
    freeMinutesSub: "आपके पहले {count} मिनट हमारी ओर से — किसी भी होस्ट के साथ कॉल शुरू करें।",
    lowOnCoins: "कॉइन कम हैं ({count} बचे)",
    lowOnCoinsSub: "अभी रीचार्ज करें ताकि कॉल बीच में न कटे।",
    topUp: "रीचार्ज करें",
    yourFavorites: "आपके पसंदीदा",
    viewAll: "सभी देखें",
    recommendedForYou: "आपके लिए अनुशंसित",
    browseByTopic: "विषय के अनुसार ब्राउज़ करें",
    availableNow: "अभी उपलब्ध",
    online: "ऑनलाइन",
    noListenersAvailable: "अभी कोई लिसनर उपलब्ध नहीं है",
    offlineListeners: "ऑफ़लाइन लिसनर",
  },

  // Random Match
  random: {
    title: "रैंडम मैच",
    randomMatch: "🎲 रैंडम मैच",
    cancel: "रद्द करें",
    voiceCall: "वॉइस कॉल",
    videoCall: "वीडियो कॉल",
    findingMatch: "आपका मैच ढूंढ़ रहे हैं…",
    listenersOnline: "{count} लिसनर ऑनलाइन",
    listenerOnline: "{count} लिसनर ऑनलाइन",
    chooseCallType: "कॉल का प्रकार चुनें",
    matchFound: "मैच मिल गया! 🎉",
    accept: "स्वीकार करें",
    decline: "अस्वीकार",
    skipNext: "स्किप / अगला",
    checking: "जाँच हो रही…",
    filters: "फ़िल्टर",
    matchFilters: "मैच फ़िल्टर",
    gender: "लिंग",
    genderAny: "कोई भी",
    genderMale: "पुरुष",
    genderFemale: "महिला",
    minimumRating: "न्यूनतम रेटिंग",
    ratingAny: "कोई भी रेटिंग",
    rating3: "3★ +",
    rating4: "4★ +",
    rating4_5: "4.5★ +",
    reset: "रीसेट",
    done: "हो गया",
    myBalance: "मेरा बैलेंस",
    needCoins: "इस कॉल को शुरू करने के लिए आपको कम से कम {count} कॉइन चाहिए।",
    statusInsufficientCoins: "रैंडम कॉल शुरू करने के लिए पर्याप्त कॉइन नहीं हैं।",
    statusNotEnoughCoinsTitle: "कॉइन कम हैं",
    statusRateLimited: "थोड़ा रुकिए, फिर कोशिश करें…",
    statusDailyLimit: "आज की रैंडम मैच सीमा पूरी हो गई।",
    statusDeclineCooldown: "बहुत बार अस्वीकार किया — कुछ देर रुकें।",
    statusNoMatchFilters: "इन फ़िल्टर से कोई होस्ट नहीं मिला — फ़िल्टर ढीले करें।",
    statusSearching: "ऑनलाइन लिसनर्स में खोज रहे हैं…",
    statusNoneOnline: "अभी कोई लिसनर ऑनलाइन नहीं है — फिर भी खोज रहे हैं…",
    statusGiveUp: "अभी कोई होस्ट नहीं मिला। थोड़ी देर बाद पुनः प्रयास करें।",
    statusNetworkError: "नेटवर्क त्रुटि, फिर से कोशिश हो रही…",
    statusServerUnreachable: "सर्वर तक नहीं पहुँच सके। कृपया फिर से प्रयास करें।",
    hostBusy: "होस्ट अभी व्यस्त हो गया — दूसरा मैच खोज रहे हैं।",
    hostOffline: "होस्ट ऑफ़लाइन हो गया — दूसरा मैच खोज रहे हैं।",
    hostUnavailable: "होस्ट उपलब्ध नहीं — दूसरा मैच खोज रहे हैं।",
    failedLoadHosts: "उपलब्ध होस्ट लोड नहीं हो सके।",
  },

  hosts: {
    host: "होस्ट",
    listener: "श्रोता",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    busy: "व्यस्त",
    rating: "रेटिंग",
    reviews: "समीक्षाएं",
    review: "समीक्षा",
    coinsPerMinute: "कॉइन/मिनट",
    totalMinutes: "कुल मिनट",
    specialties: "विशेषताएं",
    languages: "भाषाएं",
    about: "के बारे में",
    callNow: "अभी कॉल करें",
    audioCall: "ऑडियो कॉल",
    videoCall: "वीडियो कॉल",
    sendMessage: "संदेश भेजें",
    talkNow: "अभी बात करें",
    noHostsFound: "कोई होस्ट नहीं मिला",
    adjustFilters: "अपने फ़िल्टर समायोजित करें",
    topRated: "शीर्ष रेटेड",
    viewProfile: "प्रोफ़ाइल देखें",
    startCall: "कॉल शुरू करें",
  },

  calls: {
    incoming: "आने वाली कॉल",
    outgoing: "कनेक्ट हो रहा है...",
    ongoing: "कॉल पर",
    ended: "कॉल समाप्त",
    audio: "ऑडियो कॉल",
    video: "वीडियो कॉल",
    accept: "स्वीकार करें",
    decline: "अस्वीकार करें",
    endCall: "कॉल समाप्त करें",
    mute: "म्यूट",
    unmute: "अनम्यूट",
    speaker: "स्पीकर",
    flipCamera: "कैमरा बदलें",
    callDuration: "कॉल अवधि",
    callWith: "के साथ कॉल",
    rateCall: "इस कॉल को रेट करें",
    callHistory: "कॉल इतिहास",
    noCallHistory: "अभी तक कोई कॉल इतिहास नहीं",
    callCost: "कॉल लागत",
    perMinute: "प्रति मिनट",
    lowBalance: "कम कॉइन बैलेंस",
    lowBalanceMsg: "आपके कॉइन कम हैं। जारी रखने के लिए रीचार्ज करें।",
    callEnded: "कॉल समाप्त",
    callEndedMsg: "आपकी कॉल समाप्त हो गई है",
    missed: "मिस्ड",
    answered: "उत्तर दिया",
    rejected: "अस्वीकृत",
    callingHistory: "कॉलिंग इतिहास",
    audioShort: "ऑडियो",
    videoShort: "वीडियो",
    incomingVideo: "इनकमिंग वीडियो कॉल",
    incomingAudio: "इनकमिंग ऑडियो कॉल",
    unknown: "अज्ञात",
    voxlinkHost: "VoxLink होस्ट",
    voxlinkUser: "VoxLink उपयोगकर्ता",
    voiceCall: "वॉइस कॉल",
    callDeclined: "कॉल अस्वीकृत",
    noAnswer: "कोई उत्तर नहीं",
    ringing: "रिंग हो रही है",
    connecting: "कनेक्ट हो रहा है",
    coinsPerMin: "कॉइन / मिनट",
    oneMinMinimum: "न्यूनतम 1 मिनट",
    callAutoEnded: "कॉल स्वतः समाप्त",
    autoDisconnected: "आपके कॉइन समाप्त हो गए — कॉल स्वतः कट गई",
    with: "के साथ",
    minBilling: "न्यूनतम 1 मिनट की बिलिंग लागू",
    duration: "अवधि",
    coinsSpent: "खर्च किए कॉइन",
    rateName: "{name} को रेट करें",
    feedbackHelps: "आपकी प्रतिक्रिया होस्ट को बेहतर बनने में मदद करती है",
    ratingPoor: "खराब",
    ratingFair: "ठीक-ठाक",
    ratingGood: "अच्छा",
    ratingGreat: "बहुत अच्छा",
    ratingExcellent: "उत्कृष्ट!",
    submitRating: "रेटिंग सबमिट करें",
    thankYou: "धन्यवाद! 🙏",
    ratingSubmitted: "आपकी रेटिंग सबमिट हो गई",
    rechargeCoins: "कॉइन रीचार्ज करें",
    backHome: "होम पर वापस जाएं",
    rateFailed: "रेटिंग सबमिट करने में विफल, कृपया पुनः प्रयास करें।",
    errorTitle: "त्रुटि",
    completed: "पूर्ण",
    cancelled: "रद्द",
    noCallHistoryFound: "कोई कॉल इतिहास नहीं मिला",
    failedLoadHistory: "कॉल इतिहास लोड करने में विफल।",
    micAccessNeeded: "माइक्रोफ़ोन एक्सेस आवश्यक — ठीक करने के लिए टैप करें",
    coinsRunningLow: "कॉइन कम हो रहे हैं",
    secondsRemaining: "{count}s शेष",
    minLeft: "{count} मिनट शेष",
    ringingDots: "रिंग हो रही है...",
    connectingDots: "कनेक्ट हो रहा है...",
    connected: "कनेक्टेड",
    networkDrop: "नेटवर्क टूट गया — पुनः कनेक्ट हो रहा है...",
    connectionFailed: "कनेक्शन विफल — पुनः प्रयास हो रहा है...",
    callEndedShort: "कॉल समाप्त",
    mutedHint: "🔇 म्यूट",
    speakerOn: "स्पीकर चालू",
    runningOutCoins: "कॉइन खत्म हो रहे हैं!",
    autoDisconnectIn: "कॉल {time} में स्वतः कट जाएगी",
    second: "सेकंड",
    seconds: "सेकंड",
    fewSeconds: "कुछ सेकंड",
    rechargeNow: "अभी रीचार्ज करें",
    continueCall: "कॉल जारी रखें",
    cameraOff: "कैमरा बंद",
    cameraUnavailable: "कैमरा अनुपलब्ध",
    startingCamera: "कैमरा शुरू हो रहा है…",
    noPermission: "अनुमति नहीं",
    cameraOffShort: "कैमरा बंद",
    you: "आप",
    mutedLabel: "म्यूट",
    noMic: "माइक नहीं",
    lowCoins: "कॉइन कम",
    secondsLeft: "{count}s शेष",
    connectionIssue: "कनेक्शन समस्या",
    live: "लाइव",
    waitingResponse: "प्रतिक्रिया की प्रतीक्षा...",
    camera: "कैमरा",
    camOff: "कैमरा बंद",
    end: "समाप्त",
    flip: "फ्लिप",
    earpiece: "इयरपीस",
  },

  chat: {
    messages: "संदेश",
    newMessage: "नया संदेश",
    typeMessage: "संदेश लिखें...",
    send: "भेजें",
    noMessages: "अभी तक कोई संदेश नहीं",
    startConversation: "बातचीत शुरू करें",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    typing: "लिख रहा है...",
    delivered: "डिलीवर",
    read: "पढ़ा",
    deleteChat: "चैट हटाएं",
    deleteChatConfirm: "क्या आप इस बातचीत को हटाना चाहते हैं?",
    chats: "चैट",
    searchConversations: "बातचीत खोजें...",
    noConversationsFound: "कोई बातचीत नहीं मिली",
    noConversationsYet: "अभी कोई बातचीत नहीं",
    tryDifferentName: "कोई और नाम आज़माएं",
    startChattingAfterCall: "किसी होस्ट के साथ कॉल के बाद चैट शुरू करें",
  },

  wallet: {
    wallet: "वॉलेट",
    coinBalance: "कॉइन बैलेंस",
    coins: "कॉइन",
    coin: "कॉइन",
    buyCoins: "कॉइन खरीदें",
    coinHistory: "कॉइन इतिहास",
    transactions: "लेन-देन",
    noTransactions: "अभी तक कोई लेन-देन नहीं",
    purchased: "खरीदा",
    spent: "खर्च किया",
    bonus: "बोनस",
    refunded: "वापस किया",
    withdrawal: "निकासी",
    totalSpent: "कुल खर्च",
    totalPurchased: "कुल खरीद",
    popular: "सबसे लोकप्रिय",
    bestValue: "सर्वोत्तम मूल्य",
    bonus_label: "बोनस",
    recharge: "रीचार्ज",
    choosePackage: "पैकेज चुनें",
    instantDelivery: "तत्काल डिलीवरी",
    securePayment: "सुरक्षित भुगतान",
    guaranteed: "संतुष्टि की गारंटी",
  },

  profile: {
    profile: "प्रोफ़ाइल",
    editProfile: "प्रोफ़ाइल संपादित करें",
    myProfile: "मेरी प्रोफ़ाइल",
    name: "नाम",
    email: "ईमेल",
    phone: "फ़ोन",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    country: "देश",
    bio: "बायो",
    language: "भाषा",
    settings: "सेटिंग्स",
    helpCenter: "सहायता और FAQ",
    privacy: "गोपनीयता नीति",
    about: "VoxLink के बारे में",
    shareApp: "VoxLink शेयर करें",
    rateApp: "ऐप को रेट करें",
    logout: "लॉग आउट",
    deleteAccount: "खाता हटाएं",
    callHistory: "कॉल इतिहास",
    joinedOn: "शामिल हुए",
    totalCalls: "कुल कॉल",
    hoursSpent: "बिताए घंटे",
  },

  settings: {
    settings: "सेटिंग्स",
    notifications: "सूचनाएं",
    callNotifications: "कॉल सूचनाएं",
    messageNotifications: "संदेश सूचनाएं",
    promoNotifications: "प्रचार सूचनाएं",
    language: "भाषा",
    theme: "थीम",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    systemDefault: "सिस्टम डिफ़ॉल्ट",
    privacy: "गोपनीयता",
    security: "सुरक्षा",
    changePassword: "पासवर्ड बदलें",
    twoFactor: "दो-कारक प्रमाणीकरण",
    account: "खाता",
    support: "सहायता",
  },

  payment: {
    checkout: "चेकआउट",
    selectPackage: "पैकेज चुनें",
    paymentMethod: "भुगतान विधि",
    creditCard: "क्रेडिट / डेबिट कार्ड",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "भुगतान प्रक्रिया में...",
    paymentSuccess: "भुगतान सफल!",
    paymentFailed: "भुगतान विफल",
    orderSummary: "ऑर्डर सारांश",
    total: "कुल",
    coins: "कॉइन",
    bonusCoins: "बोनस कॉइन",
    tryAgain: "फिर कोशिश करें",
    secureNote: "सभी भुगतान सुरक्षित और एन्क्रिप्टेड हैं",
  },

  host: {
    dashboard: "डैशबोर्ड",
    totalEarnings: "कुल कमाई",
    thisWeek: "इस सप्ताह",
    thisMonth: "इस महीने",
    totalCalls: "कुल कॉल",
    avgRating: "औसत रेटिंग",
    onlineStatus: "ऑनलाइन स्थिति",
    goOnline: "ऑनलाइन जाएं",
    goOffline: "ऑफलाइन जाएं",
    setBusy: "व्यस्त सेट करें",
    earnings: "कमाई",
    withdraw: "निकालें",
    withdrawal: "निकासी",
    minimumWithdraw: "न्यूनतम 100 कॉइन",
    enterAmount: "राशि दर्ज करें",
    withdrawMethod: "निकासी विधि",
    bankTransfer: "बैंक ट्रांसफर",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "खाता विवरण",
    withdrawSuccess: "निकासी अनुरोध सबमिट किया गया",
    withdrawPending: "आपका अनुरोध संसाधित किया जा रहा है",
    hostSettings: "होस्ट सेटिंग्स",
    availability: "उपलब्धता",
    payoutSettings: "पेआउट सेटिंग्स",
    becomeHost: "होस्ट बनें",
    apply: "अभी आवेदन करें",
    applicationSent: "आवेदन भेजा गया!",
    applicationDesc: "हम आपके आवेदन की समीक्षा करेंगे और 2-3 कार्य दिवसों के भीतर वापस आएंगे।",
  },

  errors: {
    network: "नेटवर्क त्रुटि। कृपया अपना कनेक्शन जांचें।",
    server: "सर्वर त्रुटि। कृपया बाद में पुनः प्रयास करें।",
    unauthorized: "सत्र समाप्त। कृपया फिर से लॉग इन करें।",
    notFound: "अनुरोधित संसाधन नहीं मिला।",
    insufficientCoins: "अपर्याप्त कॉइन। कृपया रीचार्ज करें।",
    callFailed: "कॉल कनेक्ट नहीं हो सका। कृपया पुनः प्रयास करें।",
    permissionDenied: "अनुमति अस्वीकृत।",
    generic: "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
  },

  tabs: {
    home: "होम",
    listener: "लिसनर",
    random: "रैंडम",
    chat: "चैट",
    calling: "कॉलिंग",
  },

  listener: {
    allListeners: "सभी लिसनर",
    language: "भाषा",
    talkAbout: "किस बारे में बात करें",
    selectLanguage: "भाषा चुनें",
    noListenersFound: "कोई लिसनर नहीं मिला",
    failedLoad: "लिसनर लोड करने में विफल।",
    available: "उपलब्ध",
    offline: "ऑफ़लाइन",
    audio: "ऑडियो",
    video: "वीडियो",
    perMin: "/मिनट",
    hrs: "घंटे",
  },

  onboarding: {
    find: "खोजें",
    findDesc: "आप दुनिया भर के लोगों से जुड़ सकते हैं\nचैट और संदेश के लिए और\nउनके साथ संबंध बना सकते हैं।",
    chat: "चैट",
    chatDesc: "एक-दूसरे को बेहतर जानने के लिए\nअजनबियों से चैट करें और\nअच्छी अनुकूलता पाएं।",
    videoCall: "वीडियो कॉल",
    videoCallDesc: "आप अपने दोस्तों और कनेक्शनों के साथ\nअपने वीडियो और फ़ोटो साझा कर सकते हैं।",
  },

  hostsScreen: {
    allHosts: "सभी होस्ट",
    failedLoad: "होस्ट लोड नहीं हो सके। रिफ्रेश करने के लिए खींचें।",
  },

  reviews: {
    failedLoad: "समीक्षाएं लोड नहीं हो सकीं।",
    reviewsCount: "{count} समीक्षाएं",
    noReviews: "अभी तक कोई समीक्षा नहीं",
    beFirst: "समीक्षा छोड़ने वाले पहले व्यक्ति बनें",
    user: "उपयोगकर्ता",
    today: "आज",
    yesterday: "कल",
    daysAgo: "{count} दिन पहले",
    weekAgo: "{count} सप्ताह पहले",
    weeksAgo: "{count} सप्ताह पहले",
    monthAgo: "{count} माह पहले",
    monthsAgo: "{count} माह पहले",
  },
};

export default hi;
