// VoxLink — Chinese (Simplified) Strings

const zh = {
  common: {
    ok: "确定",
    cancel: "取消",
    confirm: "确认",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    done: "完成",
    back: "返回",
    close: "关闭",
    loading: "加载中...",
    error: "出现错误",
    retry: "重试",
    submit: "提交",
    next: "下一步",
    skip: "跳过",
    yes: "是",
    no: "否",
    search: "搜索",
    filter: "筛选",
    clear: "清除",
    apply: "应用",
    share: "分享",
    copy: "复制",
    copied: "已复制!",
    noResults: "未找到结果",
    optional: "可选",
    required: "必填",
    all: "全部",
    more: "更多",
    less: "收起",
    seeAll: "查看全部",
    noData: "暂无数据",
    refresh: "刷新",
  },
  auth: {
    login: "登录",
    register: "注册",
    logout: "退出登录",
    email: "邮箱",
    password: "密码",
    confirmPassword: "确认密码",
    forgotPassword: "忘记密码?",
    newPassword: "新密码",
    phone: "手机号码",
    otp: "验证码",
    sendOtp: "发送OTP",
    verifyOtp: "验证OTP",
    resendOtp: "重新发送OTP",
    fullName: "全名",
    createAccount: "创建账户",
    alreadyHaveAccount: "已有账户?",
    dontHaveAccount: "没有账户?",
    welcomeBack: "欢迎回来!",
    loginToContinue: "登录以继续",
    createYourAccount: "创建您的账户",
    joinVoxLink: "今天加入VoxLink",
    enterOtp: "输入发送至的OTP",
    passwordResetSent: "密码重置邮件已发送",
    checkEmail: "请查收邮件获取说明",
    passwordChanged: "密码修改成功",
    invalidCredentials: "邮箱或密码无效",
    accountDeleted: "账户已成功删除",
    deleteAccountConfirm: "您确定要删除账户吗？此操作无法撤销。",
    tagline: "连接。畅聊。成长。",
    welcomeToVoxLink: "欢迎来到 VoxLink",
    autoCreateAccount: "新用户？首次登录时我们会自动为您创建账户",
    continueWithGoogle: "使用 Google 继续",
    signingIn: "正在登录...",
    or: "或",
    quickLogin: "快速登录",
    pleaseWait: "请稍候...",
    quickLoginNote: "快速登录会将您的账户保存到此设备——重新安装后仍归您所有",
    welcomeName: "欢迎，{name}！",
    welcomeBackToast: "欢迎回来！",
    quickLoginTitle: "快速登录",
    accountCreated: "账户已创建！欢迎来到 VoxLink。",
    welcomeTitle: "欢迎",
    connectionError: "无网络连接。请检查您的网络。",
    connectionErrorTitle: "连接错误",
    quickLoginFailed: "快速登录失败。请重试。",
  },
  nav: {
    home: "首页",
    search: "搜索",
    messages: "消息",
    wallet: "钱包",
    profile: "我的",
    notifications: "通知",
  },
  home: {
    greeting: "你好",
    findHosts: "查找主播",
    topListeners: "顶级倾听者",
    trending: "热门",
    newHosts: "新主播",
    onlineNow: "当前在线",
    featuredHosts: "精选主播",
    seeAll: "查看全部",
    searchPlaceholder: "搜索主播、话题...",
    findMore: "发现更多",
    findMoreSub: "立即与随机倾听者连接",
    startRandomCall: "开始随机通话",
    welcome: "欢迎",
    freeMinutesTitle: "{count} 分钟免费通话可用！",
    freeMinutesSub: "您的前 {count} 分钟由我们承担——与任意主播开始通话。",
    lowOnCoins: "金币不足（剩余 {count}）",
    lowOnCoinsSub: "立即充值，以免通话中途被中断。",
    topUp: "充值",
    yourFavorites: "您的收藏",
    viewAll: "查看全部",
    recommendedForYou: "为您推荐",
    browseByTopic: "按话题浏览",
    availableNow: "现在可用",
    online: "在线",
    noListenersAvailable: "暂时没有可用的倾听者",
    offlineListeners: "离线倾听者",
  },

  // Random Match
  random: {
    title: "随机匹配",
    randomMatch: "🎲 随机匹配",
    cancel: "取消",
    voiceCall: "语音通话",
    videoCall: "视频通话",
    findingMatch: "正在为您匹配…",
    listenersOnline: "{count} 位听众在线",
    listenerOnline: "{count} 位听众在线",
    chooseCallType: "选择通话类型",
    matchFound: "匹配成功! 🎉",
    accept: "接受",
    decline: "拒绝",
    skipNext: "跳过 / 下一个",
    checking: "正在检查…",
    filters: "筛选",
    matchFilters: "匹配筛选",
    gender: "性别",
    genderAny: "不限",
    genderMale: "男性",
    genderFemale: "女性",
    minimumRating: "最低评分",
    ratingAny: "不限评分",
    rating3: "3★ +",
    rating4: "4★ +",
    rating4_5: "4.5★ +",
    reset: "重置",
    done: "完成",
    myBalance: "我的余额",
    needCoins: "您至少需要 {count} 金币才能开始此通话。",
    statusInsufficientCoins: "金币不足,无法发起随机通话。",
    statusNotEnoughCoinsTitle: "金币不足",
    statusRateLimited: "稍等片刻,然后再试…",
    statusDailyLimit: "您已达到今日的随机匹配上限。",
    statusDeclineCooldown: "拒绝次数过多 — 请稍作休息。",
    statusNoMatchFilters: "没有主播符合筛选条件 — 请放宽条件。",
    statusSearching: "正在在线听众中匹配…",
    statusNoneOnline: "目前没有听众在线 — 仍在匹配中…",
    statusGiveUp: "暂时没有可用主播。请稍后再试。",
    statusNetworkError: "网络错误,正在重试…",
    statusServerUnreachable: "无法连接服务器,请重试。",
    retryIn: "{time} 后重试",
    dailyLimitReset: "明天重置",
    hostBusy: "主播正忙 — 正在寻找其他匹配。",
    hostOffline: "主播已下线 — 正在寻找其他匹配。",
    hostUnavailable: "主播不可用 — 正在寻找其他匹配。",
    failedLoadHosts: "加载可用主播失败。",
  },
  hosts: {
    host: "主播",
    listener: "倾听者",
    online: "在线",
    offline: "离线",
    busy: "忙碌",
    rating: "评分",
    reviews: "评价",
    review: "评价",
    coinsPerMinute: "金币/分钟",
    totalMinutes: "累计分钟",
    specialties: "专长",
    languages: "语言",
    about: "关于",
    callNow: "立即通话",
    audioCall: "语音通话",
    videoCall: "视频通话",
    sendMessage: "发送消息",
    talkNow: "现在聊",
    noHostsFound: "未找到主播",
    adjustFilters: "请调整筛选条件",
    topRated: "评分最高",
    viewProfile: "查看资料",
    startCall: "开始通话",
  },
  calls: {
    incoming: "来电",
    outgoing: "连接中...",
    ongoing: "通话中",
    ended: "通话结束",
    audio: "语音通话",
    video: "视频通话",
    accept: "接受",
    decline: "拒绝",
    endCall: "结束通话",
    mute: "静音",
    unmute: "取消静音",
    speaker: "扬声器",
    flipCamera: "翻转摄像头",
    callDuration: "通话时长",
    callWith: "通话对象",
    rateCall: "评价此通话",
    callHistory: "通话记录",
    noCallHistory: "暂无通话记录",
    callCost: "通话费用",
    perMinute: "每分钟",
    lowBalance: "金币余额不足",
    lowBalanceMsg: "您的金币不足，请充值继续。",
    callEnded: "通话结束",
    callEndedMsg: "您的通话已结束",
    missed: "未接",
    answered: "已接",
    rejected: "已拒绝",
    callingHistory: "通话历史",
    audioShort: "语音",
    videoShort: "视频",
    incomingVideo: "视频来电",
    incomingAudio: "语音来电",
    unknown: "未知",
    voxlinkHost: "VoxLink 主播",
    voxlinkUser: "VoxLink 用户",
    voiceCall: "语音通话",
    callDeclined: "通话已拒绝",
    noAnswer: "无应答",
    ringing: "响铃中",
    connecting: "连接中",
    coinsPerMin: "金币 / 分钟",
    oneMinMinimum: "最低 1 分钟",
    callAutoEnded: "通话已自动结束",
    autoDisconnected: "您的金币已用完——通话已自动断开",
    with: "与",
    minBilling: "已应用最低 1 分钟计费",
    duration: "时长",
    coinsSpent: "已花费金币",
    rateName: "为 {name} 评分",
    feedbackHelps: "您的反馈有助于主播改进",
    ratingPoor: "差",
    ratingFair: "一般",
    ratingGood: "好",
    ratingGreat: "很好",
    ratingExcellent: "非常棒！",
    submitRating: "提交评分",
    thankYou: "谢谢！🙏",
    ratingSubmitted: "您的评分已提交",
    rechargeCoins: "充值金币",
    backHome: "返回首页",
    rateFailed: "提交评分失败，请重试。",
    errorTitle: "错误",
    completed: "已完成",
    cancelled: "已取消",
    noCallHistoryFound: "未找到通话历史",
    failedLoadHistory: "加载通话历史失败。",
    micAccessNeeded: "需要麦克风权限——点击修复",
    coinsRunningLow: "金币即将用完",
    secondsRemaining: "剩余 {count} 秒",
    minLeft: "剩余 {count} 分钟",
    ringingDots: "响铃中...",
    connectingDots: "连接中...",
    connected: "已连接",
    networkDrop: "网络中断——正在重新连接...",
    connectionFailed: "连接失败——正在重试...",
    callEndedShort: "通话已结束",
    mutedHint: "🔇 已静音",
    speakerOn: "扬声器已开",
    runningOutCoins: "金币即将用完！",
    autoDisconnectIn: "通话将在 {time} 后自动断开",
    second: "秒",
    seconds: "秒",
    fewSeconds: "几秒",
    rechargeNow: "立即充值",
    continueCall: "继续通话",
    cameraOff: "摄像头关闭",
    cameraUnavailable: "摄像头不可用",
    startingCamera: "正在启动摄像头…",
    noPermission: "无权限",
    cameraOffShort: "摄像头关闭",
    you: "你",
    mutedLabel: "已静音",
    noMic: "无麦克风",
    lowCoins: "金币不足",
    secondsLeft: "剩余 {count} 秒",
    connectionIssue: "连接问题",
    live: "直播",
    waitingResponse: "等待应答...",
    camera: "摄像头",
    camOff: "关摄像头",
    end: "结束",
    flip: "翻转",
    earpiece: "听筒",
  },
  chat: {
    messages: "消息",
    newMessage: "新消息",
    typeMessage: "输入消息...",
    send: "发送",
    noMessages: "暂无消息",
    startConversation: "开始对话",
    online: "在线",
    offline: "离线",
    typing: "正在输入...",
    delivered: "已送达",
    read: "已读",
    deleteChat: "删除聊天",
    deleteChatConfirm: "确定要删除此对话吗?",
    chats: "聊天",
    searchConversations: "搜索对话...",
    noConversationsFound: "未找到对话",
    noConversationsYet: "暂无对话",
    tryDifferentName: "尝试其他名称",
    startChattingAfterCall: "与主播通话后开始聊天",
  },
  wallet: {
    wallet: "钱包",
    coinBalance: "金币余额",
    coins: "金币",
    coin: "金币",
    buyCoins: "购买金币",
    coinHistory: "金币记录",
    transactions: "交易记录",
    noTransactions: "暂无交易记录",
    purchased: "已购买",
    spent: "已消费",
    bonus: "奖励",
    refunded: "已退款",
    withdrawal: "提现",
    totalSpent: "总消费",
    totalPurchased: "总购买",
    popular: "最受欢迎",
    bestValue: "最超值",
    bonus_label: "奖励",
    recharge: "充值",
    choosePackage: "选择套餐",
    instantDelivery: "即时到账",
    securePayment: "安全支付",
    guaranteed: "满意保证",
  },
  profile: {
    profile: "我的",
    editProfile: "编辑资料",
    myProfile: "我的资料",
    name: "姓名",
    email: "邮箱",
    phone: "手机号",
    gender: "性别",
    male: "男",
    female: "女",
    other: "其他",
    country: "国家",
    bio: "个人简介",
    language: "语言",
    settings: "设置",
    helpCenter: "帮助中心",
    privacy: "隐私政策",
    about: "关于VoxLink",
    shareApp: "分享VoxLink",
    rateApp: "给应用评分",
    logout: "退出登录",
    deleteAccount: "删除账户",
    callHistory: "通话记录",
    joinedOn: "加入于",
    totalCalls: "总通话次数",
    hoursSpent: "花费时间",
  },
  settings: {
    settings: "设置",
    notifications: "通知",
    callNotifications: "来电通知",
    messageNotifications: "消息通知",
    promoNotifications: "推广通知",
    language: "语言",
    theme: "主题",
    lightMode: "浅色模式",
    darkMode: "深色模式",
    systemDefault: "跟随系统",
    privacy: "隐私",
    security: "安全",
    changePassword: "修改密码",
    twoFactor: "双重验证",
    account: "账户",
    support: "支持",
  },
  payment: {
    checkout: "结账",
    selectPackage: "选择套餐",
    paymentMethod: "支付方式",
    creditCard: "信用卡/借记卡",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "支付处理中...",
    paymentSuccess: "支付成功!",
    paymentFailed: "支付失败",
    orderSummary: "订单摘要",
    total: "合计",
    coins: "金币",
    bonusCoins: "奖励金币",
    tryAgain: "重试",
    secureNote: "所有支付均已加密保护",
  },
  host: {
    dashboard: "仪表盘",
    totalEarnings: "总收益",
    thisWeek: "本周",
    thisMonth: "本月",
    totalCalls: "总通话数",
    avgRating: "平均评分",
    onlineStatus: "在线状态",
    goOnline: "上线",
    goOffline: "下线",
    setBusy: "设为忙碌",
    earnings: "收益",
    withdraw: "提现",
    withdrawal: "提现",
    minimumWithdraw: "最低100金币",
    enterAmount: "输入金额",
    withdrawMethod: "提现方式",
    bankTransfer: "银行转账",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "账户详情",
    withdrawSuccess: "提现申请已提交",
    withdrawPending: "您的申请正在处理中",
    hostSettings: "主播设置",
    availability: "可用状态",
    payoutSettings: "收款设置",
    becomeHost: "成为主播",
    apply: "立即申请",
    applicationSent: "申请已发送!",
    applicationDesc: "我们将审核您的申请并在2-3个工作日内回复。",
  },
  errors: {
    network: "网络错误，请检查您的连接。",
    server: "服务器错误，请稍后重试。",
    unauthorized: "会话已过期，请重新登录。",
    notFound: "未找到请求的资源。",
    insufficientCoins: "金币不足，请充值。",
    callFailed: "通话无法连接，请重试。",
    permissionDenied: "权限被拒绝。",
    generic: "出现错误，请重试。",
  },

  tabs: {
    home: "首页",
    listener: "倾听者",
    random: "随机",
    chat: "聊天",
    calling: "通话",
  },

  listener: {
    allListeners: "所有倾听者",
    language: "语言",
    talkAbout: "想聊什么",
    selectLanguage: "选择语言",
    noListenersFound: "未找到倾听者",
    failedLoad: "加载倾听者失败。",
    available: "可用",
    offline: "离线",
    audio: "语音",
    video: "视频",
    perMin: "/分钟",
    hrs: "小时",
  },

  onboarding: {
    find: "发现",
    findDesc: "你可以与世界各地的人建立联系\n进行聊天、发消息\n并与他们建立连接。",
    chat: "聊天",
    chatDesc: "与陌生人聊天，\n更好地了解彼此，\n建立良好的默契。",
    videoCall: "视频通话",
    videoCallDesc: "你可以与你的朋友和联系人\n分享你的视频和照片。",
  },

  hostsScreen: {
    allHosts: "全部主播",
    failedLoad: "无法加载主播，下拉刷新。",
  },

  reviews: {
    failedLoad: "无法加载评价。",
    reviewsCount: "{count} 条评价",
    noReviews: "暂无评价",
    beFirst: "成为第一个评价的人",
    user: "用户",
    today: "今天",
    yesterday: "昨天",
    daysAgo: "{count} 天前",
    weekAgo: "{count} 周前",
    weeksAgo: "{count} 周前",
    monthAgo: "{count} 个月前",
    monthsAgo: "{count} 个月前",
  },

  notFound: {
    title: "哎呀！",
    message: "此页面不存在。",
    goHome: "前往主页！",
  },

  aboutScreen: {
    title: "关于 VoxLink",
    appTagline: "语音和视频连接",
    version: "版本 {version}",
    statActiveUsers: "活跃用户",
    statHosts: "主播",
    statCallsMade: "通话次数",
    statAppRating: "应用评分",
    whatIsTitle: "什么是 VoxLink？",
    whatIsBody1: "VoxLink 是一个社交语音和视频通话平台，将用户与经过验证的主播连接，进行有意义的对话。无论你需要人生建议、语言练习、情感支持，还是只想找人聊聊——我们的主播都在这里为你服务。",
    whatIsBody2: "主播都是经过我们团队审核的真实、受训人员。每次通话都安全、私密，并由我们基于金币的支付系统支持——你只需为使用的时间付费。",
    keyFeatures: "主要功能",
    feature1: "高清音视频通话",
    feature2: "端到端加密",
    feature3: "1,200+ 位认证主播",
    feature4: "基于金币的公平定价",
    feature5: "应用内聊天",
    feature6: "评分评价系统",
    connectWithUs: "联系我们",
    linkWebsite: "网站",
    linkTwitter: "Twitter / X",
    linkInstagram: "Instagram",
    linkContact: "联系我们",
    helpCenter: "帮助中心",
    copyright: "© 2026 VoxLink Inc. 保留所有权利。",
  },

  privacyScreen: {
    bannerTitle: "您的隐私很重要",
    bannerSub: "本政策说明 VoxLink 如何收集、使用和保护您的数据。",
    lastUpdated: "最后更新：2026 年 3 月 1 日",
    contactTitle: "关于隐私有疑问？",
    s1Title: "1. 我们收集的信息",
    s1Body: "我们收集您直接提供给我们的信息，例如当您创建账户、更新资料、进行购买或联系我们寻求支持时。这包括您的姓名、电子邮件地址、用户名、头像和支付信息。\n\n当您使用 VoxLink 时，我们还会自动收集信息，包括日志数据、设备信息、位置信息（如获许可）以及使用数据，例如您使用的功能和通话所花费的时间。",
    s2Title: "2. 我们如何使用您的信息",
    s2Body: "我们使用收集的信息来提供、维护和改进我们的服务，处理交易并发送相关信息，发送通知、技术通告、更新和支持消息。\n\n我们还使用您的数据来回应您的评论、问题和请求，监测和分析趋势与使用情况，检测、调查和防止欺诈交易及其他非法活动。",
    s3Title: "3. 信息共享",
    s3Body: "除本政策所述情况外，我们不会与第三方共享您的个人信息。我们可能会与需要访问此类信息以代表我们开展工作的供应商、顾问和其他服务提供商共享信息。\n\n如果我们认为披露符合或受到任何适用法律或法律程序的要求，包括公共机构为满足国家安全或执法要求而提出的合法请求，我们可能会披露您的信息。",
    s4Title: "4. 通话数据与音频",
    s4Body: "音视频通话内容通过加密通道传输。除非您明确启用录制功能（如可用），否则我们不会录制或存储您的通话内容。通话元数据（时长、参与者、时间戳）会被存储以提供计费和历史记录功能。",
    s5Title: "5. 金币与支付",
    s5Body: "支付信息通过安全的第三方支付处理商处理。我们不会在服务器上存储完整的支付卡详情。金币交易会被记录，用于会计和争议解决目的。",
    s6Title: "6. 数据安全",
    s6Body: "我们采取合理措施帮助保护有关您的信息免遭丢失、盗窃、滥用以及未经授权的访问、披露、更改和销毁。所有数据在传输过程中使用 TLS 加密，在静态存储时使用 AES-256 加密。",
    s7Title: "7. 数据保留",
    s7Body: "我们会在提供服务和实现本隐私政策所述目的所需的期限内保留个人信息，除非法律要求或允许更长的保留期。您可以随时通过设置页面请求删除您的账户及相关数据。",
    s8Title: "8. 儿童隐私",
    s8Body: "VoxLink 不面向 18 岁以下的儿童。我们不会有意收集 18 岁以下儿童的个人信息。如果我们得知收集了 18 岁以下儿童的个人信息，我们将删除该信息。",
    s9Title: "9. 您的权利",
    s9Body: "您有权随时访问、更新或删除您的个人信息。您还可以反对处理、请求数据可携性，或在处理基于同意的情况下撤回同意。要行使这些权利，请通过帮助中心联系我们。",
    s10Title: "10. 本政策的变更",
    s10Body: "我们可能会不时更新本隐私政策。我们将通过在此页面发布新政策并更新“最后更新”日期来通知您任何变更。在任何变更后您继续使用 VoxLink 即表示您接受新的隐私政策。",
  },

  helpScreen: {
    title: "帮助中心",
    bannerTitle: "需要帮助或常见问题？",
    bannerSub: "查找常见问题的答案",
    contactTitle: "遇到问题？",
    faqTitle: "常见问题",
    q1: "什么是 VoxLink？",
    a1: "VoxLink 是一个社交平台，您可以通过音视频通话与专业倾听者和主播连接。在关系、职业、人生指导等话题上获得个性化支持。",
    q2: "主播/倾听者是谁？",
    a2: "主播是经过验证的专业人士或有经验的个人，他们提供支持和交流。他们专注于各种话题，可进行音视频通话。",
    q3: "我如何拨打电话？",
    a3: "在主页浏览可用主播，点击主播卡片查看其资料，然后点击“现在聊”开始音视频通话。通话按每分钟金币计费。",
    q4: "金币是什么？",
    a4: "金币是 VoxLink 的应用内货币。您可以在钱包部分购买金币套餐，并在与主播通话时按其每分钟费率消费。",
    q5: "我的对话是私密的吗？",
    a5: "是的，所有对话都是私密且保密的。我们遵循严格的数据保护政策，不会与第三方共享个人对话详情。",
    q6: "我如何成为主播？",
    a6: "主播功能通过我们独立的 VoxLink Host 应用进行。下载 Host 应用即可申请、验证身份并开始接听通话和赚取收益。",
    q7: "如果金币用完了怎么办？",
    a7: "如果通话期间金币用完，通话将自动结束。您可以随时在钱包部分购买更多金币。",
  },

  coinHistory: {
    title: "金币记录",
    currentBalance: "当前余额",
    earned: "获得",
    spent: "消费",
    tabAll: "全部",
    tabPurchase: "购买",
    tabSpent: "消费",
    tabBonus: "奖励",
    today: "今天",
    yesterday: "昨天",
    ref: "参考:",
    noTransactions: "未找到交易记录",
    failedLoad: "加载金币记录失败。",
  },

  notificationsScreen: {
    markAllRead: "全部标为已读",
    empty: "暂无通知",
    goBack: "返回",
    markAllReadLabel: "将所有通知标记为已读",
    failedLoad: "加载通知失败。",
    failedMarkAll: "将通知标记为已读失败。",
    failedUpdate: "更新通知失败。",
  },

  searchHosts: {
    searchPlaceholder: "按姓名搜索主播...",
    topic: "话题",
    status: "状态",
    language: "语言",
    hostsFound: "找到 {count} 位主播",
    noResults: "未找到符合搜索的主播",
    talk: "聊天",
    failedLoad: "加载主播失败。",
  },

  chatScreen: {
    defaultName: "聊天",
    emptyHint: "发送消息以开始对话",
    sending: "发送中…",
    tapToRetry: "点击重试",
    a11yBack: "返回",
    a11yPhotoMessage: "图片消息",
    a11yRetry: "重新发送消息",
    a11yAttach: "添加图片",
    a11ySend: "发送消息",
    permissionTitle: "需要权限",
    permissionPhoto: "请允许访问相册以发送图片。",
    failedLoadMessages: "加载消息失败。",
    uploadFailed: "上传失败，请重试。",
    photoSendFailed: "无法发送图片，请重试。",
  },

  hostDetail: {
    notFound: "未找到主播",
    selectCallType: "选择通话类型",
    coinPerMin: "{count} 金币/分钟",
    coin: "{count} 金币",
    levelShort: "Lv.",
    languageColon: "语言 : ",
    idLabel: "ID:",
    totalCall: "总通话",
    experience: "经验",
    recent: "最近",
    chatNow: "立即聊天",
    chatLocked: "🔒 聊天",
    chatLockedTitle: "🔒 聊天已锁定",
    chatLockedMsg: "要与 {name} 聊天，您需要先给他/她打电话。通话后聊天会自动解锁！",
    chatLockedMsg2: "先拨打电话，聊天将自动解锁！",
    offlineMsg: "{name} 当前处于离线状态。",
    idCopied: "主播 ID 已复制到剪贴板。",
    reportThanks: "感谢您的举报。我们的团队将尽快审核。",
    reportSubmitted: "举报已提交",
    reportFailMsg: "无法提交举报，请重试。",
    reportFailed: "举报失败",
    failedLoad: "加载主播详情失败。",
    reportTitle: "举报 {name}",
    reportSubtitle: "您为什么要举报此主播？",
    reportInappropriate: "不当内容",
    reportHarassment: "骚扰",
    reportFakeProfile: "虚假资料",
    reportScam: "诈骗 / 欺诈",
    reportSpam: "垃圾信息",
  },

  checkout: {
    currentBalance: "当前余额",
    popular: "热门",
    online: "在线",
    autoGateway: "自动网关",
    manualUpi: "手动 UPI",
    qrUpiId: "二维码 / UPI ID",
    manualApprovalNote: "⏱ 手动支付需要管理员审批（几个小时）。验证后将添加金币。",
    promoCode: "优惠码",
    promoPlaceholder: "输入优惠码",
    remove: "移除",
    invalidPromo: "无效的优惠码",
    percentOff: "🎉 {pct}% 折扣 — 节省 {amount}",
    bonusCoinsAdded: "🎁 已添加 +{count} 奖励金币！",
    promoBonus: "优惠奖励",
    youGet: "您将获得",
    promoDiscount: "优惠折扣",
    securePayments: "支付 100% 安全加密",
    selectPackageBtn: "选择套餐",
    payViaUpi: "通过 UPI 支付 — {price} 获得 {coins} 金币",
    continuePay: "继续 — {price} 获得 {coins} 金币",
    redirecting: "正在跳转到支付...",
    submittedForReview: "支付已提交审核！",
    submitted: "已提交",
    coinsAddedToast: "已添加 {count} 金币！",
    purchaseSuccessful: "购买成功",
    paymentFailed: "支付失败，请重试。",
    paymentFailedTitle: "支付失败",
    manualUpiTitle: "手动 UPI 支付",
    autoApproved: "⚡ 自动批准！",
    coinsAdded: "金币已添加！",
    paymentSubmitted: "支付已提交！",
    autoApprovedSub: "{count} 金币已即时添加到您的账户！",
    underReviewSub: "您的支付正在审核中。管理员批准后将添加金币（通常在几个小时内）。",
    package: "套餐",
    utrRef: "UTR / 参考",
    loadingPayment: "正在加载支付详情...",
    unavailable: "不可用",
    unavailableSub: "目前无法进行手动支付。请尝试其他支付方式。",
    scanQrStep: "扫描二维码或支付到 UPI ID",
    payToUpi: "支付到 UPI ID",
    account: "账户:",
    autoRotating: "🔄 自动轮换",
    enterUtrStep: "输入 UTR / 交易 ID",
    utrHint: "支付后，在您的 UPI 应用中找到 12 位 UTR 或交易参考号。",
    utrPlaceholder: "输入 UTR / 参考号",
    adminApprovalTitle: "⏱ 需要管理员审批",
    adminApprovalNote: "手动支付由我们的团队验证。批准后将在几个小时内入账金币。请确保支付准确金额。",
    submitProof: "提交支付凭证",
    utrRequiredMsg: "请输入 UTR / 交易参考号。",
    submissionFailed: "提交失败",
    submissionFailedMsg: "无法提交支付，请重试。",
    coinPack: "金币包",
    upiQrPayment: "UPI / 二维码支付",
    notAvailable: "不可用",
    manualUnavailable: "手动 UPI 支付当前不可用。请尝试其他支付方式。",
    retry: "重试",
    instantApproval: "即时批准",
    coinsAddedWallet: "{count} 金币已添加到您的钱包！",
    beingReviewed: "您的支付正在审核中。金币将在几个小时内入账。",
    amount: "金额",
    status: "状态",
    approved: "已批准",
    pendingReview: "待审核",
    scanQrPay: "扫描二维码并支付",
    qrNotAvailable: "二维码不可用",
    upiId: "UPI ID",
    copy: "复制",
    payExactly: "请准确支付 {amount} 到此 UPI ID",
    utrHintHistory: "支付后，在您的 UPI 应用支付历史中找到 12 位 UTR 或交易参考号。",
    utrExample: "例如 412345678901",
    whereUtr: "在哪里找到 UTR？",
    whereUtrText: "打开您的 UPI 应用（PhonePe / GPay / Paytm）→ 交易历史 → 点击该笔支付 → 复制“UTR”或“参考 ID”",
    verifyNote: "金币将在管理员验证后添加（通常在几个小时内）。请确保支付准确金额。",
    submitPayment: "提交支付",
    enterUtrContinue: "输入 UTR 以继续",
    utrRequiredMsg2: "请输入 UTR / 交易参考号",
    utrTooShort: "UTR 至少应为 6 个字符",
    invalidUtr: "无效的 UTR",
    planMissing: "缺少套餐信息。请返回并重试。",
    submissionFailedShort: "提交失败，请重试。",
  },

  successScreen: {
    title: "支付成功！",
    subtitle: "金币已添加到您的钱包",
    note: "您现在可以使用金币与主播通话",
    findHost: "寻找主播开始聊天",
    viewWallet: "查看钱包",
  },

  editProfile: {
    updated: "您的资料已更新。",
    savedTitle: "资料已保存",
    saveFailedMsg: "无法保存您的资料，请重试。",
    saveFailed: "保存失败",
    permissionTitle: "需要权限",
    permissionMsg: "请允许访问您的相册以更换头像。",
    uploadFailed: "上传失败",
    uploadFailedMsg: "无法上传头像，请重试。",
    displayName: "显示名称",
    namePlaceholder: "您的姓名",
    bioPlaceholder: "向他人介绍一下自己...",
    saveChanges: "保存更改",
  },

  referralScreen: {
    title: "推荐有奖",
    heroTitle: "邀请好友，赚取金币！",
    heroSub: "每有一位好友使用您的代码加入 VoxLink，您的好友将获得 {newUser} 奖励金币，您可赚取 {referrer} 金币！",
    yourCode: "您的推荐码",
    shareWithFriends: "分享给好友",
    yourStats: "您的推荐统计",
    friendsInvited: "已邀请好友",
    coinsEarned: "已赚取金币",
    howItWorks: "运作方式",
    step1: "与好友分享您专属的推荐码",
    step2: "好友使用您的代码注册并获得 {count} 金币",
    step3Instant: "您立即赚取 {reward} 金币！",
    step3OneCall: "当他们完成 1 次通话后，您将赚取 {reward} 金币！",
    step3Calls: "当他们完成 {count} 次通话后，您将赚取 {reward} 金币！",
    failedLoad: "加载推荐信息失败。",
    codeCopied: "推荐码已复制！",
    copyFailed: "无法复制代码，请重试。",
    shareTitle: "加入 VoxLink",
    shareMessage: "加入 VoxLink，与出色的主播进行音视频通话！\n\n使用我的推荐码：{code}，注册即可获得奖励金币！\n\n立即下载：https://voxlink.app",
  },

  splash: {
    tagline: "连接并建立有意义的关系",
  },

  dailyReward: {
    title: "每日奖励",
    titleClaimed: "奖励已领取！",
    dayOfStreak: "连续签到第 {day} 天",
    streakUnlocked: "已解锁第 {day} 天连续签到",
    claimHint: "今天领取以保持你的连续签到。",
    dayBonus: "第 {day} 天奖励：+{count} 额外金币！",
    claim: "领取 {count} 金币",
    claiming: "领取中…",
    later: "稍后",
    awesome: "太棒了！",
    addedToWallet: "已添加到你的钱包",
    baseMilestone: "{base} 基础 + {bonus} 里程碑奖励",
    newBalance: "新余额",
    coins: "金币",
    freeMinutes: "+{count} 免费通话分钟！",
    monthlyChest: "月度宝箱：+{count} 金币！",
    comebackBonus: "回归奖励：+{count} 金币",
    spinning: "转动中…",
    luckyWheel: "幸运转盘",
    lucky: "幸运！",
    scheduleLabel: "连续签到日程",
    nextMilestone: "距离第 {day} 天奖励还有 {count} 天",
    nextMilestonePlural: "距离第 {day} 天奖励还有 {count} 天",
    missedDay: "你错过了一天！",
    restoreWithSaver: "使用免费连签保护卡恢复你的 {streak} 天连签（剩余 {count} 张）。",
    restoreWithCoins: "用 {count} 金币恢复你的 {streak} 天连签。",
    restoring: "恢复中…",
    useStreakSaver: "使用连签保护卡",
    restoreForCoins: "用 {count} 金币恢复",
    atRiskCountdown: "尽快领取——你的连签将在 {time} 后重置！",
    atRisk: "尽快领取——你的连签将在午夜重置！",
  },
};

export default zh;
