// VoxLink — Chinese (Simplified) Strings

const zh = {
  common: {
    ok: "确定",
    cancel: "取消",
    confirm: "确认",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    done: "完成",
    back: "返回",
    close: "关闭",
    loading: "加载中...",
    error: "出现错误",
    retry: "重试",
    submit: "提交",
    next: "下一步",
    skip: "跳过",
    yes: "是",
    no: "否",
    search: "搜索",
    filter: "筛选",
    clear: "清除",
    apply: "应用",
    share: "分享",
    copy: "复制",
    copied: "已复制!",
    noResults: "未找到结果",
    optional: "可选",
    required: "必填",
    all: "全部",
    more: "更多",
    less: "收起",
    seeAll: "查看全部",
    noData: "暂无数据",
    refresh: "刷新",
  },
  auth: {
    login: "登录",
    register: "注册",
    logout: "退出登录",
    email: "邮箱",
    password: "密码",
    confirmPassword: "确认密码",
    forgotPassword: "忘记密码?",
    newPassword: "新密码",
    phone: "手机号码",
    otp: "验证码",
    sendOtp: "发送OTP",
    verifyOtp: "验证OTP",
    resendOtp: "重新发送OTP",
    fullName: "全名",
    createAccount: "创建账户",
    alreadyHaveAccount: "已有账户?",
    dontHaveAccount: "没有账户?",
    welcomeBack: "欢迎回来!",
    loginToContinue: "登录以继续",
    createYourAccount: "创建您的账户",
    joinVoxLink: "今天加入VoxLink",
    enterOtp: "输入发送至的OTP",
    passwordResetSent: "密码重置邮件已发送",
    checkEmail: "请查收邮件获取说明",
    passwordChanged: "密码修改成功",
    invalidCredentials: "邮箱或密码无效",
    accountDeleted: "账户已成功删除",
    deleteAccountConfirm: "您确定要删除账户吗？此操作无法撤销。",
    tagline: "连接。畅聊。成长。",
    welcomeToVoxLink: "欢迎来到 VoxLink",
    autoCreateAccount: "新用户？首次登录时我们会自动为您创建账户",
    continueWithGoogle: "使用 Google 继续",
    signingIn: "正在登录...",
    or: "或",
    quickLogin: "快速登录",
    pleaseWait: "请稍候...",
    quickLoginNote: "快速登录会将您的账户保存到此设备——重新安装后仍归您所有",
    welcomeName: "欢迎，{name}！",
    welcomeBackToast: "欢迎回来！",
    quickLoginTitle: "快速登录",
    accountCreated: "账户已创建！欢迎来到 VoxLink。",
    welcomeTitle: "欢迎",
    connectionError: "无网络连接。请检查您的网络。",
    connectionErrorTitle: "连接错误",
    quickLoginFailed: "快速登录失败。请重试。",
  },
  nav: {
    home: "首页",
    search: "搜索",
    messages: "消息",
    wallet: "钱包",
    profile: "我的",
    notifications: "通知",
  },
  home: {
    greeting: "你好",
    findHosts: "查找主播",
    topListeners: "顶级倾听者",
    trending: "热门",
    newHosts: "新主播",
    onlineNow: "当前在线",
    featuredHosts: "精选主播",
    seeAll: "查看全部",
    searchPlaceholder: "搜索主播、话题...",
    findMore: "发现更多",
    findMoreSub: "立即与随机倾听者连接",
    startRandomCall: "开始随机通话",
    welcome: "欢迎",
    freeMinutesTitle: "{count} 分钟免费通话可用！",
    freeMinutesSub: "您的前 {count} 分钟由我们承担——与任意主播开始通话。",
    lowOnCoins: "金币不足（剩余 {count}）",
    lowOnCoinsSub: "立即充值，以免通话中途被中断。",
    topUp: "充值",
    yourFavorites: "您的收藏",
    viewAll: "查看全部",
    recommendedForYou: "为您推荐",
    browseByTopic: "按话题浏览",
    availableNow: "现在可用",
    online: "在线",
    noListenersAvailable: "暂时没有可用的倾听者",
    offlineListeners: "离线倾听者",
  },

  // Random Match
  random: {
    title: "随机匹配",
    randomMatch: "🎲 随机匹配",
    cancel: "取消",
    voiceCall: "语音通话",
    videoCall: "视频通话",
    findingMatch: "正在为您匹配…",
    listenersOnline: "{count} 位听众在线",
    listenerOnline: "{count} 位听众在线",
    chooseCallType: "选择通话类型",
    matchFound: "匹配成功! 🎉",
    accept: "接受",
    decline: "拒绝",
    skipNext: "跳过 / 下一个",
    checking: "正在检查…",
    filters: "筛选",
    matchFilters: "匹配筛选",
    gender: "性别",
    genderAny: "不限",
    genderMale: "男性",
    genderFemale: "女性",
    minimumRating: "最低评分",
    ratingAny: "不限评分",
    rating3: "3★ +",
    rating4: "4★ +",
    rating4_5: "4.5★ +",
    reset: "重置",
    done: "完成",
    myBalance: "我的余额",
    needCoins: "您至少需要 {count} 金币才能开始此通话。",
    statusInsufficientCoins: "金币不足,无法发起随机通话。",
    statusNotEnoughCoinsTitle: "金币不足",
    statusRateLimited: "稍等片刻,然后再试…",
    statusDailyLimit: "您已达到今日的随机匹配上限。",
    statusDeclineCooldown: "拒绝次数过多 — 请稍作休息。",
    statusNoMatchFilters: "没有主播符合筛选条件 — 请放宽条件。",
    statusSearching: "正在在线听众中匹配…",
    statusNoneOnline: "目前没有听众在线 — 仍在匹配中…",
    statusGiveUp: "暂时没有可用主播。请稍后再试。",
    statusNetworkError: "网络错误,正在重试…",
    statusServerUnreachable: "无法连接服务器,请重试。",
    hostBusy: "主播正忙 — 正在寻找其他匹配。",
    hostOffline: "主播已下线 — 正在寻找其他匹配。",
    hostUnavailable: "主播不可用 — 正在寻找其他匹配。",
    failedLoadHosts: "加载可用主播失败。",
  },
  hosts: {
    host: "主播",
    listener: "倾听者",
    online: "在线",
    offline: "离线",
    busy: "忙碌",
    rating: "评分",
    reviews: "评价",
    review: "评价",
    coinsPerMinute: "金币/分钟",
    totalMinutes: "累计分钟",
    specialties: "专长",
    languages: "语言",
    about: "关于",
    callNow: "立即通话",
    audioCall: "语音通话",
    videoCall: "视频通话",
    sendMessage: "发送消息",
    talkNow: "现在聊",
    noHostsFound: "未找到主播",
    adjustFilters: "请调整筛选条件",
    topRated: "评分最高",
    viewProfile: "查看资料",
    startCall: "开始通话",
  },
  calls: {
    incoming: "来电",
    outgoing: "连接中...",
    ongoing: "通话中",
    ended: "通话结束",
    audio: "语音通话",
    video: "视频通话",
    accept: "接受",
    decline: "拒绝",
    endCall: "结束通话",
    mute: "静音",
    unmute: "取消静音",
    speaker: "扬声器",
    flipCamera: "翻转摄像头",
    callDuration: "通话时长",
    callWith: "通话对象",
    rateCall: "评价此通话",
    callHistory: "通话记录",
    noCallHistory: "暂无通话记录",
    callCost: "通话费用",
    perMinute: "每分钟",
    lowBalance: "金币余额不足",
    lowBalanceMsg: "您的金币不足，请充值继续。",
    callEnded: "通话结束",
    callEndedMsg: "您的通话已结束",
    missed: "未接",
    answered: "已接",
    rejected: "已拒绝",
    callingHistory: "通话历史",
    audioShort: "语音",
    videoShort: "视频",
    incomingVideo: "视频来电",
    incomingAudio: "语音来电",
    unknown: "未知",
    voxlinkHost: "VoxLink 主播",
    voxlinkUser: "VoxLink 用户",
    voiceCall: "语音通话",
    callDeclined: "通话已拒绝",
    noAnswer: "无应答",
    ringing: "响铃中",
    connecting: "连接中",
    coinsPerMin: "金币 / 分钟",
    oneMinMinimum: "最低 1 分钟",
    callAutoEnded: "通话已自动结束",
    autoDisconnected: "您的金币已用完——通话已自动断开",
    with: "与",
    minBilling: "已应用最低 1 分钟计费",
    duration: "时长",
    coinsSpent: "已花费金币",
    rateName: "为 {name} 评分",
    feedbackHelps: "您的反馈有助于主播改进",
    ratingPoor: "差",
    ratingFair: "一般",
    ratingGood: "好",
    ratingGreat: "很好",
    ratingExcellent: "非常棒！",
    submitRating: "提交评分",
    thankYou: "谢谢！🙏",
    ratingSubmitted: "您的评分已提交",
    rechargeCoins: "充值金币",
    backHome: "返回首页",
    rateFailed: "提交评分失败，请重试。",
    errorTitle: "错误",
    completed: "已完成",
    cancelled: "已取消",
    noCallHistoryFound: "未找到通话历史",
    failedLoadHistory: "加载通话历史失败。",
    micAccessNeeded: "需要麦克风权限——点击修复",
    coinsRunningLow: "金币即将用完",
    secondsRemaining: "剩余 {count} 秒",
    minLeft: "剩余 {count} 分钟",
    ringingDots: "响铃中...",
    connectingDots: "连接中...",
    connected: "已连接",
    networkDrop: "网络中断——正在重新连接...",
    connectionFailed: "连接失败——正在重试...",
    callEndedShort: "通话已结束",
    mutedHint: "🔇 已静音",
    speakerOn: "扬声器已开",
    runningOutCoins: "金币即将用完！",
    autoDisconnectIn: "通话将在 {time} 后自动断开",
    second: "秒",
    seconds: "秒",
    fewSeconds: "几秒",
    rechargeNow: "立即充值",
    continueCall: "继续通话",
    cameraOff: "摄像头关闭",
    cameraUnavailable: "摄像头不可用",
    startingCamera: "正在启动摄像头…",
    noPermission: "无权限",
    cameraOffShort: "摄像头关闭",
    you: "你",
    mutedLabel: "已静音",
    noMic: "无麦克风",
    lowCoins: "金币不足",
    secondsLeft: "剩余 {count} 秒",
    connectionIssue: "连接问题",
    live: "直播",
    waitingResponse: "等待应答...",
    camera: "摄像头",
    camOff: "关摄像头",
    end: "结束",
    flip: "翻转",
    earpiece: "听筒",
  },
  chat: {
    messages: "消息",
    newMessage: "新消息",
    typeMessage: "输入消息...",
    send: "发送",
    noMessages: "暂无消息",
    startConversation: "开始对话",
    online: "在线",
    offline: "离线",
    typing: "正在输入...",
    delivered: "已送达",
    read: "已读",
    deleteChat: "删除聊天",
    deleteChatConfirm: "确定要删除此对话吗?",
    chats: "聊天",
    searchConversations: "搜索对话...",
    noConversationsFound: "未找到对话",
    noConversationsYet: "暂无对话",
    tryDifferentName: "尝试其他名称",
    startChattingAfterCall: "与主播通话后开始聊天",
  },
  wallet: {
    wallet: "钱包",
    coinBalance: "金币余额",
    coins: "金币",
    coin: "金币",
    buyCoins: "购买金币",
    coinHistory: "金币记录",
    transactions: "交易记录",
    noTransactions: "暂无交易记录",
    purchased: "已购买",
    spent: "已消费",
    bonus: "奖励",
    refunded: "已退款",
    withdrawal: "提现",
    totalSpent: "总消费",
    totalPurchased: "总购买",
    popular: "最受欢迎",
    bestValue: "最超值",
    bonus_label: "奖励",
    recharge: "充值",
    choosePackage: "选择套餐",
    instantDelivery: "即时到账",
    securePayment: "安全支付",
    guaranteed: "满意保证",
  },
  profile: {
    profile: "我的",
    editProfile: "编辑资料",
    myProfile: "我的资料",
    name: "姓名",
    email: "邮箱",
    phone: "手机号",
    gender: "性别",
    male: "男",
    female: "女",
    other: "其他",
    country: "国家",
    bio: "个人简介",
    language: "语言",
    settings: "设置",
    helpCenter: "帮助中心",
    privacy: "隐私政策",
    about: "关于VoxLink",
    shareApp: "分享VoxLink",
    rateApp: "给应用评分",
    logout: "退出登录",
    deleteAccount: "删除账户",
    callHistory: "通话记录",
    joinedOn: "加入于",
    totalCalls: "总通话次数",
    hoursSpent: "花费时间",
  },
  settings: {
    settings: "设置",
    notifications: "通知",
    callNotifications: "来电通知",
    messageNotifications: "消息通知",
    promoNotifications: "推广通知",
    language: "语言",
    theme: "主题",
    lightMode: "浅色模式",
    darkMode: "深色模式",
    systemDefault: "跟随系统",
    privacy: "隐私",
    security: "安全",
    changePassword: "修改密码",
    twoFactor: "双重验证",
    account: "账户",
    support: "支持",
  },
  payment: {
    checkout: "结账",
    selectPackage: "选择套餐",
    paymentMethod: "支付方式",
    creditCard: "信用卡/借记卡",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "支付处理中...",
    paymentSuccess: "支付成功!",
    paymentFailed: "支付失败",
    orderSummary: "订单摘要",
    total: "合计",
    coins: "金币",
    bonusCoins: "奖励金币",
    tryAgain: "重试",
    secureNote: "所有支付均已加密保护",
  },
  host: {
    dashboard: "仪表盘",
    totalEarnings: "总收益",
    thisWeek: "本周",
    thisMonth: "本月",
    totalCalls: "总通话数",
    avgRating: "平均评分",
    onlineStatus: "在线状态",
    goOnline: "上线",
    goOffline: "下线",
    setBusy: "设为忙碌",
    earnings: "收益",
    withdraw: "提现",
    withdrawal: "提现",
    minimumWithdraw: "最低100金币",
    enterAmount: "输入金额",
    withdrawMethod: "提现方式",
    bankTransfer: "银行转账",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "账户详情",
    withdrawSuccess: "提现申请已提交",
    withdrawPending: "您的申请正在处理中",
    hostSettings: "主播设置",
    availability: "可用状态",
    payoutSettings: "收款设置",
    becomeHost: "成为主播",
    apply: "立即申请",
    applicationSent: "申请已发送!",
    applicationDesc: "我们将审核您的申请并在2-3个工作日内回复。",
  },
  errors: {
    network: "网络错误，请检查您的连接。",
    server: "服务器错误，请稍后重试。",
    unauthorized: "会话已过期，请重新登录。",
    notFound: "未找到请求的资源。",
    insufficientCoins: "金币不足，请充值。",
    callFailed: "通话无法连接，请重试。",
    permissionDenied: "权限被拒绝。",
    generic: "出现错误，请重试。",
  },

  tabs: {
    home: "首页",
    listener: "倾听者",
    random: "随机",
    chat: "聊天",
    calling: "通话",
  },

  listener: {
    allListeners: "所有倾听者",
    language: "语言",
    talkAbout: "想聊什么",
    selectLanguage: "选择语言",
    noListenersFound: "未找到倾听者",
    failedLoad: "加载倾听者失败。",
    available: "可用",
    offline: "离线",
    audio: "语音",
    video: "视频",
    perMin: "/分钟",
    hrs: "小时",
  },

  onboarding: {
    find: "发现",
    findDesc: "你可以与世界各地的人建立联系\n进行聊天、发消息\n并与他们建立连接。",
    chat: "聊天",
    chatDesc: "与陌生人聊天，\n更好地了解彼此，\n建立良好的默契。",
    videoCall: "视频通话",
    videoCallDesc: "你可以与你的朋友和联系人\n分享你的视频和照片。",
  },

  hostsScreen: {
    allHosts: "全部主播",
    failedLoad: "无法加载主播，下拉刷新。",
  },

  reviews: {
    failedLoad: "无法加载评价。",
    reviewsCount: "{count} 条评价",
    noReviews: "暂无评价",
    beFirst: "成为第一个评价的人",
    user: "用户",
    today: "今天",
    yesterday: "昨天",
    daysAgo: "{count} 天前",
    weekAgo: "{count} 周前",
    weeksAgo: "{count} 周前",
    monthAgo: "{count} 个月前",
    monthsAgo: "{count} 个月前",
  },
};

export default zh;
