// VoxLink — Arabic Strings

const ar = {
  common: {
    ok: "موافق",
    cancel: "إلغاء",
    confirm: "تأكيد",
    save: "حفظ",
    delete: "حذف",
    edit: "تعديل",
    done: "تم",
    back: "رجوع",
    close: "إغلاق",
    loading: "جاري التحميل...",
    error: "حدث خطأ",
    retry: "حاول مجددًا",
    submit: "إرسال",
    next: "التالي",
    skip: "تخطي",
    yes: "نعم",
    no: "لا",
    search: "بحث",
    filter: "تصفية",
    clear: "مسح",
    apply: "تطبيق",
    share: "مشاركة",
    copy: "نسخ",
    copied: "تم النسخ!",
    noResults: "لا توجد نتائج",
    optional: "اختياري",
    required: "مطلوب",
    all: "الكل",
    more: "المزيد",
    less: "أقل",
    seeAll: "عرض الكل",
    noData: "لا توجد بيانات",
    refresh: "تحديث",
  },
  auth: {
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    newPassword: "كلمة مرور جديدة",
    phone: "رقم الهاتف",
    otp: "رمز التحقق",
    sendOtp: "إرسال OTP",
    verifyOtp: "التحقق من OTP",
    resendOtp: "إعادة إرسال OTP",
    fullName: "الاسم الكامل",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    welcomeBack: "مرحبًا بعودتك!",
    loginToContinue: "سجّل الدخول للمتابعة",
    createYourAccount: "أنشئ حسابك",
    joinVoxLink: "انضم إلى VoxLink اليوم",
    enterOtp: "أدخل رمز OTP المُرسَل إلى",
    passwordResetSent: "تم إرسال بريد إعادة تعيين كلمة المرور",
    checkEmail: "تحقق من بريدك الإلكتروني للتعليمات",
    passwordChanged: "تم تغيير كلمة المرور بنجاح",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    accountDeleted: "تم حذف الحساب بنجاح",
    deleteAccountConfirm: "هل أنت متأكد من أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.",
  },
  nav: {
    home: "الرئيسية",
    search: "بحث",
    messages: "الرسائل",
    wallet: "المحفظة",
    profile: "الملف الشخصي",
    notifications: "الإشعارات",
  },
  home: {
    greeting: "مرحبًا",
    findHosts: "ابحث عن مضيف",
    topListeners: "أبرز المستمعين",
    trending: "الأكثر رواجًا",
    newHosts: "مضيفون جدد",
    onlineNow: "متصل الآن",
    featuredHosts: "مضيفون مميزون",
    seeAll: "عرض الكل",
    searchPlaceholder: "ابحث عن مضيفين ومواضيع...",
  },
  hosts: {
    host: "مضيف",
    listener: "مستمع",
    online: "متصل",
    offline: "غير متصل",
    busy: "مشغول",
    rating: "التقييم",
    reviews: "التقييمات",
    review: "تقييم",
    coinsPerMinute: "عملة/دقيقة",
    totalMinutes: "إجمالي الدقائق",
    specialties: "التخصصات",
    languages: "اللغات",
    about: "عن",
    callNow: "اتصل الآن",
    audioCall: "مكالمة صوتية",
    videoCall: "مكالمة مرئية",
    sendMessage: "إرسال رسالة",
    talkNow: "تحدث الآن",
    noHostsFound: "لم يتم العثور على مضيفين",
    adjustFilters: "حاول تعديل الفلاتر",
    topRated: "الأعلى تقييمًا",
    viewProfile: "عرض الملف",
    startCall: "بدء المكالمة",
  },
  calls: {
    incoming: "مكالمة واردة",
    outgoing: "جاري الاتصال...",
    ongoing: "في مكالمة",
    ended: "انتهت المكالمة",
    audio: "مكالمة صوتية",
    video: "مكالمة مرئية",
    accept: "قبول",
    decline: "رفض",
    endCall: "إنهاء المكالمة",
    mute: "كتم الصوت",
    unmute: "إلغاء الكتم",
    speaker: "مكبر الصوت",
    flipCamera: "قلب الكاميرا",
    callDuration: "مدة المكالمة",
    callWith: "مكالمة مع",
    rateCall: "قيّم هذه المكالمة",
    callHistory: "سجل المكالمات",
    noCallHistory: "لا يوجد سجل مكالمات",
    callCost: "تكلفة المكالمة",
    perMinute: "في الدقيقة",
    lowBalance: "رصيد العملات منخفض",
    lowBalanceMsg: "رصيدك من العملات منخفض. أعد الشحن للمتابعة.",
    callEnded: "انتهت المكالمة",
    callEndedMsg: "انتهت مكالمتك",
    missed: "فائتة",
    answered: "مُجاب",
    rejected: "مرفوضة",
  },
  chat: {
    messages: "الرسائل",
    newMessage: "رسالة جديدة",
    typeMessage: "اكتب رسالة...",
    send: "إرسال",
    noMessages: "لا توجد رسائل بعد",
    startConversation: "ابدأ محادثة",
    online: "متصل",
    offline: "غير متصل",
    typing: "يكتب...",
    delivered: "تم التسليم",
    read: "مقروء",
    deleteChat: "حذف المحادثة",
    deleteChatConfirm: "هل أنت متأكد من حذف هذه المحادثة؟",
  },
  wallet: {
    wallet: "المحفظة",
    coinBalance: "رصيد العملات",
    coins: "عملات",
    coin: "عملة",
    buyCoins: "شراء عملات",
    coinHistory: "سجل العملات",
    transactions: "المعاملات",
    noTransactions: "لا توجد معاملات بعد",
    purchased: "مشتراة",
    spent: "مُنفَق",
    bonus: "مكافأة",
    refunded: "مسترد",
    withdrawal: "سحب",
    totalSpent: "إجمالي الإنفاق",
    totalPurchased: "إجمالي الشراء",
    popular: "الأكثر شعبية",
    bestValue: "أفضل قيمة",
    bonus_label: "مكافأة",
    recharge: "إعادة شحن",
    choosePackage: "اختر الباقة",
    instantDelivery: "تسليم فوري",
    securePayment: "دفع آمن",
    guaranteed: "ضمان الرضا",
  },
  profile: {
    profile: "الملف الشخصي",
    editProfile: "تعديل الملف",
    myProfile: "ملفي الشخصي",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    other: "آخر",
    country: "البلد",
    bio: "النبذة",
    language: "اللغة",
    settings: "الإعدادات",
    helpCenter: "مركز المساعدة",
    privacy: "سياسة الخصوصية",
    about: "عن VoxLink",
    shareApp: "مشاركة VoxLink",
    rateApp: "قيّم التطبيق",
    logout: "تسجيل الخروج",
    deleteAccount: "حذف الحساب",
    callHistory: "سجل المكالمات",
    joinedOn: "انضم في",
    totalCalls: "إجمالي المكالمات",
    hoursSpent: "الساعات المُقضاة",
  },
  settings: {
    settings: "الإعدادات",
    notifications: "الإشعارات",
    callNotifications: "إشعارات المكالمات",
    messageNotifications: "إشعارات الرسائل",
    promoNotifications: "الإشعارات الترويجية",
    language: "اللغة",
    theme: "المظهر",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    systemDefault: "افتراضي النظام",
    privacy: "الخصوصية",
    security: "الأمان",
    changePassword: "تغيير كلمة المرور",
    twoFactor: "التحقق بخطوتين",
    account: "الحساب",
    support: "الدعم",
  },
  payment: {
    checkout: "إتمام الشراء",
    selectPackage: "اختر الباقة",
    paymentMethod: "طريقة الدفع",
    creditCard: "بطاقة ائتمان/خصم",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "جاري معالجة الدفع...",
    paymentSuccess: "تمت عملية الدفع بنجاح!",
    paymentFailed: "فشلت عملية الدفع",
    orderSummary: "ملخص الطلب",
    total: "الإجمالي",
    coins: "عملات",
    bonusCoins: "عملات مكافأة",
    tryAgain: "حاول مجددًا",
    secureNote: "جميع المدفوعات مؤمّنة ومشفّرة",
  },
  host: {
    dashboard: "لوحة التحكم",
    totalEarnings: "إجمالي الأرباح",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    totalCalls: "إجمالي المكالمات",
    avgRating: "متوسط التقييم",
    onlineStatus: "حالة الاتصال",
    goOnline: "تسجيل الدخول",
    goOffline: "تسجيل الخروج",
    setBusy: "تعيين كمشغول",
    earnings: "الأرباح",
    withdraw: "سحب",
    withdrawal: "سحب الأرباح",
    minimumWithdraw: "الحد الأدنى 100 عملة",
    enterAmount: "أدخل المبلغ",
    withdrawMethod: "طريقة السحب",
    bankTransfer: "تحويل بنكي",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "تفاصيل الحساب",
    withdrawSuccess: "تم تقديم طلب السحب",
    withdrawPending: "طلبك قيد المعالجة",
    hostSettings: "إعدادات المضيف",
    availability: "التوفر",
    payoutSettings: "إعدادات الدفع",
    becomeHost: "كن مضيفًا",
    apply: "تقدّم الآن",
    applicationSent: "تم إرسال الطلب!",
    applicationDesc: "سنراجع طلبك ونتواصل معك خلال 2-3 أيام عمل.",
  },
  errors: {
    network: "خطأ في الشبكة. يرجى التحقق من اتصالك.",
    server: "خطأ في الخادم. يرجى المحاولة لاحقًا.",
    unauthorized: "انتهت الجلسة. يرجى تسجيل الدخول مجددًا.",
    notFound: "المورد المطلوب غير موجود.",
    insufficientCoins: "عملات غير كافية. يرجى إعادة الشحن.",
    callFailed: "لا يمكن الاتصال. يرجى المحاولة مجددًا.",
    permissionDenied: "تم رفض الإذن.",
    generic: "حدث خطأ ما. يرجى المحاولة مجددًا.",
  },

  tabs: {
    home: "الرئيسية",
    chat: "الدردشة",
    calls: "المكالمات",
    wallet: "المحفظة",
    profile: "الملف الشخصي",
  },

  hostSettings: {
    title: "إعدادات المضيف",
    availability: "التوفر",
    autoOnline: "الاتصال تلقائيًا عند فتح التطبيق",
    dnd: "وضع عدم الإزعاج",
    dndOn: "مفعّل — كتم الإشعارات",
    schedule: "جدول التوفر",
    randomCalls: "المكالمات العشوائية",
    availableRandom: "متاح للمكالمات العشوائية",
    randomOn: "مفعّل — مُدرج في مجموعة المطابقة العشوائية",
    randomOff: "متوقف — المكالمات المباشرة فقط",
    allowVideoRandom: "السماح بمكالمات الفيديو العشوائية",
    videoDisabled: "معطّل — المكالمات العشوائية متوقفة",
    videoOn: "مفعّل — يقبل مكالمات الفيديو العشوائية",
    videoOff: "متوقف — مكالمات صوتية عشوائية فقط",
    loading: "جارٍ التحميل…",
    pushNotifications: "الإشعارات الفورية",
    notificationPrefs: "تفضيلات الإشعارات",
    incomingCallAlerts: "تنبيهات المكالمات الواردة",
    chatNotifications: "إشعارات الدردشة",
    coinEarnedAlerts: "تنبيهات العملات المكتسبة",
    earnings: "الأرباح",
    payoutMethod: "طريقة الدفع",
    withdrawEarnings: "سحب الأرباح",
    referEarn: "أحِل واربح",
    preferences: "التفضيلات",
    appLanguage: "لغة التطبيق",
    support: "الدعم",
    helpSupport: "المساعدة والدعم",
    privacyPolicy: "سياسة الخصوصية",
    aboutApp: "حول VoxLink Host",
    account: "الحساب",
    signOut: "تسجيل الخروج",
    deleteAccount: "حذف الحساب",
    on: "مفعّل",
    off: "متوقف",
    alwaysAvailable: "متاح دائمًا",
  },

  homeScreen: {
    online: "أنت متصل",
    offline: "أنت غير متصل",
    onlineSub: "متاح لاستقبال المكالمات",
    offlineSub: "فعّل لبدء قبول المكالمات",
    totalCalls: "إجمالي المكالمات",
    totalHours: "إجمالي الساعات",
    earnings: "الأرباح",
    yourCallRates: "أسعار مكالماتك",
    ratesSub: "العملات التي يدفعها المستخدمون لك في الدقيقة",
    edit: "تعديل",
    audioPerMin: "صوت / دقيقة",
    videoPerMin: "فيديو / دقيقة",
    manage: "إدارة",
    qaCallRates: "الأسعار",
    qaCallRatesDesc: "حدد سعرك",
    qaTopics: "مواضيعي",
    qaTopicsDesc: "الوصول لمزيد من المستخدمين",
    qaEarnings: "الأرباح",
    qaEarningsDesc: "عرض السجل",
    qaPayouts: "المدفوعات",
    qaPayoutsDesc: "سحب العملات",
    qaWallet: "المحفظة",
    qaWalletDesc: "الرصيد والسحب",
    qaCallHistory: "سجل المكالمات",
    qaCallHistoryDesc: "المكالمات السابقة",
    qaRefer: "أحِل واربح",
    qaReferDesc: "ادعُ الأصدقاء",
    qaProfile: "الملف الشخصي",
    qaProfileDesc: "تعديل التفاصيل",
    qaSettings: "الإعدادات",
    qaSettingsDesc: "تفضيلات التطبيق",
    permsRequired: "الأذونات مطلوبة",
    micLabel: "الميكروفون",
    micDesc: "مطلوب للمكالمات الصوتية",
    cameraLabel: "الكاميرا",
    cameraDesc: "مطلوبة لمكالمات الفيديو",
    notifLabel: "الإشعارات",
    notifDesc: "لتنبيهات المكالمات الواردة",
    granted: "تم المنح",
    tapToAllow: "اضغط للسماح",
    hostTips: "نصائح للمضيف",
    tip1: "كن متصلاً في ساعات الذروة (6 مساءً - 10 مساءً)",
    tip2: "أكمل ملفك الشخصي لمزيد من الحجوزات",
    tip3: "رُد بسرعة لتحسين تقييمك",
    tip4: "أضف المزيد من المواضيع للوصول لمزيد من المستخدمين",
  },

  profileScreen: {
    title: "ملفي الشخصي",
    proHost: "مضيف محترف",
    calls: "المكالمات",
    rating: "التقييم",
    coins: "العملات",
    onlineStatus: "حالة الاتصال",
    pushNotifications: "الإشعارات الفورية",
    account: "الحساب",
    editProfile: "تعديل الملف الشخصي",
    callRates: "أسعار المكالمات",
    myTopics: "مواضيعي",
    settings: "الإعدادات",
    language: "اللغة",
    more: "المزيد",
    referEarn: "أحِل واربح",
    helpCenter: "مركز المساعدة",
    privacyPolicy: "سياسة الخصوصية",
    about: "حول VoxLink",
    signOut: "تسجيل الخروج",
    signOutConfirm: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
    permRequiredTitle: "الإذن مطلوب",
    permRequiredMsg: "يرجى السماح بالوصول إلى مكتبة الصور لتغيير صورة ملفك الشخصي.",
    turnOffNotifTitle: "إيقاف الإشعارات",
    turnOffNotifMsg: "لإيقاف الإشعارات، انتقل إلى إعدادات هاتفك وأوقف إشعارات VoxLink Host.",
    openSettings: "فتح الإعدادات",
    uploadFailedTitle: "فشل الرفع",
    uploadFailedMsg: "تعذّر رفع صورتك. يرجى المحاولة مجددًا.",
    photoUpdated: "تم تحديث صورة الملف الشخصي!",
    photoSaved: "تم حفظ الصورة",
  },

  callsScreen: {
    title: "سجل المكالمات",
    all: "الكل",
    audio: "صوت",
    video: "فيديو",
    completed: "مكتملة",
    missed: "فائتة",
    cancelled: "ملغاة",
    noCalls: "لا توجد مكالمات بعد",
    loadError: "تعذّر تحميل المكالمات. اسحب للتحديث.",
  },

  chatScreen: {
    title: "الرسائل",
    searchPlaceholder: "ابحث في المحادثات...",
    noConversations: "لا توجد محادثات بعد",
    noMessagesYet: "لا توجد رسائل بعد",
    now: "الآن",
  },

  walletScreen: {
    title: "محفظة المضيف",
    availableBalance: "الرصيد المتاح",
    coins: "العملات",
    payoutValue: "قيمة الدفع",
    thisWeek: "هذا الأسبوع",
    sessions: "الجلسات",
    withdrawn: "المسحوب",
    earningsHistory: "سجل الأرباح",
    withdraw: "سحب",
    noEarnings: "لا توجد أرباح بعد",
    quickSelect: "اختيار سريع للمبلغ",
    orEnter: "أو أدخل المبلغ",
    enterCoinAmount: "أدخل عدد العملات",
    payoutTo: "الدفع إلى",
    setupPayout: "قم بإعداد طريقة الدفع",
    edit: "تعديل",
    managePayout: "إدارة طريقة الدفع",
    requestWithdrawal: "طلب سحب",
    note: "ملاحظة",
    failedLoad: "فشل تحميل بيانات الأرباح.",
  },

  loginScreen: {
    tagline: "اكسب · تواصل · نمِّ جمهورك",
    chipKyc: "تم التحقق من KYC",
    chipEarn: "اكسب العملات",
    chipPlatform: "منصة المضيف",
    welcomeBack: "مرحبًا بعودتك",
    subtitle: "سجّل الدخول إلى حساب المضيف",
    emailPlaceholder: "البريد الإلكتروني",
    passwordPlaceholder: "كلمة المرور",
    signIn: "تسجيل الدخول كمضيف",
    orContinue: "أو تابع باستخدام",
    continueGoogle: "المتابعة باستخدام Google",
    signingIn: "جاري تسجيل الدخول...",
    newPrompt: "جديد على VoxLink Host؟ ",
    applyNow: "تقدّم الآن",
  },

  registerScreen: {
    stepAccount: "الحساب",
    stepProfile: "الملف الشخصي",
    stepHostInfo: "معلومات المضيف",
    stepKyc: "مستندات KYC",
    title: "كن مضيفًا",
    headerSub: "أكمل 4 خطوات لبدء الكسب",
    createTitle: "أنشئ حسابك",
    createSub: "سيكون هذا تسجيل دخولك إلى VoxLink Host",
    namePlaceholder: "الاسم الكامل",
    emailPlaceholder: "البريد الإلكتروني",
    passwordPlaceholder: "كلمة المرور (8 أحرف أو أكثر)",
    continueBtn: "متابعة",
    orSignUp: "أو سجّل باستخدام",
    continueGoogle: "المتابعة باستخدام Google",
    signingIn: "جاري تسجيل الدخول...",
    alreadyRegistered: "مسجّل بالفعل؟ ",
    signIn: "تسجيل الدخول",
  },

  authToasts: {
    missingFields: "حقول ناقصة",
    loginMissing: "يرجى إدخال البريد الإلكتروني وكلمة المرور.",
    invalidEmail: "بريد غير صالح",
    invalidEmailMsg: "يرجى إدخال بريد إلكتروني صالح.",
    loginFailed: "فشل تسجيل الدخول",
    loginFailedMsg: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    notSupported: "غير مدعوم",
    playServices: "خدمات Google Play غير متوفرة.",
    connectionError: "خطأ في الاتصال",
    noInternet: "لا يوجد اتصال بالإنترنت.",
    signInFailed: "فشل تسجيل الدخول",
    googleFailed: "فشل تسجيل الدخول عبر Google",
    almostThere: "أوشكت على الانتهاء",
    googleWelcomeHost: "مرحبًا! يرجى إكمال ملف المضيف و KYC.",
    googleWelcomeProfile: "مرحبًا! أكمل ملفك الشخصي للتقدم كمضيف.",
    signInFailedRetry: "فشل تسجيل الدخول. يرجى المحاولة مجددًا.",
    googleNoAccount: "تعذّر الحصول على معلومات حساب Google.",
    googleNoToken: "لم يُرجع تسجيل الدخول عبر Google رمزًا. يرجى تحديث التطبيق أو المحاولة مجددًا.",
    registerMissing: "يرجى ملء جميع الحقول.",
    weakPassword: "كلمة مرور ضعيفة",
    weakPasswordMsg: "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
    welcomeBack: "مرحبًا بعودتك",
    resuming: "جارٍ استئناف تسجيلك غير المكتمل.",
    alreadyRegisteredTitle: "مسجّل بالفعل",
    alreadyRegisteredMsg: "هذا البريد مسجّل بالفعل. يرجى تسجيل الدخول.",
    createFailed: "تعذّر إنشاء الحساب. يرجى المحاولة مجددًا.",
  },

  forgotPasswordScreen: {
    checkEmail: "تحقق من بريدك",
    forgotPassword: "نسيت كلمة المرور؟",
    sentLine1: "أرسلنا رمز OTP من 6 أرقام إلى",
    sentLine2: "أدخل الرمز وعيّن كلمة مرور جديدة.",
    enterEmailPrompt: "أدخل بريدك المسجّل. سنرسل رمز OTP لإعادة تعيين كلمة المرور.",
    resetPassword: "إعادة تعيين كلمة المرور",
    otpPlaceholder: "أدخل رمز OTP",
    newPasswordPlaceholder: "كلمة مرور جديدة",
    confirmPasswordPlaceholder: "تأكيد كلمة المرور الجديدة",
    resetting: "جارٍ إعادة التعيين...",
    resetBtn: "إعادة تعيين كلمة المرور",
    didntReceive: "لم تستلمه؟ ",
    resendIn: "إعادة الإرسال خلال",
    resendOtp: "إعادة إرسال OTP",
    findAccount: "ابحث عن حسابك",
    emailPlaceholder: "البريد الإلكتروني",
    sending: "جارٍ الإرسال...",
    sendOtp: "إرسال OTP",
    backTo: "العودة إلى ",
    signIn: "تسجيل الدخول",
    enterEmailError: "يرجى إدخال بريدك الإلكتروني.",
    otpSent: "تم إرسال OTP إلى بريدك.",
    emailSent: "تم إرسال البريد",
    emailNotFound: "البريد غير موجود. يرجى التحقق والمحاولة مجددًا.",
    enterOtpError: "يرجى إدخال رمز OTP المُرسَل إلى بريدك.",
    weakPassword: "كلمة مرور ضعيفة",
    weakPasswordMsg: "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
    mismatch: "غير متطابقة",
    passwordsDontMatch: "كلمتا المرور غير متطابقتين.",
    successTitle: "نجح",
    resetSuccess: "تم تحديث كلمة المرور بنجاح! يرجى تسجيل الدخول.",
    errorTitle: "خطأ",
    resetFailed: "فشل إعادة تعيين كلمة المرور. ربما انتهت صلاحية OTP.",
  },

  onboardingScreen: {
    slide1Title: "اكتشف",
    slide1Sub: "يمكنك التواصل مع أشخاص من حول\nالعالم للدردشة وإرسال الرسائل\nوإنشاء صلات معهم.",
    slide2Title: "دردش",
    slide2Sub: "دردش مع الغرباء للتعرف على بعضكم\nبشكل أفضل وبناء انسجام\nرائع.",
    slide3Title: "مكالمة فيديو",
    slide3Sub: "يمكنك مشاركة مقاطع الفيديو والصور\nمع أصدقائك وصلاتك.",
  },

  profileSetupScreen: {
    headerSub: "الخطوة 2 من 4 — ملفك الشخصي",
    sectionTitle: "معلومات ملفك الشخصي",
    sectionSub: "ستكون مرئية للمستخدمين الذين يتصلون بك",
    uploading: "جارٍ الرفع...",
    tapAddPhoto: "اضغط لإضافة صورة الملف الشخصي",
    namePlaceholder: "اسم العرض",
    dobPlaceholder: "تاريخ الميلاد (اضغط للاختيار)",
    phonePlaceholder: "رقم الجوال",
    genderLabel: "الجنس",
    continueBtn: "متابعة ← معلومات المضيف",
    done: "تم",
    dobTitle: "تاريخ الميلاد",
    day: "اليوم",
    month: "الشهر",
    year: "السنة",
    months: ["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"],
    uploadFailed: "فشل الرفع",
    uploadFailedMsg: "تعذّر رفع الصورة. يرجى المحاولة مجددًا.",
    missingFields: "حقول ناقصة",
    missingFieldsMsg: "يرجى ملء جميع الحقول المطلوبة.",
    invalidPhone: "هاتف غير صالح",
    invalidPhoneMsg: "يرجى إدخال رقم جوال صالح.",
    saveFailed: "فشل الحفظ",
    saveFailedMsg: "تعذّر حفظ ملفك الشخصي. يرجى المحاولة مجددًا.",
  },

  becomeScreen: {
    headerSub: "الخطوة 3 من 4 — معلومات المضيف",
    sectionTitle: "ملف المضيف الخاص بك",
    sectionSub: "ساعد المستخدمين على فهم ما تقدمه",
    specialtiesLabel: "التخصصات (اختر 1–5)",
    languagesLabel: "اللغات",
    bioLabel: "النبذة",
    bioPlaceholder: "أخبر المستخدمين عن نفسك — خبرتك وشخصيتك وما يميّز مكالماتك...",
    experienceLabel: "الخبرة (اختياري)",
    experiencePlaceholder: "مثال: 3 سنوات كمدرب حياة",
    callTypeLabel: "نوع المكالمة المقدّمة",
    audioOnly: "🎤 صوت فقط",
    videoOnly: "🎥 فيديو فقط",
    both: "🎤🎥 كلاهما",
    ratesLabel: "أسعار مكالماتك (عملة/دقيقة)",
    audio: "صوت",
    video: "فيديو",
    coinsPerMin: "عملة/دقيقة",
    note: "الأسعار مجرد اقتراحات. قد يعدّلها المشرف بعد الموافقة.",
    continueBtn: "متابعة ←  مستندات KYC",
    selectSpecialty: "اختر تخصصًا",
    chooseSpecialty: "اختر تخصصًا واحدًا على الأقل.",
    bioTooShort: "النبذة قصيرة جدًا",
    bioTooShortMsg: "يرجى كتابة نبذة من 20 حرفًا على الأقل.",
  },

  kycScreen: {
    headerSub: "الخطوة 4 من 4 — مستندات KYC",
    sectionTitle: "التحقق من الهوية",
    sectionSub: "مطلوب لبدء الاستضافة. يتم تخزين مستنداتك بأمان.",
    notice: "KYC إلزامي وفقًا للوائح الهندية. تتم مراجعة المستندات من قبل المشرف فقط ولا تُشارك أبدًا مع المستخدمين.",
    dobLabel: "تاريخ الميلاد",
    fromStep2: "من الخطوة 2",
    dobPlaceholder: "يوم/شهر/سنة (مثال 22/05/1998)",
    docAadharFront: "وجه آدهار الأمامي",
    docAadharFrontSub: "صورة الوجه الأمامي لبطاقة آدهار",
    docAadharBack: "وجه آدهار الخلفي",
    docAadharBackSub: "صورة الوجه الخلفي لبطاقة آدهار",
    docVideo: "فيديو التحقق",
    docVideoSub: "فيديو قصير (5–15 ثانية) لك وأنت تحمل بطاقة آدهار",
    uploading: "جارٍ الرفع...",
    uploaded: "تم الرفع ✓",
    tipsTitle: "نصائح للموافقة",
    tip1: "تأكد من أن صور آدهار واضحة وغير ضبابية",
    tip2: "أمسك بطاقة آدهار بوضوح في فيديو التحقق",
    tip3: "انظر إلى الكاميرا أثناء التسجيل",
    submitting: "جارٍ الإرسال...",
    submit: "إرسال الطلب",
    uploadFailed: "فشل الرفع",
    uploadFailedMsg: "تعذّر رفع الملف. يرجى المحاولة مجددًا.",
    missingDocs: "مستندات ناقصة",
    missingDocsMsg: "يرجى رفع صورتي وجه آدهار الأمامي والخلفي.",
    missingDob: "تاريخ الميلاد مفقود",
    missingDobMsg: "تاريخ الميلاد مفقود. يرجى العودة إلى الخطوة 2 واختيار تاريخ ميلادك.",
    submitFailed: "فشل الإرسال",
    submitFailedMsg: "تعذّر إرسال طلبك. يرجى المحاولة مجددًا.",
  },

  statusScreen: {
    headerTitle: "طلب المضيف",
    headerSub: "تتبّع حالة التحقق من KYC",
    checking: "جارٍ التحقق من حالة الطلب...",
    pendingTitle: "تم إرسال الطلب",
    pendingMsg: "طلبك في قائمة الانتظار. سيراجعه فريقنا خلال 24–48 ساعة.",
    underReviewTitle: "قيد المراجعة",
    underReviewMsg: "فريقنا يراجع طلبك بنشاط. ستتلقى ردًا قريبًا.",
    approvedTitle: "تهانينا!",
    approvedMsg: "تمت الموافقة على طلبك! أنت الآن مضيف موثّق على VoxLink.",
    rejectedTitle: "تم رفض الطلب",
    rejectedMsg: "للأسف، لم تتم الموافقة على طلبك. يرجى الاطلاع على السبب أدناه وإعادة التقديم.",
    notAppliedTitle: "لم يُعثر على طلب",
    notAppliedMsg: "لم ترسل طلب مضيف بعد.",
    approvedSub: "أنت الآن مضيف موثّق على VoxLink. ابدأ بقبول المكالمات وكسب العملات!",
    earnCoins: "اكسب العملات",
    buildRating: "ابنِ تقييمك",
    takeCalls: "استقبل المكالمات",
    timelineTitle: "الجدول الزمني للطلب",
    tlAccount: "تم إنشاء الحساب",
    tlSubmitted: "تم إرسال الطلب",
    tlReview: "قيد المراجعة",
    tlDecision: "تم اتخاذ القرار",
    continueDashboard: "المتابعة إلى لوحة التحكم",
    reasonRejection: "سبب الرفض",
    reapply: "إعادة التقديم",
    startApplication: "بدء الطلب",
    autoChecking: "يتم التحقق تلقائيًا كل 10 ثوانٍ...",
    loadError: "فشل تحميل حالة الطلب.",
  },

  audioCallScreen: {
    voiceCall: "مكالمة صوتية",
    ringing: "يرن...",
    connecting: "جاري الاتصال...",
    connected: "متصل",
    reconnecting: "انقطاع الشبكة — إعادة الاتصال...",
    connFailed: "فشل الاتصال — إعادة المحاولة...",
    callEnded: "انتهت المكالمة",
    unknown: "غير معروف",
    muted: "🔇 مكتوم",
    coinsPerMin: "عملة / دقيقة",
    remaining: "متبقٍ",
    minLeft: "دقيقة متبقية",
    callEndingSoon: "ستنتهي المكالمة قريبًا — ",
    micNeeded: "مطلوب الوصول إلى الميكروفون — اضغط للإصلاح",
    mute: "كتم",
    unmute: "إلغاء الكتم",
    speaker: "مكبر الصوت",
    speakerOn: "مكبر الصوت مفعّل",
  },

  videoCallScreen: {
    connecting: "جاري الاتصال...",
    connected: "متصل",
    reconnecting: "انقطاع الشبكة — إعادة الاتصال...",
    connFailed: "فشل الاتصال — إعادة المحاولة...",
    ringing: "يرن...",
    cameraOff: "الكاميرا متوقفة",
    connectionIssue: "مشكلة في الاتصال",
    live: "مباشر",
    settingUp: "جارٍ إعداد اتصال آمن...",
    waitingResponse: "في انتظار الرد...",
    connectingName: "جاري الاتصال...",
    cameraUnavailable: "الكاميرا غير متاحة",
    startingCamera: "جارٍ تشغيل الكاميرا…",
    noPermission: "لا يوجد إذن",
    cameraOffLabel: "الكاميرا متوقفة",
    you: "أنت",
    mutedBadge: "مكتوم",
    noMic: "لا ميكروفون",
    callEndingSoon: "ستنتهي المكالمة قريبًا — ",
    minLeft: "دقيقة متبقية",
    secLeft: "ث متبقية",
    ctrlCamera: "الكاميرا",
    ctrlCamOff: "إيقاف الكاميرا",
    ctrlUnmute: "إلغاء الكتم",
    ctrlMute: "كتم",
    ctrlEnd: "إنهاء",
    ctrlFlip: "قلب",
    ctrlSpeaker: "مكبر",
    ctrlEarpiece: "سماعة الأذن",
  },

  incomingCallScreen: {
    incomingVideo: "مكالمة فيديو واردة",
    incomingAudio: "مكالمة صوتية واردة",
    unknown: "غير معروف",
    voxlinkHost: "مضيف VoxLink",
    voxlinkUser: "مستخدم VoxLink",
    decline: "رفض",
    accept: "قبول",
  },

  outgoingCallScreen: {
    videoCall: "مكالمة فيديو",
    voiceCall: "مكالمة صوتية",
    callDeclined: "تم رفض المكالمة",
    noAnswer: "لا يوجد رد",
    ringing: "يرن...",
    connecting: "جاري الاتصال...",
    cancel: "إلغاء",
  },

  callSummaryScreen: {
    autoEndedBanner: "نفدت عملات المستخدم — تم قطع المكالمة تلقائيًا",
    callAutoEnded: "انتهت المكالمة تلقائيًا",
    callCompleted: "اكتملت المكالمة",
    withName: "مع",
    duration: "المدة",
    coinsEarned: "العملات المكتسبة",
    video: "فيديو",
    audio: "صوت",
    ratePrefix: "قيّم",
    rateSub: "شارك تجربتك من هذه المكالمة",
    ratingLabels: ["", "سيئة", "مقبولة", "جيدة", "رائعة", "ممتازة!"],
    submitRating: "⭐ إرسال التقييم",
    skip: "تخطي",
    thankYouTitle: "شكرًا! 🙏",
    thankYouSub: "تم إرسال تقييمك",
    viewEarnings: "عرض الأرباح",
    backHome: "العودة إلى الرئيسية",
    ratingError: "فشل إرسال التقييم، يرجى المحاولة مجددًا.",
    errorTitle: "خطأ",
    user: "مستخدم",
  },

  callHistoryScreen: {
    title: "سجل المكالمات",
    all: "الكل",
    audio: "صوت",
    video: "فيديو",
    completed: "مكتملة",
    missed: "فائتة",
    cancelled: "ملغاة",
    noHistory: "لم يُعثر على سجل مكالمات",
    coins: "عملات",
    loadFailed: "فشل تحميل سجل المكالمات.",
  },

  aboutScreen: {
    title: "حول VoxLink",
    tagline: "اتصال صوتي ومرئي — إصدار المضيف",
    version: "الإصدار",
    statActiveUsers: "مستخدمون نشطون",
    statHosts: "مضيفون",
    statCallsMade: "مكالمات أُجريت",
    statAppRating: "تقييم التطبيق",
    whatIsTitle: "ما هو VoxLink Host؟",
    whatIsBody1: "VoxLink Host هو التطبيق المخصص للمضيفين الموثّقين على منصة VoxLink. كمضيف، تتواصل مع المستخدمين لإجراء محادثات صوتية ومرئية هادفة — سواء نصائح الحياة أو ممارسة اللغة أو الدعم العاطفي أو الرفقة.",
    whatIsBody2: "يكسب المضيفون عملات عن كل دقيقة من المكالمات المكتملة. تُحوَّل العملات إلى أموال حقيقية وتُسحب مباشرة إلى حسابك البنكي. حدّد جدولك الخاص، ونمِّ جمهورك، واكسب وفق شروطك.",
    featuresTitle: "ميزات المضيف",
    featHd: "مكالمات صوتية ومرئية عالية الدقة",
    featEncrypted: "مشفّر من طرف إلى طرف",
    featEarn: "اكسب عملات في الدقيقة",
    featDashboard: "لوحة أرباح فورية",
    featChat: "دردشة داخل التطبيق مع المستخدمين",
    featRatings: "التقييمات والمراجعات",
    featSchedule: "جدول توفر مرن",
    connectTitle: "تواصل معنا",
    linkWebsite: "الموقع الإلكتروني",
    linkTwitter: "Twitter / X",
    linkInstagram: "Instagram",
    linkContact: "اتصل بنا",
    privacyPolicy: "سياسة الخصوصية",
    helpCenter: "مركز المساعدة",
    copyright: "© 2026 VoxLink Inc. جميع الحقوق محفوظة.",
  },

  callRatesScreen: {
    title: "أسعار المكالمات",
    helpA: "حدّد عدد العملات التي يدفعها المستخدمون لك في الدقيقة. عادةً ما تكسب مكالمات الفيديو أكثر من الصوت. في مستواك الحالي يمكنك تحصيل حتى ",
    coinsPerMinAudio: " عملة/دقيقة للصوت",
    helpB: " و ",
    coinsPerMinVideo: " عملة/دقيقة للفيديو",
    helpC: " (حد مستوى المشرف +",
    helpD: " مكافأة). اصعد لمستويات أعلى لرفع هذه الحدود.",
    levelWord: "المستوى",
    hostSuffix: " مضيف",
    yourRates: "أسعارك",
    audioCall: "مكالمة صوتية",
    audioSub: "في الدقيقة للمكالمات الصوتية",
    videoCall: "مكالمة فيديو",
    videoSub: "في الدقيقة لمكالمات الفيديو",
    coinsMin: "عملة / دقيقة",
    maxLabel: "حد أقصى ",
    upToLabel: "حتى ",
    capSuffix: " عملة/دقيقة في مستواك",
    estTitle: "تقدير الأرباح",
    est10AudioPrefix: "مكالمة صوتية 10 دقائق ≈ ",
    est10VideoPrefix: "مكالمة فيديو 10 دقائق ≈ ",
    coinsSuffix: " عملة",
    estNote: "تُضاف العملات إلى أرباحك بعد كل مكالمة مكتملة.",
    saveRates: "حفظ الأسعار",
    ratesSaved: "تم تحديث أسعار مكالماتك.",
    ratesSavedTitle: "تم حفظ الأسعار",
    saveFailed: "فشل حفظ الأسعار. يرجى المحاولة مجددًا.",
  },

  earningsHistoryScreen: {
    title: "سجل الأرباح",
    totalEarnings: "إجمالي الأرباح",
    earned: "المكتسب",
    withdrawn: "المسحوب",
    tabAll: "الكل",
    tabEarned: "المكتسب",
    tabWithdrawn: "المسحوب",
    tabBonus: "مكافأة",
    noTransactions: "لم يُعثر على معاملات",
    loadFailed: "فشل تحميل سجل الأرباح.",
    today: "اليوم",
    yesterday: "أمس",
    ref: "مرجع: ",
  },

  helpCenterScreen: {
    title: "مركز المساعدة",
    bannerTitle: "مساعدة المضيف والأسئلة الشائعة",
    bannerSub: "اعثر على إجابات لأسئلة المضيفين الشائعة",
    contactTitle: "تواصل مع دعم المضيف",
    faqTitle: "الأسئلة الشائعة",
  },

  levelBenefitsScreen: {
    title: "مزايا المستوى",
    subtitle: "اصعد السلم واكسب أكثر",
    current: "الحالي",
    unlocked: "مفتوح",
    locked: "مغلق",
    requirements: "المتطلبات",
    ratedCalls: " مكالمة مقيّمة",
    rating: " تقييم",
    rewardsPerks: "المكافآت والمزايا",
    earningsSuffix: "٪ من الأرباح",
    audioUpTo: "🎙️ صوت حتى ",
    videoUpTo: "📹 فيديو حتى ",
    perMin: "/دقيقة",
    higherVisibility: "🚀 ظهور أعلى",
    youreAtLevel: "أنت في المستوى ",
    maxLevelMsg: "لقد وصلت إلى أعلى مستوى. واصل عملك الرائع!",
    progressMid: "٪ من الطريق إلى ",
    loadError: "تعذّر تحميل مزايا المستوى. تحقق من اتصالك وحاول مجددًا.",
    retry: "إعادة المحاولة",
    retrying: "جارٍ إعادة المحاولة…",
    footnote: "المكالمات المقيّمة هي المكالمات التي حصلت على تقييم بالنجوم. تُدفع مكافآت المستوى مرة واحدة عند وصولك لكل مستوى لأول مرة. المستويات الأعلى تتيح لك تحصيل المزيد، والاحتفاظ بحصة أكبر من الأرباح، والظهور بترتيب أعلى للمستخدمين.",
  },

  manageTopicsScreen: {
    title: "مواضيعي",
    helpPrefix: "اختر المواضيع التي تتحدث عنها. سيجدك المستخدمون الذين يتصفحون هذه المواضيع بشكل أسرع. اختر حتى ",
    helpSuffix: ".",
    topics: "المواضيع",
    addYourOwn: "أضف موضوعك",
    customPlaceholder: "مثال: التنجيم، اللياقة…",
    add: "إضافة",
    noTopics: "لا توجد مواضيع متاحة بعد. أضف موضوعك أدناه.",
    saveTopics: "حفظ المواضيع",
    maxPrefix: "يمكنك اختيار حتى ",
    maxSuffix: " مواضيع.",
    topicsSaved: "تم تحديث مواضيعك.",
    topicsSavedTitle: "تم حفظ المواضيع",
    saveFailed: "فشل حفظ المواضيع. يرجى المحاولة مجددًا.",
  },

  notificationsScreen: {
    title: "الإشعارات",
    markAllRead: "تحديد الكل كمقروء",
    empty: "لا توجد إشعارات بعد",
    loadFailed: "فشل تحميل الإشعارات.",
    markFailed: "فشل تحديد الإشعارات كمقروءة.",
    updateFailed: "فشل تحديث الإشعار.",
  },

  payoutMethodScreen: {
    title: "طريقة الدفع",
    help: "اختر كيف تريد استلام أرباحك. ستستخدم طلبات السحب هذا الحساب افتراضيًا.",
    channel: "القناة",
    details: "التفاصيل",
    bank: "حساب بنكي",
    upi: "UPI",
    paytm: "Paytm",
    phonepe: "PhonePe",
    accountHolder: "اسم صاحب الحساب",
    accountHolderPh: "الاسم الكامل على الحساب",
    accountNumber: "رقم الحساب",
    ifsc: "رمز IFSC",
    bankName: "اسم البنك",
    upiId: "معرّف UPI",
    paytmPhone: "رقم هاتف Paytm",
    phonepePhone: "رقم هاتف PhonePe",
    save: "حفظ طريقة الدفع",
    holderRequired: "اسم صاحب الحساب مطلوب.",
    accountInvalid: "أدخل رقم حساب صالح.",
    ifscInvalid: "أدخل رمز IFSC صالح.",
    bankRequired: "اسم البنك مطلوب.",
    upiInvalid: "أدخل معرّف UPI صالح (مثل name@bank).",
    phoneInvalid: "أدخل رقم هاتف صالح.",
    saved: "تم حفظ طريقة الدفع.",
    savedTitle: "تم الحفظ",
    saveFailed: "فشل حفظ طريقة الدفع. يرجى المحاولة مجددًا.",
  },

  privacyScreen: {
    title: "سياسة الخصوصية",
    bannerTitle: "خصوصيتك تهمنا",
    bannerSub: "توضح هذه السياسة كيف يجمع VoxLink Host بياناتك ويستخدمها ويحميها.",
    lastUpdated: "آخر تحديث: 1 مارس 2026",
    contactTitle: "أسئلة حول الخصوصية؟",
    sectionTitles: [
      "1. المعلومات التي نجمعها",
      "2. كيف نستخدم معلوماتك",
      "3. مشاركة المعلومات",
      "4. بيانات المكالمات والصوت",
      "5. KYC والتحقق من الهوية",
      "6. الأرباح والمدفوعات",
      "7. أمن البيانات",
      "8. الاحتفاظ بالبيانات",
      "9. حقوقك",
      "10. التغييرات على هذه السياسة",
    ],
  },

  referralScreen: {
    title: "أحِل واربح",
    heroTitle: "أحِل مضيفين، اربح أكثر!",
    heroSubA: "ادعُ مضيفين آخرين برمزك. عندما يكملون أول مكالمة، يحصلون على ",
    coinsAnd: " عملة وتربح أنت ",
    coinsBang: " عملة!",
    yourCode: "رمز الإحالة الخاص بك",
    copy: "نسخ",
    copied: "تم النسخ!",
    shareBtn: "شارك مع مضيفين آخرين",
    yourStats: "إحصاءات إحالاتك",
    hostsReferred: "المضيفون المُحالون",
    coinsEarned: "العملات المكتسبة",
    howItWorks: "كيف يعمل",
    step1: "شارك رمز إحالتك الفريد مع مضيفين آخرين",
    step2: "يسجّلون كمضيف باستخدام رمزك",
    step3Single: "يكملون مكالمة واحدة على VoxLink",
    step3Plural: "يكملون {n} مكالمات على VoxLink",
    step3Default: "يكملون أول مكالمة لهم على VoxLink",
    step4a: "تربح ",
    step4b: " عملة، ويحصلون على ",
    step4c: "!",
    shareMessage: "انضم إليّ على VoxLink كمضيف وابدأ الكسب من المكالمات الصوتية والمرئية!\n\nاستخدم رمز الإحالة: {code} للحصول على مكافأة عند التسجيل كمضيف!\n\nحمّل الآن: https://voxlink.app/host",
    shareTitle: "انضم إلى VoxLink كمضيف",
    copiedToast: "تم نسخ رمز الإحالة!",
    copiedTitle: "تم النسخ",
    copyFailed: "تعذّر نسخ الرمز. يرجى المحاولة مجددًا.",
    loadFailed: "فشل تحميل معلومات الإحالة.",
  },

  languageScreen: {
    title: "لغة التطبيق",
    subtitle: "اختر لغتك المفضلة. تُطبّق التغييرات فورًا.",
    soon: "قريبًا",
    comingSoon: "قريبًا",
    comingSoonSuffix: " ستتوفر ترجمته قريبًا. سيستمر التطبيق بالإنجليزية.",
  },

  editProfileScreen: {
    title: "تعديل ملف المضيف",
    displayName: "اسم العرض",
    namePlaceholder: "اسم العرض الخاص بك",
    bio: "النبذة",
    bioPlaceholder: "أخبر المستخدمين عن نفسك وخبرتك وما تقدمه...",
    email: "البريد الإلكتروني",
    hostSettings: "إعدادات المضيف",
    setRates: "حدّد أسعار مكالماتك (عملة / دقيقة)",
    manageTopics: "إدارة مواضيعك وتخصصاتك",
    saveChanges: "حفظ التغييرات",
    nameRequired: "يرجى إدخال اسم العرض الخاص بك.",
    saved: "تم تحديث ملف المضيف الخاص بك.",
    savedTitle: "تم حفظ الملف",
    saveFailed: "فشل حفظ الملف. يرجى المحاولة مجددًا.",
    permRequired: "الإذن مطلوب",
    permMsg: "يرجى السماح بالوصول إلى مكتبة الصور لتغيير صورة ملفك الشخصي.",
    tapToChange: "اضغط لتغيير الصورة",
    uploading: "جارٍ الرفع...",
    uploadFailed: "فشل الرفع",
    uploadFailedMsg: "تعذّر رفع صورتك. يرجى المحاولة مجددًا.",
    photoUpdated: "تم تحديث صورة الملف الشخصي!",
    photoSaved: "تم حفظ الصورة",
  },

  chatThreadScreen: {
    defaultName: "دردشة",
    online: "متصل",
    typePlaceholder: "اكتب رسالة...",
    startConvo: "أرسل رسالة لبدء المحادثة",
    notSent: "لم تُرسَل",
    loadFailed: "فشل تحميل الرسائل.",
  },

  notFoundScreen: {
    title: "عذرًا!",
    message: "هذه الشاشة غير موجودة.",
    goHome: "اذهب إلى الرئيسية!",
  },

  // Availability schedule screen
  availabilityScreen: {
    title: "جدول التوفر",
    helpText: "حدّد الساعات التي تكون متاحًا فيها عادةً. يراها المتصلون في ملفك الشخصي. إنها مجرد إشارة عرض — لا تجعلك غير متصل.",
    always24Title: "متاح دائمًا (24/7)",
    always24Sub: "لا ساعات محددة — متاح في أي وقت",
    availableHours: "ساعات التوفر",
    availableFrom: "متاح من",
    availableTo: "متاح حتى",
    sameTimeWarn: "لا يمكن أن يكون وقت البداية والنهاية متطابقين.",
    overnightHint: "فترة ليلية — تمتد بعد منتصف الليل.",
    timezone: "المنطقة الزمنية",
    callersWillSee: "سيرى المتصلون",
    available247: "متاح 24/7",
    saveSchedule: "حفظ الجدول",
    selectTimezone: "اختر المنطقة الزمنية",
    scheduleSaved: "تم حفظ جدول التوفر.",
    savedTitle: "تم الحفظ",
    invalidWindow: "فترة غير صالحة",
    featureUnavailable: "هذه الميزة غير مفعّلة على الخادم بعد. يرجى المحاولة لاحقًا.",
    unavailableTitle: "غير متاح",
    saveFailed: "فشل الحفظ. يرجى المحاولة مجددًا.",
  },
};

export default ar;
