// VoxLink — Arabic Strings

const ar = {
  common: {
    ok: "موافق",
    cancel: "إلغاء",
    confirm: "تأكيد",
    save: "حفظ",
    delete: "حذف",
    edit: "تعديل",
    done: "تم",
    back: "رجوع",
    close: "إغلاق",
    loading: "جاري التحميل...",
    error: "حدث خطأ",
    retry: "حاول مجددًا",
    submit: "إرسال",
    next: "التالي",
    skip: "تخطي",
    yes: "نعم",
    no: "لا",
    search: "بحث",
    filter: "تصفية",
    clear: "مسح",
    apply: "تطبيق",
    share: "مشاركة",
    copy: "نسخ",
    copied: "تم النسخ!",
    noResults: "لا توجد نتائج",
    optional: "اختياري",
    required: "مطلوب",
    all: "الكل",
    more: "المزيد",
    less: "أقل",
    seeAll: "عرض الكل",
    noData: "لا توجد بيانات",
    refresh: "تحديث",
  },
  auth: {
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    newPassword: "كلمة مرور جديدة",
    phone: "رقم الهاتف",
    otp: "رمز التحقق",
    sendOtp: "إرسال OTP",
    verifyOtp: "التحقق من OTP",
    resendOtp: "إعادة إرسال OTP",
    fullName: "الاسم الكامل",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    welcomeBack: "مرحبًا بعودتك!",
    loginToContinue: "سجّل الدخول للمتابعة",
    createYourAccount: "أنشئ حسابك",
    joinVoxLink: "انضم إلى VoxLink اليوم",
    enterOtp: "أدخل رمز OTP المُرسَل إلى",
    passwordResetSent: "تم إرسال بريد إعادة تعيين كلمة المرور",
    checkEmail: "تحقق من بريدك الإلكتروني للتعليمات",
    passwordChanged: "تم تغيير كلمة المرور بنجاح",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    accountDeleted: "تم حذف الحساب بنجاح",
    deleteAccountConfirm: "هل أنت متأكد من أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.",
  },
  nav: {
    home: "الرئيسية",
    search: "بحث",
    messages: "الرسائل",
    wallet: "المحفظة",
    profile: "الملف الشخصي",
    notifications: "الإشعارات",
  },
  home: {
    greeting: "مرحبًا",
    findHosts: "ابحث عن مضيف",
    topListeners: "أبرز المستمعين",
    trending: "الأكثر رواجًا",
    newHosts: "مضيفون جدد",
    onlineNow: "متصل الآن",
    featuredHosts: "مضيفون مميزون",
    seeAll: "عرض الكل",
    searchPlaceholder: "ابحث عن مضيفين ومواضيع...",
  },
  hosts: {
    host: "مضيف",
    listener: "مستمع",
    online: "متصل",
    offline: "غير متصل",
    busy: "مشغول",
    rating: "التقييم",
    reviews: "التقييمات",
    review: "تقييم",
    coinsPerMinute: "عملة/دقيقة",
    totalMinutes: "إجمالي الدقائق",
    specialties: "التخصصات",
    languages: "اللغات",
    about: "عن",
    callNow: "اتصل الآن",
    audioCall: "مكالمة صوتية",
    videoCall: "مكالمة مرئية",
    sendMessage: "إرسال رسالة",
    talkNow: "تحدث الآن",
    noHostsFound: "لم يتم العثور على مضيفين",
    adjustFilters: "حاول تعديل الفلاتر",
    topRated: "الأعلى تقييمًا",
    viewProfile: "عرض الملف",
    startCall: "بدء المكالمة",
  },
  calls: {
    incoming: "مكالمة واردة",
    outgoing: "جاري الاتصال...",
    ongoing: "في مكالمة",
    ended: "انتهت المكالمة",
    audio: "مكالمة صوتية",
    video: "مكالمة مرئية",
    accept: "قبول",
    decline: "رفض",
    endCall: "إنهاء المكالمة",
    mute: "كتم الصوت",
    unmute: "إلغاء الكتم",
    speaker: "مكبر الصوت",
    flipCamera: "قلب الكاميرا",
    callDuration: "مدة المكالمة",
    callWith: "مكالمة مع",
    rateCall: "قيّم هذه المكالمة",
    callHistory: "سجل المكالمات",
    noCallHistory: "لا يوجد سجل مكالمات",
    callCost: "تكلفة المكالمة",
    perMinute: "في الدقيقة",
    lowBalance: "رصيد العملات منخفض",
    lowBalanceMsg: "رصيدك من العملات منخفض. أعد الشحن للمتابعة.",
    callEnded: "انتهت المكالمة",
    callEndedMsg: "انتهت مكالمتك",
    missed: "فائتة",
    answered: "مُجاب",
    rejected: "مرفوضة",
  },
  chat: {
    messages: "الرسائل",
    newMessage: "رسالة جديدة",
    typeMessage: "اكتب رسالة...",
    send: "إرسال",
    noMessages: "لا توجد رسائل بعد",
    startConversation: "ابدأ محادثة",
    online: "متصل",
    offline: "غير متصل",
    typing: "يكتب...",
    delivered: "تم التسليم",
    read: "مقروء",
    deleteChat: "حذف المحادثة",
    deleteChatConfirm: "هل أنت متأكد من حذف هذه المحادثة؟",
  },
  wallet: {
    wallet: "المحفظة",
    coinBalance: "رصيد العملات",
    coins: "عملات",
    coin: "عملة",
    buyCoins: "شراء عملات",
    coinHistory: "سجل العملات",
    transactions: "المعاملات",
    noTransactions: "لا توجد معاملات بعد",
    purchased: "مشتراة",
    spent: "مُنفَق",
    bonus: "مكافأة",
    refunded: "مسترد",
    withdrawal: "سحب",
    totalSpent: "إجمالي الإنفاق",
    totalPurchased: "إجمالي الشراء",
    popular: "الأكثر شعبية",
    bestValue: "أفضل قيمة",
    bonus_label: "مكافأة",
    recharge: "إعادة شحن",
    choosePackage: "اختر الباقة",
    instantDelivery: "تسليم فوري",
    securePayment: "دفع آمن",
    guaranteed: "ضمان الرضا",
  },
  profile: {
    profile: "الملف الشخصي",
    editProfile: "تعديل الملف",
    myProfile: "ملفي الشخصي",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    other: "آخر",
    country: "البلد",
    bio: "النبذة",
    language: "اللغة",
    settings: "الإعدادات",
    helpCenter: "مركز المساعدة",
    privacy: "سياسة الخصوصية",
    about: "عن VoxLink",
    shareApp: "مشاركة VoxLink",
    rateApp: "قيّم التطبيق",
    logout: "تسجيل الخروج",
    deleteAccount: "حذف الحساب",
    callHistory: "سجل المكالمات",
    joinedOn: "انضم في",
    totalCalls: "إجمالي المكالمات",
    hoursSpent: "الساعات المُقضاة",
  },
  settings: {
    settings: "الإعدادات",
    notifications: "الإشعارات",
    callNotifications: "إشعارات المكالمات",
    messageNotifications: "إشعارات الرسائل",
    promoNotifications: "الإشعارات الترويجية",
    language: "اللغة",
    theme: "المظهر",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    systemDefault: "افتراضي النظام",
    privacy: "الخصوصية",
    security: "الأمان",
    changePassword: "تغيير كلمة المرور",
    twoFactor: "التحقق بخطوتين",
    account: "الحساب",
    support: "الدعم",
  },
  payment: {
    checkout: "إتمام الشراء",
    selectPackage: "اختر الباقة",
    paymentMethod: "طريقة الدفع",
    creditCard: "بطاقة ائتمان/خصم",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "جاري معالجة الدفع...",
    paymentSuccess: "تمت عملية الدفع بنجاح!",
    paymentFailed: "فشلت عملية الدفع",
    orderSummary: "ملخص الطلب",
    total: "الإجمالي",
    coins: "عملات",
    bonusCoins: "عملات مكافأة",
    tryAgain: "حاول مجددًا",
    secureNote: "جميع المدفوعات مؤمّنة ومشفّرة",
  },
  host: {
    dashboard: "لوحة التحكم",
    totalEarnings: "إجمالي الأرباح",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    totalCalls: "إجمالي المكالمات",
    avgRating: "متوسط التقييم",
    onlineStatus: "حالة الاتصال",
    goOnline: "تسجيل الدخول",
    goOffline: "تسجيل الخروج",
    setBusy: "تعيين كمشغول",
    earnings: "الأرباح",
    withdraw: "سحب",
    withdrawal: "سحب الأرباح",
    minimumWithdraw: "الحد الأدنى 100 عملة",
    enterAmount: "أدخل المبلغ",
    withdrawMethod: "طريقة السحب",
    bankTransfer: "تحويل بنكي",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "تفاصيل الحساب",
    withdrawSuccess: "تم تقديم طلب السحب",
    withdrawPending: "طلبك قيد المعالجة",
    hostSettings: "إعدادات المضيف",
    availability: "التوفر",
    payoutSettings: "إعدادات الدفع",
    becomeHost: "كن مضيفًا",
    apply: "تقدّم الآن",
    applicationSent: "تم إرسال الطلب!",
    applicationDesc: "سنراجع طلبك ونتواصل معك خلال 2-3 أيام عمل.",
  },
  errors: {
    network: "خطأ في الشبكة. يرجى التحقق من اتصالك.",
    server: "خطأ في الخادم. يرجى المحاولة لاحقًا.",
    unauthorized: "انتهت الجلسة. يرجى تسجيل الدخول مجددًا.",
    notFound: "المورد المطلوب غير موجود.",
    insufficientCoins: "عملات غير كافية. يرجى إعادة الشحن.",
    callFailed: "لا يمكن الاتصال. يرجى المحاولة مجددًا.",
    permissionDenied: "تم رفض الإذن.",
    generic: "حدث خطأ ما. يرجى المحاولة مجددًا.",
  },

  tabs: {
    home: "الرئيسية",
    chat: "الدردشة",
    calls: "المكالمات",
    wallet: "المحفظة",
    profile: "الملف الشخصي",
  },

  hostSettings: {
    title: "إعدادات المضيف",
    availability: "التوفر",
    autoOnline: "الاتصال تلقائيًا عند فتح التطبيق",
    dnd: "وضع عدم الإزعاج",
    dndOn: "مفعّل — كتم الإشعارات",
    schedule: "جدول التوفر",
    randomCalls: "المكالمات العشوائية",
    availableRandom: "متاح للمكالمات العشوائية",
    randomOn: "مفعّل — مُدرج في مجموعة المطابقة العشوائية",
    randomOff: "متوقف — المكالمات المباشرة فقط",
    allowVideoRandom: "السماح بمكالمات الفيديو العشوائية",
    videoDisabled: "معطّل — المكالمات العشوائية متوقفة",
    videoOn: "مفعّل — يقبل مكالمات الفيديو العشوائية",
    videoOff: "متوقف — مكالمات صوتية عشوائية فقط",
    loading: "جارٍ التحميل…",
    pushNotifications: "الإشعارات الفورية",
    notificationPrefs: "تفضيلات الإشعارات",
    incomingCallAlerts: "تنبيهات المكالمات الواردة",
    chatNotifications: "إشعارات الدردشة",
    coinEarnedAlerts: "تنبيهات العملات المكتسبة",
    earnings: "الأرباح",
    payoutMethod: "طريقة الدفع",
    withdrawEarnings: "سحب الأرباح",
    referEarn: "أحِل واربح",
    preferences: "التفضيلات",
    appLanguage: "لغة التطبيق",
    support: "الدعم",
    helpSupport: "المساعدة والدعم",
    privacyPolicy: "سياسة الخصوصية",
    aboutApp: "حول VoxLink Host",
    account: "الحساب",
    signOut: "تسجيل الخروج",
    deleteAccount: "حذف الحساب",
    on: "مفعّل",
    off: "متوقف",
    alwaysAvailable: "متاح دائمًا",
  },

  homeScreen: {
    online: "أنت متصل",
    offline: "أنت غير متصل",
    onlineSub: "متاح لاستقبال المكالمات",
    offlineSub: "فعّل لبدء قبول المكالمات",
    totalCalls: "إجمالي المكالمات",
    totalHours: "إجمالي الساعات",
    earnings: "الأرباح",
    yourCallRates: "أسعار مكالماتك",
    ratesSub: "العملات التي يدفعها المستخدمون لك في الدقيقة",
    edit: "تعديل",
    audioPerMin: "صوت / دقيقة",
    videoPerMin: "فيديو / دقيقة",
    manage: "إدارة",
    qaCallRates: "الأسعار",
    qaCallRatesDesc: "حدد سعرك",
    qaTopics: "مواضيعي",
    qaTopicsDesc: "الوصول لمزيد من المستخدمين",
    qaEarnings: "الأرباح",
    qaEarningsDesc: "عرض السجل",
    qaPayouts: "المدفوعات",
    qaPayoutsDesc: "سحب العملات",
    qaWallet: "المحفظة",
    qaWalletDesc: "الرصيد والسحب",
    qaCallHistory: "سجل المكالمات",
    qaCallHistoryDesc: "المكالمات السابقة",
    qaRefer: "أحِل واربح",
    qaReferDesc: "ادعُ الأصدقاء",
    qaProfile: "الملف الشخصي",
    qaProfileDesc: "تعديل التفاصيل",
    qaSettings: "الإعدادات",
    qaSettingsDesc: "تفضيلات التطبيق",
    permsRequired: "الأذونات مطلوبة",
    micLabel: "الميكروفون",
    micDesc: "مطلوب للمكالمات الصوتية",
    cameraLabel: "الكاميرا",
    cameraDesc: "مطلوبة لمكالمات الفيديو",
    notifLabel: "الإشعارات",
    notifDesc: "لتنبيهات المكالمات الواردة",
    granted: "تم المنح",
    tapToAllow: "اضغط للسماح",
    hostTips: "نصائح للمضيف",
    tip1: "كن متصلاً في ساعات الذروة (6 مساءً - 10 مساءً)",
    tip2: "أكمل ملفك الشخصي لمزيد من الحجوزات",
    tip3: "رُد بسرعة لتحسين تقييمك",
    tip4: "أضف المزيد من المواضيع للوصول لمزيد من المستخدمين",
  },

  profileScreen: {
    title: "ملفي الشخصي",
    proHost: "مضيف محترف",
    calls: "المكالمات",
    rating: "التقييم",
    coins: "العملات",
    onlineStatus: "حالة الاتصال",
    pushNotifications: "الإشعارات الفورية",
    account: "الحساب",
    editProfile: "تعديل الملف الشخصي",
    callRates: "أسعار المكالمات",
    myTopics: "مواضيعي",
    settings: "الإعدادات",
    language: "اللغة",
    more: "المزيد",
    referEarn: "أحِل واربح",
    helpCenter: "مركز المساعدة",
    privacyPolicy: "سياسة الخصوصية",
    about: "حول VoxLink",
    signOut: "تسجيل الخروج",
    signOutConfirm: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
    permRequiredTitle: "الإذن مطلوب",
    permRequiredMsg: "يرجى السماح بالوصول إلى مكتبة الصور لتغيير صورة ملفك الشخصي.",
    turnOffNotifTitle: "إيقاف الإشعارات",
    turnOffNotifMsg: "لإيقاف الإشعارات، انتقل إلى إعدادات هاتفك وأوقف إشعارات VoxLink Host.",
    openSettings: "فتح الإعدادات",
    uploadFailedTitle: "فشل الرفع",
    uploadFailedMsg: "تعذّر رفع صورتك. يرجى المحاولة مجددًا.",
    photoUpdated: "تم تحديث صورة الملف الشخصي!",
    photoSaved: "تم حفظ الصورة",
  },

  callsScreen: {
    title: "سجل المكالمات",
    all: "الكل",
    audio: "صوت",
    video: "فيديو",
    completed: "مكتملة",
    missed: "فائتة",
    cancelled: "ملغاة",
    noCalls: "لا توجد مكالمات بعد",
    loadError: "تعذّر تحميل المكالمات. اسحب للتحديث.",
  },

  chatScreen: {
    title: "الرسائل",
    searchPlaceholder: "ابحث في المحادثات...",
    noConversations: "لا توجد محادثات بعد",
    noMessagesYet: "لا توجد رسائل بعد",
    now: "الآن",
  },

  walletScreen: {
    title: "محفظة المضيف",
    availableBalance: "الرصيد المتاح",
    coins: "العملات",
    payoutValue: "قيمة الدفع",
    thisWeek: "هذا الأسبوع",
    sessions: "الجلسات",
    withdrawn: "المسحوب",
    earningsHistory: "سجل الأرباح",
    withdraw: "سحب",
    noEarnings: "لا توجد أرباح بعد",
    quickSelect: "اختيار سريع للمبلغ",
    orEnter: "أو أدخل المبلغ",
    enterCoinAmount: "أدخل عدد العملات",
    payoutTo: "الدفع إلى",
    setupPayout: "قم بإعداد طريقة الدفع",
    edit: "تعديل",
    managePayout: "إدارة طريقة الدفع",
    requestWithdrawal: "طلب سحب",
    note: "ملاحظة",
    failedLoad: "فشل تحميل بيانات الأرباح.",
  },
};

export default ar;
