// VoxLink — English Strings

const en = {
  // Common
  common: {
    ok: "OK",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    done: "Done",
    back: "Back",
    close: "Close",
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Try Again",
    submit: "Submit",
    next: "Next",
    skip: "Skip",
    yes: "Yes",
    no: "No",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    share: "Share",
    copy: "Copy",
    copied: "Copied!",
    noResults: "No results found",
    optional: "Optional",
    required: "Required",
    all: "All",
    more: "More",
    less: "Less",
    seeAll: "See All",
    noData: "No data available",
    refresh: "Refresh",
  },

  // Auth
  auth: {
    login: "Log In",
    register: "Sign Up",
    logout: "Log Out",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password?",
    newPassword: "New Password",
    phone: "Phone Number",
    otp: "Verification Code",
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    resendOtp: "Resend OTP",
    fullName: "Full Name",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    welcomeBack: "Welcome Back!",
    loginToContinue: "Log in to continue",
    createYourAccount: "Create Your Account",
    joinVoxLink: "Join VoxLink today",
    enterOtp: "Enter the OTP sent to",
    passwordResetSent: "Password reset email sent",
    checkEmail: "Check your email for instructions",
    passwordChanged: "Password changed successfully",
    invalidCredentials: "Invalid email or password",
    accountDeleted: "Account deleted successfully",
    deleteAccountConfirm: "Are you sure you want to delete your account? This action cannot be undone.",
  },

  // Navigation
  nav: {
    home: "Home",
    search: "Search",
    messages: "Messages",
    wallet: "Wallet",
    profile: "Profile",
    notifications: "Notifications",
  },

  // Home
  home: {
    greeting: "Hi",
    findHosts: "Find a Host",
    topListeners: "Top Listeners",
    trending: "Trending Now",
    newHosts: "New Hosts",
    onlineNow: "Online Now",
    featuredHosts: "Featured Hosts",
    seeAll: "See All",
    searchPlaceholder: "Search hosts, topics...",
  },

  // Hosts
  hosts: {
    host: "Host",
    listener: "Listener",
    online: "Online",
    offline: "Offline",
    busy: "Busy",
    rating: "Rating",
    reviews: "Reviews",
    review: "Review",
    coinsPerMinute: "coins/min",
    totalMinutes: "min total",
    specialties: "Specialties",
    languages: "Languages",
    about: "About",
    callNow: "Call Now",
    audioCall: "Audio Call",
    videoCall: "Video Call",
    sendMessage: "Send Message",
    talkNow: "Talk Now",
    noHostsFound: "No hosts found",
    adjustFilters: "Try adjusting your filters",
    topRated: "Top Rated",
    viewProfile: "View Profile",
    startCall: "Start Call",
  },

  // Calls
  calls: {
    incoming: "Incoming Call",
    outgoing: "Connecting...",
    ongoing: "On Call",
    ended: "Call Ended",
    audio: "Audio Call",
    video: "Video Call",
    accept: "Accept",
    decline: "Decline",
    endCall: "End Call",
    mute: "Mute",
    unmute: "Unmute",
    speaker: "Speaker",
    flipCamera: "Flip Camera",
    callDuration: "Call Duration",
    callWith: "Call with",
    rateCall: "Rate this call",
    callHistory: "Call History",
    noCallHistory: "No call history yet",
    callCost: "Call Cost",
    perMinute: "per minute",
    lowBalance: "Low Coin Balance",
    lowBalanceMsg: "You're running low on coins. Recharge to continue.",
    callEnded: "Call Ended",
    callEndedMsg: "Your call has ended",
    missed: "Missed",
    answered: "Answered",
    rejected: "Rejected",
  },

  // Chat
  chat: {
    messages: "Messages",
    newMessage: "New Message",
    typeMessage: "Type a message...",
    send: "Send",
    noMessages: "No messages yet",
    startConversation: "Start a conversation",
    online: "Online",
    offline: "Offline",
    typing: "typing...",
    delivered: "Delivered",
    read: "Read",
    deleteChat: "Delete Chat",
    deleteChatConfirm: "Are you sure you want to delete this conversation?",
  },

  // Wallet
  wallet: {
    wallet: "Wallet",
    coinBalance: "Coin Balance",
    coins: "Coins",
    coin: "Coin",
    buyCoins: "Buy Coins",
    coinHistory: "Coin History",
    transactions: "Transactions",
    noTransactions: "No transactions yet",
    purchased: "Purchased",
    spent: "Spent",
    bonus: "Bonus",
    refunded: "Refunded",
    withdrawal: "Withdrawal",
    totalSpent: "Total Spent",
    totalPurchased: "Total Purchased",
    popular: "Most Popular",
    bestValue: "Best Value",
    bonus_label: "BONUS",
    recharge: "Recharge",
    choosePackage: "Choose a Package",
    instantDelivery: "Instant Delivery",
    securePayment: "Secure Payment",
    guaranteed: "Satisfaction Guaranteed",
  },

  // Profile
  profile: {
    profile: "Profile",
    editProfile: "Edit Profile",
    myProfile: "My Profile",
    name: "Name",
    email: "Email",
    phone: "Phone",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    country: "Country",
    bio: "Bio",
    language: "Language",
    settings: "Settings",
    helpCenter: "Help & FAQ",
    privacy: "Privacy Policy",
    about: "About VoxLink",
    shareApp: "Share VoxLink",
    rateApp: "Rate the App",
    logout: "Log Out",
    deleteAccount: "Delete Account",
    callHistory: "Call History",
    joinedOn: "Joined",
    totalCalls: "Total Calls",
    hoursSpent: "Hours Spent",
  },

  // Settings
  settings: {
    settings: "Settings",
    notifications: "Notifications",
    callNotifications: "Call Notifications",
    messageNotifications: "Message Notifications",
    promoNotifications: "Promotional Notifications",
    language: "Language",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemDefault: "System Default",
    privacy: "Privacy",
    security: "Security",
    changePassword: "Change Password",
    twoFactor: "Two-Factor Authentication",
    account: "Account",
    support: "Support",
  },

  // Payments
  payment: {
    checkout: "Checkout",
    selectPackage: "Select Package",
    paymentMethod: "Payment Method",
    creditCard: "Credit / Debit Card",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "Processing Payment...",
    paymentSuccess: "Payment Successful!",
    paymentFailed: "Payment Failed",
    orderSummary: "Order Summary",
    total: "Total",
    coins: "Coins",
    bonusCoins: "Bonus Coins",
    tryAgain: "Try Again",
    secureNote: "All payments are secured and encrypted",
  },

  // Host Mode
  host: {
    dashboard: "Dashboard",
    totalEarnings: "Total Earnings",
    thisWeek: "This Week",
    thisMonth: "This Month",
    totalCalls: "Total Calls",
    avgRating: "Avg. Rating",
    onlineStatus: "Online Status",
    goOnline: "Go Online",
    goOffline: "Go Offline",
    setBusy: "Set Busy",
    earnings: "Earnings",
    withdraw: "Withdraw",
    withdrawal: "Withdrawal",
    minimumWithdraw: "Minimum 100 coins",
    enterAmount: "Enter Amount",
    withdrawMethod: "Withdrawal Method",
    bankTransfer: "Bank Transfer",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "Account Details",
    withdrawSuccess: "Withdrawal request submitted",
    withdrawPending: "Your request is being processed",
    hostSettings: "Host Settings",
    availability: "Availability",
    payoutSettings: "Payout Settings",
    becomeHost: "Become a Host",
    apply: "Apply Now",
    applicationSent: "Application Sent!",
    applicationDesc: "We'll review your application and get back to you within 2-3 business days.",
  },

  // Errors
  errors: {
    network: "Network error. Please check your connection.",
    server: "Server error. Please try again later.",
    unauthorized: "Session expired. Please log in again.",
    notFound: "The requested resource was not found.",
    insufficientCoins: "Insufficient coins. Please recharge.",
    callFailed: "Call could not be connected. Please try again.",
    permissionDenied: "Permission denied.",
    generic: "Something went wrong. Please try again.",
  },

  // Bottom tab bar
  tabs: {
    home: "Home",
    chat: "Chat",
    calls: "Calls",
    wallet: "Wallet",
    profile: "Profile",
  },

  // Host Settings screen
  hostSettings: {
    title: "Host Settings",
    availability: "Availability",
    autoOnline: "Auto Go Online on App Open",
    dnd: "Do Not Disturb Mode",
    dndOn: "On — silencing notifications",
    schedule: "Availability Schedule",
    randomCalls: "Random Calls",
    availableRandom: "Available for Random Calls",
    randomOn: "On — included in random match pool",
    randomOff: "Off — only direct calls",
    allowVideoRandom: "Allow Video Random Calls",
    videoDisabled: "Disabled — random calls are off",
    videoOn: "On — accepts video random calls",
    videoOff: "Off — audio random calls only",
    loading: "Loading…",
    pushNotifications: "Push Notifications",
    notificationPrefs: "Notification Preferences",
    incomingCallAlerts: "Incoming Call Alerts",
    chatNotifications: "Chat Notifications",
    coinEarnedAlerts: "Coin Earned Alerts",
    earnings: "Earnings",
    payoutMethod: "Payout Method",
    withdrawEarnings: "Withdraw Earnings",
    referEarn: "Refer & Earn",
    preferences: "Preferences",
    appLanguage: "App Language",
    support: "Support",
    helpSupport: "Help & Support",
    privacyPolicy: "Privacy Policy",
    aboutApp: "About VoxLink Host",
    account: "Account",
    signOut: "Sign Out",
    deleteAccount: "Delete Account",
    on: "On",
    off: "Off",
    alwaysAvailable: "Always available",
  },

  // Home / Dashboard screen
  homeScreen: {
    online: "You're Online",
    offline: "You're Offline",
    onlineSub: "Available to receive calls",
    offlineSub: "Toggle to start accepting calls",
    totalCalls: "Total Calls",
    totalHours: "Total Hours",
    earnings: "Earnings",
    yourCallRates: "Your Call Rates",
    ratesSub: "Coins users pay you per minute",
    edit: "Edit",
    audioPerMin: "Audio / min",
    videoPerMin: "Video / min",
    manage: "Manage",
    qaCallRates: "Call Rates",
    qaCallRatesDesc: "Set your price",
    qaTopics: "My Topics",
    qaTopicsDesc: "Reach more users",
    qaEarnings: "Earnings",
    qaEarningsDesc: "View history",
    qaPayouts: "Payouts",
    qaPayoutsDesc: "Withdraw coins",
    qaWallet: "Wallet",
    qaWalletDesc: "Balance & withdraw",
    qaCallHistory: "Call History",
    qaCallHistoryDesc: "Past calls",
    qaRefer: "Refer & Earn",
    qaReferDesc: "Invite friends",
    qaProfile: "Profile",
    qaProfileDesc: "Edit details",
    qaSettings: "Settings",
    qaSettingsDesc: "App preferences",
    permsRequired: "Permissions Required",
    micLabel: "Microphone",
    micDesc: "Required for audio calls",
    cameraLabel: "Camera",
    cameraDesc: "Required for video calls",
    notifLabel: "Notifications",
    notifDesc: "For incoming call alerts",
    granted: "Granted",
    tapToAllow: "Tap to allow",
    hostTips: "Host Tips",
    tip1: "Be online during peak hours (6PM - 10PM)",
    tip2: "Complete your profile for more bookings",
    tip3: "Respond quickly to improve your rating",
    tip4: "Add more topics to reach more users",
  },

  // Profile tab
  profileScreen: {
    title: "My Profile",
    proHost: "Professional Host",
    calls: "Calls",
    rating: "Rating",
    coins: "Coins",
    onlineStatus: "Online Status",
    pushNotifications: "Push Notifications",
    account: "Account",
    editProfile: "Edit Profile",
    callRates: "Call Rates",
    myTopics: "My Topics",
    settings: "Settings",
    language: "Language",
    more: "More",
    referEarn: "Refer & Earn",
    helpCenter: "Help Center",
    privacyPolicy: "Privacy Policy",
    about: "About VoxLink",
    signOut: "Sign Out",
    signOutConfirm: "Are you sure you want to sign out?",
    permRequiredTitle: "Permission Required",
    permRequiredMsg: "Please allow access to your photo library to change your profile photo.",
    turnOffNotifTitle: "Turn Off Notifications",
    turnOffNotifMsg: "To disable notifications, go to your phone's Settings and turn off notifications for VoxLink Host.",
    openSettings: "Open Settings",
    uploadFailedTitle: "Upload Failed",
    uploadFailedMsg: "Could not upload your photo. Please try again.",
    photoUpdated: "Profile photo updated!",
    photoSaved: "Photo Saved",
  },

  // Call History tab
  callsScreen: {
    title: "Call History",
    all: "All",
    audio: "Audio",
    video: "Video",
    completed: "Completed",
    missed: "Missed",
    cancelled: "Cancelled",
    noCalls: "No calls yet",
    loadError: "Couldn't load calls. Pull to refresh.",
  },

  // Messages tab
  chatScreen: {
    title: "Messages",
    searchPlaceholder: "Search conversations...",
    noConversations: "No conversations yet",
    noMessagesYet: "No messages yet",
    now: "now",
  },

  // Wallet tab
  walletScreen: {
    title: "Host Wallet",
    availableBalance: "Available Balance",
    coins: "Coins",
    payoutValue: "payout value",
    thisWeek: "This Week",
    sessions: "Sessions",
    withdrawn: "Withdrawn",
    earningsHistory: "Earnings History",
    withdraw: "Withdraw",
    noEarnings: "No earnings yet",
    quickSelect: "Quick Select Amount",
    orEnter: "Or Enter Amount",
    enterCoinAmount: "Enter coin amount",
    payoutTo: "Payout To",
    setupPayout: "Set up your payout method",
    edit: "Edit",
    managePayout: "Manage Payout Method",
    requestWithdrawal: "Request Withdrawal",
    note: "Note",
    failedLoad: "Failed to load earnings data.",
  },
};

export type Translations = typeof en;
export default en;
