// VoxLink — English Strings

const en = {
  // Common
  common: {
    ok: "OK",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    done: "Done",
    back: "Back",
    close: "Close",
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Try Again",
    submit: "Submit",
    next: "Next",
    skip: "Skip",
    yes: "Yes",
    no: "No",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    share: "Share",
    copy: "Copy",
    copied: "Copied!",
    noResults: "No results found",
    optional: "Optional",
    required: "Required",
    all: "All",
    more: "More",
    less: "Less",
    seeAll: "See All",
    noData: "No data available",
    refresh: "Refresh",
  },

  // Auth
  auth: {
    login: "Log In",
    register: "Sign Up",
    logout: "Log Out",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password?",
    newPassword: "New Password",
    phone: "Phone Number",
    otp: "Verification Code",
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    resendOtp: "Resend OTP",
    fullName: "Full Name",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    welcomeBack: "Welcome Back!",
    loginToContinue: "Log in to continue",
    createYourAccount: "Create Your Account",
    joinVoxLink: "Join VoxLink today",
    enterOtp: "Enter the OTP sent to",
    passwordResetSent: "Password reset email sent",
    checkEmail: "Check your email for instructions",
    passwordChanged: "Password changed successfully",
    invalidCredentials: "Invalid email or password",
    accountDeleted: "Account deleted successfully",
    deleteAccountConfirm: "Are you sure you want to delete your account? This action cannot be undone.",
  },

  // Navigation
  nav: {
    home: "Home",
    search: "Search",
    messages: "Messages",
    wallet: "Wallet",
    profile: "Profile",
    notifications: "Notifications",
  },

  // Home
  home: {
    greeting: "Hi",
    findHosts: "Find a Host",
    topListeners: "Top Listeners",
    trending: "Trending Now",
    newHosts: "New Hosts",
    onlineNow: "Online Now",
    featuredHosts: "Featured Hosts",
    seeAll: "See All",
    searchPlaceholder: "Search hosts, topics...",
  },

  // Hosts
  hosts: {
    host: "Host",
    listener: "Listener",
    online: "Online",
    offline: "Offline",
    busy: "Busy",
    rating: "Rating",
    reviews: "Reviews",
    review: "Review",
    coinsPerMinute: "coins/min",
    totalMinutes: "min total",
    specialties: "Specialties",
    languages: "Languages",
    about: "About",
    callNow: "Call Now",
    audioCall: "Audio Call",
    videoCall: "Video Call",
    sendMessage: "Send Message",
    talkNow: "Talk Now",
    noHostsFound: "No hosts found",
    adjustFilters: "Try adjusting your filters",
    topRated: "Top Rated",
    viewProfile: "View Profile",
    startCall: "Start Call",
  },

  // Calls
  calls: {
    incoming: "Incoming Call",
    outgoing: "Connecting...",
    ongoing: "On Call",
    ended: "Call Ended",
    audio: "Audio Call",
    video: "Video Call",
    accept: "Accept",
    decline: "Decline",
    endCall: "End Call",
    mute: "Mute",
    unmute: "Unmute",
    speaker: "Speaker",
    flipCamera: "Flip Camera",
    callDuration: "Call Duration",
    callWith: "Call with",
    rateCall: "Rate this call",
    callHistory: "Call History",
    noCallHistory: "No call history yet",
    callCost: "Call Cost",
    perMinute: "per minute",
    lowBalance: "Low Coin Balance",
    lowBalanceMsg: "You're running low on coins. Recharge to continue.",
    callEnded: "Call Ended",
    callEndedMsg: "Your call has ended",
    missed: "Missed",
    answered: "Answered",
    rejected: "Rejected",
  },

  // Chat
  chat: {
    messages: "Messages",
    newMessage: "New Message",
    typeMessage: "Type a message...",
    send: "Send",
    noMessages: "No messages yet",
    startConversation: "Start a conversation",
    online: "Online",
    offline: "Offline",
    typing: "typing...",
    delivered: "Delivered",
    read: "Read",
    deleteChat: "Delete Chat",
    deleteChatConfirm: "Are you sure you want to delete this conversation?",
  },

  // Wallet
  wallet: {
    wallet: "Wallet",
    coinBalance: "Coin Balance",
    coins: "Coins",
    coin: "Coin",
    buyCoins: "Buy Coins",
    coinHistory: "Coin History",
    transactions: "Transactions",
    noTransactions: "No transactions yet",
    purchased: "Purchased",
    spent: "Spent",
    bonus: "Bonus",
    refunded: "Refunded",
    withdrawal: "Withdrawal",
    totalSpent: "Total Spent",
    totalPurchased: "Total Purchased",
    popular: "Most Popular",
    bestValue: "Best Value",
    bonus_label: "BONUS",
    recharge: "Recharge",
    choosePackage: "Choose a Package",
    instantDelivery: "Instant Delivery",
    securePayment: "Secure Payment",
    guaranteed: "Satisfaction Guaranteed",
  },

  // Profile
  profile: {
    profile: "Profile",
    editProfile: "Edit Profile",
    myProfile: "My Profile",
    name: "Name",
    email: "Email",
    phone: "Phone",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    country: "Country",
    bio: "Bio",
    language: "Language",
    settings: "Settings",
    helpCenter: "Help & FAQ",
    privacy: "Privacy Policy",
    about: "About VoxLink",
    shareApp: "Share VoxLink",
    rateApp: "Rate the App",
    logout: "Log Out",
    deleteAccount: "Delete Account",
    callHistory: "Call History",
    joinedOn: "Joined",
    totalCalls: "Total Calls",
    hoursSpent: "Hours Spent",
  },

  // Settings
  settings: {
    settings: "Settings",
    notifications: "Notifications",
    callNotifications: "Call Notifications",
    messageNotifications: "Message Notifications",
    promoNotifications: "Promotional Notifications",
    language: "Language",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemDefault: "System Default",
    privacy: "Privacy",
    security: "Security",
    changePassword: "Change Password",
    twoFactor: "Two-Factor Authentication",
    account: "Account",
    support: "Support",
  },

  // Payments
  payment: {
    checkout: "Checkout",
    selectPackage: "Select Package",
    paymentMethod: "Payment Method",
    creditCard: "Credit / Debit Card",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "Processing Payment...",
    paymentSuccess: "Payment Successful!",
    paymentFailed: "Payment Failed",
    orderSummary: "Order Summary",
    total: "Total",
    coins: "Coins",
    bonusCoins: "Bonus Coins",
    tryAgain: "Try Again",
    secureNote: "All payments are secured and encrypted",
  },

  // Host Mode
  host: {
    dashboard: "Dashboard",
    totalEarnings: "Total Earnings",
    thisWeek: "This Week",
    thisMonth: "This Month",
    totalCalls: "Total Calls",
    avgRating: "Avg. Rating",
    onlineStatus: "Online Status",
    goOnline: "Go Online",
    goOffline: "Go Offline",
    setBusy: "Set Busy",
    earnings: "Earnings",
    withdraw: "Withdraw",
    withdrawal: "Withdrawal",
    minimumWithdraw: "Minimum 100 coins",
    enterAmount: "Enter Amount",
    withdrawMethod: "Withdrawal Method",
    bankTransfer: "Bank Transfer",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "Account Details",
    withdrawSuccess: "Withdrawal request submitted",
    withdrawPending: "Your request is being processed",
    hostSettings: "Host Settings",
    availability: "Availability",
    payoutSettings: "Payout Settings",
    becomeHost: "Become a Host",
    apply: "Apply Now",
    applicationSent: "Application Sent!",
    applicationDesc: "We'll review your application and get back to you within 2-3 business days.",
  },

  // Errors
  errors: {
    network: "Network error. Please check your connection.",
    server: "Server error. Please try again later.",
    unauthorized: "Session expired. Please log in again.",
    notFound: "The requested resource was not found.",
    insufficientCoins: "Insufficient coins. Please recharge.",
    callFailed: "Call could not be connected. Please try again.",
    permissionDenied: "Permission denied.",
    generic: "Something went wrong. Please try again.",
  },

  // Bottom tab bar
  tabs: {
    home: "Home",
    chat: "Chat",
    calls: "Calls",
    wallet: "Wallet",
    profile: "Profile",
  },

  // Host Settings screen
  hostSettings: {
    title: "Host Settings",
    availability: "Availability",
    autoOnline: "Auto Go Online on App Open",
    dnd: "Do Not Disturb Mode",
    dndOn: "On — silencing notifications",
    schedule: "Availability Schedule",
    randomCalls: "Random Calls",
    availableRandom: "Available for Random Calls",
    randomOn: "On — included in random match pool",
    randomOff: "Off — only direct calls",
    allowVideoRandom: "Allow Video Random Calls",
    videoDisabled: "Disabled — random calls are off",
    videoOn: "On — accepts video random calls",
    videoOff: "Off — audio random calls only",
    loading: "Loading…",
    pushNotifications: "Push Notifications",
    notificationPrefs: "Notification Preferences",
    incomingCallAlerts: "Incoming Call Alerts",
    chatNotifications: "Chat Notifications",
    coinEarnedAlerts: "Coin Earned Alerts",
    earnings: "Earnings",
    payoutMethod: "Payout Method",
    withdrawEarnings: "Withdraw Earnings",
    referEarn: "Refer & Earn",
    preferences: "Preferences",
    appLanguage: "App Language",
    support: "Support",
    helpSupport: "Help & Support",
    privacyPolicy: "Privacy Policy",
    aboutApp: "About VoxLink Host",
    account: "Account",
    signOut: "Sign Out",
    deleteAccount: "Delete Account",
    on: "On",
    off: "Off",
    alwaysAvailable: "Always available",
  },

  // Home / Dashboard screen
  homeScreen: {
    online: "You're Online",
    offline: "You're Offline",
    onlineSub: "Available to receive calls",
    offlineSub: "Toggle to start accepting calls",
    totalCalls: "Total Calls",
    totalHours: "Total Hours",
    earnings: "Earnings",
    yourCallRates: "Your Call Rates",
    ratesSub: "Coins users pay you per minute",
    edit: "Edit",
    audioPerMin: "Audio / min",
    videoPerMin: "Video / min",
    manage: "Manage",
    qaCallRates: "Call Rates",
    qaCallRatesDesc: "Set your price",
    qaTopics: "My Topics",
    qaTopicsDesc: "Reach more users",
    qaEarnings: "Earnings",
    qaEarningsDesc: "View history",
    qaPayouts: "Payouts",
    qaPayoutsDesc: "Withdraw coins",
    qaWallet: "Wallet",
    qaWalletDesc: "Balance & withdraw",
    qaCallHistory: "Call History",
    qaCallHistoryDesc: "Past calls",
    qaRefer: "Refer & Earn",
    qaReferDesc: "Invite friends",
    qaProfile: "Profile",
    qaProfileDesc: "Edit details",
    qaSettings: "Settings",
    qaSettingsDesc: "App preferences",
    permsRequired: "Permissions Required",
    micLabel: "Microphone",
    micDesc: "Required for audio calls",
    cameraLabel: "Camera",
    cameraDesc: "Required for video calls",
    notifLabel: "Notifications",
    notifDesc: "For incoming call alerts",
    granted: "Granted",
    tapToAllow: "Tap to allow",
    hostTips: "Host Tips",
    tip1: "Be online during peak hours (6PM - 10PM)",
    tip2: "Complete your profile for more bookings",
    tip3: "Respond quickly to improve your rating",
    tip4: "Add more topics to reach more users",
  },

  // Profile tab
  profileScreen: {
    title: "My Profile",
    proHost: "Professional Host",
    calls: "Calls",
    rating: "Rating",
    coins: "Coins",
    onlineStatus: "Online Status",
    pushNotifications: "Push Notifications",
    account: "Account",
    editProfile: "Edit Profile",
    callRates: "Call Rates",
    myTopics: "My Topics",
    settings: "Settings",
    language: "Language",
    more: "More",
    referEarn: "Refer & Earn",
    helpCenter: "Help Center",
    privacyPolicy: "Privacy Policy",
    about: "About VoxLink",
    signOut: "Sign Out",
    signOutConfirm: "Are you sure you want to sign out?",
    permRequiredTitle: "Permission Required",
    permRequiredMsg: "Please allow access to your photo library to change your profile photo.",
    turnOffNotifTitle: "Turn Off Notifications",
    turnOffNotifMsg: "To disable notifications, go to your phone's Settings and turn off notifications for VoxLink Host.",
    openSettings: "Open Settings",
    uploadFailedTitle: "Upload Failed",
    uploadFailedMsg: "Could not upload your photo. Please try again.",
    photoUpdated: "Profile photo updated!",
    photoSaved: "Photo Saved",
  },

  // Call History tab
  callsScreen: {
    title: "Call History",
    all: "All",
    audio: "Audio",
    video: "Video",
    completed: "Completed",
    missed: "Missed",
    cancelled: "Cancelled",
    noCalls: "No calls yet",
    loadError: "Couldn't load calls. Pull to refresh.",
  },

  // Messages tab
  chatScreen: {
    title: "Messages",
    searchPlaceholder: "Search conversations...",
    noConversations: "No conversations yet",
    noMessagesYet: "No messages yet",
    now: "now",
  },

  // Wallet tab
  walletScreen: {
    title: "Host Wallet",
    availableBalance: "Available Balance",
    coins: "Coins",
    payoutValue: "payout value",
    thisWeek: "This Week",
    sessions: "Sessions",
    withdrawn: "Withdrawn",
    earningsHistory: "Earnings History",
    withdraw: "Withdraw",
    noEarnings: "No earnings yet",
    quickSelect: "Quick Select Amount",
    orEnter: "Or Enter Amount",
    enterCoinAmount: "Enter coin amount",
    payoutTo: "Payout To",
    setupPayout: "Set up your payout method",
    edit: "Edit",
    managePayout: "Manage Payout Method",
    requestWithdrawal: "Request Withdrawal",
    note: "Note",
    failedLoad: "Failed to load earnings data.",
  },

  // Login screen
  loginScreen: {
    tagline: "Earn · Connect · Grow your audience",
    chipKyc: "KYC Verified",
    chipEarn: "Earn Coins",
    chipPlatform: "Host Platform",
    welcomeBack: "Welcome back",
    subtitle: "Sign in to your host account",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Password",
    signIn: "Sign In as Host",
    orContinue: "or continue with",
    continueGoogle: "Continue with Google",
    signingIn: "Signing in...",
    newPrompt: "New to VoxLink Host? ",
    applyNow: "Apply Now",
  },

  // Register screen
  registerScreen: {
    stepAccount: "Account",
    stepProfile: "Profile",
    stepHostInfo: "Host Info",
    stepKyc: "KYC Docs",
    title: "Become a Host",
    headerSub: "Complete 4 steps to start earning",
    createTitle: "Create Your Account",
    createSub: "This will be your VoxLink Host login",
    namePlaceholder: "Full name",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Password (8+ characters)",
    continueBtn: "Continue",
    orSignUp: "or sign up with",
    continueGoogle: "Continue with Google",
    signingIn: "Signing in...",
    alreadyRegistered: "Already registered? ",
    signIn: "Sign In",
  },

  // Shared auth toasts (login / register / google)
  authToasts: {
    missingFields: "Missing Fields",
    loginMissing: "Please enter both email and password.",
    invalidEmail: "Invalid Email",
    invalidEmailMsg: "Please enter a valid email address.",
    loginFailed: "Login Failed",
    loginFailedMsg: "Invalid email or password.",
    notSupported: "Not Supported",
    playServices: "Google Play Services not available.",
    connectionError: "Connection Error",
    noInternet: "No internet connection.",
    signInFailed: "Sign In Failed",
    googleFailed: "Google sign-in failed",
    almostThere: "Almost There",
    googleWelcomeHost: "Welcome! Please complete your host profile and KYC.",
    googleWelcomeProfile: "Welcome! Please complete your profile to apply as a host.",
    signInFailedRetry: "Sign-in failed. Please try again.",
    googleNoAccount: "Could not retrieve Google account info.",
    googleNoToken: "Google sign-in did not return a token. Please update the app or try again.",
    registerMissing: "Please fill in all fields.",
    weakPassword: "Weak Password",
    weakPasswordMsg: "Password must be at least 8 characters.",
    welcomeBack: "Welcome Back",
    resuming: "Resuming your incomplete registration.",
    alreadyRegisteredTitle: "Already Registered",
    alreadyRegisteredMsg: "This email is already registered. Please sign in instead.",
    createFailed: "Could not create account. Please try again.",
  },

  // Forgot password screen
  forgotPasswordScreen: {
    checkEmail: "Check Your Email",
    forgotPassword: "Forgot Password?",
    sentLine1: "We sent a 6-digit OTP to",
    sentLine2: "Enter the code and set a new password.",
    enterEmailPrompt: "Enter your registered email. We'll send an OTP to reset your password.",
    resetPassword: "Reset Password",
    otpPlaceholder: "Enter OTP Code",
    newPasswordPlaceholder: "New Password",
    confirmPasswordPlaceholder: "Confirm New Password",
    resetting: "Resetting...",
    resetBtn: "Reset Password",
    didntReceive: "Didn't receive it? ",
    resendIn: "Resend in",
    resendOtp: "Resend OTP",
    findAccount: "Find your account",
    emailPlaceholder: "Email Address",
    sending: "Sending...",
    sendOtp: "Send OTP",
    backTo: "Back to ",
    signIn: "Sign In",
    enterEmailError: "Please enter your email address.",
    otpSent: "OTP sent to your email.",
    emailSent: "Email Sent",
    emailNotFound: "Email not found. Please check and try again.",
    enterOtpError: "Please enter the OTP sent to your email.",
    weakPassword: "Weak Password",
    weakPasswordMsg: "Password must be at least 8 characters.",
    mismatch: "Mismatch",
    passwordsDontMatch: "Passwords don't match.",
    successTitle: "Success",
    resetSuccess: "Password updated successfully! Please sign in.",
    errorTitle: "Error",
    resetFailed: "Failed to reset password. The OTP may have expired.",
  },

  // Onboarding screen
  onboardingScreen: {
    slide1Title: "FIND",
    slide1Sub: "You can connect with people around\nthe world to chat, message and\nmake connections with them.",
    slide2Title: "CHAT",
    slide2Sub: "Chat with strangers to get to know\neach other better and build\na nice rapport.",
    slide3Title: "VIDEO CALL",
    slide3Sub: "You can share your videos and photos\nwith your friends and connections.",
  },

  // Profile setup screen (register step 2)
  profileSetupScreen: {
    headerSub: "Step 2 of 4 — Your Profile",
    sectionTitle: "Your Profile Info",
    sectionSub: "This will be visible to users calling you",
    uploading: "Uploading...",
    tapAddPhoto: "Tap to add profile photo",
    namePlaceholder: "Display name",
    dobPlaceholder: "Date of birth (tap to pick)",
    phonePlaceholder: "Mobile number",
    genderLabel: "Gender",
    continueBtn: "Continue → Host Info",
    done: "Done",
    dobTitle: "Date of Birth",
    day: "Day",
    month: "Month",
    year: "Year",
    months: ["January","February","March","April","May","June","July","August","September","October","November","December"],
    uploadFailed: "Upload Failed",
    uploadFailedMsg: "Could not upload photo. Please try again.",
    missingFields: "Missing Fields",
    missingFieldsMsg: "Please fill in all required fields.",
    invalidPhone: "Invalid Phone",
    invalidPhoneMsg: "Please enter a valid mobile number.",
    saveFailed: "Save Failed",
    saveFailedMsg: "Could not save your profile. Please try again.",
  },

  // Become a host screen (register step 3)
  becomeScreen: {
    headerSub: "Step 3 of 4 — Host Info",
    sectionTitle: "Your Host Profile",
    sectionSub: "Help users understand what you offer",
    specialtiesLabel: "Specialties (pick 1–5)",
    languagesLabel: "Languages",
    bioLabel: "Bio",
    bioPlaceholder: "Tell users about yourself — your expertise, personality, and what makes your calls special...",
    experienceLabel: "Experience (optional)",
    experiencePlaceholder: "e.g. 3 years as life coach",
    callTypeLabel: "Call Type Offered",
    audioOnly: "🎤 Audio Only",
    videoOnly: "🎥 Video Only",
    both: "🎤🎥 Both",
    ratesLabel: "Your Call Rates (coins/min)",
    audio: "Audio",
    video: "Video",
    coinsPerMin: "coins/min",
    note: "Rates are suggestions. Admin may adjust them after approval.",
    continueBtn: "Continue →  KYC Documents",
    selectSpecialty: "Select Specialty",
    chooseSpecialty: "Choose at least one specialty.",
    bioTooShort: "Bio Too Short",
    bioTooShortMsg: "Please write a bio of at least 20 characters.",
  },

  // KYC screen (register step 4)
  kycScreen: {
    headerSub: "Step 4 of 4 — KYC Documents",
    sectionTitle: "Identity Verification",
    sectionSub: "Required to start hosting. Your documents are securely stored.",
    notice: "KYC is mandatory per Indian regulations. Documents are reviewed only by admin and never shared with users.",
    dobLabel: "Date of Birth",
    fromStep2: "From Step 2",
    dobPlaceholder: "DD/MM/YYYY (e.g. 22/05/1998)",
    docAadharFront: "Aadhar Front",
    docAadharFrontSub: "Photo of front side of Aadhar card",
    docAadharBack: "Aadhar Back",
    docAadharBackSub: "Photo of back side of Aadhar card",
    docVideo: "Verification Video",
    docVideoSub: "Short video (5–15 sec) of yourself holding the Aadhar",
    uploading: "Uploading...",
    uploaded: "Uploaded ✓",
    tipsTitle: "Tips for Approval",
    tip1: "Ensure Aadhar photos are clear and not blurry",
    tip2: "Hold your Aadhar card clearly in the verification video",
    tip3: "Look into the camera while recording",
    submitting: "Submitting...",
    submit: "Submit Application",
    uploadFailed: "Upload Failed",
    uploadFailedMsg: "Could not upload file. Please try again.",
    missingDocs: "Missing Documents",
    missingDocsMsg: "Please upload both Aadhar front and back photos.",
    missingDob: "Missing DOB",
    missingDobMsg: "Date of birth is missing. Please go back to Step 2 and select your DOB.",
    submitFailed: "Submission Failed",
    submitFailedMsg: "Could not submit your application. Please try again.",
  },

  // Host application status screen
  statusScreen: {
    headerTitle: "Host Application",
    headerSub: "Track your KYC verification status",
    checking: "Checking application status...",
    pendingTitle: "Application Submitted",
    pendingMsg: "Your application is in the queue. Our team will review it within 24–48 hours.",
    underReviewTitle: "Under Review",
    underReviewMsg: "Our team is actively reviewing your application. You'll hear back soon.",
    approvedTitle: "Congratulations!",
    approvedMsg: "Your application has been approved! You are now a verified host on VoxLink.",
    rejectedTitle: "Application Rejected",
    rejectedMsg: "Unfortunately, your application was not approved. Please see the reason below and re-apply.",
    notAppliedTitle: "No Application Found",
    notAppliedMsg: "You haven't submitted a host application yet.",
    approvedSub: "You are now a verified host on VoxLink. Start accepting calls and earning coins!",
    earnCoins: "Earn Coins",
    buildRating: "Build Rating",
    takeCalls: "Take Calls",
    timelineTitle: "Application Timeline",
    tlAccount: "Account Created",
    tlSubmitted: "Application Submitted",
    tlReview: "Under Review",
    tlDecision: "Decision Made",
    continueDashboard: "Continue to Dashboard",
    reasonRejection: "Reason for Rejection",
    reapply: "Re-apply",
    startApplication: "Start Application",
    autoChecking: "Auto-checking every 10 seconds...",
    loadError: "Failed to load application status.",
  },

  // Audio call screen
  audioCallScreen: {
    voiceCall: "Voice Call",
    ringing: "Ringing...",
    connecting: "Connecting...",
    connected: "Connected",
    reconnecting: "Network drop — reconnecting...",
    connFailed: "Connection failed — retrying...",
    callEnded: "Call ended",
    unknown: "Unknown",
    muted: "🔇 Muted",
    coinsPerMin: "coins / min",
    remaining: "remaining",
    minLeft: "min left",
    callEndingSoon: "Call ending soon — ",
    micNeeded: "Microphone access needed — Tap to fix",
    mute: "Mute",
    unmute: "Unmute",
    speaker: "Speaker",
    speakerOn: "Speaker On",
  },

  // Video call screen
  videoCallScreen: {
    connecting: "Connecting...",
    connected: "Connected",
    reconnecting: "Network drop — reconnecting...",
    connFailed: "Connection failed — retrying...",
    ringing: "Ringing...",
    cameraOff: "Camera off",
    connectionIssue: "Connection issue",
    live: "LIVE",
    settingUp: "Setting up secure connection...",
    waitingResponse: "Waiting for response...",
    connectingName: "Connecting...",
    cameraUnavailable: "Camera unavailable",
    startingCamera: "Starting camera…",
    noPermission: "No Permission",
    cameraOffLabel: "Camera Off",
    you: "You",
    mutedBadge: "Muted",
    noMic: "No mic",
    callEndingSoon: "Call ending soon — ",
    minLeft: "min left",
    secLeft: "s left",
    ctrlCamera: "Camera",
    ctrlCamOff: "Cam Off",
    ctrlUnmute: "Unmute",
    ctrlMute: "Mute",
    ctrlEnd: "End",
    ctrlFlip: "Flip",
    ctrlSpeaker: "Speaker",
    ctrlEarpiece: "Earpiece",
  },

  // Incoming call screen
  incomingCallScreen: {
    incomingVideo: "Incoming Video Call",
    incomingAudio: "Incoming Audio Call",
    unknown: "Unknown",
    voxlinkHost: "VoxLink Host",
    voxlinkUser: "VoxLink User",
    decline: "Decline",
    accept: "Accept",
  },

  // Outgoing call screen
  outgoingCallScreen: {
    videoCall: "Video Call",
    voiceCall: "Voice Call",
    callDeclined: "Call Declined",
    noAnswer: "No Answer",
    ringing: "Ringing...",
    connecting: "Connecting...",
    cancel: "Cancel",
  },

  // Call summary screen
  callSummaryScreen: {
    autoEndedBanner: "User ran out of coins — call was auto-disconnected",
    connectionLostBanner: "Call disconnected — connection lost",
    callAutoEnded: "Call Auto-Ended",
    callCompleted: "Call Completed",
    withName: "with",
    duration: "Duration",
    coinsEarned: "Coins Earned",
    video: "Video",
    audio: "Audio",
    ratePrefix: "Rate",
    rateSub: "Share your experience from this call",
    ratingLabels: ["", "Poor", "Fair", "Good", "Great", "Excellent!"],
    submitRating: "⭐ Submit Rating",
    skip: "Skip",
    thankYouTitle: "Thank you! 🙏",
    thankYouSub: "Your rating has been submitted",
    viewEarnings: "View Earnings",
    backHome: "Back to Home",
    ratingError: "Failed to submit rating, please try again.",
    errorTitle: "Error",
    user: "User",
  },

  // Call history screen
  callHistoryScreen: {
    title: "Call History",
    all: "All",
    audio: "Audio",
    video: "Video",
    completed: "Completed",
    missed: "Missed",
    cancelled: "Cancelled",
    noHistory: "No call history found",
    coins: "coins",
    loadFailed: "Failed to load call history.",
  },

  // About screen
  aboutScreen: {
    title: "About VoxLink",
    tagline: "Voice & Video Connection — Host Edition",
    version: "Version",
    statActiveUsers: "Active Users",
    statHosts: "Hosts",
    statCallsMade: "Calls Made",
    statAppRating: "App Rating",
    whatIsTitle: "What is VoxLink Host?",
    whatIsBody1: "VoxLink Host is the dedicated app for verified hosts on the VoxLink platform. As a host, you connect with users for meaningful audio and video conversations — whether it's life advice, language practice, emotional support, or companionship.",
    whatIsBody2: "Hosts earn coins for every minute of calls they complete. Coins are converted to real money and withdrawn directly to your bank account. Set your own schedule, grow your audience, and earn on your terms.",
    featuresTitle: "Host Features",
    featHd: "HD Audio & Video Calls",
    featEncrypted: "End-to-End Encrypted",
    featEarn: "Earn Coins Per Minute",
    featDashboard: "Real-Time Earnings Dashboard",
    featChat: "In-App Chat with Users",
    featRatings: "Ratings & Reviews",
    featSchedule: "Flexible Availability Schedule",
    connectTitle: "Connect With Us",
    linkWebsite: "Website",
    linkTwitter: "Twitter / X",
    linkInstagram: "Instagram",
    linkContact: "Contact Us",
    privacyPolicy: "Privacy Policy",
    helpCenter: "Help Center",
    copyright: "© 2026 VoxLink Inc. All rights reserved.",
  },

  // Call rates screen
  callRatesScreen: {
    title: "Call Rates",
    helpA: "Set how many coins users pay you per minute. Video calls usually earn more than audio. At your current level you can charge up to ",
    coinsPerMinAudio: " coins/min for audio",
    helpB: " and ",
    coinsPerMinVideo: " coins/min for video",
    helpC: " (admin level cap +",
    helpD: " bonus). Reach higher levels to raise these caps.",
    levelWord: "Level",
    hostSuffix: " host",
    yourRates: "Your Rates",
    audioCall: "Audio Call",
    audioSub: "Per minute for voice calls",
    videoCall: "Video Call",
    videoSub: "Per minute for video calls",
    coinsMin: "coins / min",
    maxLabel: "Max ",
    upToLabel: "Up to ",
    capSuffix: " coins/min at your level",
    estTitle: "Earnings estimate",
    est10AudioPrefix: "10-min audio call ≈ ",
    est10VideoPrefix: "10-min video call ≈ ",
    coinsSuffix: " coins",
    estNote: "Coins are added to your earnings after each completed call.",
    saveRates: "Save Rates",
    ratesSaved: "Your call rates have been updated.",
    ratesSavedTitle: "Rates Saved",
    saveFailed: "Failed to save rates. Please try again.",
  },

  // Earnings history screen
  earningsHistoryScreen: {
    title: "Earnings History",
    totalEarnings: "Total Earnings",
    earned: "Earned",
    withdrawn: "Withdrawn",
    tabAll: "All",
    tabEarned: "Earned",
    tabWithdrawn: "Withdrawn",
    tabBonus: "Bonus",
    noTransactions: "No transactions found",
    loadFailed: "Failed to load earnings history.",
    today: "Today",
    yesterday: "Yesterday",
    ref: "Ref: ",
  },

  // Help center screen
  helpCenterScreen: {
    title: "Help Center",
    bannerTitle: "Host Help & FAQ",
    bannerSub: "Find answers to common host questions",
    contactTitle: "Contact Host Support",
    faqTitle: "Frequently Asked Questions",
  },

  // Level benefits screen
  levelBenefitsScreen: {
    title: "Level Benefits",
    subtitle: "Climb the ladder, earn more",
    current: "Current",
    unlocked: "Unlocked",
    locked: "Locked",
    requirements: "Requirements",
    ratedCalls: " rated calls",
    rating: " rating",
    rewardsPerks: "Rewards & Perks",
    earningsSuffix: "% earnings",
    audioUpTo: "🎙️ Audio up to ",
    videoUpTo: "📹 Video up to ",
    perMin: "/min",
    higherVisibility: "🚀 Higher visibility",
    youreAtLevel: "You're at Level ",
    maxLevelMsg: "You've reached the top level. Keep up the great work!",
    progressMid: "% of the way to ",
    loadError: "Couldn't load level benefits. Check your connection and try again.",
    retry: "Retry",
    retrying: "Retrying…",
    footnote: "Rated calls are calls that received a star rating. Level rewards are paid once when you first reach each level. Higher levels let you charge more, keep a bigger share of earnings, and rank higher to users.",
  },

  // Manage topics screen
  manageTopicsScreen: {
    title: "My Topics",
    helpPrefix: "Pick the topics you talk about. Users browsing these topics will find you faster. Select up to ",
    helpSuffix: ".",
    topics: "Topics",
    addYourOwn: "Add Your Own",
    customPlaceholder: "e.g. Astrology, Fitness…",
    add: "Add",
    noTopics: "No topics available yet. Add your own below.",
    saveTopics: "Save Topics",
    maxPrefix: "You can select up to ",
    maxSuffix: " topics.",
    topicsSaved: "Your topics have been updated.",
    topicsSavedTitle: "Topics Saved",
    saveFailed: "Failed to save topics. Please try again.",
  },

  // Notifications screen
  notificationsScreen: {
    title: "Notifications",
    markAllRead: "Mark all read",
    empty: "No notifications yet",
    loadFailed: "Failed to load notifications.",
    markFailed: "Failed to mark notifications as read.",
    updateFailed: "Failed to update notification.",
  },

  // Payout method screen
  payoutMethodScreen: {
    title: "Payout Method",
    help: "Choose how you want to receive your earnings. Your withdrawal requests will use this account by default.",
    channel: "Channel",
    details: "Details",
    bank: "Bank Account",
    upi: "UPI",
    paytm: "Paytm",
    phonepe: "PhonePe",
    accountHolder: "Account Holder Name",
    accountHolderPh: "Full name on the account",
    accountNumber: "Account Number",
    ifsc: "IFSC Code",
    bankName: "Bank Name",
    upiId: "UPI ID",
    paytmPhone: "Paytm Phone Number",
    phonepePhone: "PhonePe Phone Number",
    save: "Save Payout Method",
    holderRequired: "Account holder name is required.",
    accountInvalid: "Enter a valid account number.",
    ifscInvalid: "Enter a valid IFSC code.",
    bankRequired: "Bank name is required.",
    upiInvalid: "Enter a valid UPI ID (e.g. name@bank).",
    phoneInvalid: "Enter a valid phone number.",
    saved: "Payout method saved.",
    savedTitle: "Saved",
    saveFailed: "Failed to save payout method. Please try again.",
  },

  // Privacy policy screen
  privacyScreen: {
    title: "Privacy Policy",
    bannerTitle: "Your Privacy Matters",
    bannerSub: "This policy explains how VoxLink Host collects, uses, and protects your data.",
    lastUpdated: "Last Updated: March 1, 2026",
    contactTitle: "Questions about Privacy?",
    sectionTitles: [
      "1. Information We Collect",
      "2. How We Use Your Information",
      "3. Sharing of Information",
      "4. Call Data & Audio",
      "5. KYC & Identity Verification",
      "6. Earnings & Payouts",
      "7. Data Security",
      "8. Data Retention",
      "9. Your Rights",
      "10. Changes to This Policy",
    ],
  },

  // Referral screen
  referralScreen: {
    title: "Refer & Earn",
    heroTitle: "Refer Hosts, Earn More!",
    heroSubA: "Invite other hosts with your code. When they complete their first call, they get ",
    coinsAnd: " coins and you earn ",
    coinsBang: " coins!",
    yourCode: "Your Referral Code",
    copy: "Copy",
    copied: "Copied!",
    shareBtn: "Share with Other Hosts",
    yourStats: "Your Referral Stats",
    hostsReferred: "Hosts Referred",
    coinsEarned: "Coins Earned",
    howItWorks: "How it Works",
    step1: "Share your unique referral code with other hosts",
    step2: "They sign up as a host using your code",
    step3Single: "They complete 1 call on VoxLink",
    step3Plural: "They complete {n} calls on VoxLink",
    step3Default: "They complete their first call on VoxLink",
    step4a: "You earn ",
    step4b: " coins, they get ",
    step4c: "!",
    shareMessage: "Join me on VoxLink as a host and start earning from audio & video calls!\n\nUse my referral code: {code} to get a bonus when you sign up as a host!\n\nDownload now: https://voxlink.app/host",
    shareTitle: "Join VoxLink as a Host",
    copiedToast: "Referral code copied!",
    copiedTitle: "Copied",
    copyFailed: "Couldn't copy the code. Please try again.",
    loadFailed: "Failed to load referral info.",
  },

  // Language screen
  languageScreen: {
    title: "App Language",
    subtitle: "Select your preferred language. Changes apply immediately.",
    soon: "Soon",
    comingSoon: "Coming Soon",
    comingSoonSuffix: " translation is coming soon. The app will continue in English.",
  },

  // Edit host profile screen
  editProfileScreen: {
    title: "Edit Host Profile",
    displayName: "Display Name",
    namePlaceholder: "Your display name",
    bio: "Bio",
    bioPlaceholder: "Tell users about yourself, your expertise, and what you offer...",
    email: "Email",
    hostSettings: "Host Settings",
    setRates: "Set your call rates (coins / min)",
    manageTopics: "Manage your topics & specialties",
    saveChanges: "Save Changes",
    nameRequired: "Please enter your display name.",
    saved: "Your host profile has been updated.",
    savedTitle: "Profile Saved",
    saveFailed: "Failed to save profile. Please try again.",
    permRequired: "Permission Required",
    permMsg: "Please allow access to your photo library to change your profile photo.",
    tapToChange: "Tap to change photo",
    uploading: "Uploading...",
    uploadFailed: "Upload Failed",
    uploadFailedMsg: "Could not upload your photo. Please try again.",
    photoUpdated: "Profile photo updated!",
    photoSaved: "Photo Saved",
  },

  // Chat thread screen (chat/[id])
  chatThreadScreen: {
    defaultName: "Chat",
    online: "Online",
    typePlaceholder: "Type a message...",
    startConvo: "Send a message to start the conversation",
    notSent: "Not sent",
    loadFailed: "Failed to load messages.",
  },

  // Not found screen
  notFoundScreen: {
    title: "Oops!",
    message: "This screen doesn't exist.",
    goHome: "Go to Home!",
  },

  // Availability schedule screen
  availabilityScreen: {
    title: "Availability Schedule",
    helpText: "Set the hours you're usually available. Callers see this on your profile. It's a display hint — it doesn't force you offline.",
    always24Title: "Always Available (24/7)",
    always24Sub: "No fixed hours — available any time",
    availableHours: "Available Hours",
    availableFrom: "Available From",
    availableTo: "Available To",
    sameTimeWarn: "Start and end time can't be the same.",
    overnightHint: "Overnight window — spans past midnight.",
    timezone: "Timezone",
    callersWillSee: "Callers will see",
    available247: "Available 24/7",
    saveSchedule: "Save Schedule",
    selectTimezone: "Select Timezone",
    scheduleSaved: "Availability schedule saved.",
    savedTitle: "Saved",
    invalidWindow: "Invalid Window",
    featureUnavailable: "This feature isn't enabled on the server yet. Please try again later.",
    unavailableTitle: "Unavailable",
    saveFailed: "Failed to save. Please try again.",
  },
};

export type Translations = typeof en;
export default en;
