// VoxLink — Spanish Strings

const es = {
  common: {
    ok: "Aceptar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Guardar",
    delete: "Eliminar",
    edit: "Editar",
    done: "Listo",
    back: "Atrás",
    close: "Cerrar",
    loading: "Cargando...",
    error: "Algo salió mal",
    retry: "Reintentar",
    submit: "Enviar",
    next: "Siguiente",
    skip: "Omitir",
    yes: "Sí",
    no: "No",
    search: "Buscar",
    filter: "Filtrar",
    clear: "Limpiar",
    apply: "Aplicar",
    share: "Compartir",
    copy: "Copiar",
    copied: "Copiado!",
    noResults: "Sin resultados",
    optional: "Opcional",
    required: "Requerido",
    all: "Todos",
    more: "Más",
    less: "Menos",
    seeAll: "Ver todo",
    noData: "Sin datos disponibles",
    refresh: "Actualizar",
  },
  auth: {
    login: "Iniciar sesión",
    register: "Registrarse",
    logout: "Cerrar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    newPassword: "Nueva contraseña",
    phone: "Número de teléfono",
    otp: "Código de verificación",
    sendOtp: "Enviar OTP",
    verifyOtp: "Verificar OTP",
    resendOtp: "Reenviar OTP",
    fullName: "Nombre completo",
    createAccount: "Crear cuenta",
    alreadyHaveAccount: "¿Ya tienes cuenta?",
    dontHaveAccount: "¿No tienes cuenta?",
    welcomeBack: "¡Bienvenido de nuevo!",
    loginToContinue: "Inicia sesión para continuar",
    createYourAccount: "Crea tu cuenta",
    joinVoxLink: "Únete a VoxLink hoy",
    enterOtp: "Introduce el OTP enviado a",
    passwordResetSent: "Correo de restablecimiento enviado",
    checkEmail: "Revisa tu correo para las instrucciones",
    passwordChanged: "Contraseña cambiada exitosamente",
    invalidCredentials: "Correo o contraseña inválidos",
    accountDeleted: "Cuenta eliminada exitosamente",
    deleteAccountConfirm: "¿Seguro que quieres eliminar tu cuenta? Esta acción es irreversible.",
  },
  nav: {
    home: "Inicio",
    search: "Buscar",
    messages: "Mensajes",
    wallet: "Billetera",
    profile: "Perfil",
    notifications: "Notificaciones",
  },
  home: {
    greeting: "Hola",
    findHosts: "Buscar anfitrión",
    topListeners: "Mejores oyentes",
    trending: "En tendencia",
    newHosts: "Nuevos anfitriones",
    onlineNow: "En línea ahora",
    featuredHosts: "Anfitriones destacados",
    seeAll: "Ver todo",
    searchPlaceholder: "Buscar anfitriones, temas...",
  },
  hosts: {
    host: "Anfitrión",
    listener: "Oyente",
    online: "En línea",
    offline: "Fuera de línea",
    busy: "Ocupado",
    rating: "Calificación",
    reviews: "Reseñas",
    review: "Reseña",
    coinsPerMinute: "monedas/min",
    totalMinutes: "min totales",
    specialties: "Especialidades",
    languages: "Idiomas",
    about: "Acerca de",
    callNow: "Llamar ahora",
    audioCall: "Llamada de audio",
    videoCall: "Videollamada",
    sendMessage: "Enviar mensaje",
    talkNow: "Hablar ahora",
    noHostsFound: "No se encontraron anfitriones",
    adjustFilters: "Intenta ajustar los filtros",
    topRated: "Mejor calificado",
    viewProfile: "Ver perfil",
    startCall: "Iniciar llamada",
  },
  calls: {
    incoming: "Llamada entrante",
    outgoing: "Conectando...",
    ongoing: "En llamada",
    ended: "Llamada terminada",
    audio: "Llamada de audio",
    video: "Videollamada",
    accept: "Aceptar",
    decline: "Rechazar",
    endCall: "Terminar llamada",
    mute: "Silenciar",
    unmute: "Activar micrófono",
    speaker: "Altavoz",
    flipCamera: "Voltear cámara",
    callDuration: "Duración de la llamada",
    callWith: "Llamada con",
    rateCall: "Calificar esta llamada",
    callHistory: "Historial de llamadas",
    noCallHistory: "Sin historial de llamadas",
    callCost: "Costo de la llamada",
    perMinute: "por minuto",
    lowBalance: "Saldo bajo de monedas",
    lowBalanceMsg: "Pocas monedas. Recarga para continuar.",
    callEnded: "Llamada terminada",
    callEndedMsg: "Tu llamada ha terminado",
    missed: "Perdida",
    answered: "Contestada",
    rejected: "Rechazada",
  },
  chat: {
    messages: "Mensajes",
    newMessage: "Nuevo mensaje",
    typeMessage: "Escribe un mensaje...",
    send: "Enviar",
    noMessages: "Sin mensajes aún",
    startConversation: "Iniciar conversación",
    online: "En línea",
    offline: "Fuera de línea",
    typing: "escribiendo...",
    delivered: "Entregado",
    read: "Leído",
    deleteChat: "Eliminar chat",
    deleteChatConfirm: "¿Seguro que quieres eliminar esta conversación?",
  },
  wallet: {
    wallet: "Billetera",
    coinBalance: "Saldo de monedas",
    coins: "Monedas",
    coin: "Moneda",
    buyCoins: "Comprar monedas",
    coinHistory: "Historial de monedas",
    transactions: "Transacciones",
    noTransactions: "Sin transacciones aún",
    purchased: "Comprado",
    spent: "Gastado",
    bonus: "Bono",
    refunded: "Reembolsado",
    withdrawal: "Retiro",
    totalSpent: "Total gastado",
    totalPurchased: "Total comprado",
    popular: "Más popular",
    bestValue: "Mejor valor",
    bonus_label: "BONO",
    recharge: "Recargar",
    choosePackage: "Elegir paquete",
    instantDelivery: "Entrega instantánea",
    securePayment: "Pago seguro",
    guaranteed: "Satisfacción garantizada",
  },
  profile: {
    profile: "Perfil",
    editProfile: "Editar perfil",
    myProfile: "Mi perfil",
    name: "Nombre",
    email: "Correo electrónico",
    phone: "Teléfono",
    gender: "Género",
    male: "Masculino",
    female: "Femenino",
    other: "Otro",
    country: "País",
    bio: "Biografía",
    language: "Idioma",
    settings: "Configuración",
    helpCenter: "Centro de ayuda",
    privacy: "Política de privacidad",
    about: "Acerca de VoxLink",
    shareApp: "Compartir VoxLink",
    rateApp: "Calificar la app",
    logout: "Cerrar sesión",
    deleteAccount: "Eliminar cuenta",
    callHistory: "Historial de llamadas",
    joinedOn: "Miembro desde",
    totalCalls: "Total de llamadas",
    hoursSpent: "Horas dedicadas",
  },
  settings: {
    settings: "Configuración",
    notifications: "Notificaciones",
    callNotifications: "Notificaciones de llamadas",
    messageNotifications: "Notificaciones de mensajes",
    promoNotifications: "Notificaciones promocionales",
    language: "Idioma",
    theme: "Tema",
    lightMode: "Modo claro",
    darkMode: "Modo oscuro",
    systemDefault: "Predeterminado del sistema",
    privacy: "Privacidad",
    security: "Seguridad",
    changePassword: "Cambiar contraseña",
    twoFactor: "Autenticación de dos factores",
    account: "Cuenta",
    support: "Soporte",
  },
  payment: {
    checkout: "Pagar",
    selectPackage: "Seleccionar paquete",
    paymentMethod: "Método de pago",
    creditCard: "Tarjeta de crédito/débito",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "Procesando pago...",
    paymentSuccess: "Pago exitoso!",
    paymentFailed: "Pago fallido",
    orderSummary: "Resumen del pedido",
    total: "Total",
    coins: "Monedas",
    bonusCoins: "Monedas de bono",
    tryAgain: "Intentar de nuevo",
    secureNote: "Todos los pagos están protegidos y encriptados",
  },
  host: {
    dashboard: "Panel",
    totalEarnings: "Ganancias totales",
    thisWeek: "Esta semana",
    thisMonth: "Este mes",
    totalCalls: "Total llamadas",
    avgRating: "Calificación promedio",
    onlineStatus: "Estado en línea",
    goOnline: "Conectarse",
    goOffline: "Desconectarse",
    setBusy: "Marcar como ocupado",
    earnings: "Ganancias",
    withdraw: "Retirar",
    withdrawal: "Retiro",
    minimumWithdraw: "Mínimo 100 monedas",
    enterAmount: "Ingresar monto",
    withdrawMethod: "Método de retiro",
    bankTransfer: "Transferencia bancaria",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "Detalles de cuenta",
    withdrawSuccess: "Solicitud de retiro enviada",
    withdrawPending: "Tu solicitud está siendo procesada",
    hostSettings: "Configuración del anfitrión",
    availability: "Disponibilidad",
    payoutSettings: "Configuración de pago",
    becomeHost: "Ser anfitrión",
    apply: "Aplicar ahora",
    applicationSent: "¡Solicitud enviada!",
    applicationDesc: "Revisaremos tu solicitud y te contactaremos en 2-3 días hábiles.",
  },
  errors: {
    network: "Error de red. Por favor verifica tu conexión.",
    server: "Error del servidor. Intenta más tarde.",
    unauthorized: "Sesión expirada. Por favor inicia sesión de nuevo.",
    notFound: "El recurso solicitado no fue encontrado.",
    insufficientCoins: "Monedas insuficientes. Por favor recarga.",
    callFailed: "La llamada no pudo conectarse. Intenta de nuevo.",
    permissionDenied: "Permiso denegado.",
    generic: "Algo salió mal. Por favor intenta de nuevo.",
  },

  tabs: {
    home: "Inicio",
    chat: "Chat",
    calls: "Llamadas",
    wallet: "Billetera",
    profile: "Perfil",
  },

  hostSettings: {
    title: "Ajustes de Host",
    availability: "Disponibilidad",
    autoOnline: "Conectarse al abrir la app",
    dnd: "Modo No Molestar",
    dndOn: "Activado — silenciando notificaciones",
    schedule: "Horario de disponibilidad",
    randomCalls: "Llamadas aleatorias",
    availableRandom: "Disponible para llamadas aleatorias",
    randomOn: "Activado — incluido en el grupo aleatorio",
    randomOff: "Desactivado — solo llamadas directas",
    allowVideoRandom: "Permitir videollamadas aleatorias",
    videoDisabled: "Deshabilitado — las llamadas aleatorias están desactivadas",
    videoOn: "Activado — acepta videollamadas aleatorias",
    videoOff: "Desactivado — solo llamadas de audio",
    loading: "Cargando…",
    pushNotifications: "Notificaciones push",
    notificationPrefs: "Preferencias de notificación",
    incomingCallAlerts: "Alertas de llamada entrante",
    chatNotifications: "Notificaciones de chat",
    coinEarnedAlerts: "Alertas de monedas ganadas",
    earnings: "Ganancias",
    payoutMethod: "Método de pago",
    withdrawEarnings: "Retirar ganancias",
    referEarn: "Refiere y gana",
    preferences: "Preferencias",
    appLanguage: "Idioma de la app",
    support: "Soporte",
    helpSupport: "Ayuda y soporte",
    privacyPolicy: "Política de privacidad",
    aboutApp: "Acerca de VoxLink Host",
    account: "Cuenta",
    signOut: "Cerrar sesión",
    deleteAccount: "Eliminar cuenta",
    on: "Activado",
    off: "Desactivado",
    alwaysAvailable: "Siempre disponible",
  },

  homeScreen: {
    online: "Estás en línea",
    offline: "Estás desconectado",
    onlineSub: "Disponible para recibir llamadas",
    offlineSub: "Activa para empezar a aceptar llamadas",
    totalCalls: "Llamadas totales",
    totalHours: "Horas totales",
    earnings: "Ganancias",
    yourCallRates: "Tus tarifas de llamada",
    ratesSub: "Monedas que los usuarios te pagan por minuto",
    edit: "Editar",
    audioPerMin: "Audio / min",
    videoPerMin: "Video / min",
    manage: "Gestionar",
    qaCallRates: "Tarifas",
    qaCallRatesDesc: "Fija tu precio",
    qaTopics: "Mis temas",
    qaTopicsDesc: "Llega a más usuarios",
    qaEarnings: "Ganancias",
    qaEarningsDesc: "Ver historial",
    qaPayouts: "Pagos",
    qaPayoutsDesc: "Retirar monedas",
    qaWallet: "Billetera",
    qaWalletDesc: "Saldo y retiro",
    qaCallHistory: "Historial",
    qaCallHistoryDesc: "Llamadas pasadas",
    qaRefer: "Refiere y gana",
    qaReferDesc: "Invita amigos",
    qaProfile: "Perfil",
    qaProfileDesc: "Editar datos",
    qaSettings: "Ajustes",
    qaSettingsDesc: "Preferencias de la app",
    permsRequired: "Permisos requeridos",
    micLabel: "Micrófono",
    micDesc: "Necesario para llamadas de audio",
    cameraLabel: "Cámara",
    cameraDesc: "Necesario para videollamadas",
    notifLabel: "Notificaciones",
    notifDesc: "Para alertas de llamadas entrantes",
    granted: "Concedido",
    tapToAllow: "Toca para permitir",
    hostTips: "Consejos para hosts",
    tip1: "Conéctate en horas pico (6PM - 10PM)",
    tip2: "Completa tu perfil para más reservas",
    tip3: "Responde rápido para mejorar tu calificación",
    tip4: "Añade más temas para llegar a más usuarios",
  },

  profileScreen: {
    title: "Mi perfil",
    proHost: "Host profesional",
    calls: "Llamadas",
    rating: "Calificación",
    coins: "Monedas",
    onlineStatus: "Estado en línea",
    pushNotifications: "Notificaciones push",
    account: "Cuenta",
    editProfile: "Editar perfil",
    callRates: "Tarifas de llamada",
    myTopics: "Mis temas",
    settings: "Ajustes",
    language: "Idioma",
    more: "Más",
    referEarn: "Refiere y gana",
    helpCenter: "Centro de ayuda",
    privacyPolicy: "Política de privacidad",
    about: "Acerca de VoxLink",
    signOut: "Cerrar sesión",
    signOutConfirm: "¿Seguro que quieres cerrar sesión?",
    permRequiredTitle: "Permiso requerido",
    permRequiredMsg: "Permite el acceso a tu galería de fotos para cambiar tu foto de perfil.",
    turnOffNotifTitle: "Desactivar notificaciones",
    turnOffNotifMsg: "Para desactivar las notificaciones, ve a los Ajustes de tu teléfono y desactiva las notificaciones de VoxLink Host.",
    openSettings: "Abrir ajustes",
    uploadFailedTitle: "Error al subir",
    uploadFailedMsg: "No se pudo subir tu foto. Inténtalo de nuevo.",
    photoUpdated: "¡Foto de perfil actualizada!",
    photoSaved: "Foto guardada",
  },

  callsScreen: {
    title: "Historial de llamadas",
    all: "Todas",
    audio: "Audio",
    video: "Video",
    completed: "Completada",
    missed: "Perdida",
    cancelled: "Cancelada",
    noCalls: "Aún no hay llamadas",
    loadError: "No se pudieron cargar las llamadas. Desliza para actualizar.",
  },

  chatScreen: {
    title: "Mensajes",
    searchPlaceholder: "Buscar conversaciones...",
    noConversations: "Aún no hay conversaciones",
    noMessagesYet: "Aún no hay mensajes",
    now: "ahora",
  },

  walletScreen: {
    title: "Billetera del host",
    availableBalance: "Saldo disponible",
    coins: "Monedas",
    payoutValue: "valor de pago",
    thisWeek: "Esta semana",
    sessions: "Sesiones",
    withdrawn: "Retirado",
    earningsHistory: "Historial de ganancias",
    withdraw: "Retirar",
    noEarnings: "Aún no hay ganancias",
    quickSelect: "Selección rápida de monto",
    orEnter: "O ingresa el monto",
    enterCoinAmount: "Ingresa la cantidad de monedas",
    payoutTo: "Pagar a",
    setupPayout: "Configura tu método de pago",
    edit: "Editar",
    managePayout: "Gestionar método de pago",
    requestWithdrawal: "Solicitar retiro",
    note: "Nota",
    failedLoad: "Error al cargar los datos de ganancias.",
  },
};

export default es;
