// VoxLink — Spanish Strings

const es = {
  common: {
    ok: "Aceptar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Guardar",
    delete: "Eliminar",
    edit: "Editar",
    done: "Listo",
    back: "Atrás",
    close: "Cerrar",
    loading: "Cargando...",
    error: "Algo salió mal",
    retry: "Reintentar",
    submit: "Enviar",
    next: "Siguiente",
    skip: "Omitir",
    yes: "Sí",
    no: "No",
    search: "Buscar",
    filter: "Filtrar",
    clear: "Limpiar",
    apply: "Aplicar",
    share: "Compartir",
    copy: "Copiar",
    copied: "Copiado!",
    noResults: "Sin resultados",
    optional: "Opcional",
    required: "Requerido",
    all: "Todos",
    more: "Más",
    less: "Menos",
    seeAll: "Ver todo",
    noData: "Sin datos disponibles",
    refresh: "Actualizar",
  },
  auth: {
    login: "Iniciar sesión",
    register: "Registrarse",
    logout: "Cerrar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    newPassword: "Nueva contraseña",
    phone: "Número de teléfono",
    otp: "Código de verificación",
    sendOtp: "Enviar OTP",
    verifyOtp: "Verificar OTP",
    resendOtp: "Reenviar OTP",
    fullName: "Nombre completo",
    createAccount: "Crear cuenta",
    alreadyHaveAccount: "¿Ya tienes cuenta?",
    dontHaveAccount: "¿No tienes cuenta?",
    welcomeBack: "¡Bienvenido de nuevo!",
    loginToContinue: "Inicia sesión para continuar",
    createYourAccount: "Crea tu cuenta",
    joinVoxLink: "Únete a VoxLink hoy",
    enterOtp: "Introduce el OTP enviado a",
    passwordResetSent: "Correo de restablecimiento enviado",
    checkEmail: "Revisa tu correo para las instrucciones",
    passwordChanged: "Contraseña cambiada exitosamente",
    invalidCredentials: "Correo o contraseña inválidos",
    accountDeleted: "Cuenta eliminada exitosamente",
    deleteAccountConfirm: "¿Seguro que quieres eliminar tu cuenta? Esta acción es irreversible.",
  },
  nav: {
    home: "Inicio",
    search: "Buscar",
    messages: "Mensajes",
    wallet: "Billetera",
    profile: "Perfil",
    notifications: "Notificaciones",
  },
  home: {
    greeting: "Hola",
    findHosts: "Buscar anfitrión",
    topListeners: "Mejores oyentes",
    trending: "En tendencia",
    newHosts: "Nuevos anfitriones",
    onlineNow: "En línea ahora",
    featuredHosts: "Anfitriones destacados",
    seeAll: "Ver todo",
    searchPlaceholder: "Buscar anfitriones, temas...",
  },
  hosts: {
    host: "Anfitrión",
    listener: "Oyente",
    online: "En línea",
    offline: "Fuera de línea",
    busy: "Ocupado",
    rating: "Calificación",
    reviews: "Reseñas",
    review: "Reseña",
    coinsPerMinute: "monedas/min",
    totalMinutes: "min totales",
    specialties: "Especialidades",
    languages: "Idiomas",
    about: "Acerca de",
    callNow: "Llamar ahora",
    audioCall: "Llamada de audio",
    videoCall: "Videollamada",
    sendMessage: "Enviar mensaje",
    talkNow: "Hablar ahora",
    noHostsFound: "No se encontraron anfitriones",
    adjustFilters: "Intenta ajustar los filtros",
    topRated: "Mejor calificado",
    viewProfile: "Ver perfil",
    startCall: "Iniciar llamada",
  },
  calls: {
    incoming: "Llamada entrante",
    outgoing: "Conectando...",
    ongoing: "En llamada",
    ended: "Llamada terminada",
    audio: "Llamada de audio",
    video: "Videollamada",
    accept: "Aceptar",
    decline: "Rechazar",
    endCall: "Terminar llamada",
    mute: "Silenciar",
    unmute: "Activar micrófono",
    speaker: "Altavoz",
    flipCamera: "Voltear cámara",
    callDuration: "Duración de la llamada",
    callWith: "Llamada con",
    rateCall: "Calificar esta llamada",
    callHistory: "Historial de llamadas",
    noCallHistory: "Sin historial de llamadas",
    callCost: "Costo de la llamada",
    perMinute: "por minuto",
    lowBalance: "Saldo bajo de monedas",
    lowBalanceMsg: "Pocas monedas. Recarga para continuar.",
    callEnded: "Llamada terminada",
    callEndedMsg: "Tu llamada ha terminado",
    missed: "Perdida",
    answered: "Contestada",
    rejected: "Rechazada",
  },
  chat: {
    messages: "Mensajes",
    newMessage: "Nuevo mensaje",
    typeMessage: "Escribe un mensaje...",
    send: "Enviar",
    noMessages: "Sin mensajes aún",
    startConversation: "Iniciar conversación",
    online: "En línea",
    offline: "Fuera de línea",
    typing: "escribiendo...",
    delivered: "Entregado",
    read: "Leído",
    deleteChat: "Eliminar chat",
    deleteChatConfirm: "¿Seguro que quieres eliminar esta conversación?",
  },
  wallet: {
    wallet: "Billetera",
    coinBalance: "Saldo de monedas",
    coins: "Monedas",
    coin: "Moneda",
    buyCoins: "Comprar monedas",
    coinHistory: "Historial de monedas",
    transactions: "Transacciones",
    noTransactions: "Sin transacciones aún",
    purchased: "Comprado",
    spent: "Gastado",
    bonus: "Bono",
    refunded: "Reembolsado",
    withdrawal: "Retiro",
    totalSpent: "Total gastado",
    totalPurchased: "Total comprado",
    popular: "Más popular",
    bestValue: "Mejor valor",
    bonus_label: "BONO",
    recharge: "Recargar",
    choosePackage: "Elegir paquete",
    instantDelivery: "Entrega instantánea",
    securePayment: "Pago seguro",
    guaranteed: "Satisfacción garantizada",
  },
  profile: {
    profile: "Perfil",
    editProfile: "Editar perfil",
    myProfile: "Mi perfil",
    name: "Nombre",
    email: "Correo electrónico",
    phone: "Teléfono",
    gender: "Género",
    male: "Masculino",
    female: "Femenino",
    other: "Otro",
    country: "País",
    bio: "Biografía",
    language: "Idioma",
    settings: "Configuración",
    helpCenter: "Centro de ayuda",
    privacy: "Política de privacidad",
    about: "Acerca de VoxLink",
    shareApp: "Compartir VoxLink",
    rateApp: "Calificar la app",
    logout: "Cerrar sesión",
    deleteAccount: "Eliminar cuenta",
    callHistory: "Historial de llamadas",
    joinedOn: "Miembro desde",
    totalCalls: "Total de llamadas",
    hoursSpent: "Horas dedicadas",
  },
  settings: {
    settings: "Configuración",
    notifications: "Notificaciones",
    callNotifications: "Notificaciones de llamadas",
    messageNotifications: "Notificaciones de mensajes",
    promoNotifications: "Notificaciones promocionales",
    language: "Idioma",
    theme: "Tema",
    lightMode: "Modo claro",
    darkMode: "Modo oscuro",
    systemDefault: "Predeterminado del sistema",
    privacy: "Privacidad",
    security: "Seguridad",
    changePassword: "Cambiar contraseña",
    twoFactor: "Autenticación de dos factores",
    account: "Cuenta",
    support: "Soporte",
  },
  payment: {
    checkout: "Pagar",
    selectPackage: "Seleccionar paquete",
    paymentMethod: "Método de pago",
    creditCard: "Tarjeta de crédito/débito",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "Procesando pago...",
    paymentSuccess: "Pago exitoso!",
    paymentFailed: "Pago fallido",
    orderSummary: "Resumen del pedido",
    total: "Total",
    coins: "Monedas",
    bonusCoins: "Monedas de bono",
    tryAgain: "Intentar de nuevo",
    secureNote: "Todos los pagos están protegidos y encriptados",
  },
  host: {
    dashboard: "Panel",
    totalEarnings: "Ganancias totales",
    thisWeek: "Esta semana",
    thisMonth: "Este mes",
    totalCalls: "Total llamadas",
    avgRating: "Calificación promedio",
    onlineStatus: "Estado en línea",
    goOnline: "Conectarse",
    goOffline: "Desconectarse",
    setBusy: "Marcar como ocupado",
    earnings: "Ganancias",
    withdraw: "Retirar",
    withdrawal: "Retiro",
    minimumWithdraw: "Mínimo 100 monedas",
    enterAmount: "Ingresar monto",
    withdrawMethod: "Método de retiro",
    bankTransfer: "Transferencia bancaria",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "Detalles de cuenta",
    withdrawSuccess: "Solicitud de retiro enviada",
    withdrawPending: "Tu solicitud está siendo procesada",
    hostSettings: "Configuración del anfitrión",
    availability: "Disponibilidad",
    payoutSettings: "Configuración de pago",
    becomeHost: "Ser anfitrión",
    apply: "Aplicar ahora",
    applicationSent: "¡Solicitud enviada!",
    applicationDesc: "Revisaremos tu solicitud y te contactaremos en 2-3 días hábiles.",
  },
  errors: {
    network: "Error de red. Por favor verifica tu conexión.",
    server: "Error del servidor. Intenta más tarde.",
    unauthorized: "Sesión expirada. Por favor inicia sesión de nuevo.",
    notFound: "El recurso solicitado no fue encontrado.",
    insufficientCoins: "Monedas insuficientes. Por favor recarga.",
    callFailed: "La llamada no pudo conectarse. Intenta de nuevo.",
    permissionDenied: "Permiso denegado.",
    generic: "Algo salió mal. Por favor intenta de nuevo.",
  },

  tabs: {
    home: "Inicio",
    chat: "Chat",
    calls: "Llamadas",
    wallet: "Billetera",
    profile: "Perfil",
  },

  hostSettings: {
    title: "Ajustes de Host",
    availability: "Disponibilidad",
    autoOnline: "Conectarse al abrir la app",
    dnd: "Modo No Molestar",
    dndOn: "Activado — silenciando notificaciones",
    schedule: "Horario de disponibilidad",
    randomCalls: "Llamadas aleatorias",
    availableRandom: "Disponible para llamadas aleatorias",
    randomOn: "Activado — incluido en el grupo aleatorio",
    randomOff: "Desactivado — solo llamadas directas",
    allowVideoRandom: "Permitir videollamadas aleatorias",
    videoDisabled: "Deshabilitado — las llamadas aleatorias están desactivadas",
    videoOn: "Activado — acepta videollamadas aleatorias",
    videoOff: "Desactivado — solo llamadas de audio",
    loading: "Cargando…",
    pushNotifications: "Notificaciones push",
    notificationPrefs: "Preferencias de notificación",
    incomingCallAlerts: "Alertas de llamada entrante",
    chatNotifications: "Notificaciones de chat",
    coinEarnedAlerts: "Alertas de monedas ganadas",
    earnings: "Ganancias",
    payoutMethod: "Método de pago",
    withdrawEarnings: "Retirar ganancias",
    referEarn: "Refiere y gana",
    preferences: "Preferencias",
    appLanguage: "Idioma de la app",
    support: "Soporte",
    helpSupport: "Ayuda y soporte",
    privacyPolicy: "Política de privacidad",
    aboutApp: "Acerca de VoxLink Host",
    account: "Cuenta",
    signOut: "Cerrar sesión",
    deleteAccount: "Eliminar cuenta",
    on: "Activado",
    off: "Desactivado",
    alwaysAvailable: "Siempre disponible",
  },

  homeScreen: {
    online: "Estás en línea",
    offline: "Estás desconectado",
    onlineSub: "Disponible para recibir llamadas",
    offlineSub: "Activa para empezar a aceptar llamadas",
    totalCalls: "Llamadas totales",
    totalHours: "Horas totales",
    earnings: "Ganancias",
    yourCallRates: "Tus tarifas de llamada",
    ratesSub: "Monedas que los usuarios te pagan por minuto",
    edit: "Editar",
    audioPerMin: "Audio / min",
    videoPerMin: "Video / min",
    manage: "Gestionar",
    qaCallRates: "Tarifas",
    qaCallRatesDesc: "Fija tu precio",
    qaTopics: "Mis temas",
    qaTopicsDesc: "Llega a más usuarios",
    qaEarnings: "Ganancias",
    qaEarningsDesc: "Ver historial",
    qaPayouts: "Pagos",
    qaPayoutsDesc: "Retirar monedas",
    qaWallet: "Billetera",
    qaWalletDesc: "Saldo y retiro",
    qaCallHistory: "Historial",
    qaCallHistoryDesc: "Llamadas pasadas",
    qaRefer: "Refiere y gana",
    qaReferDesc: "Invita amigos",
    qaProfile: "Perfil",
    qaProfileDesc: "Editar datos",
    qaSettings: "Ajustes",
    qaSettingsDesc: "Preferencias de la app",
    permsRequired: "Permisos requeridos",
    micLabel: "Micrófono",
    micDesc: "Necesario para llamadas de audio",
    cameraLabel: "Cámara",
    cameraDesc: "Necesario para videollamadas",
    notifLabel: "Notificaciones",
    notifDesc: "Para alertas de llamadas entrantes",
    granted: "Concedido",
    tapToAllow: "Toca para permitir",
    hostTips: "Consejos para hosts",
    tip1: "Conéctate en horas pico (6PM - 10PM)",
    tip2: "Completa tu perfil para más reservas",
    tip3: "Responde rápido para mejorar tu calificación",
    tip4: "Añade más temas para llegar a más usuarios",
  },

  profileScreen: {
    title: "Mi perfil",
    proHost: "Host profesional",
    calls: "Llamadas",
    rating: "Calificación",
    coins: "Monedas",
    onlineStatus: "Estado en línea",
    pushNotifications: "Notificaciones push",
    account: "Cuenta",
    editProfile: "Editar perfil",
    callRates: "Tarifas de llamada",
    myTopics: "Mis temas",
    settings: "Ajustes",
    language: "Idioma",
    more: "Más",
    referEarn: "Refiere y gana",
    helpCenter: "Centro de ayuda",
    privacyPolicy: "Política de privacidad",
    about: "Acerca de VoxLink",
    signOut: "Cerrar sesión",
    signOutConfirm: "¿Seguro que quieres cerrar sesión?",
    permRequiredTitle: "Permiso requerido",
    permRequiredMsg: "Permite el acceso a tu galería de fotos para cambiar tu foto de perfil.",
    turnOffNotifTitle: "Desactivar notificaciones",
    turnOffNotifMsg: "Para desactivar las notificaciones, ve a los Ajustes de tu teléfono y desactiva las notificaciones de VoxLink Host.",
    openSettings: "Abrir ajustes",
    uploadFailedTitle: "Error al subir",
    uploadFailedMsg: "No se pudo subir tu foto. Inténtalo de nuevo.",
    photoUpdated: "¡Foto de perfil actualizada!",
    photoSaved: "Foto guardada",
  },

  callsScreen: {
    title: "Historial de llamadas",
    all: "Todas",
    audio: "Audio",
    video: "Video",
    completed: "Completada",
    missed: "Perdida",
    cancelled: "Cancelada",
    noCalls: "Aún no hay llamadas",
    loadError: "No se pudieron cargar las llamadas. Desliza para actualizar.",
  },

  chatScreen: {
    title: "Mensajes",
    searchPlaceholder: "Buscar conversaciones...",
    noConversations: "Aún no hay conversaciones",
    noMessagesYet: "Aún no hay mensajes",
    now: "ahora",
  },

  walletScreen: {
    title: "Billetera del host",
    availableBalance: "Saldo disponible",
    coins: "Monedas",
    payoutValue: "valor de pago",
    thisWeek: "Esta semana",
    sessions: "Sesiones",
    withdrawn: "Retirado",
    earningsHistory: "Historial de ganancias",
    withdraw: "Retirar",
    noEarnings: "Aún no hay ganancias",
    quickSelect: "Selección rápida de monto",
    orEnter: "O ingresa el monto",
    enterCoinAmount: "Ingresa la cantidad de monedas",
    payoutTo: "Pagar a",
    setupPayout: "Configura tu método de pago",
    edit: "Editar",
    managePayout: "Gestionar método de pago",
    requestWithdrawal: "Solicitar retiro",
    note: "Nota",
    failedLoad: "Error al cargar los datos de ganancias.",
  },

  loginScreen: {
    tagline: "Gana · Conecta · Haz crecer tu audiencia",
    chipKyc: "KYC verificado",
    chipEarn: "Gana monedas",
    chipPlatform: "Plataforma de host",
    welcomeBack: "Bienvenido de nuevo",
    subtitle: "Inicia sesión en tu cuenta de host",
    emailPlaceholder: "Correo electrónico",
    passwordPlaceholder: "Contraseña",
    signIn: "Iniciar sesión como host",
    orContinue: "o continúa con",
    continueGoogle: "Continuar con Google",
    signingIn: "Iniciando sesión...",
    newPrompt: "¿Nuevo en VoxLink Host? ",
    applyNow: "Aplicar ahora",
  },

  registerScreen: {
    stepAccount: "Cuenta",
    stepProfile: "Perfil",
    stepHostInfo: "Datos de host",
    stepKyc: "Docs KYC",
    title: "Conviértete en host",
    headerSub: "Completa 4 pasos para empezar a ganar",
    createTitle: "Crea tu cuenta",
    createSub: "Este será tu acceso a VoxLink Host",
    namePlaceholder: "Nombre completo",
    emailPlaceholder: "Correo electrónico",
    passwordPlaceholder: "Contraseña (8+ caracteres)",
    continueBtn: "Continuar",
    orSignUp: "o regístrate con",
    continueGoogle: "Continuar con Google",
    signingIn: "Iniciando sesión...",
    alreadyRegistered: "¿Ya estás registrado? ",
    signIn: "Iniciar sesión",
  },

  authToasts: {
    missingFields: "Campos faltantes",
    loginMissing: "Por favor ingresa el correo y la contraseña.",
    invalidEmail: "Correo inválido",
    invalidEmailMsg: "Por favor ingresa un correo válido.",
    loginFailed: "Error de inicio de sesión",
    loginFailedMsg: "Correo o contraseña inválidos.",
    notSupported: "No compatible",
    playServices: "Google Play Services no está disponible.",
    connectionError: "Error de conexión",
    noInternet: "Sin conexión a internet.",
    signInFailed: "Error de inicio de sesión",
    googleFailed: "Falló el inicio de sesión con Google",
    almostThere: "Casi listo",
    googleWelcomeHost: "¡Bienvenido! Completa tu perfil de host y el KYC.",
    googleWelcomeProfile: "¡Bienvenido! Completa tu perfil para aplicar como host.",
    signInFailedRetry: "Falló el inicio de sesión. Inténtalo de nuevo.",
    googleNoAccount: "No se pudo obtener la información de la cuenta de Google.",
    googleNoToken: "El inicio de sesión con Google no devolvió un token. Actualiza la app o inténtalo de nuevo.",
    registerMissing: "Por favor completa todos los campos.",
    weakPassword: "Contraseña débil",
    weakPasswordMsg: "La contraseña debe tener al menos 8 caracteres.",
    welcomeBack: "Bienvenido de nuevo",
    resuming: "Reanudando tu registro incompleto.",
    alreadyRegisteredTitle: "Ya registrado",
    alreadyRegisteredMsg: "Este correo ya está registrado. Por favor inicia sesión.",
    createFailed: "No se pudo crear la cuenta. Inténtalo de nuevo.",
  },

  forgotPasswordScreen: {
    checkEmail: "Revisa tu correo",
    forgotPassword: "¿Olvidaste tu contraseña?",
    sentLine1: "Enviamos un OTP de 6 dígitos a",
    sentLine2: "Ingresa el código y establece una nueva contraseña.",
    enterEmailPrompt: "Ingresa tu correo registrado. Te enviaremos un OTP para restablecer tu contraseña.",
    resetPassword: "Restablecer contraseña",
    otpPlaceholder: "Ingresa el código OTP",
    newPasswordPlaceholder: "Nueva contraseña",
    confirmPasswordPlaceholder: "Confirmar nueva contraseña",
    resetting: "Restableciendo...",
    resetBtn: "Restablecer contraseña",
    didntReceive: "¿No lo recibiste? ",
    resendIn: "Reenviar en",
    resendOtp: "Reenviar OTP",
    findAccount: "Encuentra tu cuenta",
    emailPlaceholder: "Correo electrónico",
    sending: "Enviando...",
    sendOtp: "Enviar OTP",
    backTo: "Volver a ",
    signIn: "Iniciar sesión",
    enterEmailError: "Por favor ingresa tu correo electrónico.",
    otpSent: "OTP enviado a tu correo.",
    emailSent: "Correo enviado",
    emailNotFound: "Correo no encontrado. Verifica e inténtalo de nuevo.",
    enterOtpError: "Por favor ingresa el OTP enviado a tu correo.",
    weakPassword: "Contraseña débil",
    weakPasswordMsg: "La contraseña debe tener al menos 8 caracteres.",
    mismatch: "No coinciden",
    passwordsDontMatch: "Las contraseñas no coinciden.",
    successTitle: "Éxito",
    resetSuccess: "¡Contraseña actualizada con éxito! Por favor inicia sesión.",
    errorTitle: "Error",
    resetFailed: "No se pudo restablecer la contraseña. El OTP puede haber expirado.",
  },

  onboardingScreen: {
    slide1Title: "ENCUENTRA",
    slide1Sub: "Puedes conectarte con personas de\ntodo el mundo para chatear, enviar mensajes\ny hacer conexiones con ellas.",
    slide2Title: "CHATEA",
    slide2Sub: "Chatea con desconocidos para conocerse\nmejor y tener una buena\ncompatibilidad.",
    slide3Title: "VIDEOLLAMADA",
    slide3Sub: "Puedes compartir tus videos y fotos\ncon tus amigos y conexiones.",
  },

  profileSetupScreen: {
    headerSub: "Paso 2 de 4 — Tu perfil",
    sectionTitle: "Información de tu perfil",
    sectionSub: "Esto será visible para los usuarios que te llamen",
    uploading: "Subiendo...",
    tapAddPhoto: "Toca para añadir foto de perfil",
    namePlaceholder: "Nombre para mostrar",
    dobPlaceholder: "Fecha de nacimiento (toca para elegir)",
    phonePlaceholder: "Número de móvil",
    genderLabel: "Género",
    continueBtn: "Continuar → Datos de host",
    done: "Listo",
    dobTitle: "Fecha de nacimiento",
    day: "Día",
    month: "Mes",
    year: "Año",
    months: ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],
    uploadFailed: "Error al subir",
    uploadFailedMsg: "No se pudo subir la foto. Inténtalo de nuevo.",
    missingFields: "Campos faltantes",
    missingFieldsMsg: "Por favor completa todos los campos requeridos.",
    invalidPhone: "Teléfono inválido",
    invalidPhoneMsg: "Por favor ingresa un número de móvil válido.",
    saveFailed: "Error al guardar",
    saveFailedMsg: "No se pudo guardar tu perfil. Inténtalo de nuevo.",
  },

  becomeScreen: {
    headerSub: "Paso 3 de 4 — Datos de host",
    sectionTitle: "Tu perfil de host",
    sectionSub: "Ayuda a los usuarios a entender lo que ofreces",
    specialtiesLabel: "Especialidades (elige 1–5)",
    languagesLabel: "Idiomas",
    bioLabel: "Biografía",
    bioPlaceholder: "Cuéntales a los usuarios sobre ti — tu experiencia, personalidad y qué hace especiales tus llamadas...",
    experienceLabel: "Experiencia (opcional)",
    experiencePlaceholder: "ej. 3 años como coach de vida",
    callTypeLabel: "Tipo de llamada ofrecida",
    audioOnly: "🎤 Solo audio",
    videoOnly: "🎥 Solo video",
    both: "🎤🎥 Ambos",
    ratesLabel: "Tus tarifas de llamada (monedas/min)",
    audio: "Audio",
    video: "Video",
    coinsPerMin: "monedas/min",
    note: "Las tarifas son sugerencias. El admin puede ajustarlas tras la aprobación.",
    continueBtn: "Continuar →  Documentos KYC",
    selectSpecialty: "Selecciona especialidad",
    chooseSpecialty: "Elige al menos una especialidad.",
    bioTooShort: "Biografía muy corta",
    bioTooShortMsg: "Por favor escribe una biografía de al menos 20 caracteres.",
  },

  kycScreen: {
    headerSub: "Paso 4 de 4 — Documentos KYC",
    sectionTitle: "Verificación de identidad",
    sectionSub: "Requerida para empezar a hospedar. Tus documentos se almacenan de forma segura.",
    notice: "El KYC es obligatorio según las normas de India. Los documentos solo los revisa el admin y nunca se comparten con los usuarios.",
    dobLabel: "Fecha de nacimiento",
    fromStep2: "Del paso 2",
    dobPlaceholder: "DD/MM/AAAA (ej. 22/05/1998)",
    docAadharFront: "Aadhar frente",
    docAadharFrontSub: "Foto del frente de la tarjeta Aadhar",
    docAadharBack: "Aadhar reverso",
    docAadharBackSub: "Foto del reverso de la tarjeta Aadhar",
    docVideo: "Video de verificación",
    docVideoSub: "Video corto (5–15 seg) tuyo sosteniendo el Aadhar",
    uploading: "Subiendo...",
    uploaded: "Subido ✓",
    tipsTitle: "Consejos para la aprobación",
    tip1: "Asegúrate de que las fotos del Aadhar sean claras y no borrosas",
    tip2: "Sostén tu tarjeta Aadhar claramente en el video de verificación",
    tip3: "Mira a la cámara mientras grabas",
    submitting: "Enviando...",
    submit: "Enviar solicitud",
    uploadFailed: "Error al subir",
    uploadFailedMsg: "No se pudo subir el archivo. Inténtalo de nuevo.",
    missingDocs: "Documentos faltantes",
    missingDocsMsg: "Por favor sube las fotos del frente y reverso del Aadhar.",
    missingDob: "Falta fecha de nacimiento",
    missingDobMsg: "Falta la fecha de nacimiento. Vuelve al paso 2 y selecciona tu fecha.",
    submitFailed: "Error al enviar",
    submitFailedMsg: "No se pudo enviar tu solicitud. Inténtalo de nuevo.",
  },

  statusScreen: {
    headerTitle: "Solicitud de host",
    headerSub: "Sigue el estado de tu verificación KYC",
    checking: "Comprobando el estado de la solicitud...",
    pendingTitle: "Solicitud enviada",
    pendingMsg: "Tu solicitud está en la cola. Nuestro equipo la revisará en 24–48 horas.",
    underReviewTitle: "En revisión",
    underReviewMsg: "Nuestro equipo está revisando activamente tu solicitud. Pronto tendrás respuesta.",
    approvedTitle: "¡Felicidades!",
    approvedMsg: "¡Tu solicitud ha sido aprobada! Ahora eres un host verificado en VoxLink.",
    rejectedTitle: "Solicitud rechazada",
    rejectedMsg: "Lamentablemente, tu solicitud no fue aprobada. Consulta el motivo abajo y vuelve a aplicar.",
    notAppliedTitle: "No se encontró solicitud",
    notAppliedMsg: "Aún no has enviado una solicitud de host.",
    approvedSub: "Ahora eres un host verificado en VoxLink. ¡Empieza a aceptar llamadas y ganar monedas!",
    earnCoins: "Gana monedas",
    buildRating: "Construye tu calificación",
    takeCalls: "Recibe llamadas",
    timelineTitle: "Cronología de la solicitud",
    tlAccount: "Cuenta creada",
    tlSubmitted: "Solicitud enviada",
    tlReview: "En revisión",
    tlDecision: "Decisión tomada",
    continueDashboard: "Continuar al panel",
    reasonRejection: "Motivo del rechazo",
    reapply: "Volver a aplicar",
    startApplication: "Iniciar solicitud",
    autoChecking: "Comprobando automáticamente cada 10 segundos...",
    loadError: "Error al cargar el estado de la solicitud.",
  },

  audioCallScreen: {
    voiceCall: "Llamada de voz",
    ringing: "Sonando...",
    connecting: "Conectando...",
    connected: "Conectado",
    reconnecting: "Caída de red — reconectando...",
    connFailed: "Conexión fallida — reintentando...",
    callEnded: "Llamada finalizada",
    unknown: "Desconocido",
    muted: "🔇 Silenciado",
    coinsPerMin: "monedas / min",
    remaining: "restante",
    minLeft: "min restantes",
    callEndingSoon: "La llamada terminará pronto — ",
    micNeeded: "Se necesita acceso al micrófono — Toca para arreglar",
    mute: "Silenciar",
    unmute: "Activar mic",
    speaker: "Altavoz",
    speakerOn: "Altavoz activado",
  },

  videoCallScreen: {
    connecting: "Conectando...",
    connected: "Conectado",
    reconnecting: "Caída de red — reconectando...",
    connFailed: "Conexión fallida — reintentando...",
    ringing: "Sonando...",
    cameraOff: "Cámara apagada",
    connectionIssue: "Problema de conexión",
    live: "EN VIVO",
    settingUp: "Estableciendo conexión segura...",
    waitingResponse: "Esperando respuesta...",
    connectingName: "Conectando...",
    cameraUnavailable: "Cámara no disponible",
    startingCamera: "Iniciando cámara…",
    noPermission: "Sin permiso",
    cameraOffLabel: "Cámara apagada",
    you: "Tú",
    mutedBadge: "Silenciado",
    noMic: "Sin mic",
    callEndingSoon: "La llamada terminará pronto — ",
    minLeft: "min restantes",
    secLeft: "s restantes",
    ctrlCamera: "Cámara",
    ctrlCamOff: "Cám apagada",
    ctrlUnmute: "Activar",
    ctrlMute: "Silenciar",
    ctrlEnd: "Finalizar",
    ctrlFlip: "Voltear",
    ctrlSpeaker: "Altavoz",
    ctrlEarpiece: "Auricular",
  },

  incomingCallScreen: {
    incomingVideo: "Videollamada entrante",
    incomingAudio: "Llamada de audio entrante",
    unknown: "Desconocido",
    voxlinkHost: "Host de VoxLink",
    voxlinkUser: "Usuario de VoxLink",
    decline: "Rechazar",
    accept: "Aceptar",
  },

  outgoingCallScreen: {
    videoCall: "Videollamada",
    voiceCall: "Llamada de voz",
    callDeclined: "Llamada rechazada",
    noAnswer: "Sin respuesta",
    ringing: "Sonando...",
    connecting: "Conectando...",
    cancel: "Cancelar",
  },

  callSummaryScreen: {
    autoEndedBanner: "El usuario se quedó sin monedas — la llamada se desconectó automáticamente",
    callAutoEnded: "Llamada finalizada automáticamente",
    callCompleted: "Llamada completada",
    withName: "con",
    duration: "Duración",
    coinsEarned: "Monedas ganadas",
    video: "Video",
    audio: "Audio",
    ratePrefix: "Calificar a",
    rateSub: "Comparte tu experiencia de esta llamada",
    ratingLabels: ["", "Mala", "Regular", "Buena", "Muy buena", "¡Excelente!"],
    submitRating: "⭐ Enviar calificación",
    skip: "Omitir",
    thankYouTitle: "¡Gracias! 🙏",
    thankYouSub: "Tu calificación ha sido enviada",
    viewEarnings: "Ver ganancias",
    backHome: "Volver al inicio",
    ratingError: "Error al enviar la calificación, inténtalo de nuevo.",
    errorTitle: "Error",
    user: "Usuario",
  },

  callHistoryScreen: {
    title: "Historial de llamadas",
    all: "Todas",
    audio: "Audio",
    video: "Video",
    completed: "Completada",
    missed: "Perdida",
    cancelled: "Cancelada",
    noHistory: "No se encontró historial de llamadas",
    coins: "monedas",
    loadFailed: "Error al cargar el historial de llamadas.",
  },

  aboutScreen: {
    title: "Acerca de VoxLink",
    tagline: "Conexión de voz y video — Edición host",
    version: "Versión",
    statActiveUsers: "Usuarios activos",
    statHosts: "Hosts",
    statCallsMade: "Llamadas realizadas",
    statAppRating: "Calificación de la app",
    whatIsTitle: "¿Qué es VoxLink Host?",
    whatIsBody1: "VoxLink Host es la app dedicada a los hosts verificados de la plataforma VoxLink. Como host, te conectas con usuarios para conversaciones de audio y video significativas — ya sea consejos de vida, práctica de idiomas, apoyo emocional o compañía.",
    whatIsBody2: "Los hosts ganan monedas por cada minuto de llamadas completadas. Las monedas se convierten en dinero real y se retiran directamente a tu cuenta bancaria. Define tu propio horario, haz crecer tu audiencia y gana según tus condiciones.",
    featuresTitle: "Funciones para hosts",
    featHd: "Llamadas de audio y video en HD",
    featEncrypted: "Cifrado de extremo a extremo",
    featEarn: "Gana monedas por minuto",
    featDashboard: "Panel de ganancias en tiempo real",
    featChat: "Chat con usuarios en la app",
    featRatings: "Calificaciones y reseñas",
    featSchedule: "Horario de disponibilidad flexible",
    connectTitle: "Conéctate con nosotros",
    linkWebsite: "Sitio web",
    linkTwitter: "Twitter / X",
    linkInstagram: "Instagram",
    linkContact: "Contáctanos",
    privacyPolicy: "Política de privacidad",
    helpCenter: "Centro de ayuda",
    copyright: "© 2026 VoxLink Inc. Todos los derechos reservados.",
  },

  callRatesScreen: {
    title: "Tarifas de llamada",
    helpA: "Define cuántas monedas te pagan los usuarios por minuto. Las videollamadas suelen ganar más que el audio. En tu nivel actual puedes cobrar hasta ",
    coinsPerMinAudio: " monedas/min por audio",
    helpB: " y ",
    coinsPerMinVideo: " monedas/min por video",
    helpC: " (límite del nivel admin +",
    helpD: " de bono). Alcanza niveles más altos para subir estos límites.",
    levelWord: "Nivel",
    hostSuffix: " host",
    yourRates: "Tus tarifas",
    audioCall: "Llamada de audio",
    audioSub: "Por minuto para llamadas de voz",
    videoCall: "Videollamada",
    videoSub: "Por minuto para videollamadas",
    coinsMin: "monedas / min",
    maxLabel: "Máx ",
    upToLabel: "Hasta ",
    capSuffix: " monedas/min en tu nivel",
    estTitle: "Estimación de ganancias",
    est10AudioPrefix: "Llamada de audio de 10 min ≈ ",
    est10VideoPrefix: "Videollamada de 10 min ≈ ",
    coinsSuffix: " monedas",
    estNote: "Las monedas se añaden a tus ganancias después de cada llamada completada.",
    saveRates: "Guardar tarifas",
    ratesSaved: "Tus tarifas de llamada se han actualizado.",
    ratesSavedTitle: "Tarifas guardadas",
    saveFailed: "Error al guardar las tarifas. Inténtalo de nuevo.",
  },

  earningsHistoryScreen: {
    title: "Historial de ganancias",
    totalEarnings: "Ganancias totales",
    earned: "Ganado",
    withdrawn: "Retirado",
    tabAll: "Todo",
    tabEarned: "Ganado",
    tabWithdrawn: "Retirado",
    tabBonus: "Bono",
    noTransactions: "No se encontraron transacciones",
    loadFailed: "Error al cargar el historial de ganancias.",
    today: "Hoy",
    yesterday: "Ayer",
    ref: "Ref: ",
  },

  helpCenterScreen: {
    title: "Centro de ayuda",
    bannerTitle: "Ayuda y FAQ para hosts",
    bannerSub: "Encuentra respuestas a preguntas comunes de hosts",
    contactTitle: "Contactar soporte de host",
    faqTitle: "Preguntas frecuentes",
  },

  levelBenefitsScreen: {
    title: "Beneficios de nivel",
    subtitle: "Sube de nivel, gana más",
    current: "Actual",
    unlocked: "Desbloqueado",
    locked: "Bloqueado",
    requirements: "Requisitos",
    ratedCalls: " llamadas calificadas",
    rating: " de calificación",
    rewardsPerks: "Recompensas y beneficios",
    earningsSuffix: "% de ganancias",
    audioUpTo: "🎙️ Audio hasta ",
    videoUpTo: "📹 Video hasta ",
    perMin: "/min",
    higherVisibility: "🚀 Mayor visibilidad",
    youreAtLevel: "Estás en el nivel ",
    maxLevelMsg: "Has alcanzado el nivel máximo. ¡Sigue así!",
    progressMid: "% del camino hacia ",
    loadError: "No se pudieron cargar los beneficios de nivel. Verifica tu conexión e inténtalo de nuevo.",
    retry: "Reintentar",
    retrying: "Reintentando…",
    footnote: "Las llamadas calificadas son las que recibieron una calificación de estrellas. Las recompensas de nivel se pagan una vez al alcanzar cada nivel por primera vez. Los niveles más altos te permiten cobrar más, quedarte con una mayor parte de las ganancias y posicionarte mejor ante los usuarios.",
  },

  manageTopicsScreen: {
    title: "Mis temas",
    helpPrefix: "Elige los temas de los que hablas. Los usuarios que naveguen por estos temas te encontrarán más rápido. Selecciona hasta ",
    helpSuffix: ".",
    topics: "Temas",
    addYourOwn: "Añade el tuyo",
    customPlaceholder: "ej. Astrología, Fitness…",
    add: "Añadir",
    noTopics: "Aún no hay temas disponibles. Añade el tuyo abajo.",
    saveTopics: "Guardar temas",
    maxPrefix: "Puedes seleccionar hasta ",
    maxSuffix: " temas.",
    topicsSaved: "Tus temas se han actualizado.",
    topicsSavedTitle: "Temas guardados",
    saveFailed: "Error al guardar los temas. Inténtalo de nuevo.",
  },

  notificationsScreen: {
    title: "Notificaciones",
    markAllRead: "Marcar todo como leído",
    empty: "Aún no hay notificaciones",
    loadFailed: "Error al cargar las notificaciones.",
    markFailed: "Error al marcar las notificaciones como leídas.",
    updateFailed: "Error al actualizar la notificación.",
  },

  payoutMethodScreen: {
    title: "Método de pago",
    help: "Elige cómo quieres recibir tus ganancias. Tus solicitudes de retiro usarán esta cuenta por defecto.",
    channel: "Canal",
    details: "Detalles",
    bank: "Cuenta bancaria",
    upi: "UPI",
    paytm: "Paytm",
    phonepe: "PhonePe",
    accountHolder: "Nombre del titular de la cuenta",
    accountHolderPh: "Nombre completo en la cuenta",
    accountNumber: "Número de cuenta",
    ifsc: "Código IFSC",
    bankName: "Nombre del banco",
    upiId: "ID de UPI",
    paytmPhone: "Número de teléfono Paytm",
    phonepePhone: "Número de teléfono PhonePe",
    save: "Guardar método de pago",
    holderRequired: "El nombre del titular es obligatorio.",
    accountInvalid: "Ingresa un número de cuenta válido.",
    ifscInvalid: "Ingresa un código IFSC válido.",
    bankRequired: "El nombre del banco es obligatorio.",
    upiInvalid: "Ingresa un ID de UPI válido (ej. name@bank).",
    phoneInvalid: "Ingresa un número de teléfono válido.",
    saved: "Método de pago guardado.",
    savedTitle: "Guardado",
    saveFailed: "Error al guardar el método de pago. Inténtalo de nuevo.",
  },

  privacyScreen: {
    title: "Política de privacidad",
    bannerTitle: "Tu privacidad importa",
    bannerSub: "Esta política explica cómo VoxLink Host recopila, usa y protege tus datos.",
    lastUpdated: "Última actualización: 1 de marzo de 2026",
    contactTitle: "¿Preguntas sobre privacidad?",
    sectionTitles: [
      "1. Información que recopilamos",
      "2. Cómo usamos tu información",
      "3. Compartir información",
      "4. Datos de llamadas y audio",
      "5. KYC y verificación de identidad",
      "6. Ganancias y pagos",
      "7. Seguridad de los datos",
      "8. Retención de datos",
      "9. Tus derechos",
      "10. Cambios en esta política",
    ],
  },

  referralScreen: {
    title: "Refiere y gana",
    heroTitle: "¡Refiere hosts, gana más!",
    heroSubA: "Invita a otros hosts con tu código. Cuando completen su primera llamada, reciben ",
    coinsAnd: " monedas y tú ganas ",
    coinsBang: " monedas!",
    yourCode: "Tu código de referido",
    copy: "Copiar",
    copied: "¡Copiado!",
    shareBtn: "Compartir con otros hosts",
    yourStats: "Tus estadísticas de referidos",
    hostsReferred: "Hosts referidos",
    coinsEarned: "Monedas ganadas",
    howItWorks: "Cómo funciona",
    step1: "Comparte tu código de referido único con otros hosts",
    step2: "Se registran como host usando tu código",
    step3Single: "Completan 1 llamada en VoxLink",
    step3Plural: "Completan {n} llamadas en VoxLink",
    step3Default: "Completan su primera llamada en VoxLink",
    step4a: "Tú ganas ",
    step4b: " monedas, ellos reciben ",
    step4c: "!",
    shareMessage: "¡Únete a mí en VoxLink como host y empieza a ganar con llamadas de audio y video!\n\nUsa mi código de referido: {code} para obtener un bono al registrarte como host.\n\nDescarga ahora: https://voxlink.app/host",
    shareTitle: "Únete a VoxLink como host",
    copiedToast: "¡Código de referido copiado!",
    copiedTitle: "Copiado",
    copyFailed: "No se pudo copiar el código. Inténtalo de nuevo.",
    loadFailed: "Error al cargar la información de referidos.",
  },

  languageScreen: {
    title: "Idioma de la app",
    subtitle: "Selecciona tu idioma preferido. Los cambios se aplican de inmediato.",
    soon: "Pronto",
    comingSoon: "Próximamente",
    comingSoonSuffix: " estará disponible pronto. La app continuará en inglés.",
  },

  editProfileScreen: {
    title: "Editar perfil de host",
    displayName: "Nombre para mostrar",
    namePlaceholder: "Tu nombre para mostrar",
    bio: "Biografía",
    bioPlaceholder: "Cuéntales a los usuarios sobre ti, tu experiencia y lo que ofreces...",
    email: "Correo electrónico",
    hostSettings: "Ajustes de host",
    setRates: "Establece tus tarifas de llamada (monedas / min)",
    manageTopics: "Gestiona tus temas y especialidades",
    saveChanges: "Guardar cambios",
    nameRequired: "Por favor ingresa tu nombre para mostrar.",
    saved: "Tu perfil de host se ha actualizado.",
    savedTitle: "Perfil guardado",
    saveFailed: "Error al guardar el perfil. Inténtalo de nuevo.",
    permRequired: "Permiso requerido",
    permMsg: "Permite el acceso a tu galería de fotos para cambiar tu foto de perfil.",
    tapToChange: "Toca para cambiar la foto",
    uploading: "Subiendo...",
    uploadFailed: "Error al subir",
    uploadFailedMsg: "No se pudo subir tu foto. Inténtalo de nuevo.",
    photoUpdated: "¡Foto de perfil actualizada!",
    photoSaved: "Foto guardada",
  },

  chatThreadScreen: {
    defaultName: "Chat",
    online: "En línea",
    typePlaceholder: "Escribe un mensaje...",
    startConvo: "Envía un mensaje para iniciar la conversación",
    notSent: "No enviado",
    loadFailed: "Error al cargar los mensajes.",
  },

  notFoundScreen: {
    title: "¡Ups!",
    message: "Esta pantalla no existe.",
    goHome: "¡Ir al inicio!",
  },

  // Availability schedule screen
  availabilityScreen: {
    title: "Horario de disponibilidad",
    helpText: "Define las horas en que sueles estar disponible. Quienes llaman lo ven en tu perfil. Es solo una indicación — no te desconecta.",
    always24Title: "Siempre disponible (24/7)",
    always24Sub: "Sin horario fijo — disponible en cualquier momento",
    availableHours: "Horas disponibles",
    availableFrom: "Disponible desde",
    availableTo: "Disponible hasta",
    sameTimeWarn: "La hora de inicio y de fin no pueden ser iguales.",
    overnightHint: "Franja nocturna — pasa de la medianoche.",
    timezone: "Zona horaria",
    callersWillSee: "Quienes llamen verán",
    available247: "Disponible 24/7",
    saveSchedule: "Guardar horario",
    selectTimezone: "Seleccionar zona horaria",
    scheduleSaved: "Horario de disponibilidad guardado.",
    savedTitle: "Guardado",
    invalidWindow: "Franja no válida",
    featureUnavailable: "Esta función aún no está habilitada en el servidor. Inténtalo más tarde.",
    unavailableTitle: "No disponible",
    saveFailed: "Error al guardar. Inténtalo de nuevo.",
  },
};

export default es;
