// VoxLink — Hindi Strings

const hi = {
  common: {
    ok: "ठीक है",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    save: "सहेजें",
    delete: "हटाएं",
    edit: "संपादित करें",
    done: "हो गया",
    back: "वापस",
    close: "बंद करें",
    loading: "लोड हो रहा है...",
    error: "कुछ गलत हो गया",
    retry: "फिर कोशिश करें",
    submit: "जमा करें",
    next: "अगला",
    skip: "छोड़ें",
    yes: "हाँ",
    no: "नहीं",
    search: "खोजें",
    filter: "फ़िल्टर",
    clear: "साफ़ करें",
    apply: "लागू करें",
    share: "साझा करें",
    copy: "कॉपी करें",
    copied: "कॉपी हो गया!",
    noResults: "कोई परिणाम नहीं मिला",
    optional: "वैकल्पिक",
    required: "ज़रूरी",
    all: "सभी",
    more: "अधिक",
    less: "कम",
    seeAll: "सब देखें",
    noData: "कोई डेटा उपलब्ध नहीं",
    refresh: "रीफ्रेश",
  },

  auth: {
    login: "लॉग इन",
    register: "साइन अप",
    logout: "लॉग आउट",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    forgotPassword: "पासवर्ड भूल गए?",
    newPassword: "नया पासवर्ड",
    phone: "फ़ोन नंबर",
    otp: "सत्यापन कोड",
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP सत्यापित करें",
    resendOtp: "OTP फिर भेजें",
    fullName: "पूरा नाम",
    createAccount: "खाता बनाएं",
    alreadyHaveAccount: "पहले से खाता है?",
    dontHaveAccount: "खाता नहीं है?",
    welcomeBack: "वापस स्वागत है!",
    loginToContinue: "जारी रखने के लिए लॉग इन करें",
    createYourAccount: "अपना खाता बनाएं",
    joinVoxLink: "आज VoxLink से जुड़ें",
    enterOtp: "इस नंबर पर भेजा OTP दर्ज करें",
    passwordResetSent: "पासवर्ड रीसेट ईमेल भेजा गया",
    checkEmail: "निर्देशों के लिए ईमेल जांचें",
    passwordChanged: "पासवर्ड सफलतापूर्वक बदला गया",
    invalidCredentials: "अमान्य ईमेल या पासवर्ड",
    accountDeleted: "खाता सफलतापूर्वक हटाया गया",
    deleteAccountConfirm: "क्या आप वाकई अपना खाता हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।",
  },

  nav: {
    home: "होम",
    search: "खोजें",
    messages: "संदेश",
    wallet: "वॉलेट",
    profile: "प्रोफ़ाइल",
    notifications: "सूचनाएं",
  },

  home: {
    greeting: "नमस्ते",
    findHosts: "होस्ट खोजें",
    topListeners: "शीर्ष श्रोता",
    trending: "अभी ट्रेंडिंग",
    newHosts: "नए होस्ट",
    onlineNow: "अभी ऑनलाइन",
    featuredHosts: "विशेष होस्ट",
    seeAll: "सब देखें",
    searchPlaceholder: "होस्ट, विषय खोजें...",
  },

  hosts: {
    host: "होस्ट",
    listener: "श्रोता",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    busy: "व्यस्त",
    rating: "रेटिंग",
    reviews: "समीक्षाएं",
    review: "समीक्षा",
    coinsPerMinute: "कॉइन/मिनट",
    totalMinutes: "कुल मिनट",
    specialties: "विशेषताएं",
    languages: "भाषाएं",
    about: "के बारे में",
    callNow: "अभी कॉल करें",
    audioCall: "ऑडियो कॉल",
    videoCall: "वीडियो कॉल",
    sendMessage: "संदेश भेजें",
    talkNow: "अभी बात करें",
    noHostsFound: "कोई होस्ट नहीं मिला",
    adjustFilters: "अपने फ़िल्टर समायोजित करें",
    topRated: "शीर्ष रेटेड",
    viewProfile: "प्रोफ़ाइल देखें",
    startCall: "कॉल शुरू करें",
  },

  calls: {
    incoming: "आने वाली कॉल",
    outgoing: "कनेक्ट हो रहा है...",
    ongoing: "कॉल पर",
    ended: "कॉल समाप्त",
    audio: "ऑडियो कॉल",
    video: "वीडियो कॉल",
    accept: "स्वीकार करें",
    decline: "अस्वीकार करें",
    endCall: "कॉल समाप्त करें",
    mute: "म्यूट",
    unmute: "अनम्यूट",
    speaker: "स्पीकर",
    flipCamera: "कैमरा बदलें",
    callDuration: "कॉल अवधि",
    callWith: "के साथ कॉल",
    rateCall: "इस कॉल को रेट करें",
    callHistory: "कॉल इतिहास",
    noCallHistory: "अभी तक कोई कॉल इतिहास नहीं",
    callCost: "कॉल लागत",
    perMinute: "प्रति मिनट",
    lowBalance: "कम कॉइन बैलेंस",
    lowBalanceMsg: "आपके कॉइन कम हैं। जारी रखने के लिए रीचार्ज करें।",
    callEnded: "कॉल समाप्त",
    callEndedMsg: "आपकी कॉल समाप्त हो गई है",
    missed: "मिस्ड",
    answered: "उत्तर दिया",
    rejected: "अस्वीकृत",
  },

  chat: {
    messages: "संदेश",
    newMessage: "नया संदेश",
    typeMessage: "संदेश लिखें...",
    send: "भेजें",
    noMessages: "अभी तक कोई संदेश नहीं",
    startConversation: "बातचीत शुरू करें",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    typing: "लिख रहा है...",
    delivered: "डिलीवर",
    read: "पढ़ा",
    deleteChat: "चैट हटाएं",
    deleteChatConfirm: "क्या आप इस बातचीत को हटाना चाहते हैं?",
  },

  wallet: {
    wallet: "वॉलेट",
    coinBalance: "कॉइन बैलेंस",
    coins: "कॉइन",
    coin: "कॉइन",
    buyCoins: "कॉइन खरीदें",
    coinHistory: "कॉइन इतिहास",
    transactions: "लेन-देन",
    noTransactions: "अभी तक कोई लेन-देन नहीं",
    purchased: "खरीदा",
    spent: "खर्च किया",
    bonus: "बोनस",
    refunded: "वापस किया",
    withdrawal: "निकासी",
    totalSpent: "कुल खर्च",
    totalPurchased: "कुल खरीद",
    popular: "सबसे लोकप्रिय",
    bestValue: "सर्वोत्तम मूल्य",
    bonus_label: "बोनस",
    recharge: "रीचार्ज",
    choosePackage: "पैकेज चुनें",
    instantDelivery: "तत्काल डिलीवरी",
    securePayment: "सुरक्षित भुगतान",
    guaranteed: "संतुष्टि की गारंटी",
  },

  profile: {
    profile: "प्रोफ़ाइल",
    editProfile: "प्रोफ़ाइल संपादित करें",
    myProfile: "मेरी प्रोफ़ाइल",
    name: "नाम",
    email: "ईमेल",
    phone: "फ़ोन",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    country: "देश",
    bio: "बायो",
    language: "भाषा",
    settings: "सेटिंग्स",
    helpCenter: "सहायता और FAQ",
    privacy: "गोपनीयता नीति",
    about: "VoxLink के बारे में",
    shareApp: "VoxLink शेयर करें",
    rateApp: "ऐप को रेट करें",
    logout: "लॉग आउट",
    deleteAccount: "खाता हटाएं",
    callHistory: "कॉल इतिहास",
    joinedOn: "शामिल हुए",
    totalCalls: "कुल कॉल",
    hoursSpent: "बिताए घंटे",
  },

  settings: {
    settings: "सेटिंग्स",
    notifications: "सूचनाएं",
    callNotifications: "कॉल सूचनाएं",
    messageNotifications: "संदेश सूचनाएं",
    promoNotifications: "प्रचार सूचनाएं",
    language: "भाषा",
    theme: "थीम",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    systemDefault: "सिस्टम डिफ़ॉल्ट",
    privacy: "गोपनीयता",
    security: "सुरक्षा",
    changePassword: "पासवर्ड बदलें",
    twoFactor: "दो-कारक प्रमाणीकरण",
    account: "खाता",
    support: "सहायता",
  },

  payment: {
    checkout: "चेकआउट",
    selectPackage: "पैकेज चुनें",
    paymentMethod: "भुगतान विधि",
    creditCard: "क्रेडिट / डेबिट कार्ड",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "भुगतान प्रक्रिया में...",
    paymentSuccess: "भुगतान सफल!",
    paymentFailed: "भुगतान विफल",
    orderSummary: "ऑर्डर सारांश",
    total: "कुल",
    coins: "कॉइन",
    bonusCoins: "बोनस कॉइन",
    tryAgain: "फिर कोशिश करें",
    secureNote: "सभी भुगतान सुरक्षित और एन्क्रिप्टेड हैं",
  },

  host: {
    dashboard: "डैशबोर्ड",
    totalEarnings: "कुल कमाई",
    thisWeek: "इस सप्ताह",
    thisMonth: "इस महीने",
    totalCalls: "कुल कॉल",
    avgRating: "औसत रेटिंग",
    onlineStatus: "ऑनलाइन स्थिति",
    goOnline: "ऑनलाइन जाएं",
    goOffline: "ऑफलाइन जाएं",
    setBusy: "व्यस्त सेट करें",
    earnings: "कमाई",
    withdraw: "निकालें",
    withdrawal: "निकासी",
    minimumWithdraw: "न्यूनतम 100 कॉइन",
    enterAmount: "राशि दर्ज करें",
    withdrawMethod: "निकासी विधि",
    bankTransfer: "बैंक ट्रांसफर",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "खाता विवरण",
    withdrawSuccess: "निकासी अनुरोध सबमिट किया गया",
    withdrawPending: "आपका अनुरोध संसाधित किया जा रहा है",
    hostSettings: "होस्ट सेटिंग्स",
    availability: "उपलब्धता",
    payoutSettings: "पेआउट सेटिंग्स",
    becomeHost: "होस्ट बनें",
    apply: "अभी आवेदन करें",
    applicationSent: "आवेदन भेजा गया!",
    applicationDesc: "हम आपके आवेदन की समीक्षा करेंगे और 2-3 कार्य दिवसों के भीतर वापस आएंगे।",
  },

  errors: {
    network: "नेटवर्क त्रुटि। कृपया अपना कनेक्शन जांचें।",
    server: "सर्वर त्रुटि। कृपया बाद में पुनः प्रयास करें।",
    unauthorized: "सत्र समाप्त। कृपया फिर से लॉग इन करें।",
    notFound: "अनुरोधित संसाधन नहीं मिला।",
    insufficientCoins: "अपर्याप्त कॉइन। कृपया रीचार्ज करें।",
    callFailed: "कॉल कनेक्ट नहीं हो सका। कृपया पुनः प्रयास करें।",
    permissionDenied: "अनुमति अस्वीकृत।",
    generic: "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
  },

  tabs: {
    home: "होम",
    chat: "चैट",
    calls: "कॉल",
    wallet: "वॉलेट",
    profile: "प्रोफ़ाइल",
  },

  hostSettings: {
    title: "होस्ट सेटिंग्स",
    availability: "उपलब्धता",
    autoOnline: "ऐप खुलते ही ऑनलाइन हों",
    dnd: "परेशान न करें मोड",
    dndOn: "चालू — सूचनाएं म्यूट",
    schedule: "उपलब्धता शेड्यूल",
    randomCalls: "रैंडम कॉल",
    availableRandom: "रैंडम कॉल के लिए उपलब्ध",
    randomOn: "चालू — रैंडम मैच पूल में शामिल",
    randomOff: "बंद — केवल सीधी कॉल",
    allowVideoRandom: "वीडियो रैंडम कॉल की अनुमति दें",
    videoDisabled: "अक्षम — रैंडम कॉल बंद हैं",
    videoOn: "चालू — वीडियो रैंडम कॉल स्वीकार",
    videoOff: "बंद — केवल ऑडियो रैंडम कॉल",
    loading: "लोड हो रहा है…",
    pushNotifications: "पुश सूचनाएं",
    notificationPrefs: "सूचना प्राथमिकताएं",
    incomingCallAlerts: "इनकमिंग कॉल अलर्ट",
    chatNotifications: "चैट सूचनाएं",
    coinEarnedAlerts: "कॉइन अर्जित अलर्ट",
    earnings: "कमाई",
    payoutMethod: "भुगतान विधि",
    withdrawEarnings: "कमाई निकालें",
    referEarn: "रेफर करें और कमाएं",
    preferences: "प्राथमिकताएं",
    appLanguage: "ऐप भाषा",
    support: "सहायता",
    helpSupport: "सहायता और समर्थन",
    privacyPolicy: "गोपनीयता नीति",
    aboutApp: "VoxLink Host के बारे में",
    account: "खाता",
    signOut: "साइन आउट",
    deleteAccount: "खाता हटाएं",
    on: "चालू",
    off: "बंद",
    alwaysAvailable: "हमेशा उपलब्ध",
  },

  homeScreen: {
    online: "आप ऑनलाइन हैं",
    offline: "आप ऑफ़लाइन हैं",
    onlineSub: "कॉल प्राप्त करने के लिए उपलब्ध",
    offlineSub: "कॉल स्वीकार करना शुरू करने के लिए टॉगल करें",
    totalCalls: "कुल कॉल",
    totalHours: "कुल घंटे",
    earnings: "कमाई",
    yourCallRates: "आपकी कॉल दरें",
    ratesSub: "उपयोगकर्ता प्रति मिनट आपको कितने कॉइन देते हैं",
    edit: "संपादित करें",
    audioPerMin: "ऑडियो / मिनट",
    videoPerMin: "वीडियो / मिनट",
    manage: "प्रबंधित करें",
    qaCallRates: "कॉल दरें",
    qaCallRatesDesc: "अपनी कीमत तय करें",
    qaTopics: "मेरे विषय",
    qaTopicsDesc: "अधिक उपयोगकर्ताओं तक पहुंचें",
    qaEarnings: "कमाई",
    qaEarningsDesc: "इतिहास देखें",
    qaPayouts: "भुगतान",
    qaPayoutsDesc: "कॉइन निकालें",
    qaWallet: "वॉलेट",
    qaWalletDesc: "बैलेंस और निकासी",
    qaCallHistory: "कॉल इतिहास",
    qaCallHistoryDesc: "पिछली कॉल",
    qaRefer: "रेफर करें और कमाएं",
    qaReferDesc: "दोस्तों को आमंत्रित करें",
    qaProfile: "प्रोफ़ाइल",
    qaProfileDesc: "विवरण संपादित करें",
    qaSettings: "सेटिंग्स",
    qaSettingsDesc: "ऐप प्राथमिकताएं",
    permsRequired: "अनुमतियां आवश्यक",
    micLabel: "माइक्रोफ़ोन",
    micDesc: "ऑडियो कॉल के लिए आवश्यक",
    cameraLabel: "कैमरा",
    cameraDesc: "वीडियो कॉल के लिए आवश्यक",
    notifLabel: "सूचनाएं",
    notifDesc: "इनकमिंग कॉल अलर्ट के लिए",
    granted: "अनुमति दी गई",
    tapToAllow: "अनुमति देने के लिए टैप करें",
    hostTips: "होस्ट टिप्स",
    tip1: "पीक आवर्स (शाम 6 - रात 10) में ऑनलाइन रहें",
    tip2: "अधिक बुकिंग के लिए अपनी प्रोफ़ाइल पूरी करें",
    tip3: "अपनी रेटिंग सुधारने के लिए जल्दी जवाब दें",
    tip4: "अधिक उपयोगकर्ताओं तक पहुंचने के लिए विषय जोड़ें",
  },

  profileScreen: {
    title: "मेरी प्रोफ़ाइल",
    proHost: "पेशेवर होस्ट",
    calls: "कॉल",
    rating: "रेटिंग",
    coins: "कॉइन",
    onlineStatus: "ऑनलाइन स्थिति",
    pushNotifications: "पुश सूचनाएं",
    account: "खाता",
    editProfile: "प्रोफ़ाइल संपादित करें",
    callRates: "कॉल दरें",
    myTopics: "मेरे विषय",
    settings: "सेटिंग्स",
    language: "भाषा",
    more: "अधिक",
    referEarn: "रेफर करें और कमाएं",
    helpCenter: "सहायता केंद्र",
    privacyPolicy: "गोपनीयता नीति",
    about: "VoxLink के बारे में",
    signOut: "साइन आउट",
    signOutConfirm: "क्या आप वाकई साइन आउट करना चाहते हैं?",
    permRequiredTitle: "अनुमति आवश्यक",
    permRequiredMsg: "अपनी प्रोफ़ाइल फ़ोटो बदलने के लिए कृपया अपनी फ़ोटो लाइब्रेरी तक पहुंच की अनुमति दें।",
    turnOffNotifTitle: "सूचनाएं बंद करें",
    turnOffNotifMsg: "सूचनाएं बंद करने के लिए, अपने फ़ोन की सेटिंग्स में जाएं और VoxLink Host के लिए सूचनाएं बंद करें।",
    openSettings: "सेटिंग्स खोलें",
    uploadFailedTitle: "अपलोड विफल",
    uploadFailedMsg: "आपकी फ़ोटो अपलोड नहीं हो सकी। कृपया पुनः प्रयास करें।",
    photoUpdated: "प्रोफ़ाइल फ़ोटो अपडेट हो गई!",
    photoSaved: "फ़ोटो सहेजी गई",
  },

  callsScreen: {
    title: "कॉल इतिहास",
    all: "सभी",
    audio: "ऑडियो",
    video: "वीडियो",
    completed: "पूर्ण",
    missed: "छूटी",
    cancelled: "रद्द",
    noCalls: "अभी तक कोई कॉल नहीं",
    loadError: "कॉल लोड नहीं हो सकीं। रिफ्रेश करने के लिए खींचें।",
  },

  chatScreen: {
    title: "संदेश",
    searchPlaceholder: "बातचीत खोजें...",
    noConversations: "अभी तक कोई बातचीत नहीं",
    noMessagesYet: "अभी तक कोई संदेश नहीं",
    now: "अभी",
  },

  walletScreen: {
    title: "होस्ट वॉलेट",
    availableBalance: "उपलब्ध बैलेंस",
    coins: "कॉइन",
    payoutValue: "भुगतान मूल्य",
    thisWeek: "इस सप्ताह",
    sessions: "सत्र",
    withdrawn: "निकाला गया",
    earningsHistory: "कमाई इतिहास",
    withdraw: "निकासी",
    noEarnings: "अभी तक कोई कमाई नहीं",
    quickSelect: "त्वरित राशि चुनें",
    orEnter: "या राशि दर्ज करें",
    enterCoinAmount: "कॉइन राशि दर्ज करें",
    payoutTo: "भुगतान किसे",
    setupPayout: "अपनी भुगतान विधि सेट करें",
    edit: "संपादित करें",
    managePayout: "भुगतान विधि प्रबंधित करें",
    requestWithdrawal: "निकासी का अनुरोध करें",
    note: "नोट",
    failedLoad: "कमाई डेटा लोड करने में विफल।",
  },

  loginScreen: {
    tagline: "कमाएं · जुड़ें · अपने दर्शक बढ़ाएं",
    chipKyc: "KYC सत्यापित",
    chipEarn: "कॉइन कमाएं",
    chipPlatform: "होस्ट प्लेटफ़ॉर्म",
    welcomeBack: "वापस स्वागत है",
    subtitle: "अपने होस्ट खाते में साइन इन करें",
    emailPlaceholder: "ईमेल पता",
    passwordPlaceholder: "पासवर्ड",
    signIn: "होस्ट के रूप में साइन इन करें",
    orContinue: "या इसके साथ जारी रखें",
    continueGoogle: "Google के साथ जारी रखें",
    signingIn: "साइन इन हो रहा है...",
    newPrompt: "VoxLink Host पर नए हैं? ",
    applyNow: "अभी आवेदन करें",
  },

  registerScreen: {
    stepAccount: "खाता",
    stepProfile: "प्रोफ़ाइल",
    stepHostInfo: "होस्ट जानकारी",
    stepKyc: "KYC दस्तावेज़",
    title: "होस्ट बनें",
    headerSub: "कमाई शुरू करने के लिए 4 चरण पूरे करें",
    createTitle: "अपना खाता बनाएं",
    createSub: "यह आपका VoxLink Host लॉगिन होगा",
    namePlaceholder: "पूरा नाम",
    emailPlaceholder: "ईमेल पता",
    passwordPlaceholder: "पासवर्ड (8+ अक्षर)",
    continueBtn: "जारी रखें",
    orSignUp: "या इसके साथ साइन अप करें",
    continueGoogle: "Google के साथ जारी रखें",
    signingIn: "साइन इन हो रहा है...",
    alreadyRegistered: "पहले से पंजीकृत हैं? ",
    signIn: "साइन इन करें",
  },

  authToasts: {
    missingFields: "अधूरी जानकारी",
    loginMissing: "कृपया ईमेल और पासवर्ड दोनों दर्ज करें।",
    invalidEmail: "अमान्य ईमेल",
    invalidEmailMsg: "कृपया एक मान्य ईमेल पता दर्ज करें।",
    loginFailed: "लॉगिन विफल",
    loginFailedMsg: "अमान्य ईमेल या पासवर्ड।",
    notSupported: "समर्थित नहीं",
    playServices: "Google Play Services उपलब्ध नहीं है।",
    connectionError: "कनेक्शन त्रुटि",
    noInternet: "कोई इंटरनेट कनेक्शन नहीं।",
    signInFailed: "साइन इन विफल",
    googleFailed: "Google साइन-इन विफल",
    almostThere: "बस थोड़ा और",
    googleWelcomeHost: "स्वागत है! कृपया अपनी होस्ट प्रोफ़ाइल और KYC पूरी करें।",
    googleWelcomeProfile: "स्वागत है! होस्ट के रूप में आवेदन करने के लिए अपनी प्रोफ़ाइल पूरी करें।",
    signInFailedRetry: "साइन-इन विफल। कृपया पुनः प्रयास करें।",
    googleNoAccount: "Google खाता जानकारी प्राप्त नहीं हो सकी।",
    googleNoToken: "Google साइन-इन ने टोकन नहीं लौटाया। कृपया ऐप अपडेट करें या पुनः प्रयास करें।",
    registerMissing: "कृपया सभी फ़ील्ड भरें।",
    weakPassword: "कमज़ोर पासवर्ड",
    weakPasswordMsg: "पासवर्ड कम से कम 8 अक्षर का होना चाहिए।",
    welcomeBack: "वापस स्वागत है",
    resuming: "आपका अधूरा पंजीकरण फिर से शुरू कर रहे हैं।",
    alreadyRegisteredTitle: "पहले से पंजीकृत",
    alreadyRegisteredMsg: "यह ईमेल पहले से पंजीकृत है। कृपया साइन इन करें।",
    createFailed: "खाता नहीं बनाया जा सका। कृपया पुनः प्रयास करें।",
  },

  forgotPasswordScreen: {
    checkEmail: "अपना ईमेल जांचें",
    forgotPassword: "पासवर्ड भूल गए?",
    sentLine1: "हमने 6-अंकीय OTP भेजा है",
    sentLine2: "कोड दर्ज करें और नया पासवर्ड सेट करें।",
    enterEmailPrompt: "अपना पंजीकृत ईमेल दर्ज करें। हम पासवर्ड रीसेट करने के लिए OTP भेजेंगे।",
    resetPassword: "पासवर्ड रीसेट करें",
    otpPlaceholder: "OTP कोड दर्ज करें",
    newPasswordPlaceholder: "नया पासवर्ड",
    confirmPasswordPlaceholder: "नए पासवर्ड की पुष्टि करें",
    resetting: "रीसेट हो रहा है...",
    resetBtn: "पासवर्ड रीसेट करें",
    didntReceive: "नहीं मिला? ",
    resendIn: "पुनः भेजें",
    resendOtp: "OTP पुनः भेजें",
    findAccount: "अपना खाता खोजें",
    emailPlaceholder: "ईमेल पता",
    sending: "भेजा जा रहा है...",
    sendOtp: "OTP भेजें",
    backTo: "वापस ",
    signIn: "साइन इन",
    enterEmailError: "कृपया अपना ईमेल पता दर्ज करें।",
    otpSent: "आपके ईमेल पर OTP भेजा गया।",
    emailSent: "ईमेल भेजा गया",
    emailNotFound: "ईमेल नहीं मिला। कृपया जांचें और पुनः प्रयास करें।",
    enterOtpError: "कृपया अपने ईमेल पर भेजा गया OTP दर्ज करें।",
    weakPassword: "कमज़ोर पासवर्ड",
    weakPasswordMsg: "पासवर्ड कम से कम 8 अक्षर का होना चाहिए।",
    mismatch: "मेल नहीं खाता",
    passwordsDontMatch: "पासवर्ड मेल नहीं खाते।",
    successTitle: "सफल",
    resetSuccess: "पासवर्ड सफलतापूर्वक अपडेट हुआ! कृपया साइन इन करें।",
    errorTitle: "त्रुटि",
    resetFailed: "पासवर्ड रीसेट करने में विफल। OTP समाप्त हो सकता है।",
  },

  onboardingScreen: {
    slide1Title: "खोजें",
    slide1Sub: "आप दुनिया भर के लोगों से जुड़कर\nचैट, संदेश और उनके साथ\nसंबंध बना सकते हैं।",
    slide2Title: "चैट करें",
    slide2Sub: "एक-दूसरे को बेहतर जानने और\nअच्छा तालमेल बनाने के लिए\nअजनबियों से चैट करें।",
    slide3Title: "वीडियो कॉल",
    slide3Sub: "आप अपने वीडियो और फ़ोटो अपने\nदोस्तों और संपर्कों के साथ साझा कर सकते हैं।",
  },

  profileSetupScreen: {
    headerSub: "चरण 2 / 4 — आपकी प्रोफ़ाइल",
    sectionTitle: "आपकी प्रोफ़ाइल जानकारी",
    sectionSub: "यह आपको कॉल करने वाले उपयोगकर्ताओं को दिखाई देगी",
    uploading: "अपलोड हो रहा है...",
    tapAddPhoto: "प्रोफ़ाइल फ़ोटो जोड़ने के लिए टैप करें",
    namePlaceholder: "प्रदर्शन नाम",
    dobPlaceholder: "जन्म तिथि (चुनने के लिए टैप करें)",
    phonePlaceholder: "मोबाइल नंबर",
    genderLabel: "लिंग",
    continueBtn: "जारी रखें → होस्ट जानकारी",
    done: "हो गया",
    dobTitle: "जन्म तिथि",
    day: "दिन",
    month: "महीना",
    year: "वर्ष",
    months: ["जनवरी","फ़रवरी","मार्च","अप्रैल","मई","जून","जुलाई","अगस्त","सितंबर","अक्टूबर","नवंबर","दिसंबर"],
    uploadFailed: "अपलोड विफल",
    uploadFailedMsg: "फ़ोटो अपलोड नहीं हो सकी। कृपया पुनः प्रयास करें।",
    missingFields: "अधूरी जानकारी",
    missingFieldsMsg: "कृपया सभी आवश्यक फ़ील्ड भरें।",
    invalidPhone: "अमान्य फ़ोन",
    invalidPhoneMsg: "कृपया एक मान्य मोबाइल नंबर दर्ज करें।",
    saveFailed: "सहेजना विफल",
    saveFailedMsg: "आपकी प्रोफ़ाइल सहेजी नहीं जा सकी। कृपया पुनः प्रयास करें।",
  },

  becomeScreen: {
    headerSub: "चरण 3 / 4 — होस्ट जानकारी",
    sectionTitle: "आपकी होस्ट प्रोफ़ाइल",
    sectionSub: "उपयोगकर्ताओं को समझाएं कि आप क्या पेश करते हैं",
    specialtiesLabel: "विशेषताएं (1–5 चुनें)",
    languagesLabel: "भाषाएं",
    bioLabel: "बायो",
    bioPlaceholder: "उपयोगकर्ताओं को अपने बारे में बताएं — आपकी विशेषज्ञता, व्यक्तित्व, और आपकी कॉल को क्या खास बनाता है...",
    experienceLabel: "अनुभव (वैकल्पिक)",
    experiencePlaceholder: "जैसे 3 साल का लाइफ कोच अनुभव",
    callTypeLabel: "पेश की गई कॉल का प्रकार",
    audioOnly: "🎤 केवल ऑडियो",
    videoOnly: "🎥 केवल वीडियो",
    both: "🎤🎥 दोनों",
    ratesLabel: "आपकी कॉल दरें (कॉइन/मिनट)",
    audio: "ऑडियो",
    video: "वीडियो",
    coinsPerMin: "कॉइन/मिनट",
    note: "दरें सुझाव हैं। अनुमोदन के बाद एडमिन उन्हें समायोजित कर सकता है।",
    continueBtn: "जारी रखें →  KYC दस्तावेज़",
    selectSpecialty: "विशेषता चुनें",
    chooseSpecialty: "कम से कम एक विशेषता चुनें।",
    bioTooShort: "बायो बहुत छोटा",
    bioTooShortMsg: "कृपया कम से कम 20 अक्षरों का बायो लिखें।",
  },

  kycScreen: {
    headerSub: "चरण 4 / 4 — KYC दस्तावेज़",
    sectionTitle: "पहचान सत्यापन",
    sectionSub: "होस्टिंग शुरू करने के लिए आवश्यक। आपके दस्तावेज़ सुरक्षित रूप से संग्रहीत हैं।",
    notice: "भारतीय नियमों के अनुसार KYC अनिवार्य है। दस्तावेज़ केवल एडमिन द्वारा समीक्षित होते हैं और उपयोगकर्ताओं के साथ साझा नहीं किए जाते।",
    dobLabel: "जन्म तिथि",
    fromStep2: "चरण 2 से",
    dobPlaceholder: "DD/MM/YYYY (जैसे 22/05/1998)",
    docAadharFront: "आधार सामने",
    docAadharFrontSub: "आधार कार्ड के सामने की फ़ोटो",
    docAadharBack: "आधार पीछे",
    docAadharBackSub: "आधार कार्ड के पीछे की फ़ोटो",
    docVideo: "सत्यापन वीडियो",
    docVideoSub: "आधार पकड़े हुए अपना छोटा वीडियो (5–15 सेकंड)",
    uploading: "अपलोड हो रहा है...",
    uploaded: "अपलोड हो गया ✓",
    tipsTitle: "अनुमोदन के लिए सुझाव",
    tip1: "सुनिश्चित करें कि आधार फ़ोटो स्पष्ट और धुंधली न हों",
    tip2: "सत्यापन वीडियो में अपना आधार कार्ड स्पष्ट रूप से पकड़ें",
    tip3: "रिकॉर्डिंग के दौरान कैमरे में देखें",
    submitting: "जमा हो रहा है...",
    submit: "आवेदन जमा करें",
    uploadFailed: "अपलोड विफल",
    uploadFailedMsg: "फ़ाइल अपलोड नहीं हो सकी। कृपया पुनः प्रयास करें।",
    missingDocs: "दस्तावेज़ अधूरे",
    missingDocsMsg: "कृपया आधार के सामने और पीछे दोनों फ़ोटो अपलोड करें।",
    missingDob: "जन्म तिथि अनुपलब्ध",
    missingDobMsg: "जन्म तिथि अनुपलब्ध है। कृपया चरण 2 पर वापस जाएं और अपनी DOB चुनें।",
    submitFailed: "जमा करना विफल",
    submitFailedMsg: "आपका आवेदन जमा नहीं हो सका। कृपया पुनः प्रयास करें।",
  },

  statusScreen: {
    headerTitle: "होस्ट आवेदन",
    headerSub: "अपनी KYC सत्यापन स्थिति ट्रैक करें",
    checking: "आवेदन स्थिति जांची जा रही है...",
    pendingTitle: "आवेदन जमा किया गया",
    pendingMsg: "आपका आवेदन कतार में है। हमारी टीम 24–48 घंटों के भीतर इसकी समीक्षा करेगी।",
    underReviewTitle: "समीक्षाधीन",
    underReviewMsg: "हमारी टीम सक्रिय रूप से आपके आवेदन की समीक्षा कर रही है। आपको जल्द ही जवाब मिलेगा।",
    approvedTitle: "बधाई हो!",
    approvedMsg: "आपका आवेदन स्वीकृत हो गया है! अब आप VoxLink पर एक सत्यापित होस्ट हैं।",
    rejectedTitle: "आवेदन अस्वीकृत",
    rejectedMsg: "दुर्भाग्य से, आपका आवेदन स्वीकृत नहीं हुआ। कृपया नीचे कारण देखें और पुनः आवेदन करें।",
    notAppliedTitle: "कोई आवेदन नहीं मिला",
    notAppliedMsg: "आपने अभी तक होस्ट आवेदन जमा नहीं किया है।",
    approvedSub: "अब आप VoxLink पर एक सत्यापित होस्ट हैं। कॉल स्वीकार करना और कॉइन कमाना शुरू करें!",
    earnCoins: "कॉइन कमाएं",
    buildRating: "रेटिंग बनाएं",
    takeCalls: "कॉल लें",
    timelineTitle: "आवेदन समयरेखा",
    tlAccount: "खाता बनाया गया",
    tlSubmitted: "आवेदन जमा किया गया",
    tlReview: "समीक्षाधीन",
    tlDecision: "निर्णय लिया गया",
    continueDashboard: "डैशबोर्ड पर जारी रखें",
    reasonRejection: "अस्वीकृति का कारण",
    reapply: "पुनः आवेदन करें",
    startApplication: "आवेदन शुरू करें",
    autoChecking: "हर 10 सेकंड में स्वतः जांच हो रही है...",
    loadError: "आवेदन स्थिति लोड करने में विफल।",
  },

  audioCallScreen: {
    voiceCall: "वॉइस कॉल",
    ringing: "घंटी बज रही है...",
    connecting: "कनेक्ट हो रहा है...",
    connected: "कनेक्ट हुआ",
    reconnecting: "नेटवर्क टूटा — पुनः कनेक्ट हो रहा है...",
    connFailed: "कनेक्शन विफल — पुनः प्रयास हो रहा है...",
    callEnded: "कॉल समाप्त",
    unknown: "अज्ञात",
    muted: "🔇 म्यूट",
    coinsPerMin: "कॉइन / मिनट",
    remaining: "शेष",
    minLeft: "मिनट शेष",
    callEndingSoon: "कॉल जल्द समाप्त होगी — ",
    micNeeded: "माइक्रोफ़ोन एक्सेस आवश्यक — ठीक करने के लिए टैप करें",
    mute: "म्यूट",
    unmute: "अनम्यूट",
    speaker: "स्पीकर",
    speakerOn: "स्पीकर चालू",
  },

  videoCallScreen: {
    connecting: "कनेक्ट हो रहा है...",
    connected: "कनेक्ट हुआ",
    reconnecting: "नेटवर्क टूटा — पुनः कनेक्ट हो रहा है...",
    connFailed: "कनेक्शन विफल — पुनः प्रयास हो रहा है...",
    ringing: "घंटी बज रही है...",
    cameraOff: "कैमरा बंद",
    connectionIssue: "कनेक्शन समस्या",
    live: "लाइव",
    settingUp: "सुरक्षित कनेक्शन सेट हो रहा है...",
    waitingResponse: "प्रतिक्रिया की प्रतीक्षा...",
    connectingName: "कनेक्ट हो रहा है...",
    cameraUnavailable: "कैमरा अनुपलब्ध",
    startingCamera: "कैमरा शुरू हो रहा है…",
    noPermission: "कोई अनुमति नहीं",
    cameraOffLabel: "कैमरा बंद",
    you: "आप",
    mutedBadge: "म्यूट",
    noMic: "कोई माइक नहीं",
    callEndingSoon: "कॉल जल्द समाप्त होगी — ",
    minLeft: "मिनट शेष",
    secLeft: "से. शेष",
    ctrlCamera: "कैमरा",
    ctrlCamOff: "कैम बंद",
    ctrlUnmute: "अनम्यूट",
    ctrlMute: "म्यूट",
    ctrlEnd: "समाप्त",
    ctrlFlip: "पलटें",
    ctrlSpeaker: "स्पीकर",
    ctrlEarpiece: "इयरपीस",
  },

  incomingCallScreen: {
    incomingVideo: "आने वाली वीडियो कॉल",
    incomingAudio: "आने वाली ऑडियो कॉल",
    unknown: "अज्ञात",
    voxlinkHost: "VoxLink होस्ट",
    voxlinkUser: "VoxLink उपयोगकर्ता",
    decline: "अस्वीकार करें",
    accept: "स्वीकार करें",
  },

  outgoingCallScreen: {
    videoCall: "वीडियो कॉल",
    voiceCall: "वॉइस कॉल",
    callDeclined: "कॉल अस्वीकृत",
    noAnswer: "कोई उत्तर नहीं",
    ringing: "घंटी बज रही है...",
    connecting: "कनेक्ट हो रहा है...",
    cancel: "रद्द करें",
  },

  callSummaryScreen: {
    autoEndedBanner: "उपयोगकर्ता के कॉइन समाप्त हो गए — कॉल स्वतः डिस्कनेक्ट हुई",
    callAutoEnded: "कॉल स्वतः समाप्त",
    callCompleted: "कॉल पूर्ण",
    withName: "के साथ",
    duration: "अवधि",
    coinsEarned: "अर्जित कॉइन",
    video: "वीडियो",
    audio: "ऑडियो",
    ratePrefix: "रेट करें",
    rateSub: "इस कॉल का अपना अनुभव साझा करें",
    ratingLabels: ["", "खराब", "ठीक", "अच्छा", "बहुत अच्छा", "उत्कृष्ट!"],
    submitRating: "⭐ रेटिंग जमा करें",
    skip: "छोड़ें",
    thankYouTitle: "धन्यवाद! 🙏",
    thankYouSub: "आपकी रेटिंग जमा हो गई है",
    viewEarnings: "कमाई देखें",
    backHome: "होम पर वापस जाएं",
    ratingError: "रेटिंग जमा करने में विफल, कृपया पुनः प्रयास करें।",
    errorTitle: "त्रुटि",
    user: "उपयोगकर्ता",
  },

  callHistoryScreen: {
    title: "कॉल इतिहास",
    all: "सभी",
    audio: "ऑडियो",
    video: "वीडियो",
    completed: "पूर्ण",
    missed: "छूटी",
    cancelled: "रद्द",
    noHistory: "कोई कॉल इतिहास नहीं मिला",
    coins: "कॉइन",
    loadFailed: "कॉल इतिहास लोड करने में विफल।",
  },

  aboutScreen: {
    title: "VoxLink के बारे में",
    tagline: "वॉइस और वीडियो कनेक्शन — होस्ट संस्करण",
    version: "संस्करण",
    statActiveUsers: "सक्रिय उपयोगकर्ता",
    statHosts: "होस्ट",
    statCallsMade: "की गई कॉल",
    statAppRating: "ऐप रेटिंग",
    whatIsTitle: "VoxLink Host क्या है?",
    whatIsBody1: "VoxLink Host, VoxLink प्लेटफ़ॉर्म पर सत्यापित होस्ट के लिए समर्पित ऐप है। होस्ट के रूप में, आप उपयोगकर्ताओं से सार्थक ऑडियो और वीडियो बातचीत के लिए जुड़ते हैं — चाहे वह जीवन सलाह हो, भाषा अभ्यास, भावनात्मक समर्थन, या साथ।",
    whatIsBody2: "होस्ट हर मिनट की पूरी की गई कॉल के लिए कॉइन कमाते हैं। कॉइन वास्तविक पैसे में बदले जाते हैं और सीधे आपके बैंक खाते में निकाले जाते हैं। अपना खुद का समय तय करें, अपने दर्शक बढ़ाएं, और अपनी शर्तों पर कमाएं।",
    featuresTitle: "होस्ट सुविधाएं",
    featHd: "HD ऑडियो और वीडियो कॉल",
    featEncrypted: "एंड-टू-एंड एन्क्रिप्टेड",
    featEarn: "प्रति मिनट कॉइन कमाएं",
    featDashboard: "रीयल-टाइम कमाई डैशबोर्ड",
    featChat: "उपयोगकर्ताओं के साथ इन-ऐप चैट",
    featRatings: "रेटिंग और समीक्षाएं",
    featSchedule: "लचीला उपलब्धता शेड्यूल",
    connectTitle: "हमसे जुड़ें",
    linkWebsite: "वेबसाइट",
    linkTwitter: "Twitter / X",
    linkInstagram: "Instagram",
    linkContact: "संपर्क करें",
    privacyPolicy: "गोपनीयता नीति",
    helpCenter: "सहायता केंद्र",
    copyright: "© 2026 VoxLink Inc. सर्वाधिकार सुरक्षित।",
  },

  callRatesScreen: {
    title: "कॉल दरें",
    helpA: "तय करें कि उपयोगकर्ता प्रति मिनट आपको कितने कॉइन देंगे। वीडियो कॉल आमतौर पर ऑडियो से अधिक कमाती हैं। अपने वर्तमान स्तर पर आप अधिकतम ",
    coinsPerMinAudio: " कॉइन/मिनट ऑडियो के लिए",
    helpB: " और ",
    coinsPerMinVideo: " कॉइन/मिनट वीडियो के लिए",
    helpC: " चार्ज कर सकते हैं (एडमिन स्तर सीमा +",
    helpD: " बोनस)। इन सीमाओं को बढ़ाने के लिए उच्च स्तर तक पहुंचें।",
    levelWord: "स्तर",
    hostSuffix: " होस्ट",
    yourRates: "आपकी दरें",
    audioCall: "ऑडियो कॉल",
    audioSub: "वॉइस कॉल के लिए प्रति मिनट",
    videoCall: "वीडियो कॉल",
    videoSub: "वीडियो कॉल के लिए प्रति मिनट",
    coinsMin: "कॉइन / मिनट",
    maxLabel: "अधिकतम ",
    upToLabel: "तक ",
    capSuffix: " कॉइन/मिनट आपके स्तर पर",
    estTitle: "कमाई का अनुमान",
    est10AudioPrefix: "10-मिनट ऑडियो कॉल ≈ ",
    est10VideoPrefix: "10-मिनट वीडियो कॉल ≈ ",
    coinsSuffix: " कॉइन",
    estNote: "हर पूरी हुई कॉल के बाद कॉइन आपकी कमाई में जुड़ जाते हैं।",
    saveRates: "दरें सहेजें",
    ratesSaved: "आपकी कॉल दरें अपडेट हो गई हैं।",
    ratesSavedTitle: "दरें सहेजी गईं",
    saveFailed: "दरें सहेजने में विफल। कृपया पुनः प्रयास करें।",
  },

  earningsHistoryScreen: {
    title: "कमाई इतिहास",
    totalEarnings: "कुल कमाई",
    earned: "अर्जित",
    withdrawn: "निकाला गया",
    tabAll: "सभी",
    tabEarned: "अर्जित",
    tabWithdrawn: "निकाला गया",
    tabBonus: "बोनस",
    noTransactions: "कोई लेन-देन नहीं मिला",
    loadFailed: "कमाई इतिहास लोड करने में विफल।",
    today: "आज",
    yesterday: "कल",
    ref: "संदर्भ: ",
  },

  helpCenterScreen: {
    title: "सहायता केंद्र",
    bannerTitle: "होस्ट सहायता और FAQ",
    bannerSub: "सामान्य होस्ट प्रश्नों के उत्तर खोजें",
    contactTitle: "होस्ट सहायता से संपर्क करें",
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
  },

  levelBenefitsScreen: {
    title: "स्तर लाभ",
    subtitle: "सीढ़ी चढ़ें, अधिक कमाएं",
    current: "वर्तमान",
    unlocked: "अनलॉक",
    locked: "लॉक",
    requirements: "आवश्यकताएं",
    ratedCalls: " रेटेड कॉल",
    rating: " रेटिंग",
    rewardsPerks: "पुरस्कार और लाभ",
    earningsSuffix: "% कमाई",
    audioUpTo: "🎙️ ऑडियो अधिकतम ",
    videoUpTo: "📹 वीडियो अधिकतम ",
    perMin: "/मिनट",
    higherVisibility: "🚀 अधिक दृश्यता",
    youreAtLevel: "आप स्तर पर हैं ",
    maxLevelMsg: "आप शीर्ष स्तर पर पहुंच गए हैं। बढ़िया काम जारी रखें!",
    progressMid: "% का रास्ता पूरा ",
    loadError: "स्तर लाभ लोड नहीं हो सके। अपना कनेक्शन जांचें और पुनः प्रयास करें।",
    retry: "पुनः प्रयास करें",
    retrying: "पुनः प्रयास हो रहा है…",
    footnote: "रेटेड कॉल वे कॉल हैं जिन्हें स्टार रेटिंग मिली। स्तर पुरस्कार एक बार दिए जाते हैं जब आप पहली बार प्रत्येक स्तर पर पहुंचते हैं। उच्च स्तर आपको अधिक चार्ज करने, कमाई का बड़ा हिस्सा रखने, और उपयोगकर्ताओं के सामने ऊंची रैंक देते हैं।",
  },

  manageTopicsScreen: {
    title: "मेरे विषय",
    helpPrefix: "उन विषयों को चुनें जिन पर आप बात करते हैं। इन विषयों को ब्राउज़ करने वाले उपयोगकर्ता आपको तेज़ी से ढूंढेंगे। अधिकतम चुनें ",
    helpSuffix: "।",
    topics: "विषय",
    addYourOwn: "अपना जोड़ें",
    customPlaceholder: "जैसे ज्योतिष, फिटनेस…",
    add: "जोड़ें",
    noTopics: "अभी तक कोई विषय उपलब्ध नहीं। नीचे अपना जोड़ें।",
    saveTopics: "विषय सहेजें",
    maxPrefix: "आप अधिकतम ",
    maxSuffix: " विषय चुन सकते हैं।",
    topicsSaved: "आपके विषय अपडेट हो गए हैं।",
    topicsSavedTitle: "विषय सहेजे गए",
    saveFailed: "विषय सहेजने में विफल। कृपया पुनः प्रयास करें।",
  },

  notificationsScreen: {
    title: "सूचनाएं",
    markAllRead: "सभी पढ़ा हुआ चिह्नित करें",
    empty: "अभी तक कोई सूचना नहीं",
    loadFailed: "सूचनाएं लोड करने में विफल।",
    markFailed: "सूचनाओं को पढ़ा हुआ चिह्नित करने में विफल।",
    updateFailed: "सूचना अपडेट करने में विफल।",
  },

  payoutMethodScreen: {
    title: "भुगतान विधि",
    help: "चुनें कि आप अपनी कमाई कैसे प्राप्त करना चाहते हैं। आपके निकासी अनुरोध डिफ़ॉल्ट रूप से इस खाते का उपयोग करेंगे।",
    channel: "चैनल",
    details: "विवरण",
    bank: "बैंक खाता",
    upi: "UPI",
    paytm: "Paytm",
    phonepe: "PhonePe",
    accountHolder: "खाताधारक का नाम",
    accountHolderPh: "खाते पर पूरा नाम",
    accountNumber: "खाता संख्या",
    ifsc: "IFSC कोड",
    bankName: "बैंक का नाम",
    upiId: "UPI आईडी",
    paytmPhone: "Paytm फ़ोन नंबर",
    phonepePhone: "PhonePe फ़ोन नंबर",
    save: "भुगतान विधि सहेजें",
    holderRequired: "खाताधारक का नाम आवश्यक है।",
    accountInvalid: "एक मान्य खाता संख्या दर्ज करें।",
    ifscInvalid: "एक मान्य IFSC कोड दर्ज करें।",
    bankRequired: "बैंक का नाम आवश्यक है।",
    upiInvalid: "एक मान्य UPI आईडी दर्ज करें (जैसे name@bank)।",
    phoneInvalid: "एक मान्य फ़ोन नंबर दर्ज करें।",
    saved: "भुगतान विधि सहेजी गई।",
    savedTitle: "सहेजा गया",
    saveFailed: "भुगतान विधि सहेजने में विफल। कृपया पुनः प्रयास करें।",
  },

  privacyScreen: {
    title: "गोपनीयता नीति",
    bannerTitle: "आपकी गोपनीयता मायने रखती है",
    bannerSub: "यह नीति बताती है कि VoxLink Host आपके डेटा को कैसे एकत्र, उपयोग और सुरक्षित करता है।",
    lastUpdated: "अंतिम अपडेट: 1 मार्च, 2026",
    contactTitle: "गोपनीयता के बारे में प्रश्न?",
    sectionTitles: [
      "1. हम कौन सी जानकारी एकत्र करते हैं",
      "2. हम आपकी जानकारी का उपयोग कैसे करते हैं",
      "3. जानकारी साझा करना",
      "4. कॉल डेटा और ऑडियो",
      "5. KYC और पहचान सत्यापन",
      "6. कमाई और भुगतान",
      "7. डेटा सुरक्षा",
      "8. डेटा प्रतिधारण",
      "9. आपके अधिकार",
      "10. इस नीति में परिवर्तन",
    ],
  },

  referralScreen: {
    title: "रेफर करें और कमाएं",
    heroTitle: "होस्ट रेफर करें, अधिक कमाएं!",
    heroSubA: "अन्य होस्ट को अपने कोड के साथ आमंत्रित करें। जब वे अपनी पहली कॉल पूरी करते हैं, तो उन्हें मिलते हैं ",
    coinsAnd: " कॉइन और आप कमाते हैं ",
    coinsBang: " कॉइन!",
    yourCode: "आपका रेफरल कोड",
    copy: "कॉपी करें",
    copied: "कॉपी हो गया!",
    shareBtn: "अन्य होस्ट के साथ साझा करें",
    yourStats: "आपके रेफरल आँकड़े",
    hostsReferred: "रेफर किए गए होस्ट",
    coinsEarned: "अर्जित कॉइन",
    howItWorks: "यह कैसे काम करता है",
    step1: "अपना अनूठा रेफरल कोड अन्य होस्ट के साथ साझा करें",
    step2: "वे आपके कोड का उपयोग करके होस्ट के रूप में साइन अप करते हैं",
    step3Single: "वे VoxLink पर 1 कॉल पूरी करते हैं",
    step3Plural: "वे VoxLink पर {n} कॉल पूरी करते हैं",
    step3Default: "वे VoxLink पर अपनी पहली कॉल पूरी करते हैं",
    step4a: "आप कमाते हैं ",
    step4b: " कॉइन, उन्हें मिलते हैं ",
    step4c: "!",
    shareMessage: "VoxLink पर होस्ट के रूप में मेरे साथ जुड़ें और ऑडियो व वीडियो कॉल से कमाई शुरू करें!\n\nहोस्ट के रूप में साइन अप करते समय बोनस पाने के लिए मेरा रेफरल कोड उपयोग करें: {code}!\n\nअभी डाउनलोड करें: https://voxlink.app/host",
    shareTitle: "VoxLink पर होस्ट के रूप में जुड़ें",
    copiedToast: "रेफरल कोड कॉपी हो गया!",
    copiedTitle: "कॉपी हो गया",
    copyFailed: "कोड कॉपी नहीं हो सका। कृपया पुनः प्रयास करें।",
    loadFailed: "रेफरल जानकारी लोड करने में विफल।",
  },

  languageScreen: {
    title: "ऐप भाषा",
    subtitle: "अपनी पसंदीदा भाषा चुनें। परिवर्तन तुरंत लागू होते हैं।",
    soon: "जल्द",
    comingSoon: "जल्द आ रहा है",
    comingSoonSuffix: " अनुवाद जल्द आ रहा है। ऐप अंग्रेज़ी में जारी रहेगा।",
  },

  editProfileScreen: {
    title: "होस्ट प्रोफ़ाइल संपादित करें",
    displayName: "प्रदर्शन नाम",
    namePlaceholder: "आपका प्रदर्शन नाम",
    bio: "बायो",
    bioPlaceholder: "उपयोगकर्ताओं को अपने बारे में, अपनी विशेषज्ञता, और आप क्या पेश करते हैं बताएं...",
    email: "ईमेल",
    hostSettings: "होस्ट सेटिंग्स",
    setRates: "अपनी कॉल दरें सेट करें (कॉइन / मिनट)",
    manageTopics: "अपने विषय और विशेषताएं प्रबंधित करें",
    saveChanges: "परिवर्तन सहेजें",
    nameRequired: "कृपया अपना प्रदर्शन नाम दर्ज करें।",
    saved: "आपकी होस्ट प्रोफ़ाइल अपडेट हो गई है।",
    savedTitle: "प्रोफ़ाइल सहेजी गई",
    saveFailed: "प्रोफ़ाइल सहेजने में विफल। कृपया पुनः प्रयास करें।",
    permRequired: "अनुमति आवश्यक",
    permMsg: "अपनी प्रोफ़ाइल फ़ोटो बदलने के लिए कृपया अपनी फ़ोटो लाइब्रेरी तक पहुंच की अनुमति दें।",
    tapToChange: "फ़ोटो बदलने के लिए टैप करें",
    uploading: "अपलोड हो रहा है...",
    uploadFailed: "अपलोड विफल",
    uploadFailedMsg: "आपकी फ़ोटो अपलोड नहीं हो सकी। कृपया पुनः प्रयास करें।",
    photoUpdated: "प्रोफ़ाइल फ़ोटो अपडेट हो गई!",
    photoSaved: "फ़ोटो सहेजी गई",
  },

  chatThreadScreen: {
    defaultName: "चैट",
    online: "ऑनलाइन",
    typePlaceholder: "संदेश लिखें...",
    startConvo: "बातचीत शुरू करने के लिए संदेश भेजें",
    notSent: "नहीं भेजा गया",
    loadFailed: "संदेश लोड करने में विफल।",
  },

  notFoundScreen: {
    title: "ओह!",
    message: "यह स्क्रीन मौजूद नहीं है।",
    goHome: "होम पर जाएं!",
  },

  // Availability schedule screen
  availabilityScreen: {
    title: "उपलब्धता शेड्यूल",
    helpText: "वे घंटे सेट करें जब आप आमतौर पर उपलब्ध रहते हैं। कॉलर इसे आपकी प्रोफ़ाइल पर देखते हैं। यह केवल एक प्रदर्शन संकेत है — यह आपको ऑफ़लाइन नहीं करता।",
    always24Title: "हमेशा उपलब्ध (24/7)",
    always24Sub: "कोई निश्चित घंटे नहीं — किसी भी समय उपलब्ध",
    availableHours: "उपलब्ध घंटे",
    availableFrom: "उपलब्ध से",
    availableTo: "उपलब्ध तक",
    sameTimeWarn: "आरंभ और समाप्ति समय समान नहीं हो सकते।",
    overnightHint: "रातभर की अवधि — आधी रात के पार जाती है।",
    timezone: "समय क्षेत्र",
    callersWillSee: "कॉलर देखेंगे",
    available247: "24/7 उपलब्ध",
    saveSchedule: "शेड्यूल सहेजें",
    selectTimezone: "समय क्षेत्र चुनें",
    scheduleSaved: "उपलब्धता शेड्यूल सहेजा गया।",
    savedTitle: "सहेजा गया",
    invalidWindow: "अमान्य अवधि",
    featureUnavailable: "यह सुविधा अभी सर्वर पर सक्षम नहीं है। कृपया बाद में पुनः प्रयास करें।",
    unavailableTitle: "अनुपलब्ध",
    saveFailed: "सहेजने में विफल। कृपया पुनः प्रयास करें।",
  },
};

export default hi;
