// VoxLink — Chinese (Simplified) Strings

const zh = {
  common: {
    ok: "确定",
    cancel: "取消",
    confirm: "确认",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    done: "完成",
    back: "返回",
    close: "关闭",
    loading: "加载中...",
    error: "出现错误",
    retry: "重试",
    submit: "提交",
    next: "下一步",
    skip: "跳过",
    yes: "是",
    no: "否",
    search: "搜索",
    filter: "筛选",
    clear: "清除",
    apply: "应用",
    share: "分享",
    copy: "复制",
    copied: "已复制!",
    noResults: "未找到结果",
    optional: "可选",
    required: "必填",
    all: "全部",
    more: "更多",
    less: "收起",
    seeAll: "查看全部",
    noData: "暂无数据",
    refresh: "刷新",
  },
  auth: {
    login: "登录",
    register: "注册",
    logout: "退出登录",
    email: "邮箱",
    password: "密码",
    confirmPassword: "确认密码",
    forgotPassword: "忘记密码?",
    newPassword: "新密码",
    phone: "手机号码",
    otp: "验证码",
    sendOtp: "发送OTP",
    verifyOtp: "验证OTP",
    resendOtp: "重新发送OTP",
    fullName: "全名",
    createAccount: "创建账户",
    alreadyHaveAccount: "已有账户?",
    dontHaveAccount: "没有账户?",
    welcomeBack: "欢迎回来!",
    loginToContinue: "登录以继续",
    createYourAccount: "创建您的账户",
    joinVoxLink: "今天加入VoxLink",
    enterOtp: "输入发送至的OTP",
    passwordResetSent: "密码重置邮件已发送",
    checkEmail: "请查收邮件获取说明",
    passwordChanged: "密码修改成功",
    invalidCredentials: "邮箱或密码无效",
    accountDeleted: "账户已成功删除",
    deleteAccountConfirm: "您确定要删除账户吗？此操作无法撤销。",
  },
  nav: {
    home: "首页",
    search: "搜索",
    messages: "消息",
    wallet: "钱包",
    profile: "我的",
    notifications: "通知",
  },
  home: {
    greeting: "你好",
    findHosts: "查找主播",
    topListeners: "顶级倾听者",
    trending: "热门",
    newHosts: "新主播",
    onlineNow: "当前在线",
    featuredHosts: "精选主播",
    seeAll: "查看全部",
    searchPlaceholder: "搜索主播、话题...",
  },
  hosts: {
    host: "主播",
    listener: "倾听者",
    online: "在线",
    offline: "离线",
    busy: "忙碌",
    rating: "评分",
    reviews: "评价",
    review: "评价",
    coinsPerMinute: "金币/分钟",
    totalMinutes: "累计分钟",
    specialties: "专长",
    languages: "语言",
    about: "关于",
    callNow: "立即通话",
    audioCall: "语音通话",
    videoCall: "视频通话",
    sendMessage: "发送消息",
    talkNow: "现在聊",
    noHostsFound: "未找到主播",
    adjustFilters: "请调整筛选条件",
    topRated: "评分最高",
    viewProfile: "查看资料",
    startCall: "开始通话",
  },
  calls: {
    incoming: "来电",
    outgoing: "连接中...",
    ongoing: "通话中",
    ended: "通话结束",
    audio: "语音通话",
    video: "视频通话",
    accept: "接受",
    decline: "拒绝",
    endCall: "结束通话",
    mute: "静音",
    unmute: "取消静音",
    speaker: "扬声器",
    flipCamera: "翻转摄像头",
    callDuration: "通话时长",
    callWith: "通话对象",
    rateCall: "评价此通话",
    callHistory: "通话记录",
    noCallHistory: "暂无通话记录",
    callCost: "通话费用",
    perMinute: "每分钟",
    lowBalance: "金币余额不足",
    lowBalanceMsg: "您的金币不足，请充值继续。",
    callEnded: "通话结束",
    callEndedMsg: "您的通话已结束",
    missed: "未接",
    answered: "已接",
    rejected: "已拒绝",
  },
  chat: {
    messages: "消息",
    newMessage: "新消息",
    typeMessage: "输入消息...",
    send: "发送",
    noMessages: "暂无消息",
    startConversation: "开始对话",
    online: "在线",
    offline: "离线",
    typing: "正在输入...",
    delivered: "已送达",
    read: "已读",
    deleteChat: "删除聊天",
    deleteChatConfirm: "确定要删除此对话吗?",
  },
  wallet: {
    wallet: "钱包",
    coinBalance: "金币余额",
    coins: "金币",
    coin: "金币",
    buyCoins: "购买金币",
    coinHistory: "金币记录",
    transactions: "交易记录",
    noTransactions: "暂无交易记录",
    purchased: "已购买",
    spent: "已消费",
    bonus: "奖励",
    refunded: "已退款",
    withdrawal: "提现",
    totalSpent: "总消费",
    totalPurchased: "总购买",
    popular: "最受欢迎",
    bestValue: "最超值",
    bonus_label: "奖励",
    recharge: "充值",
    choosePackage: "选择套餐",
    instantDelivery: "即时到账",
    securePayment: "安全支付",
    guaranteed: "满意保证",
  },
  profile: {
    profile: "我的",
    editProfile: "编辑资料",
    myProfile: "我的资料",
    name: "姓名",
    email: "邮箱",
    phone: "手机号",
    gender: "性别",
    male: "男",
    female: "女",
    other: "其他",
    country: "国家",
    bio: "个人简介",
    language: "语言",
    settings: "设置",
    helpCenter: "帮助中心",
    privacy: "隐私政策",
    about: "关于VoxLink",
    shareApp: "分享VoxLink",
    rateApp: "给应用评分",
    logout: "退出登录",
    deleteAccount: "删除账户",
    callHistory: "通话记录",
    joinedOn: "加入于",
    totalCalls: "总通话次数",
    hoursSpent: "花费时间",
  },
  settings: {
    settings: "设置",
    notifications: "通知",
    callNotifications: "来电通知",
    messageNotifications: "消息通知",
    promoNotifications: "推广通知",
    language: "语言",
    theme: "主题",
    lightMode: "浅色模式",
    darkMode: "深色模式",
    systemDefault: "跟随系统",
    privacy: "隐私",
    security: "安全",
    changePassword: "修改密码",
    twoFactor: "双重验证",
    account: "账户",
    support: "支持",
  },
  payment: {
    checkout: "结账",
    selectPackage: "选择套餐",
    paymentMethod: "支付方式",
    creditCard: "信用卡/借记卡",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "支付处理中...",
    paymentSuccess: "支付成功!",
    paymentFailed: "支付失败",
    orderSummary: "订单摘要",
    total: "合计",
    coins: "金币",
    bonusCoins: "奖励金币",
    tryAgain: "重试",
    secureNote: "所有支付均已加密保护",
  },
  host: {
    dashboard: "仪表盘",
    totalEarnings: "总收益",
    thisWeek: "本周",
    thisMonth: "本月",
    totalCalls: "总通话数",
    avgRating: "平均评分",
    onlineStatus: "在线状态",
    goOnline: "上线",
    goOffline: "下线",
    setBusy: "设为忙碌",
    earnings: "收益",
    withdraw: "提现",
    withdrawal: "提现",
    minimumWithdraw: "最低100金币",
    enterAmount: "输入金额",
    withdrawMethod: "提现方式",
    bankTransfer: "银行转账",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "账户详情",
    withdrawSuccess: "提现申请已提交",
    withdrawPending: "您的申请正在处理中",
    hostSettings: "主播设置",
    availability: "可用状态",
    payoutSettings: "收款设置",
    becomeHost: "成为主播",
    apply: "立即申请",
    applicationSent: "申请已发送!",
    applicationDesc: "我们将审核您的申请并在2-3个工作日内回复。",
  },
  errors: {
    network: "网络错误，请检查您的连接。",
    server: "服务器错误，请稍后重试。",
    unauthorized: "会话已过期，请重新登录。",
    notFound: "未找到请求的资源。",
    insufficientCoins: "金币不足，请充值。",
    callFailed: "通话无法连接，请重试。",
    permissionDenied: "权限被拒绝。",
    generic: "出现错误，请重试。",
  },

  tabs: {
    home: "首页",
    chat: "聊天",
    calls: "通话",
    wallet: "钱包",
    profile: "我的",
  },

  hostSettings: {
    title: "主播设置",
    availability: "可用状态",
    autoOnline: "打开应用时自动上线",
    dnd: "勿扰模式",
    dndOn: "开启 — 静音通知",
    schedule: "可用时间表",
    randomCalls: "随机通话",
    availableRandom: "可接受随机通话",
    randomOn: "开启 — 已加入随机匹配池",
    randomOff: "关闭 — 仅限直接通话",
    allowVideoRandom: "允许随机视频通话",
    videoDisabled: "已禁用 — 随机通话已关闭",
    videoOn: "开启 — 接受随机视频通话",
    videoOff: "关闭 — 仅限随机语音通话",
    loading: "加载中…",
    pushNotifications: "推送通知",
    notificationPrefs: "通知偏好",
    incomingCallAlerts: "来电提醒",
    chatNotifications: "聊天通知",
    coinEarnedAlerts: "金币收益提醒",
    earnings: "收益",
    payoutMethod: "提现方式",
    withdrawEarnings: "提取收益",
    referEarn: "推荐赚钱",
    preferences: "偏好设置",
    appLanguage: "应用语言",
    support: "支持",
    helpSupport: "帮助与支持",
    privacyPolicy: "隐私政策",
    aboutApp: "关于 VoxLink Host",
    account: "账户",
    signOut: "退出登录",
    deleteAccount: "删除账户",
    on: "开启",
    off: "关闭",
    alwaysAvailable: "始终可用",
  },

  homeScreen: {
    online: "您已上线",
    offline: "您已离线",
    onlineSub: "可接收通话",
    offlineSub: "开启以开始接受通话",
    totalCalls: "总通话数",
    totalHours: "总时长",
    earnings: "收益",
    yourCallRates: "您的通话费率",
    ratesSub: "用户每分钟支付给您的金币",
    edit: "编辑",
    audioPerMin: "语音 / 分钟",
    videoPerMin: "视频 / 分钟",
    manage: "管理",
    qaCallRates: "通话费率",
    qaCallRatesDesc: "设置您的价格",
    qaTopics: "我的话题",
    qaTopicsDesc: "触达更多用户",
    qaEarnings: "收益",
    qaEarningsDesc: "查看历史",
    qaPayouts: "提现",
    qaPayoutsDesc: "提取金币",
    qaWallet: "钱包",
    qaWalletDesc: "余额与提现",
    qaCallHistory: "通话记录",
    qaCallHistoryDesc: "过往通话",
    qaRefer: "推荐赚钱",
    qaReferDesc: "邀请好友",
    qaProfile: "个人资料",
    qaProfileDesc: "编辑详情",
    qaSettings: "设置",
    qaSettingsDesc: "应用偏好",
    permsRequired: "需要权限",
    micLabel: "麦克风",
    micDesc: "语音通话所需",
    cameraLabel: "摄像头",
    cameraDesc: "视频通话所需",
    notifLabel: "通知",
    notifDesc: "用于来电提醒",
    granted: "已授权",
    tapToAllow: "点击以允许",
    hostTips: "主播提示",
    tip1: "在高峰时段（晚6点-10点）保持在线",
    tip2: "完善资料以获得更多预约",
    tip3: "快速回复以提高您的评分",
    tip4: "添加更多话题以触达更多用户",
  },

  profileScreen: {
    title: "我的资料",
    proHost: "专业主播",
    calls: "通话",
    rating: "评分",
    coins: "金币",
    onlineStatus: "在线状态",
    pushNotifications: "推送通知",
    account: "账户",
    editProfile: "编辑资料",
    callRates: "通话费率",
    myTopics: "我的话题",
    settings: "设置",
    language: "语言",
    more: "更多",
    referEarn: "推荐赚钱",
    helpCenter: "帮助中心",
    privacyPolicy: "隐私政策",
    about: "关于 VoxLink",
    signOut: "退出登录",
    signOutConfirm: "确定要退出登录吗？",
    permRequiredTitle: "需要权限",
    permRequiredMsg: "请允许访问您的照片库以更换头像。",
    turnOffNotifTitle: "关闭通知",
    turnOffNotifMsg: "要关闭通知，请前往手机设置并关闭 VoxLink Host 的通知。",
    openSettings: "打开设置",
    uploadFailedTitle: "上传失败",
    uploadFailedMsg: "无法上传您的照片，请重试。",
    photoUpdated: "头像已更新！",
    photoSaved: "照片已保存",
  },

  callsScreen: {
    title: "通话记录",
    all: "全部",
    audio: "语音",
    video: "视频",
    completed: "已完成",
    missed: "未接",
    cancelled: "已取消",
    noCalls: "暂无通话",
    loadError: "无法加载通话，下拉刷新。",
  },

  chatScreen: {
    title: "消息",
    searchPlaceholder: "搜索对话...",
    noConversations: "暂无对话",
    noMessagesYet: "暂无消息",
    now: "刚刚",
  },

  walletScreen: {
    title: "主播钱包",
    availableBalance: "可用余额",
    coins: "金币",
    payoutValue: "提现价值",
    thisWeek: "本周",
    sessions: "场次",
    withdrawn: "已提现",
    earningsHistory: "收益历史",
    withdraw: "提现",
    noEarnings: "暂无收益",
    quickSelect: "快速选择金额",
    orEnter: "或输入金额",
    enterCoinAmount: "输入金币数量",
    payoutTo: "提现至",
    setupPayout: "设置您的提现方式",
    edit: "编辑",
    managePayout: "管理提现方式",
    requestWithdrawal: "申请提现",
    note: "注意",
    failedLoad: "加载收益数据失败。",
  },

  loginScreen: {
    tagline: "赚取 · 连接 · 扩大你的受众",
    chipKyc: "KYC 已验证",
    chipEarn: "赚取金币",
    chipPlatform: "主播平台",
    welcomeBack: "欢迎回来",
    subtitle: "登录您的主播账户",
    emailPlaceholder: "邮箱地址",
    passwordPlaceholder: "密码",
    signIn: "以主播身份登录",
    orContinue: "或使用以下方式继续",
    continueGoogle: "使用 Google 继续",
    signingIn: "正在登录...",
    newPrompt: "初次使用 VoxLink Host？ ",
    applyNow: "立即申请",
  },

  registerScreen: {
    stepAccount: "账户",
    stepProfile: "资料",
    stepHostInfo: "主播信息",
    stepKyc: "KYC 文件",
    title: "成为主播",
    headerSub: "完成 4 个步骤即可开始赚钱",
    createTitle: "创建您的账户",
    createSub: "这将是您的 VoxLink Host 登录账号",
    namePlaceholder: "全名",
    emailPlaceholder: "邮箱地址",
    passwordPlaceholder: "密码（8 个以上字符）",
    continueBtn: "继续",
    orSignUp: "或使用以下方式注册",
    continueGoogle: "使用 Google 继续",
    signingIn: "正在登录...",
    alreadyRegistered: "已经注册？ ",
    signIn: "登录",
  },

  authToasts: {
    missingFields: "信息不完整",
    loginMissing: "请输入邮箱和密码。",
    invalidEmail: "邮箱无效",
    invalidEmailMsg: "请输入有效的邮箱地址。",
    loginFailed: "登录失败",
    loginFailedMsg: "邮箱或密码无效。",
    notSupported: "不支持",
    playServices: "Google Play 服务不可用。",
    connectionError: "连接错误",
    noInternet: "无网络连接。",
    signInFailed: "登录失败",
    googleFailed: "Google 登录失败",
    almostThere: "就快完成了",
    googleWelcomeHost: "欢迎！请完善您的主播资料和 KYC。",
    googleWelcomeProfile: "欢迎！请完善资料以申请成为主播。",
    signInFailedRetry: "登录失败，请重试。",
    googleNoAccount: "无法获取 Google 账户信息。",
    googleNoToken: "Google 登录未返回令牌。请更新应用或重试。",
    registerMissing: "请填写所有字段。",
    weakPassword: "密码太弱",
    weakPasswordMsg: "密码至少需要 8 个字符。",
    welcomeBack: "欢迎回来",
    resuming: "正在恢复您未完成的注册。",
    alreadyRegisteredTitle: "已注册",
    alreadyRegisteredMsg: "此邮箱已注册，请直接登录。",
    createFailed: "无法创建账户，请重试。",
  },

  forgotPasswordScreen: {
    checkEmail: "查收您的邮件",
    forgotPassword: "忘记密码？",
    sentLine1: "我们已发送 6 位 OTP 至",
    sentLine2: "输入验证码并设置新密码。",
    enterEmailPrompt: "输入您注册的邮箱，我们将发送 OTP 以重置密码。",
    resetPassword: "重置密码",
    otpPlaceholder: "输入 OTP 验证码",
    newPasswordPlaceholder: "新密码",
    confirmPasswordPlaceholder: "确认新密码",
    resetting: "正在重置...",
    resetBtn: "重置密码",
    didntReceive: "没有收到？ ",
    resendIn: "重新发送于",
    resendOtp: "重新发送 OTP",
    findAccount: "查找您的账户",
    emailPlaceholder: "邮箱地址",
    sending: "正在发送...",
    sendOtp: "发送 OTP",
    backTo: "返回 ",
    signIn: "登录",
    enterEmailError: "请输入您的邮箱地址。",
    otpSent: "OTP 已发送至您的邮箱。",
    emailSent: "邮件已发送",
    emailNotFound: "未找到该邮箱，请检查后重试。",
    enterOtpError: "请输入发送至您邮箱的 OTP。",
    weakPassword: "密码太弱",
    weakPasswordMsg: "密码至少需要 8 个字符。",
    mismatch: "不匹配",
    passwordsDontMatch: "两次密码不一致。",
    successTitle: "成功",
    resetSuccess: "密码更新成功！请登录。",
    errorTitle: "错误",
    resetFailed: "重置密码失败，OTP 可能已过期。",
  },

  onboardingScreen: {
    slide1Title: "发现",
    slide1Sub: "您可以与世界各地的人\n建立联系，进行聊天、发送消息\n并与他们建立连接。",
    slide2Title: "聊天",
    slide2Sub: "与陌生人聊天，更好地了解彼此\n并建立良好的\n默契。",
    slide3Title: "视频通话",
    slide3Sub: "您可以与好友和联系人\n分享您的视频和照片。",
  },

  profileSetupScreen: {
    headerSub: "第 2 步 / 共 4 步 — 您的资料",
    sectionTitle: "您的资料信息",
    sectionSub: "这将对呼叫您的用户可见",
    uploading: "正在上传...",
    tapAddPhoto: "点击添加头像",
    namePlaceholder: "显示名称",
    dobPlaceholder: "出生日期（点击选择）",
    phonePlaceholder: "手机号码",
    genderLabel: "性别",
    continueBtn: "继续 → 主播信息",
    done: "完成",
    dobTitle: "出生日期",
    day: "日",
    month: "月",
    year: "年",
    months: ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
    uploadFailed: "上传失败",
    uploadFailedMsg: "无法上传照片，请重试。",
    missingFields: "信息不完整",
    missingFieldsMsg: "请填写所有必填字段。",
    invalidPhone: "电话无效",
    invalidPhoneMsg: "请输入有效的手机号码。",
    saveFailed: "保存失败",
    saveFailedMsg: "无法保存您的资料，请重试。",
  },

  becomeScreen: {
    headerSub: "第 3 步 / 共 4 步 — 主播信息",
    sectionTitle: "您的主播资料",
    sectionSub: "帮助用户了解您能提供什么",
    specialtiesLabel: "专长（选择 1–5 个）",
    languagesLabel: "语言",
    bioLabel: "个人简介",
    bioPlaceholder: "向用户介绍您自己 — 您的专长、个性，以及您的通话有何特别之处...",
    experienceLabel: "经验（可选）",
    experiencePlaceholder: "例如：3 年生活教练经验",
    callTypeLabel: "提供的通话类型",
    audioOnly: "🎤 仅语音",
    videoOnly: "🎥 仅视频",
    both: "🎤🎥 两者",
    ratesLabel: "您的通话费率（金币/分钟）",
    audio: "语音",
    video: "视频",
    coinsPerMin: "金币/分钟",
    note: "费率仅为建议。审核通过后管理员可能会调整。",
    continueBtn: "继续 →  KYC 文件",
    selectSpecialty: "选择专长",
    chooseSpecialty: "请至少选择一个专长。",
    bioTooShort: "简介过短",
    bioTooShortMsg: "请撰写至少 20 个字符的简介。",
  },

  kycScreen: {
    headerSub: "第 4 步 / 共 4 步 — KYC 文件",
    sectionTitle: "身份验证",
    sectionSub: "开始接单前必需。您的文件将被安全存储。",
    notice: "根据印度法规，KYC 为强制要求。文件仅由管理员审核，绝不与用户分享。",
    dobLabel: "出生日期",
    fromStep2: "来自第 2 步",
    dobPlaceholder: "日/月/年（例如 22/05/1998）",
    docAadharFront: "Aadhar 正面",
    docAadharFrontSub: "Aadhar 卡正面照片",
    docAadharBack: "Aadhar 背面",
    docAadharBackSub: "Aadhar 卡背面照片",
    docVideo: "验证视频",
    docVideoSub: "您手持 Aadhar 的短视频（5–15 秒）",
    uploading: "正在上传...",
    uploaded: "已上传 ✓",
    tipsTitle: "审核通过提示",
    tip1: "确保 Aadhar 照片清晰、不模糊",
    tip2: "在验证视频中清晰地手持 Aadhar 卡",
    tip3: "录制时直视摄像头",
    submitting: "正在提交...",
    submit: "提交申请",
    uploadFailed: "上传失败",
    uploadFailedMsg: "无法上传文件，请重试。",
    missingDocs: "文件缺失",
    missingDocsMsg: "请上传 Aadhar 正面和背面照片。",
    missingDob: "缺少出生日期",
    missingDobMsg: "缺少出生日期。请返回第 2 步选择您的出生日期。",
    submitFailed: "提交失败",
    submitFailedMsg: "无法提交您的申请，请重试。",
  },

  statusScreen: {
    headerTitle: "主播申请",
    headerSub: "跟踪您的 KYC 验证状态",
    checking: "正在检查申请状态...",
    pendingTitle: "申请已提交",
    pendingMsg: "您的申请已进入队列。我们的团队将在 24–48 小时内审核。",
    underReviewTitle: "审核中",
    underReviewMsg: "我们的团队正在积极审核您的申请。您很快会收到回复。",
    approvedTitle: "恭喜！",
    approvedMsg: "您的申请已通过！您现在是 VoxLink 的认证主播。",
    rejectedTitle: "申请被拒",
    rejectedMsg: "很遗憾，您的申请未通过。请查看下方原因并重新申请。",
    notAppliedTitle: "未找到申请",
    notAppliedMsg: "您尚未提交主播申请。",
    approvedSub: "您现在是 VoxLink 的认证主播。开始接听通话并赚取金币吧！",
    earnCoins: "赚取金币",
    buildRating: "建立评分",
    takeCalls: "接听通话",
    timelineTitle: "申请时间线",
    tlAccount: "账户已创建",
    tlSubmitted: "申请已提交",
    tlReview: "审核中",
    tlDecision: "已作出决定",
    continueDashboard: "前往仪表盘",
    reasonRejection: "拒绝原因",
    reapply: "重新申请",
    startApplication: "开始申请",
    autoChecking: "每 10 秒自动检查一次...",
    loadError: "加载申请状态失败。",
  },

  audioCallScreen: {
    voiceCall: "语音通话",
    ringing: "正在响铃...",
    connecting: "连接中...",
    connected: "已连接",
    reconnecting: "网络中断 — 正在重连...",
    connFailed: "连接失败 — 正在重试...",
    callEnded: "通话结束",
    unknown: "未知",
    muted: "🔇 已静音",
    coinsPerMin: "金币 / 分钟",
    remaining: "剩余",
    minLeft: "分钟剩余",
    callEndingSoon: "通话即将结束 — ",
    micNeeded: "需要麦克风权限 — 点击修复",
    mute: "静音",
    unmute: "取消静音",
    speaker: "扬声器",
    speakerOn: "扬声器已开",
  },

  videoCallScreen: {
    connecting: "连接中...",
    connected: "已连接",
    reconnecting: "网络中断 — 正在重连...",
    connFailed: "连接失败 — 正在重试...",
    ringing: "正在响铃...",
    cameraOff: "摄像头关闭",
    connectionIssue: "连接问题",
    live: "直播",
    settingUp: "正在建立安全连接...",
    waitingResponse: "等待响应...",
    connectingName: "连接中...",
    cameraUnavailable: "摄像头不可用",
    startingCamera: "正在启动摄像头…",
    noPermission: "无权限",
    cameraOffLabel: "摄像头关闭",
    you: "你",
    mutedBadge: "已静音",
    noMic: "无麦克风",
    callEndingSoon: "通话即将结束 — ",
    minLeft: "分钟剩余",
    secLeft: "秒剩余",
    ctrlCamera: "摄像头",
    ctrlCamOff: "摄像头关",
    ctrlUnmute: "取消静音",
    ctrlMute: "静音",
    ctrlEnd: "结束",
    ctrlFlip: "翻转",
    ctrlSpeaker: "扬声器",
    ctrlEarpiece: "听筒",
  },

  incomingCallScreen: {
    incomingVideo: "视频来电",
    incomingAudio: "语音来电",
    unknown: "未知",
    voxlinkHost: "VoxLink 主播",
    voxlinkUser: "VoxLink 用户",
    decline: "拒绝",
    accept: "接听",
  },

  outgoingCallScreen: {
    videoCall: "视频通话",
    voiceCall: "语音通话",
    callDeclined: "通话被拒",
    noAnswer: "无人接听",
    ringing: "正在响铃...",
    connecting: "连接中...",
    cancel: "取消",
  },

  callSummaryScreen: {
    autoEndedBanner: "用户金币用尽 — 通话已自动断开",
    callAutoEnded: "通话自动结束",
    callCompleted: "通话完成",
    withName: "与",
    duration: "时长",
    coinsEarned: "已赚金币",
    video: "视频",
    audio: "语音",
    ratePrefix: "评价",
    rateSub: "分享您本次通话的体验",
    ratingLabels: ["", "差", "一般", "好", "很好", "非常好！"],
    submitRating: "⭐ 提交评分",
    skip: "跳过",
    thankYouTitle: "谢谢！🙏",
    thankYouSub: "您的评分已提交",
    viewEarnings: "查看收益",
    backHome: "返回首页",
    ratingError: "提交评分失败，请重试。",
    errorTitle: "错误",
    user: "用户",
  },

  callHistoryScreen: {
    title: "通话记录",
    all: "全部",
    audio: "语音",
    video: "视频",
    completed: "已完成",
    missed: "未接",
    cancelled: "已取消",
    noHistory: "未找到通话记录",
    coins: "金币",
    loadFailed: "加载通话记录失败。",
  },

  aboutScreen: {
    title: "关于 VoxLink",
    tagline: "语音与视频连接 — 主播版",
    version: "版本",
    statActiveUsers: "活跃用户",
    statHosts: "主播",
    statCallsMade: "已完成通话",
    statAppRating: "应用评分",
    whatIsTitle: "什么是 VoxLink Host？",
    whatIsBody1: "VoxLink Host 是 VoxLink 平台认证主播的专属应用。作为主播，您可与用户进行有意义的语音和视频对话 — 无论是人生建议、语言练习、情感支持还是陪伴。",
    whatIsBody2: "主播按完成通话的每分钟赚取金币。金币可兑换成真实货币并直接提现到您的银行账户。自定您的时间表，扩大受众，按自己的方式赚钱。",
    featuresTitle: "主播功能",
    featHd: "高清语音与视频通话",
    featEncrypted: "端到端加密",
    featEarn: "按分钟赚取金币",
    featDashboard: "实时收益仪表盘",
    featChat: "应用内与用户聊天",
    featRatings: "评分与评价",
    featSchedule: "灵活的可用时间表",
    connectTitle: "联系我们",
    linkWebsite: "网站",
    linkTwitter: "Twitter / X",
    linkInstagram: "Instagram",
    linkContact: "联系我们",
    privacyPolicy: "隐私政策",
    helpCenter: "帮助中心",
    copyright: "© 2026 VoxLink Inc. 保留所有权利。",
  },

  callRatesScreen: {
    title: "通话费率",
    helpA: "设置用户每分钟支付给您多少金币。视频通话通常比语音赚得多。在您当前等级，您最多可收取 ",
    coinsPerMinAudio: " 金币/分钟（语音）",
    helpB: " 和 ",
    coinsPerMinVideo: " 金币/分钟（视频）",
    helpC: "（管理员等级上限 +",
    helpD: " 奖励）。达到更高等级以提升这些上限。",
    levelWord: "等级",
    hostSuffix: " 主播",
    yourRates: "您的费率",
    audioCall: "语音通话",
    audioSub: "语音通话每分钟",
    videoCall: "视频通话",
    videoSub: "视频通话每分钟",
    coinsMin: "金币 / 分钟",
    maxLabel: "最高 ",
    upToLabel: "最多 ",
    capSuffix: " 金币/分钟（您的等级）",
    estTitle: "收益估算",
    est10AudioPrefix: "10 分钟语音通话 ≈ ",
    est10VideoPrefix: "10 分钟视频通话 ≈ ",
    coinsSuffix: " 金币",
    estNote: "每次完成通话后，金币会添加到您的收益中。",
    saveRates: "保存费率",
    ratesSaved: "您的通话费率已更新。",
    ratesSavedTitle: "费率已保存",
    saveFailed: "保存费率失败，请重试。",
  },

  earningsHistoryScreen: {
    title: "收益历史",
    totalEarnings: "总收益",
    earned: "已赚",
    withdrawn: "已提现",
    tabAll: "全部",
    tabEarned: "已赚",
    tabWithdrawn: "已提现",
    tabBonus: "奖励",
    noTransactions: "未找到交易记录",
    loadFailed: "加载收益历史失败。",
    today: "今天",
    yesterday: "昨天",
    ref: "参考: ",
  },

  helpCenterScreen: {
    title: "帮助中心",
    bannerTitle: "主播帮助与常见问题",
    bannerSub: "查找常见主播问题的答案",
    contactTitle: "联系主播支持",
    faqTitle: "常见问题",
  },

  levelBenefitsScreen: {
    title: "等级福利",
    subtitle: "升级阶梯，赚得更多",
    current: "当前",
    unlocked: "已解锁",
    locked: "已锁定",
    requirements: "要求",
    ratedCalls: " 次评分通话",
    rating: " 评分",
    rewardsPerks: "奖励与福利",
    earningsSuffix: "% 收益",
    audioUpTo: "🎙️ 语音最高 ",
    videoUpTo: "📹 视频最高 ",
    perMin: "/分钟",
    higherVisibility: "🚀 更高曝光",
    youreAtLevel: "您处于等级 ",
    maxLevelMsg: "您已达到最高等级。继续加油！",
    progressMid: "% 的进度，距离 ",
    loadError: "无法加载等级福利。请检查网络后重试。",
    retry: "重试",
    retrying: "正在重试…",
    footnote: "评分通话是指获得星级评价的通话。等级奖励在您首次达到每个等级时一次性发放。更高等级让您收费更高、保留更大份额的收益，并在用户面前获得更高排名。",
  },

  manageTopicsScreen: {
    title: "我的话题",
    helpPrefix: "选择您擅长的话题。浏览这些话题的用户能更快找到您。最多选择 ",
    helpSuffix: " 个。",
    topics: "话题",
    addYourOwn: "添加自定义",
    customPlaceholder: "例如：占星、健身…",
    add: "添加",
    noTopics: "暂无可用话题。在下方添加您自己的。",
    saveTopics: "保存话题",
    maxPrefix: "您最多可选择 ",
    maxSuffix: " 个话题。",
    topicsSaved: "您的话题已更新。",
    topicsSavedTitle: "话题已保存",
    saveFailed: "保存话题失败，请重试。",
  },

  notificationsScreen: {
    title: "通知",
    markAllRead: "全部标为已读",
    empty: "暂无通知",
    loadFailed: "加载通知失败。",
    markFailed: "将通知标为已读失败。",
    updateFailed: "更新通知失败。",
  },

  payoutMethodScreen: {
    title: "提现方式",
    help: "选择您希望如何收取收益。您的提现请求将默认使用此账户。",
    channel: "渠道",
    details: "详情",
    bank: "银行账户",
    upi: "UPI",
    paytm: "Paytm",
    phonepe: "PhonePe",
    accountHolder: "账户持有人姓名",
    accountHolderPh: "账户上的全名",
    accountNumber: "账号",
    ifsc: "IFSC 代码",
    bankName: "银行名称",
    upiId: "UPI ID",
    paytmPhone: "Paytm 电话号码",
    phonepePhone: "PhonePe 电话号码",
    save: "保存提现方式",
    holderRequired: "账户持有人姓名为必填项。",
    accountInvalid: "请输入有效的账号。",
    ifscInvalid: "请输入有效的 IFSC 代码。",
    bankRequired: "银行名称为必填项。",
    upiInvalid: "请输入有效的 UPI ID（例如 name@bank）。",
    phoneInvalid: "请输入有效的电话号码。",
    saved: "提现方式已保存。",
    savedTitle: "已保存",
    saveFailed: "保存提现方式失败，请重试。",
  },

  privacyScreen: {
    title: "隐私政策",
    bannerTitle: "您的隐私至关重要",
    bannerSub: "本政策说明 VoxLink Host 如何收集、使用和保护您的数据。",
    lastUpdated: "最后更新：2026 年 3 月 1 日",
    contactTitle: "关于隐私有疑问？",
    sectionTitles: [
      "1. 我们收集的信息",
      "2. 我们如何使用您的信息",
      "3. 信息共享",
      "4. 通话数据与音频",
      "5. KYC 与身份验证",
      "6. 收益与提现",
      "7. 数据安全",
      "8. 数据保留",
      "9. 您的权利",
      "10. 本政策的变更",
    ],
  },

  referralScreen: {
    title: "推荐赚钱",
    heroTitle: "推荐主播，赚得更多！",
    heroSubA: "用您的代码邀请其他主播。当他们完成首次通话时，他们获得 ",
    coinsAnd: " 金币，您赚得 ",
    coinsBang: " 金币！",
    yourCode: "您的推荐码",
    copy: "复制",
    copied: "已复制！",
    shareBtn: "与其他主播分享",
    yourStats: "您的推荐统计",
    hostsReferred: "已推荐主播",
    coinsEarned: "已赚金币",
    howItWorks: "运作方式",
    step1: "与其他主播分享您的专属推荐码",
    step2: "他们使用您的代码注册为主播",
    step3Single: "他们在 VoxLink 上完成 1 次通话",
    step3Plural: "他们在 VoxLink 上完成 {n} 次通话",
    step3Default: "他们在 VoxLink 上完成首次通话",
    step4a: "您赚得 ",
    step4b: " 金币，他们获得 ",
    step4c: "！",
    shareMessage: "在 VoxLink 上加入我成为主播，开始通过语音和视频通话赚钱！\n\n注册成为主播时使用我的推荐码：{code} 即可获得奖励！\n\n立即下载：https://voxlink.app/host",
    shareTitle: "加入 VoxLink 成为主播",
    copiedToast: "推荐码已复制！",
    copiedTitle: "已复制",
    copyFailed: "无法复制代码，请重试。",
    loadFailed: "加载推荐信息失败。",
  },

  languageScreen: {
    title: "应用语言",
    subtitle: "选择您偏好的语言。更改将立即生效。",
    soon: "即将推出",
    comingSoon: "即将推出",
    comingSoonSuffix: " 的翻译即将推出。应用将继续以英语显示。",
  },

  editProfileScreen: {
    title: "编辑主播资料",
    displayName: "显示名称",
    namePlaceholder: "您的显示名称",
    bio: "个人简介",
    bioPlaceholder: "向用户介绍您自己、您的专长以及您能提供什么...",
    email: "邮箱",
    hostSettings: "主播设置",
    setRates: "设置您的通话费率（金币 / 分钟）",
    manageTopics: "管理您的话题与专长",
    saveChanges: "保存更改",
    nameRequired: "请输入您的显示名称。",
    saved: "您的主播资料已更新。",
    savedTitle: "资料已保存",
    saveFailed: "保存资料失败，请重试。",
    permRequired: "需要权限",
    permMsg: "请允许访问您的照片库以更换头像。",
    tapToChange: "点击更换照片",
    uploading: "正在上传...",
    uploadFailed: "上传失败",
    uploadFailedMsg: "无法上传您的照片，请重试。",
    photoUpdated: "头像已更新！",
    photoSaved: "照片已保存",
  },

  chatThreadScreen: {
    defaultName: "聊天",
    online: "在线",
    typePlaceholder: "输入消息...",
    startConvo: "发送一条消息开始对话",
    notSent: "未发送",
    loadFailed: "加载消息失败。",
  },

  notFoundScreen: {
    title: "哎呀！",
    message: "此页面不存在。",
    goHome: "前往首页！",
  },

  // Availability schedule screen
  availabilityScreen: {
    title: "可用时间安排",
    helpText: "设置您通常可用的时间。来电者会在您的资料中看到。这只是显示提示——不会强制您离线。",
    always24Title: "全天候可用 (24/7)",
    always24Sub: "无固定时间——随时可用",
    availableHours: "可用时段",
    availableFrom: "可用起始",
    availableTo: "可用结束",
    sameTimeWarn: "开始和结束时间不能相同。",
    overnightHint: "跨夜时段——延续到午夜之后。",
    timezone: "时区",
    callersWillSee: "来电者将看到",
    available247: "24/7 可用",
    saveSchedule: "保存安排",
    selectTimezone: "选择时区",
    scheduleSaved: "可用时间安排已保存。",
    savedTitle: "已保存",
    invalidWindow: "无效时段",
    featureUnavailable: "此功能尚未在服务器上启用。请稍后再试。",
    unavailableTitle: "不可用",
    saveFailed: "保存失败，请重试。",
  },
};

export default zh;
