// VoxLink — Chinese (Simplified) Strings

const zh = {
  common: {
    ok: "确定",
    cancel: "取消",
    confirm: "确认",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    done: "完成",
    back: "返回",
    close: "关闭",
    loading: "加载中...",
    error: "出现错误",
    retry: "重试",
    submit: "提交",
    next: "下一步",
    skip: "跳过",
    yes: "是",
    no: "否",
    search: "搜索",
    filter: "筛选",
    clear: "清除",
    apply: "应用",
    share: "分享",
    copy: "复制",
    copied: "已复制!",
    noResults: "未找到结果",
    optional: "可选",
    required: "必填",
    all: "全部",
    more: "更多",
    less: "收起",
    seeAll: "查看全部",
    noData: "暂无数据",
    refresh: "刷新",
  },
  auth: {
    login: "登录",
    register: "注册",
    logout: "退出登录",
    email: "邮箱",
    password: "密码",
    confirmPassword: "确认密码",
    forgotPassword: "忘记密码?",
    newPassword: "新密码",
    phone: "手机号码",
    otp: "验证码",
    sendOtp: "发送OTP",
    verifyOtp: "验证OTP",
    resendOtp: "重新发送OTP",
    fullName: "全名",
    createAccount: "创建账户",
    alreadyHaveAccount: "已有账户?",
    dontHaveAccount: "没有账户?",
    welcomeBack: "欢迎回来!",
    loginToContinue: "登录以继续",
    createYourAccount: "创建您的账户",
    joinVoxLink: "今天加入VoxLink",
    enterOtp: "输入发送至的OTP",
    passwordResetSent: "密码重置邮件已发送",
    checkEmail: "请查收邮件获取说明",
    passwordChanged: "密码修改成功",
    invalidCredentials: "邮箱或密码无效",
    accountDeleted: "账户已成功删除",
    deleteAccountConfirm: "您确定要删除账户吗？此操作无法撤销。",
  },
  nav: {
    home: "首页",
    search: "搜索",
    messages: "消息",
    wallet: "钱包",
    profile: "我的",
    notifications: "通知",
  },
  home: {
    greeting: "你好",
    findHosts: "查找主播",
    topListeners: "顶级倾听者",
    trending: "热门",
    newHosts: "新主播",
    onlineNow: "当前在线",
    featuredHosts: "精选主播",
    seeAll: "查看全部",
    searchPlaceholder: "搜索主播、话题...",
  },
  hosts: {
    host: "主播",
    listener: "倾听者",
    online: "在线",
    offline: "离线",
    busy: "忙碌",
    rating: "评分",
    reviews: "评价",
    review: "评价",
    coinsPerMinute: "金币/分钟",
    totalMinutes: "累计分钟",
    specialties: "专长",
    languages: "语言",
    about: "关于",
    callNow: "立即通话",
    audioCall: "语音通话",
    videoCall: "视频通话",
    sendMessage: "发送消息",
    talkNow: "现在聊",
    noHostsFound: "未找到主播",
    adjustFilters: "请调整筛选条件",
    topRated: "评分最高",
    viewProfile: "查看资料",
    startCall: "开始通话",
  },
  calls: {
    incoming: "来电",
    outgoing: "连接中...",
    ongoing: "通话中",
    ended: "通话结束",
    audio: "语音通话",
    video: "视频通话",
    accept: "接受",
    decline: "拒绝",
    endCall: "结束通话",
    mute: "静音",
    unmute: "取消静音",
    speaker: "扬声器",
    flipCamera: "翻转摄像头",
    callDuration: "通话时长",
    callWith: "通话对象",
    rateCall: "评价此通话",
    callHistory: "通话记录",
    noCallHistory: "暂无通话记录",
    callCost: "通话费用",
    perMinute: "每分钟",
    lowBalance: "金币余额不足",
    lowBalanceMsg: "您的金币不足，请充值继续。",
    callEnded: "通话结束",
    callEndedMsg: "您的通话已结束",
    missed: "未接",
    answered: "已接",
    rejected: "已拒绝",
  },
  chat: {
    messages: "消息",
    newMessage: "新消息",
    typeMessage: "输入消息...",
    send: "发送",
    noMessages: "暂无消息",
    startConversation: "开始对话",
    online: "在线",
    offline: "离线",
    typing: "正在输入...",
    delivered: "已送达",
    read: "已读",
    deleteChat: "删除聊天",
    deleteChatConfirm: "确定要删除此对话吗?",
  },
  wallet: {
    wallet: "钱包",
    coinBalance: "金币余额",
    coins: "金币",
    coin: "金币",
    buyCoins: "购买金币",
    coinHistory: "金币记录",
    transactions: "交易记录",
    noTransactions: "暂无交易记录",
    purchased: "已购买",
    spent: "已消费",
    bonus: "奖励",
    refunded: "已退款",
    withdrawal: "提现",
    totalSpent: "总消费",
    totalPurchased: "总购买",
    popular: "最受欢迎",
    bestValue: "最超值",
    bonus_label: "奖励",
    recharge: "充值",
    choosePackage: "选择套餐",
    instantDelivery: "即时到账",
    securePayment: "安全支付",
    guaranteed: "满意保证",
  },
  profile: {
    profile: "我的",
    editProfile: "编辑资料",
    myProfile: "我的资料",
    name: "姓名",
    email: "邮箱",
    phone: "手机号",
    gender: "性别",
    male: "男",
    female: "女",
    other: "其他",
    country: "国家",
    bio: "个人简介",
    language: "语言",
    settings: "设置",
    helpCenter: "帮助中心",
    privacy: "隐私政策",
    about: "关于VoxLink",
    shareApp: "分享VoxLink",
    rateApp: "给应用评分",
    logout: "退出登录",
    deleteAccount: "删除账户",
    callHistory: "通话记录",
    joinedOn: "加入于",
    totalCalls: "总通话次数",
    hoursSpent: "花费时间",
  },
  settings: {
    settings: "设置",
    notifications: "通知",
    callNotifications: "来电通知",
    messageNotifications: "消息通知",
    promoNotifications: "推广通知",
    language: "语言",
    theme: "主题",
    lightMode: "浅色模式",
    darkMode: "深色模式",
    systemDefault: "跟随系统",
    privacy: "隐私",
    security: "安全",
    changePassword: "修改密码",
    twoFactor: "双重验证",
    account: "账户",
    support: "支持",
  },
  payment: {
    checkout: "结账",
    selectPackage: "选择套餐",
    paymentMethod: "支付方式",
    creditCard: "信用卡/借记卡",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "支付处理中...",
    paymentSuccess: "支付成功!",
    paymentFailed: "支付失败",
    orderSummary: "订单摘要",
    total: "合计",
    coins: "金币",
    bonusCoins: "奖励金币",
    tryAgain: "重试",
    secureNote: "所有支付均已加密保护",
  },
  host: {
    dashboard: "仪表盘",
    totalEarnings: "总收益",
    thisWeek: "本周",
    thisMonth: "本月",
    totalCalls: "总通话数",
    avgRating: "平均评分",
    onlineStatus: "在线状态",
    goOnline: "上线",
    goOffline: "下线",
    setBusy: "设为忙碌",
    earnings: "收益",
    withdraw: "提现",
    withdrawal: "提现",
    minimumWithdraw: "最低100金币",
    enterAmount: "输入金额",
    withdrawMethod: "提现方式",
    bankTransfer: "银行转账",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "账户详情",
    withdrawSuccess: "提现申请已提交",
    withdrawPending: "您的申请正在处理中",
    hostSettings: "主播设置",
    availability: "可用状态",
    payoutSettings: "收款设置",
    becomeHost: "成为主播",
    apply: "立即申请",
    applicationSent: "申请已发送!",
    applicationDesc: "我们将审核您的申请并在2-3个工作日内回复。",
  },
  errors: {
    network: "网络错误，请检查您的连接。",
    server: "服务器错误，请稍后重试。",
    unauthorized: "会话已过期，请重新登录。",
    notFound: "未找到请求的资源。",
    insufficientCoins: "金币不足，请充值。",
    callFailed: "通话无法连接，请重试。",
    permissionDenied: "权限被拒绝。",
    generic: "出现错误，请重试。",
  },

  tabs: {
    home: "首页",
    chat: "聊天",
    calls: "通话",
    wallet: "钱包",
    profile: "我的",
  },

  hostSettings: {
    title: "主播设置",
    availability: "可用状态",
    autoOnline: "打开应用时自动上线",
    dnd: "勿扰模式",
    dndOn: "开启 — 静音通知",
    schedule: "可用时间表",
    randomCalls: "随机通话",
    availableRandom: "可接受随机通话",
    randomOn: "开启 — 已加入随机匹配池",
    randomOff: "关闭 — 仅限直接通话",
    allowVideoRandom: "允许随机视频通话",
    videoDisabled: "已禁用 — 随机通话已关闭",
    videoOn: "开启 — 接受随机视频通话",
    videoOff: "关闭 — 仅限随机语音通话",
    loading: "加载中…",
    pushNotifications: "推送通知",
    notificationPrefs: "通知偏好",
    incomingCallAlerts: "来电提醒",
    chatNotifications: "聊天通知",
    coinEarnedAlerts: "金币收益提醒",
    earnings: "收益",
    payoutMethod: "提现方式",
    withdrawEarnings: "提取收益",
    referEarn: "推荐赚钱",
    preferences: "偏好设置",
    appLanguage: "应用语言",
    support: "支持",
    helpSupport: "帮助与支持",
    privacyPolicy: "隐私政策",
    aboutApp: "关于 VoxLink Host",
    account: "账户",
    signOut: "退出登录",
    deleteAccount: "删除账户",
    on: "开启",
    off: "关闭",
    alwaysAvailable: "始终可用",
  },

  homeScreen: {
    online: "您已上线",
    offline: "您已离线",
    onlineSub: "可接收通话",
    offlineSub: "开启以开始接受通话",
    totalCalls: "总通话数",
    totalHours: "总时长",
    earnings: "收益",
    yourCallRates: "您的通话费率",
    ratesSub: "用户每分钟支付给您的金币",
    edit: "编辑",
    audioPerMin: "语音 / 分钟",
    videoPerMin: "视频 / 分钟",
    manage: "管理",
    qaCallRates: "通话费率",
    qaCallRatesDesc: "设置您的价格",
    qaTopics: "我的话题",
    qaTopicsDesc: "触达更多用户",
    qaEarnings: "收益",
    qaEarningsDesc: "查看历史",
    qaPayouts: "提现",
    qaPayoutsDesc: "提取金币",
    qaWallet: "钱包",
    qaWalletDesc: "余额与提现",
    qaCallHistory: "通话记录",
    qaCallHistoryDesc: "过往通话",
    qaRefer: "推荐赚钱",
    qaReferDesc: "邀请好友",
    qaProfile: "个人资料",
    qaProfileDesc: "编辑详情",
    qaSettings: "设置",
    qaSettingsDesc: "应用偏好",
    permsRequired: "需要权限",
    micLabel: "麦克风",
    micDesc: "语音通话所需",
    cameraLabel: "摄像头",
    cameraDesc: "视频通话所需",
    notifLabel: "通知",
    notifDesc: "用于来电提醒",
    granted: "已授权",
    tapToAllow: "点击以允许",
    hostTips: "主播提示",
    tip1: "在高峰时段（晚6点-10点）保持在线",
    tip2: "完善资料以获得更多预约",
    tip3: "快速回复以提高您的评分",
    tip4: "添加更多话题以触达更多用户",
  },

  profileScreen: {
    title: "我的资料",
    proHost: "专业主播",
    calls: "通话",
    rating: "评分",
    coins: "金币",
    onlineStatus: "在线状态",
    pushNotifications: "推送通知",
    account: "账户",
    editProfile: "编辑资料",
    callRates: "通话费率",
    myTopics: "我的话题",
    settings: "设置",
    language: "语言",
    more: "更多",
    referEarn: "推荐赚钱",
    helpCenter: "帮助中心",
    privacyPolicy: "隐私政策",
    about: "关于 VoxLink",
    signOut: "退出登录",
    signOutConfirm: "确定要退出登录吗？",
    permRequiredTitle: "需要权限",
    permRequiredMsg: "请允许访问您的照片库以更换头像。",
    turnOffNotifTitle: "关闭通知",
    turnOffNotifMsg: "要关闭通知，请前往手机设置并关闭 VoxLink Host 的通知。",
    openSettings: "打开设置",
    uploadFailedTitle: "上传失败",
    uploadFailedMsg: "无法上传您的照片，请重试。",
    photoUpdated: "头像已更新！",
    photoSaved: "照片已保存",
  },

  callsScreen: {
    title: "通话记录",
    all: "全部",
    audio: "语音",
    video: "视频",
    completed: "已完成",
    missed: "未接",
    cancelled: "已取消",
    noCalls: "暂无通话",
    loadError: "无法加载通话，下拉刷新。",
  },

  chatScreen: {
    title: "消息",
    searchPlaceholder: "搜索对话...",
    noConversations: "暂无对话",
    noMessagesYet: "暂无消息",
    now: "刚刚",
  },

  walletScreen: {
    title: "主播钱包",
    availableBalance: "可用余额",
    coins: "金币",
    payoutValue: "提现价值",
    thisWeek: "本周",
    sessions: "场次",
    withdrawn: "已提现",
    earningsHistory: "收益历史",
    withdraw: "提现",
    noEarnings: "暂无收益",
    quickSelect: "快速选择金额",
    orEnter: "或输入金额",
    enterCoinAmount: "输入金币数量",
    payoutTo: "提现至",
    setupPayout: "设置您的提现方式",
    edit: "编辑",
    managePayout: "管理提现方式",
    requestWithdrawal: "申请提现",
    note: "注意",
    failedLoad: "加载收益数据失败。",
  },
};

export default zh;
